### PREREQUISITES

#### Importing Modules and Tables

In [1]:
import pandas as pd

In [2]:
candidate_df = pd.read_csv(r"C:\Users\SalauddinKhan\Desktop\PYTHON\candidates.csv")
vacancy_df = pd.read_csv(r"C:\Users\SalauddinKhan\Desktop\PYTHON\vacancy_table.csv")

C:\Users\SalauddinKhan\AppData\Local\Temp\ipykernel_17748\2298745054.py:1: DtypeWarning: Columns (35,42) have mixed types. Specify dtype option on import or set low_memory=False.
  candidate_df = pd.read_csv(r"C:\Users\SalauddinKhan\Desktop\PYTHON\candidates.csv")

In [ ]:
# candidate_df = pd.read_csv(r"C:\Users\Aviral Chaudhary\Downloads\RP_CHSL_23\candidates.csv")
# vacancy_df = pd.read_csv(r"C:\Users\Aviral Chaudhary\Downloads\RP_CHSL_23\vacancy.csv")

In [3]:
candidate_df.columns[:10]

Index(['id', 'registrationNo', 'otrId', 'myApplicationId', 'emailId',
       'phoneNo', 'name', 'new_name', 'father_name', 'mother_name'],
      dtype='object')

In [4]:
vacancy_df.columns

Index(['ministry_name', 'department_name', 'post_name', 'department_code',
       'category', 'category_code', 'initial_vacancy', 'gender', 'current',
       'allocated', 'left_vacancy'],
      dtype='object')

In [ ]:
candidate_df['lengthofservice'].unique()

In [ ]:
candidate_df['service_period'].unique()

In [68]:
candidate_df.columns[100:]

Index(['section1', 'section2', 'total', 'mistakes_ldc', 'ldc_medium',
       'mistakes_deo', 'deo_medium', 'debarred', 'rejection_provision',
       'remarks', 'cand_name', 'agerelax_code', 'service_period', 'post_pref',
       'post_pref_original'],
      dtype='object')

In [5]:
candidate_df['rejection_provision'].unique()

array(['C', 'W', 'D'], dtype=object)

#### ARC Table from Notice

In [6]:
arc_dict = {'arc_code': ['1', '2', '3', '4', '5', '6', '8', '9', '10', '11', '12', '13'], 
            'arc_year': [5, 3, 10, 13, 15, 3, 3, 8, 13, 18, 8, 13],
            'arc_cat1': ['1,2', '6', '0,9', '6', '1,2', '0,1,2,6,9', '0,6,9', '1,2', '0,6,9', '1,2', '0,6,9', '1,2'],
            'arc_cat2': ['', '', '', '', '', '3', '', '', '', '', '',''],
            'arc_cat3': ['', '', '4,5,7,8', '4,5,7,8', '4,5,7,8', '', '', '', '', '', '', ''],
            'arc_gender': ['1,2,3', '1,2,3', '1,2,3', '1,2,3', '1,2,3', '1,2,3', '1,2,3', '1,2,3', '1,2,3', '1,2,3', '1', '1'],
            'arc_year_against_ur': [ None, None, 10, 10, 10, None, 3, 3, 13, 13, 8, 8]
           }

arc_df = pd.DataFrame(arc_dict)

#### Cutoff Table from Notice

In [4]:
# cutoff_data = [
#     {'serial_id': 1, 'category': 9, 'paper1': 153.91142, 'paper2': 108, 'mistakes_ldc': 7, 'mistakes_deo': None, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_ldc'},
#     {'serial_id': 2, 'category': 1, 'paper1': 136.41166, 'paper2': 72, 'mistakes_ldc': 10, 'mistakes_deo': None, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_ldc'},
#     {'serial_id': 3, 'category': 2, 'paper1': 124.52592, 'paper2': 72, 'mistakes_ldc': 10, 'mistakes_deo': None, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_ldc'},
#     {'serial_id': 4, 'category': 6, 'paper1': 152.13383, 'paper2': 90, 'mistakes_ldc': 10, 'mistakes_deo': None, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_ldc'},
#     {'serial_id': 5, 'category': 0, 'paper1': 151.09782, 'paper2': 90, 'mistakes_ldc': 10, 'mistakes_deo': None, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_ldc'},
#     {'serial_id': 6, 'category': 3, 'paper1': 102.47651, 'paper2': 72, 'mistakes_ldc': 10, 'mistakes_deo': None, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_ldc'},
#     {'serial_id': 7, 'category': 4, 'paper1': 132.44172, 'paper2': 72, 'mistakes_ldc': 10, 'mistakes_deo': None, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_ldc'},
#     {'serial_id': 8, 'category': 5, 'paper1': 94.08855, 'paper2': 72, 'mistakes_ldc': 10, 'mistakes_deo': None, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_ldc'},
#     {'serial_id': 9, 'category': 7, 'paper1': 132.21752, 'paper2': 72, 'mistakes_ldc': 10, 'mistakes_deo': None, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_ldc'},
#     {'serial_id': 10, 'category': 8, 'paper1': 115.27865, 'paper2': 72, 'mistakes_ldc': 10, 'mistakes_deo': None, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_ldc'},
#     {'serial_id': 11, 'category': 9, 'paper1': 169.92585, 'paper2': 108, 'mistakes_ldc': None, 'mistakes_deo': None, 'mistakes_deo_a': 5, 'cut_off_name': 'cutoff_flag_deo_a'},
#     {'serial_id': 12, 'category': 1, 'paper1': 157.67965, 'paper2': 72, 'mistakes_ldc': None, 'mistakes_deo': None, 'mistakes_deo_a': 7, 'cut_off_name': 'cutoff_flag_deo_a'},
#     {'serial_id': 13, 'category': 2, 'paper1': 999.99999, 'paper2': 72, 'mistakes_ldc': None, 'mistakes_deo': None, 'mistakes_deo_a': 7, 'cut_off_name': 'cutoff_flag_deo_a'},
#     {'serial_id': 14, 'category': 6, 'paper1': 169.92585, 'paper2': 90, 'mistakes_ldc': None, 'mistakes_deo': None, 'mistakes_deo_a': 7, 'cut_off_name': 'cutoff_flag_deo_a'},
#     {'serial_id': 15, 'category': 0, 'paper1': 999.99999, 'paper2': 90, 'mistakes_ldc': None, 'mistakes_deo': None, 'mistakes_deo_a': 7, 'cut_off_name': 'cutoff_flag_deo_a'},
#     {'serial_id': 16, 'category': 3, 'paper1': 999.99999, 'paper2': 72, 'mistakes_ldc': None, 'mistakes_deo': None, 'mistakes_deo_a': 7, 'cut_off_name': 'cutoff_flag_deo_a'},
#     {'serial_id': 17, 'category': 4, 'paper1': 999.99999, 'paper2': 72, 'mistakes_ldc': None, 'mistakes_deo': None, 'mistakes_deo_a': 7, 'cut_off_name': 'cutoff_flag_deo_a'},
#     {'serial_id': 18, 'category': 5, 'paper1': 999.99999, 'paper2': 72, 'mistakes_ldc': None, 'mistakes_deo': None, 'mistakes_deo_a': 7, 'cut_off_name': 'cutoff_flag_deo_a'},
#     {'serial_id': 19, 'category': 7, 'paper1': 999.99999, 'paper2': 72, 'mistakes_ldc': None, 'mistakes_deo': None, 'mistakes_deo_a': 7, 'cut_off_name': 'cutoff_flag_deo_a'},
#     {'serial_id': 20, 'category': 8, 'paper1': 999.99999, 'paper2': 72, 'mistakes_ldc': None, 'mistakes_deo': None, 'mistakes_deo_a': 7, 'cut_off_name': 'cutoff_flag_deo_a'},
#     {'serial_id': 21, 'category': 9, 'paper1': 169.24309, 'paper2': 108, 'mistakes_ldc': None, 'mistakes_deo': 5, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_deo'},
#     {'serial_id': 22, 'category': 1, 'paper1': 157.32139, 'paper2': 72, 'mistakes_ldc': None, 'mistakes_deo': 7, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_deo'},
#     {'serial_id': 23, 'category': 2, 'paper1': 154.5803, 'paper2': 72, 'mistakes_ldc': None, 'mistakes_deo': 7, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_deo'},
#     {'serial_id': 24, 'category': 6, 'paper1': 168.77506, 'paper2': 90, 'mistakes_ldc': None, 'mistakes_deo': 7, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_deo'},
#     {'serial_id': 25, 'category': 0, 'paper1': 169.28877, 'paper2': 90, 'mistakes_ldc': None, 'mistakes_deo': 7, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_deo'},
#     {'serial_id': 26, 'category': 3, 'paper1': 126.84662, 'paper2': 72, 'mistakes_ldc': None, 'mistakes_deo': 7, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_deo'},
#     {'serial_id': 27, 'category': 4, 'paper1': 999.99999, 'paper2': 72, 'mistakes_ldc': None, 'mistakes_deo': 7, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_deo'},
#     {'serial_id': 28, 'category': 5, 'paper1': 115.87954, 'paper2': 72, 'mistakes_ldc': None, 'mistakes_deo': 7, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_deo'},
#     {'serial_id': 29, 'category': 7, 'paper1': 999.99999, 'paper2': 72, 'mistakes_ldc': None, 'mistakes_deo': 7, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_deo'},
#     {'serial_id': 30, 'category': 8, 'paper1': 999.99999, 'paper2': 72, 'mistakes_ldc': None, 'mistakes_deo': 7, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_deo'},
# ]
# cutoff_df = pd.DataFrame(cutoff_data)

In [7]:
cutoff_data = [
    {'serial_id': 1, 'category': 9, 'paper1': 157.36168, 'paper2': 54, 'paper3': 54, 'mistakes_ldc': 7, 'mistakes_deo': None, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_ldc'},
    {'serial_id': 2, 'category': 1, 'paper1': 139.68408, 'paper2': 36, 'paper3': 36, 'mistakes_ldc': 10, 'mistakes_deo': None, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_ldc'},
    {'serial_id': 3, 'category': 2, 'paper1': 129.44568, 'paper2': 36, 'paper3': 36, 'mistakes_ldc': 10, 'mistakes_deo': None, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_ldc'},
    {'serial_id': 4, 'category': 6, 'paper1': 156.61665, 'paper2': 45, 'paper3': 45, 'mistakes_ldc': 10, 'mistakes_deo': None, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_ldc'},
    {'serial_id': 5, 'category': 0, 'paper1': 150.51731, 'paper2': 45, 'paper3': 45, 'mistakes_ldc': 10, 'mistakes_deo': None, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_ldc'},
    {'serial_id': 6, 'category': 3, 'paper1': 78.23008, 'paper2': 36, 'paper3': 36, 'mistakes_ldc': 10, 'mistakes_deo': None, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_ldc'},
    {'serial_id': 7, 'category': 4, 'paper1': 124.70219, 'paper2': 36, 'paper3': 36, 'mistakes_ldc': 10, 'mistakes_deo': None, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_ldc'},
    {'serial_id': 8, 'category': 5, 'paper1': 81.06810, 'paper2': 36, 'paper3': 36, 'mistakes_ldc': 10, 'mistakes_deo': None, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_ldc'},
    {'serial_id': 9, 'category': 7, 'paper1': 123.78593, 'paper2': 36, 'paper3': 36, 'mistakes_ldc': 10, 'mistakes_deo': None, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_ldc'},
    {'serial_id': 10, 'category': 8, 'paper1': 72.53530, 'paper2': 36, 'paper3': 36, 'mistakes_ldc': 10, 'mistakes_deo': None, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_ldc'},
    {'serial_id': 11, 'category': 9, 'paper1': 176.27042, 'paper2': 54, 'paper3': 54, 'mistakes_ldc': None, 'mistakes_deo': None, 'mistakes_deo_a': 5, 'cut_off_name': 'cutoff_flag_deo_a'},
    {'serial_id': 12, 'category': 1, 'paper1': 166.67647, 'paper2': 36, 'paper3': 36, 'mistakes_ldc': None, 'mistakes_deo': None, 'mistakes_deo_a': 7, 'cut_off_name': 'cutoff_flag_deo_a'},
    {'serial_id': 13, 'category': 2, 'paper1': 165.07894, 'paper2': 36, 'paper3': 36, 'mistakes_ldc': None, 'mistakes_deo': None, 'mistakes_deo_a': 7, 'cut_off_name': 'cutoff_flag_deo_a'},
    {'serial_id': 14, 'category': 6, 'paper1': 176.27042, 'paper2': 45, 'paper3': 45, 'mistakes_ldc': None, 'mistakes_deo': None, 'mistakes_deo_a': 7, 'cut_off_name': 'cutoff_flag_deo_a'},
    {'serial_id': 15, 'category': 0, 'paper1': 176.27042, 'paper2': 45, 'paper3': 45, 'mistakes_ldc': None, 'mistakes_deo': None, 'mistakes_deo_a': 7, 'cut_off_name': 'cutoff_flag_deo_a'},
    {'serial_id': 16, 'category': 3, 'paper1': 133.93856, 'paper2': 36, 'paper3': 36, 'mistakes_ldc': None, 'mistakes_deo': None, 'mistakes_deo_a': 7, 'cut_off_name': 'cutoff_flag_deo_a'},
    {'serial_id': 17, 'category': 4, 'paper1': 166.25113, 'paper2': 36, 'paper3': 36, 'mistakes_ldc': None, 'mistakes_deo': None, 'mistakes_deo_a': 7, 'cut_off_name': 'cutoff_flag_deo_a'},
    {'serial_id': 18, 'category': 5, 'paper1': 999.99999, 'paper2': 36, 'paper3': 36, 'mistakes_ldc': None, 'mistakes_deo': None, 'mistakes_deo_a': 7, 'cut_off_name': 'cutoff_flag_deo_a'},
    {'serial_id': 19, 'category': 7, 'paper1': 999.99999, 'paper2': 36, 'paper3': 36, 'mistakes_ldc': None, 'mistakes_deo': None, 'mistakes_deo_a': 7, 'cut_off_name': 'cutoff_flag_deo_a'},
    {'serial_id': 20, 'category': 8, 'paper1': 999.99999, 'paper2': 36, 'paper3': 36, 'mistakes_ldc': None, 'mistakes_deo': None, 'mistakes_deo_a': 7, 'cut_off_name': 'cutoff_flag_deo_a'},
    {'serial_id': 21, 'category': 9, 'paper1': 176.27042, 'paper2': 54, 'paper3': 54, 'mistakes_ldc': None, 'mistakes_deo': 5, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_deo'},
    {'serial_id': 22, 'category': 1, 'paper1': 166.67647, 'paper2': 36, 'paper3': 36, 'mistakes_ldc': None, 'mistakes_deo': 7, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_deo'},
    {'serial_id': 23, 'category': 2, 'paper1': 165.07894, 'paper2': 36, 'paper3': 36, 'mistakes_ldc': None, 'mistakes_deo': 7, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_deo'},
    {'serial_id': 24, 'category': 6, 'paper1': 176.27042, 'paper2': 45, 'paper3': 45, 'mistakes_ldc': None, 'mistakes_deo': 7, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_deo'},
    {'serial_id': 25, 'category': 0, 'paper1': 176.27042, 'paper2': 45, 'paper3': 45, 'mistakes_ldc': None, 'mistakes_deo': 7, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_deo'},
    {'serial_id': 26, 'category': 3, 'paper1': 133.93856, 'paper2': 36, 'paper3': 36, 'mistakes_ldc': None, 'mistakes_deo': 7, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_deo'},
    {'serial_id': 27, 'category': 4, 'paper1': 166.25113, 'paper2': 36,'paper3': 36, 'mistakes_ldc': None, 'mistakes_deo': 7, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_deo'},
    {'serial_id': 28, 'category': 5, 'paper1': 999.99999, 'paper2': 36, 'paper3': 36,'mistakes_ldc': None, 'mistakes_deo': 7, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_deo'},
    {'serial_id': 29, 'category': 7, 'paper1': 999.99999, 'paper2': 36,'paper3': 36, 'mistakes_ldc': None, 'mistakes_deo': 7, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_deo'},
    {'serial_id': 30, 'category': 8, 'paper1': 999.99999, 'paper2': 36, 'paper3': 36, 'mistakes_ldc': None, 'mistakes_deo': 7, 'mistakes_deo_a': None, 'cut_off_name': 'cutoff_flag_deo'},
]
cutoff_df = pd.DataFrame(cutoff_data)

In [8]:
candidate_df['dob'] = pd.to_datetime(candidate_df['dob'])

### MERIT

#### CODE

In [6]:
# def get_merit(candidate_df):    
    
#     candidate_df['merit'] = None
    
#     candidates =  candidate_df[
#     (candidate_df['total'].notnull()) & 
#     (candidate_df['rejection_provision'].astype(str).isin(['C', 'P', 'W']))
#     ].sort_values(by = ['total', 'score_s1', 'dob', 'name'], ascending=[False, False, True, True])
    
#     candidates['merit'] = range(1, len(candidates) + 1)

#     rollno_to_merit = candidates.set_index('rollno')['merit'].to_dict()
#     candidate_df['merit'] = candidate_df['rollno'].map(rollno_to_merit)
    
#     return "{flag_name} updated successfully for {merit} candidates".format(
#         flag_name='merit',
#         merit=len(candidates))

In [9]:
def get_merit(candidate_df):    
    
    candidate_df['merit'] = None
    
    candidates =  candidate_df[
    (candidate_df['total'].notnull()) & 
    (candidate_df['rejection_provision'].astype(str).isin(['C', 'P', 'W']))
    ].sort_values(by = ['total', 'section1', 'section2', 'dob'], ascending=[False, False, False, True])
    
    candidates['merit'] = range(1, len(candidates) + 1)

    rollno_to_merit = candidates.set_index('rollno')['merit'].to_dict()
    candidate_df['merit'] = candidate_df['rollno'].map(rollno_to_merit)
    
    return "{flag_name} updated successfully for {merit} candidates".format(
        flag_name='merit',
        merit=len(candidates))

#### EXECUTION

In [10]:
get_merit(candidate_df)

'merit updated successfully for 34865 candidates'

In [11]:
candidate_df[['rollno', 'merit']].head()

       rollno    merit
0  7204015544  22521.0
1  7204012107   3892.0
2  2405116873   9430.0
3  3206088844  14624.0
4  3008017298  17581.0

In [12]:
candidate_df['merit']=candidate_df['merit'].fillna(0).astype(int)
candidate_df[['rollno', 'merit']].head()

       rollno  merit
0  7204015544  22521
1  7204012107   3892
2  2405116873   9430
3  3206088844  14624
4  3008017298  17581

In [13]:
zero_merit_count = (candidate_df['merit'] == 0).sum()
print(zero_merit_count)

55

### CUTOFF FLAG

#### CODE

In [9]:
# def get_cutoff(cutoff_df, candidate_df, medium):
    
#     exempted_lst = [2201286417, 2201261819, 2201022351, 2201321776, 2201115567, 2201231307, 2201089921, 2201196691, 2201320812, 2201117510, 2201050320, 2201261999, 2201196486, 2201221643, 2201188348, 2201229543, 2201188592, 2201254226, 2201163360, 2201261589, 2201260862, 2201321322, 2201294542, 2201254582, 2201331414, 2201021190, 2201195932, 2201287571, 2201329297, 2201152549, 2201162975, 2201286706, 2201196010, 2201187759, 2201161977, 2201254033, 2201321241, 2201320948, 2201294927, 2201087336, 2201163399, 2201154132, 2201020780, 2201082050, 2201320397, 2201195690, 2201230097, 2201162405, 2201075707, 2201018586, 2201338344, 2201050279, 2201296252, 2406014257, 2409000949, 2409006110, 2404017084, 2404007713, 2405117847, 2405154183, 2405170367, 2405029019, 2405069865, 2405071899, 2405098510, 2405097019, 2405075071, 2405007865, 2405151608, 2405190440, 2405075698, 2405113125, 2405072008, 2003008594, 2201049240, 2201081680, 2201082570, 2201087827, 2201089360, 2201115269, 2201115722, 2201126816, 2201161925, 2201229506, 2201328495, 2201328973, 6005010618, 6005021845, 6005001956, 6005022440, 6005022512, 1601004301, 1403004556, 8012004348, 8601009735, 8601016144, 8601017436, 8601029132, 8601015829, 8012011555, 8603004052, 3001009360, 3001019378, 3003011451, 3003072673, 3009003647, 3009054032, 3009061176, 3010017883, 3010037186, 3010040110, 3010048226, 3010078545, 3013014334, 3013055415, 3013064442, 3205048021, 3206055602, 3206055671, 3206064429, 3206066550, 3206068251, 3206117320, 3009003653, 4419012118, 4205056007, 4205005392]

#     candidate_df.loc[(candidate_df['rollno'].isin(exempted_lst)), 'mistakes_ldc'] = 0
    
#     if medium == 'LDC':
#         cutoff = 'cutoff_flag_ldc'
#         mistakes_col = 'mistakes_ldc'
        
    
#     elif medium == 'DEO':
#         cutoff = 'cutoff_flag_deo'
#         mistakes_col = 'mistakes_deo'
    
#     elif medium == 'DEO_A':
#         cutoff = 'cutoff_flag_deo_a'
#         mistakes_col = 'mistakes_deo_a'
    
#     else:
#         return "Enter Correct Medium i.e. Either 'LDC' or 'DEO' or 'DEO_A'"

#     ckm_dict = {9:13.5, 6:11.25, 0:11.25, 1:9, 2:9, 3:9, 4:9, 5:9, 7:9, 8:9}
#     candidate_df[cutoff] = None
#     cutoff_dict = {}

#     for index, row in cutoff_df[cutoff_df['cut_off_name'].astype(str) == cutoff].iterrows():
#         category = int(row['category'])
#         paper1 = float(row['paper1'])
#         paper2 = float(row['paper2'])
#         mistakes = float(row[mistakes_col])
#         cutoff_dict[category] = [paper1, paper2, mistakes]
    
#     sorted_candidates = candidate_df[candidate_df['merit'].notnull()].sort_values(by='merit')

#     def calculate_cutoff(candidate):
        
#         cutoff = ''

#         if (candidate['tier1_final'] >= cutoff_dict[9][0]) & (candidate['total'] >= cutoff_dict[9][1]) & (candidate['computer_knowledge_module'] >= ckm_dict[9]) & (candidate[mistakes_col] <= cutoff_dict[9][2]):
#             cutoff += '9'

#         for cat in [0, 1, 2, 6]:
#             if (candidate['cat1'] == cat) & (cat in cutoff_dict):
#                 if (candidate['tier1_final'] >= cutoff_dict[cat][0]) & (candidate['total'] >= cutoff_dict[cat][1]) & (candidate['computer_knowledge_module'] >= ckm_dict[cat]) & (candidate[mistakes_col] <= cutoff_dict[cat][2]):
#                     cutoff += str(cat)

#         if (candidate['cat2'] == 3) & (3 in cutoff_dict):
#             if (candidate['tier1_final'] >= cutoff_dict[3][0]) & (candidate['total'] >= cutoff_dict[3][1]) & (candidate['computer_knowledge_module'] >= ckm_dict[3]) & (candidate[mistakes_col] <= cutoff_dict[3][2]):
#                 cutoff += '3'

#         for cat in [4, 5, 7, 8]:
#             if (candidate['cat3'] == cat) & (cat in cutoff_dict):
#                 if (candidate['tier1_final'] >= cutoff_dict[cat][0]) & (candidate['total'] >= cutoff_dict[cat][1]) & (candidate['computer_knowledge_module'] >= ckm_dict[cat]) & (candidate[mistakes_col] <= cutoff_dict[cat][2]):
#                     cutoff += str(cat)

#         return cutoff

#     sorted_candidates[cutoff] = sorted_candidates.apply(lambda row: calculate_cutoff(row), axis=1)
#     candidate_df.update(sorted_candidates)

#     return f"{cutoff} updated successfully"

In [14]:
def get_cutoff(cutoff_df, candidate_df, medium):
    
    #exempted_lst = [2201286417, 2201261819, 2201022351, 2201321776, 2201115567, 2201231307, 2201089921, 2201196691, 2201320812, 2201117510, 2201050320, 2201261999, 2201196486, 2201221643, 2201188348, 2201229543, 2201188592, 2201254226, 2201163360, 2201261589, 2201260862, 2201321322, 2201294542, 2201254582, 2201331414, 2201021190, 2201195932, 2201287571, 2201329297, 2201152549, 2201162975, 2201286706, 2201196010, 2201187759, 2201161977, 2201254033, 2201321241, 2201320948, 2201294927, 2201087336, 2201163399, 2201154132, 2201020780, 2201082050, 2201320397, 2201195690, 2201230097, 2201162405, 2201075707, 2201018586, 2201338344, 2201050279, 2201296252, 2406014257, 2409000949, 2409006110, 2404017084, 2404007713, 2405117847, 2405154183, 2405170367, 2405029019, 2405069865, 2405071899, 2405098510, 2405097019, 2405075071, 2405007865, 2405151608, 2405190440, 2405075698, 2405113125, 2405072008, 2003008594, 2201049240, 2201081680, 2201082570, 2201087827, 2201089360, 2201115269, 2201115722, 2201126816, 2201161925, 2201229506, 2201328495, 2201328973, 6005010618, 6005021845, 6005001956, 6005022440, 6005022512, 1601004301, 1403004556, 8012004348, 8601009735, 8601016144, 8601017436, 8601029132, 8601015829, 8012011555, 8603004052, 3001009360, 3001019378, 3003011451, 3003072673, 3009003647, 3009054032, 3009061176, 3010017883, 3010037186, 3010040110, 3010048226, 3010078545, 3013014334, 3013055415, 3013064442, 3205048021, 3206055602, 3206055671, 3206064429, 3206066550, 3206068251, 3206117320, 3009003653, 4419012118, 4205056007, 4205005392]
    exempted_lst = [2201025745, 3009039068, 2201157582, 2201262759, 3009057507, 3009027862, 2201237763, 2201123632, 2201279231, 2201326965, 2201127466, 3206067019, 2405085664, 2201265181, 2201299722, 2201136974, 2201326973, 2201311384, 2201157815, 2201173997, 6005013737, 2201007495, 4205010275, 2201009572, 2201097177, 3005018641, 2201136936, 8601010394, 3205016589, 2406016014, 3011028492, 2405023850, 2201202688, 2201193750, 2201046848, 4205012477, 2201307032, 4417015349, 5501005018, 2201193815, 2201046701, 2405048881, 8201003405, 8601020458, 2201200620, 2201237620, 2201136081, 3001002703, 3010071952, 3009070855, 2201164164, 2201308646, 2201025777, 3011015514, 3005001163, 3206148073, 2201228820, 2405112487, 2201100137, 4206012993, 3206105660, 2405112472, 4206015022, 4410076721, 5701000795, 2405072841, 2201197947, 2201306535, 2401003901, 7201006348, 8012009197, 3001018798, 2201271662, 5501000101, 2201237413, 3011023833, 2201189293, 2201090612, 2401002105, 3013031377, 3005027722, 2201326971, 2201237068, 3010040160, 2201188940, 4410037683, 3001018880, 2201104299, 2201023416, 6204014573, 6005000799, 2404002241, 8201003561, 2201123527, 2404004341, 2201021588, 2201134225, 5105018078, 2201191945, 2405111996, 2201058682, 2201082126, 2404005920, 4205026073, 8601003596, 4205014342, 9205004061, 2201088199, 2201123200, 3013031360, 2201018583, 2201164555, 2201148557, 4609007238, 3003034955, 2201306327, 2201230833, 4205002512, 3010012574, 3013040610, 2201009823, 2201014517, 2405049121, 2201174049, 3206012199, 2201088194, 2201200855, 2201122864, 3010035435, 2405045824, 2201092599, 3001043806, 2201058398, 2201134420, 2201086347, 2201316308, 1401013499, 4417013172, 2201237284, 2406008694, 3010030320, 2201010151, 2201136065, 2201272019, 2201125115, 3205039397, 2405040348, 2201279303, 2201046780, 2201036955, 2201055473, 3003012757, 2201316499, 3010098235, 2201265083, 4410042859, 4602002405, 2003005270, 2201058561, 3206025694, 2405112567, 2201202868, 3206047602, 4207011293, 3003003885, 4410100924, 2405072781, 2201307109, 2201058077, 9001009622, 2201237995, 2201122917, 3001006702, 1004001262, 2201263106, 2405006374, 2201092664, 3011023958, 4410004204, 2201193791, 2201307106, 3007019409, 3009059632, 4410023202, 6001004368, 3003031280, 3201013460, 2201058557]

    candidate_df.loc[(candidate_df['rollno'].isin(exempted_lst)), 'mistakes_ldc'] = 0
    
    if medium == 'LDC':
        cutoff = 'cutoff_flag_ldc'
        mistakes_col = 'mistakes_ldc'
        
    
    elif medium == 'DEO':
        cutoff = 'cutoff_flag_deo'
        mistakes_col = 'mistakes_deo'
    
    elif medium == 'DEO_A':
        cutoff = 'cutoff_flag_deo_a'
        mistakes_col = 'mistakes_deo_a'
    
    else:
        return "Enter Correct Medium i.e. Either 'LDC' or 'DEO' or 'DEO_A'"

    ckm_dict = {9:13.5, 6:11.25, 0:11.25, 1:9, 2:9, 3:9, 4:9, 5:9, 7:9, 8:9}
    candidate_df[cutoff] = None
    cutoff_dict = {}

    for index, row in cutoff_df[cutoff_df['cut_off_name'].astype(str) == cutoff].iterrows():
        category = int(row['category'])
        paper1 = float(row['paper1'])
        paper2 = float(row['paper2'])
        paper3 = float(row['paper3'])
        mistakes = float(row[mistakes_col])
        cutoff_dict[category] = [paper1, paper2, paper3, mistakes]
    
    #sorted_candidates = candidate_df[candidate_df['merit'].notnull()].sort_values(by='merit')
    sorted_candidates = candidate_df[candidate_df['merit'] != 0].sort_values(by='merit')

    def calculate_cutoff(candidate):
        
        cutoff = ''

        if (candidate['tier1_final'] >= cutoff_dict[9][0]) & (candidate['section1'] >= cutoff_dict[9][1]) & (candidate['section2'] >= cutoff_dict[9][2]) & (candidate['computer_knowledge_module'] >= ckm_dict[9]) & (candidate[mistakes_col] <= cutoff_dict[9][3]):
            cutoff += '9'

        for cat in [0, 1, 2, 6]:
            if (candidate['cat1'] == cat) & (cat in cutoff_dict):
                if (candidate['tier1_final'] >= cutoff_dict[cat][0]) & (candidate['section1'] >= cutoff_dict[cat][1]) & (candidate['section2'] >= cutoff_dict[cat][2]) & (candidate['computer_knowledge_module'] >= ckm_dict[cat]) & (candidate[mistakes_col] <= cutoff_dict[cat][3]):
                    cutoff += str(cat)

        if (candidate['cat2'] == 3) & (3 in cutoff_dict):
            if (candidate['tier1_final'] >= cutoff_dict[3][0]) & (candidate['section1'] >= cutoff_dict[3][1]) & (candidate['section2'] >= cutoff_dict[3][2]) & (candidate['computer_knowledge_module'] >= ckm_dict[3]) & (candidate[mistakes_col] <= cutoff_dict[3][3]):
                cutoff += '3'

        for cat in [4, 5, 7, 8]:
            if (candidate['cat3'] == cat) & (cat in cutoff_dict):
                if (candidate['tier1_final'] >= cutoff_dict[cat][0]) & (candidate['section1'] >= cutoff_dict[cat][1]) & (candidate['section2'] >= cutoff_dict[cat][2]) & (candidate['computer_knowledge_module'] >= ckm_dict[cat]) & (candidate[mistakes_col] <= cutoff_dict[cat][3]):
                    cutoff += str(cat)

        return cutoff

    sorted_candidates[cutoff] = sorted_candidates.apply(lambda row: calculate_cutoff(row), axis=1)
    candidate_df.update(sorted_candidates)

    return f"{cutoff} updated successfully"

#### EXECUTION

##### For LDC

In [15]:
medium = 'LDC'
get_cutoff(cutoff_df, candidate_df, medium)

'cutoff_flag_ldc updated successfully'

In [17]:
candidate_df[['rollno', 'cutoff_flag_ldc']].head()

       rollno cutoff_flag_ldc
0  7204015544
1  7204012107              91
2  2405116873               1
3  3206088844              96
4  3008017298               6

##### For DEO

In [18]:
candidate_df['cutoff_flag_ldc'].unique()

array(['', '91', '1', '96', '6', '90', '9', '2', '4', '0', '3', '92', '8',
       '7', '5', None, '918', '14', '914', '964', '924', '97', '967',
       '93', '27', '907', '94', '24', '17', '98', '38', '917', '913',
       '05', '04', '07', '927', '64', '904', '965', '968', '35'],
      dtype=object)

In [19]:
none_values = candidate_df[candidate_df['cutoff_flag_ldc'].isna()][['cat1','tier1_final','section1','section2','mistakes_ldc','mistakes_deo','computer_knowledge_module','cutoff_flag_ldc','merit','rejection_provision']]
print(none_values.head(10))

      cat1  tier1_final  section1  section2  mistakes_ldc  mistakes_deo  \
1595     9    137.55278        96        85     32.440476           NaN
1598     2    139.44310       129       146     23.628049           NaN
1600     1    124.96402        29        54     50.446429           NaN
1919     6    168.29585       -10        27     30.030488           NaN
2019     2    130.36525        16        20      3.571429           NaN
2505     9    130.17351        96        45     58.689024           NaN
3731     2    171.43673       172       116      9.603659     11.971831
4112     0    148.19789        60        64      0.000000           NaN
7424     2    162.44649       144       151      5.335366           NaN
7807     1    160.02176       159       148      0.000000           NaN

      computer_knowledge_module cutoff_flag_ldc  merit rejection_provision
1595                         21            None      0                   D
1598                         15            None      0                   D
1600                         11            None      0                   D
1919                         22            None      0                   D
2019                         13            None      0                   D
2505                         24            None      0                   D
3731                         19            None      0                   D
4112                         10            None      0                   D
7424                         20            None      0                   D
7807                         17            None      0                   D

In [20]:
medium = 'DEO'
get_cutoff(cutoff_df, candidate_df, medium)

'cutoff_flag_deo updated successfully'

In [21]:
candidate_df[['rollno', 'cutoff_flag_deo']].head()

       rollno cutoff_flag_deo
0  7204015544
1  7204012107
2  2405116873
3  3206088844
4  3008017298

In [22]:
candidate_df['cutoff_flag_deo'].unique()

array(['', '90', '9', '1', '3', '2', '6', '96', '0', '92', '91', '4',
       None, '14', '93', '964'], dtype=object)

##### FOR DEO_A

In [ ]:
# medium = 'DEO_A'
# get_cutoff(cutoff_df, candidate_df, medium)

In [ ]:
# candidate_df[['rollno', 'cutoff_flag_deo_a']].head()

### DOB FLAG

#### PREREQIUSITES

In [23]:
mask = candidate_df['cat1'].isnull()
candidate_df.loc[mask, 'cat1'] = ''
candidate_df.loc[~mask, 'cat1'] = candidate_df.loc[~mask, 'cat1'].astype(int).astype(str)

mask = candidate_df['cat2'].isnull()
candidate_df.loc[mask, 'cat2'] = ''
candidate_df.loc[~mask, 'cat2'] = candidate_df.loc[~mask, 'cat2'].astype(int).astype(str)

mask = candidate_df['cat3'].isnull()
candidate_df.loc[mask, 'cat3'] = ''
candidate_df.loc[~mask, 'cat3'] = candidate_df.loc[~mask, 'cat3'].astype(int).astype(str)

mask = candidate_df['agerelax_code'].isnull()
candidate_df.loc[mask, 'agerelax_code'] = ''
candidate_df.loc[~mask, 'agerelax_code'] = candidate_df.loc[~mask, 'agerelax_code'].astype(int).astype(str)

C:\Users\SalauddinKhan\AppData\Local\Temp\ipykernel_17748\1307339542.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  candidate_df.loc[mask, 'cat1'] = ''
C:\Users\SalauddinKhan\AppData\Local\Temp\ipykernel_17748\1307339542.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  candidate_df.loc[mask, 'cat2'] = ''
C:\Users\SalauddinKhan\AppData\Local\Temp\ipykernel_17748\1307339542.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_df.loc[mask, 'cat3'] = ''
C:\Users\SalauddinKhan\AppData\Local\Temp\ipykernel_17748\1307339542.py:14: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_df.loc[mask, 'agerelax_code'] = ''

In [211]:
#candidate_df['cat1'].unique()

array(['9', '1', '6', '0', '2'], dtype=object)

In [212]:
#candidate_df['agerelax_code'].unique()

array(['', '1', '6', '3', '2', '10', '12', '5', '4', '11', '8', '9'],
      dtype=object)

In [24]:
candidate_df[['exsm_yrs', 'exsm_months', 'exsm_days']] = candidate_df['service_period'].str.extract(r'(\d+) Year[s]* (\d+) Month[s]* (\d+) Day[s]*')

candidate_df[['exsm_yrs', 'exsm_months', 'exsm_days']] = candidate_df[['exsm_yrs', 'exsm_months', 'exsm_days']].apply(pd.to_numeric)

In [25]:
candidate_df['exsm_yrs']=candidate_df['exsm_yrs'].fillna(0).astype(int)

In [26]:
candidate_df['exsm_months']=candidate_df['exsm_months'].fillna(0).astype(int)

In [27]:
candidate_df['exsm_days']=candidate_df['exsm_days'].fillna(0).astype(int)

In [ ]:
#candidate_df['exsm_yrs'].unique()
#candidate_df['exsm_months'].head()
#candidate_df['exsm_days'].head()

#### CODE

In [28]:
def get_dob_flag(candidate_df, arc_df):
    dob_to_date = pd.to_datetime('08/01/2006', format="%m/%d/%Y")
    dob_from_date = pd.to_datetime('08/01/1997', format="%m/%d/%Y")
    
    arc_year_dict = dict(zip(arc_df['arc_code'].astype(str), arc_df['arc_year']))

    candidate_df['dob_flag'] = ''

    def calculate_verification_flag(row):
        dob = row['dob']
        verification_flag = ''
        
        if dob > dob_to_date:
            verification_flag = 'U'
        elif dob_from_date <= dob <= dob_to_date:
            verification_flag = '9'
        elif dob < dob_from_date:
            agerelax_code = row['agerelax_code']
            
            if pd.isna(agerelax_code) or agerelax_code == '':
                agerelax_code = '99'
            
            if isinstance(agerelax_code, str) and len(agerelax_code.strip()) == 1:
                agerelax_code = agerelax_code.strip()
            
            age_rlx_year = arc_year_dict.get(agerelax_code, 0)
            
            if agerelax_code == '6':
                ex_service_years = row['exsm_yrs']
                ex_service_months = row['exsm_months']
                ex_service_days = row['exsm_days']
                age_rlx_year += int(ex_service_years) if ex_service_years else 0
                new_dob = dob + pd.DateOffset(years=age_rlx_year, months=ex_service_months, days=ex_service_days)
            
            else:
                extract_year = dob.year
                extract_month = dob.month
                extract_day = dob.day
                new_year = extract_year + int(age_rlx_year)
                
                if extract_month == 2 and extract_day == 29:
                    extract_day = 28
            
                new_dob = pd.to_datetime(f"{new_year}-{extract_month}-{extract_day}", format='%Y-%m-%d')
                
            if new_dob > dob_from_date:
                if len(agerelax_code) < 2:
                    verification_flag = '0' + agerelax_code
                else:
                    verification_flag = agerelax_code
            else:
                verification_flag = '99'

        return verification_flag

    sorted_candidates = candidate_df[(candidate_df['merit'].notnull())]
    #sorted_candidates = candidate_df[(candidate_df['merit'] != 0)]
    
    sorted_candidates['dob_flag'] = sorted_candidates.apply(calculate_verification_flag, axis=1)

    candidate_df.update(sorted_candidates)
    
    return f"dob_flag updated successfully"

#### EXECUTION

In [29]:
get_dob_flag(candidate_df, arc_df)

'dob_flag updated successfully'

In [30]:
candidate_df[['rollno', 'dob_flag']].head()

       rollno dob_flag
0  7204015544        9
1  7204012107       01
2  2405116873        9
3  3206088844        9
4  3008017298        9

In [31]:
candidate_df['dob_flag'].unique()

array(['9', '01', '06', '03', '02', '10', '12', '05', '04', '11', '99',
       '08', '09'], dtype=object)

In [32]:
none_values = candidate_df[candidate_df['dob_flag'] == '99'].shape[0]
print(none_values)

198

In [35]:
#candidate_df.loc[candidate_df['rollno'] == 9213011384, 'dob_flag'] = '06'

candidate_df[candidate_df['rollno'] == 9213011384][['merit', 'dob', 'dob_flag']]

#candidate_df[candidate_df['rollno'] == 9213011384 ]

       merit        dob dob_flag
30882  31726 1991-03-23       06

In [36]:
# If dob_flag is a string
none_values = candidate_df[candidate_df['dob_flag'] == '99'][['merit','cat1','cat2','cat3','agerelax_code','exsm_yrs','exsm_months','dob']]

# Display first 10 rows
print(none_values.head(10))

      merit cat1 cat2 cat3 agerelax_code  exsm_yrs  exsm_months        dob
801   34462    6    3                  2        19            7 1987-05-01
887   29896    6    3                  2        14           11 1988-01-01
1148  31163    0    3                  8        20            0 1982-10-15
1638  32904    6    3                  8        26            0 1980-04-01
2027  31165    6    3                  2        20            0 1977-11-16
2108  33727    6    3                  2        22            0 1983-03-17
2234  34264    6    3                  2        20            8 1980-09-10
2587  32944    9    3                  8        20            0 1983-04-07
2632  33280    6    3                  2        28            7 1975-06-15
2642  32306    6    3                  2        17            0 1986-07-15

### CATSEL DOB FLAG

#### PREREQUISITES

In [37]:
arc_df['arc_code'] = arc_df['arc_code'].astype(str)

mask = arc_df['arc_cat2'].isnull()
arc_df.loc[mask, 'arc_cat2'] = ''

mask = arc_df['arc_cat3'].isnull()
arc_df.loc[mask, 'arc_cat3'] = ''

In [38]:
arc_df['arc_code'] = arc_df['arc_code'].apply(lambda x: str(x).zfill(2))

#### CODE

In [39]:
def get_catsel_dob(candidate_df, arc_df):
    dob_from_date = pd.to_datetime('08/01/1997', format="%m/%d/%Y")
    
    dob_flag = 'dob_flag'
    catsel_dob_flag = 'catsel_dob_flag'

    candidate_df[catsel_dob_flag] = ''
    
    #filtered_and_sorted_candidates = candidate_df[(candidate_df['merit'].notnull()) 
    filtered_and_sorted_candidates = candidate_df[(candidate_df['merit'] != 0) 
    & (candidate_df[dob_flag].notnull()) 
    & (candidate_df[dob_flag] != '')]
    
    def calculate_catsel_dob(row, dob_flag_name):
        dob_flag = row[dob_flag_name]
       
        if dob_flag is not None and dob_flag != '' and dob_flag != '9':
            matching_rows = arc_df[arc_df['arc_code'] == dob_flag]
            if not matching_rows.empty:
                catsel = matching_rows.iloc[0]
                catsel_cat1 = catsel['arc_cat1'].split(',')
                catsel_cat2 = catsel['arc_cat2'].split(',')
                catsel_cat3 = catsel['arc_cat3'].split(',')
                catsel_gender = catsel['arc_gender'].split(',')
                condition = (str(row['cat1']) in catsel_cat1) & (str(int(row['gender'])) in catsel_gender)
                catsel_dob = ''
                if row['cat2'] == '3' and row['cat2'] in catsel_cat2:
                    catsel_dob = row['cat2']
                else:
                    if pd.isnull(catsel['arc_year_against_ur']):
                        catsel['arc_year_against_ur'] = 0
                    dob_datetime = pd.to_datetime(row['dob'])
                    extract_year = dob_datetime.year
                    extract_month = dob_datetime.month
                    extract_day = dob_datetime.day
                    if (extract_day == 29) and (extract_month == 2):
                        extract_day = 28
                    new_year = extract_year + int(catsel['arc_year_against_ur'])
                    new_dob = pd.to_datetime(f'{new_year}-{extract_month}-{extract_day}')
                    catsel_dob_decision = new_dob > dob_from_date
                    if (str(row['cat3']) in catsel_cat3 and str(row['cat3']) != ''):
                        if catsel_dob_decision:
                            catsel_dob = '9'
                        else:
                            catsel_dob = row['cat3']  
                    else:
                        catsel_dob = '9' if catsel_dob_decision else row['cat1']
                return catsel_dob if condition else ''
            else:
                return ''
        else:
            return dob_flag
    
    filtered_and_sorted_candidates[catsel_dob_flag] = filtered_and_sorted_candidates.apply(calculate_catsel_dob, args = (dob_flag, ), axis=1)
    candidate_df.update(filtered_and_sorted_candidates)
    
    print('Successfully updated ' + catsel_dob_flag)

#### EXECUTION

In [40]:
get_catsel_dob(candidate_df, arc_df)

C:\Users\SalauddinKhan\AppData\Local\Temp\ipykernel_17748\2065129407.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_and_sorted_candidates[catsel_dob_flag] = filtered_and_sorted_candidates.apply(calculate_catsel_dob, args = (dob_flag, ), axis=1)

Successfully updated catsel_dob_flag

In [41]:
candidate_df[['rollno', 'catsel_dob_flag']].head()

       rollno catsel_dob_flag
0  7204015544               9
1  7204012107               1
2  2405116873               9
3  3206088844               9
4  3008017298               9

In [42]:
candidate_df['catsel_dob_flag'].unique()

array(['9', '1', '3', '6', '2', '', '7', '5', '4', '8'], dtype=object)

In [43]:
candidate_df[candidate_df['rollno'] == 9213011384 ][['merit','dob_flag','catsel_dob_flag']]

       merit dob_flag catsel_dob_flag
30882  31726       06               3

### CATSEL FLAG

#### CODE

In [44]:
def get_catsel(candidate_df, medium):
    
    if medium == 'LDC':
        cutoff_flag = 'cutoff_flag_ldc'
    elif medium == 'DEO':
        cutoff_flag = 'cutoff_flag_deo'
    elif medium == 'DEO_A':
        cutoff_flag = 'cutoff_flag_deo_a'
    else:
        return "Incorrect medium entered"


    catsel_flag = 'catsel_'+medium.lower()
    candidate_df[catsel_flag] = ''
    
    #candidates = candidate_df[candidate_df['merit'].notnull()].sort_values(by='rollno')
    candidates = candidate_df[candidate_df['merit'] != 0].sort_values(by='rollno')

    
    def update_cutoff_flag(candidate_record):
        if candidate_record['cat2'] == '3' and candidate_record['exs_reservation'] == 'No':
            candidate_record[cutoff_flag] = candidate_record[cutoff_flag].replace('3', '').strip()

        if candidate_record['catsel_dob_flag'] in ['1', '2', '6', '4', '5', '7', '8']:
            return candidate_record[cutoff_flag].replace('9', '').strip()
        elif pd.isna(candidate_record['catsel_dob_flag']) or candidate_record['catsel_dob_flag'] == '':
            return ''
        else:
            return candidate_record[cutoff_flag]
    
    candidate_df[catsel_flag] = candidates.apply(update_cutoff_flag, axis=1)

    return 'Successfully updated '+ catsel_flag

#### EXECUTION

##### For LDC

In [45]:
medium = 'LDC'
get_catsel(candidate_df, medium)

'Successfully updated catsel_ldc'

In [46]:
candidate_df[['rollno', 'catsel_ldc']].head()

       rollno catsel_ldc
0  7204015544
1  7204012107          1
2  2405116873          1
3  3206088844         96
4  3008017298          6

In [47]:
candidate_df['catsel_ldc'].unique()

array(['', '1', '96', '6', '90', '9', '2', '91', '4', '0', '3', '92', '8',
       '7', '5', nan, '918', '14', '914', '964', '924', '97', '967', '93',
       '27', '907', '94', '24', '17', '98', '38', '917', '913', '05',
       '04', '07', '927', '64', '904', '965', '968', '35', '65'],
      dtype=object)

##### For DEO

In [48]:
medium = 'DEO'
get_catsel(candidate_df, medium)

'Successfully updated catsel_deo'

In [49]:
candidate_df[['rollno', 'catsel_deo']].head()

       rollno catsel_deo
0  7204015544
1  7204012107
2  2405116873
3  3206088844
4  3008017298

In [50]:
candidate_df['catsel_deo'].unique()

array(['', '90', '9', '1', '3', '2', '6', '96', '0', '92', '91', '4', nan,
       '14', '93', '964'], dtype=object)

##### FOR DEO_A

In [31]:
# medium = 'DEO_A'
# get_catsel(candidate_df, medium)

'Successfully updated catsel_deo_a'

In [ ]:
# candidate_df[['rollno', 'catsel_deo_a']].head()

### ALLOCATION

#### PREREQUISITES

In [51]:
cand = candidate_df.copy()
vac = vacancy_df.copy()

In [52]:
cand[['allocated_category', 'allocated_dept', 'allocated_against_ur']] = None

In [53]:
mask = cand['post_pref'].isnull()
cand.loc[mask, 'post_pref'] = ''
cand.loc[~mask, 'post_pref'] = cand.loc[~mask, 'post_pref'].astype(str)

mask = cand['catsel_ldc'].isnull()
cand.loc[mask, 'catsel_ldc'] = ''
cand.loc[~mask, 'catsel_ldc'] = cand.loc[~mask, 'catsel_ldc'].astype(str)

mask = cand['catsel_deo'].isnull()
cand.loc[mask, 'catsel_deo'] = ''
cand.loc[~mask, 'catsel_deo'] = cand.loc[~mask, 'catsel_deo'].astype(str)

#mask = cand['catsel_deo_a'].isnull()
#cand.loc[mask, 'catsel_deo_a'] = ''
#cand.loc[~mask, 'catsel_deo_a'] = cand.loc[~mask, 'catsel_deo_a'].astype(str)

mask = cand['catsel_dob_flag'].isnull()
cand.loc[mask, 'catsel_dob_flag'] = ''
cand.loc[~mask, 'catsel_dob_flag'] = cand.loc[~mask, 'catsel_dob_flag'].astype(str)

In [54]:
vac['allocated_hc'] = 0
vac['allocated_hc_prev'] = 0

In [55]:
vac['left_vacancy'] = vac['current']
vacancy_dict = {}
vac['key'] = vac['department_code'].astype(str) + vac['category_code'].astype(str)

for index, row in vac.iterrows():
    key = row['key']
    vacancy_dict[key] = row.to_dict()

#### CODE

In [242]:
# def update_allocation(candidates_df, category, department, allocated_against_ur, candidate, vacancy_dict):
#     if str(category) in ['3', '4', '5', '7', '8']:
    
#         key_cat1 = str(department) + str(candidate['cat1'])
        
#         if (key_cat1 not in vacancy_dict.keys()) or (vacancy_dict[key_cat1]['initial_vacancy'] == 0):
#             keyCat2= str(department) + '9' 
            
#             if (keyCat2 not in vacancy_dict.keys()) or (vacancy_dict[keyCat2]['initial_vacancy'] == 0):
#                 return False
#             else:
#                 if vacancy_dict[keyCat2]['allocated_hc'] != vacancy_dict[keyCat2]['initial_vacancy']:
#                     vacancy_dict[keyCat2]['allocated_hc'] += 1
#                 allocated_against_ur = '1'
#         else:
#             if vacancy_dict[key_cat1]['allocated_hc'] != vacancy_dict[key_cat1]['initial_vacancy']:
#                 vacancy_dict[key_cat1]['allocated_hc'] += 1
#             else :
#                 keyCat2= str(department) + '9'
#                 if candidate['catsel_dob_flag'] == '9' and keyCat2 in vacancy_dict.keys():
#                     if vacancy_dict[keyCat2]['allocated_hc'] != vacancy_dict[keyCat2]['initial_vacancy']:
#                         vacancy_dict[keyCat2]['allocated_hc'] += 1
#                         allocated_against_ur = '1'
#                     else:
#                         return False      
#                 else:
#                     return False
                    
#     candidates_df.loc[candidate.name, 'allocated_category'] = category
#     candidates_df.loc[candidate.name, 'allocated_dept'] = department
#     candidates_df.loc[candidate.name, 'allocated_against_ur'] = allocated_against_ur
    
#     return True

In [56]:
def update_allocation(candidates_df, category, department, allocated_against_ur, candidate, vacancy_dict):
    if str(category) in ['3', '4', '5', '7', '8']:
    
        key_cat1 = str(department) + str(candidate['cat1'])
        
        if (key_cat1 not in vacancy_dict.keys()) or (vacancy_dict[key_cat1]['initial_vacancy'] == 0):
            keyCat2= str(department) + '9' 
            
            if (keyCat2 not in vacancy_dict.keys()) or (vacancy_dict[keyCat2]['initial_vacancy'] == 0):
                return False
            else:
                if vacancy_dict[keyCat2]['allocated_hc'] != vacancy_dict[keyCat2]['initial_vacancy']:
                    vacancy_dict[keyCat2]['allocated_hc'] += 1
                    allocated_against_ur = '1'
                else:
                        return False 
        else:
            if vacancy_dict[key_cat1]['allocated_hc'] != vacancy_dict[key_cat1]['initial_vacancy']:
                vacancy_dict[key_cat1]['allocated_hc'] += 1
            else :
                keyCat2= str(department) + '9'
                if candidate['catsel_dob_flag'] == '9' and keyCat2 in vacancy_dict.keys():
                    if vacancy_dict[keyCat2]['allocated_hc'] != vacancy_dict[keyCat2]['initial_vacancy']:
                        vacancy_dict[keyCat2]['allocated_hc'] += 1
                        allocated_against_ur = '1'
                    else:
                        return False      
                else:
                    return False
                    
    candidates_df.loc[candidate.name, 'allocated_category'] = category
    candidates_df.loc[candidate.name, 'allocated_dept'] = department
    candidates_df.loc[candidate.name, 'allocated_against_ur'] = allocated_against_ur
    
    return True

In [57]:
def allocate_candidates(candidates_df, vacancy_dict):
     
    #filtered_candidates = candidates_df[(candidates_df['merit'].notnull())].sort_values(by='merit')
    filtered_candidates = candidates_df[(candidates_df['merit'] != 0)].sort_values(by='merit')

    for idx, candidate in filtered_candidates.iterrows():
        allocated = False
        roll = candidate['rollno']
        department_preference = candidate['post_pref']
        DOB = candidate['dob']
        
        for department in department_preference.split(','):

            if department.startswith("L"):
                catsel = candidate['catsel_ldc']
            elif department.startswith("D"):
                catsel = candidate['catsel_deo']
                #if department == 'D53':
                 #   catsel = candidate['catsel_deo']
                #else:
                    #catsel = candidate['catsel_deo_a']

            else:
                continue
            
            for category in catsel:
                key =  str(department) + str(category)
                
                allocated_against_ur = ''
                
                if key in vacancy_dict and vacancy_dict[key]['current'] > 0:
                                
                    allocated = update_allocation(candidates_df, category, department, allocated_against_ur, candidate, vacancy_dict)
                    if allocated:
                        vacancy_dict[key]['current'] -= 1
                        vacancy_dict[key]['allocated'] += 1
                        break
            if allocated:
                break

    return vacancy_dict

In [58]:
def adjust_vacancy(candidates_df, vacancy_df):
    vacancy_df['current'] = vacancy_df['initial_vacancy'] - vacancy_df['allocated_hc']
    vacancy_df['allocated'] = 0
    vacancy_df['left_vacancy'] = 0
        
    vacancy_df['allocated_hc_prev'] = vacancy_df['allocated_hc']
    vacancy_df['allocated_hc'] = 0

    return vacancy_df

In [41]:
# def find_lowest_marks(candidates_df, vacancy_df):
#     vc = []
#     vacancy_df['min_total'] = 0
#     for _, row in vacancy_df.iterrows():
#         lmv = {
#             "department_code": str(row["department_code"]),
#             "category_code": str(row["category_code"])
#         }

#         vc.append(lmv)

#     print("Vector size--->", len(vc))

#     for lmv1 in vc:
#         highest_merit_candidate = get_highest_merit_candidate(candidates_df, lmv1["department_code"], lmv1["category_code"])
#         update_vacancy_table(vacancy_df, lmv1["department_code"], lmv1["category_code"], highest_merit_candidate)

# def get_highest_merit_candidate(candidates_df, department_code, category_code):
#     highest_merit_candidate = None

#     mask = (
#         (candidates_df["allocated_dept"] == str(department_code))
#         & (candidates_df["allocated_category"] == str(category_code))
#     )

#     filtered_cand = candidates_df[mask]

#     if not filtered_cand.empty:
#         highest_merit_candidate = filtered_cand.loc[filtered_cand['merit'].idxmax()]
    
#     return highest_merit_candidate

# def update_vacancy_table(vacancy_df, department_code, category_code, highest_merit_candidate):
#     key = str(department_code) + str(category_code)
#     mask = (vacancy_df['key'] == key)
#     vacancy = vacancy_df.loc[mask].copy()

#     if highest_merit_candidate is not None:
#         vacancy["min_marks"] = highest_merit_candidate['total']
#         vacancy["min_paper1"] = highest_merit_candidate['tier1_final']
#         vacancy["min_marks_cand_dob"] = highest_merit_candidate['dob']
#         vacancy["min_marks_section1"] = highest_merit_candidate['score_s1']
        
#         vacancy_df.loc[mask, 'min_marks'] = vacancy["min_marks"]
#         vacancy_df.loc[mask, 'min_paper1'] = vacancy["min_paper1"]
#         vacancy_df.loc[mask, 'min_marks_cand_dob'] = vacancy["min_marks_cand_dob"]
#         vacancy_df.loc[mask, 'min_marks_section1'] = vacancy["min_marks_section1"]

In [59]:
def find_lowest_marks(candidates_df, vacancy_df):
    vc = []
    vacancy_df['min_total'] = 0
    for _, row in vacancy_df.iterrows():
        lmv = {
            "department_code": str(row["department_code"]),
            "category_code": str(row["category_code"])
        }

        vc.append(lmv)

    print("Vector size--->", len(vc))

    for lmv1 in vc:
        highest_merit_candidate = get_highest_merit_candidate(candidates_df, lmv1["department_code"], lmv1["category_code"])
        update_vacancy_table(vacancy_df, lmv1["department_code"], lmv1["category_code"], highest_merit_candidate)

def get_highest_merit_candidate(candidates_df, department_code, category_code):
    highest_merit_candidate = None

    mask = (
        (candidates_df["allocated_dept"] == str(department_code))
        & (candidates_df["allocated_category"] == str(category_code))
    )

    filtered_cand = candidates_df[mask]

    if not filtered_cand.empty:
        highest_merit_candidate = filtered_cand.loc[filtered_cand['merit'].idxmax()]
    
    return highest_merit_candidate

def update_vacancy_table(vacancy_df, department_code, category_code, highest_merit_candidate):
    key = str(department_code) + str(category_code)
    mask = (vacancy_df['key'] == key)
    vacancy = vacancy_df.loc[mask].copy()

    if highest_merit_candidate is not None:
        vacancy["min_marks"] = highest_merit_candidate['total']
        vacancy["min_paper1"] = highest_merit_candidate['tier1_final']
        vacancy["min_marks_cand_dob"] = highest_merit_candidate['dob']
        vacancy["min_marks_section1"] = highest_merit_candidate['section1']
        vacancy["min_marks_section2"] = highest_merit_candidate['section2']
        
        vacancy_df.loc[mask, 'min_marks'] = vacancy["min_marks"]
        vacancy_df.loc[mask, 'min_paper1'] = vacancy["min_paper1"]
        vacancy_df.loc[mask, 'min_marks_cand_dob'] = vacancy["min_marks_cand_dob"]
        vacancy_df.loc[mask, 'min_marks_section1'] = vacancy["min_marks_section1"]
        vacancy_df.loc[mask, 'min_marks_section2'] = vacancy["min_marks_section2"]

#### EXECUTION

##### FIRST TIME

In [60]:
upd_vacancy_dict = allocate_candidates(cand, vacancy_dict)

In [67]:
cand[cand['allocated_category'].notnull()].shape[0]

3421

In [62]:
cand['allocated_category'].unique()

array([None, '1', '6', '9', '2', '3', '0', '8', '7', '4', '5'],
      dtype=object)

##### ADJUST LOOP

In [63]:
updated_vacancy_df = pd.DataFrame.from_dict(upd_vacancy_dict, orient='index')
i =0
while (updated_vacancy_df['allocated_hc_prev'] != updated_vacancy_df['allocated_hc']).any():
    i+=1
    print('Attempt-'+str(i))
    upd_vacancy_df = adjust_vacancy(cand, updated_vacancy_df)
    
    upd_vacancy_df['left_vacancy'] = upd_vacancy_df['current']
    vacancy_dict = {}
    upd_vacancy_df['key'] = upd_vacancy_df['department_code'].astype(str) + upd_vacancy_df['category_code'].astype(str)
    
    for index, row in upd_vacancy_df.iterrows():
        key = row['key']
        vacancy_dict[key] = row.to_dict()
    cand[['allocated_category', 'allocated_dept', 'allocated_against_ur']] = None
    upd_vacancy_dict = allocate_candidates(cand, vacancy_dict)
    updated_vacancy_df = pd.DataFrame.from_dict(upd_vacancy_dict, orient='index')

Attempt-1

In [64]:
updated_vacancy_df['left_vacancy'] = updated_vacancy_df['current']
updated_vacancy_df['current'] = updated_vacancy_df['left_vacancy'] + updated_vacancy_df['allocated']

In [65]:
find_lowest_marks(cand, updated_vacancy_df)

Vector size---> 530

#### WRITING TO CSV

In [47]:
# cand.to_csv(r"C:\Users\Aviral Chaudhary\Downloads\RP_CHSL_23\allocated_candidates.csv", index = False)
# cand[cand['allocated_category'].notnull()].to_csv(r"C:\Users\Aviral Chaudhary\Downloads\RP_CHSL_23\only_allocated_candidates.csv", index = False)
# updated_vacancy_df.to_csv(r"C:\Users\Aviral Chaudhary\Downloads\RP_CHSL_23\allocated_vacancy.csv", index = False)

In [68]:
cand.to_csv(r"C:\Users\SalauddinKhan\Desktop\PYTHON\allocated_candidates5.csv", index = False)
cand[cand['allocated_category'].notnull()].to_csv(r"C:\Users\SalauddinKhan\Desktop\PYTHON\only_allocated5.csv", index = False)
updated_vacancy_df.to_csv(r"C:\Users\SalauddinKhan\Desktop\PYTHON\allocated_vacancy5.csv", index = False)

In [262]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [ ]:
cand.to_excel(r"C:\Users\SalauddinKhan\Desktop\PYTHON\allocated_candidates.xlsx", index = False)
cand[cand['allocated_category'].notnull()].to_csv(r"C:\Users\SalauddinKhan\Desktop\PYTHON\only_allocated.xlsx", index = False)
updated_vacancy_df.to_csv(r"C:\Users\SalauddinKhan\Desktop\PYTHON\allocated_vacancy.xlsx", index = False)

In [264]:
!pip install xlsxwriter

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting xlsxwriter
  Downloading XlsxWriter-3.2.2-py3-none-any.whl.metadata (2.8 kB)
Downloading XlsxWriter-3.2.2-py3-none-any.whl (165 kB)
Installing collected packages: xlsxwriter
Successfully installed xlsxwriter-3.2.2

In [69]:
cand.to_excel(r"C:\Users\SalauddinKhan\Desktop\PYTHON\allocated_candidates_new5.xlsx", index = False,engine='xlsxwriter')
cand[cand['allocated_category'].notnull()].to_excel(r"C:\Users\SalauddinKhan\Desktop\PYTHON\only_allocated_new5.xlsx", index = False,engine='xlsxwriter')
updated_vacancy_df.to_excel(r"C:\Users\SalauddinKhan\Desktop\PYTHON\allocated_vacancy_new5.xlsx", index = False,engine='xlsxwriter')