### UNDERSTANDING RESULT

#### 1.) There will be 2 flags for Merit and Cutoff i.e 'C' (Civil) and 'EM' (Electrical_Mechanical) because vacancy for Civil is different and Electrical Mechanical is same and different as well so combined for E and M

#### 2.) There will be 2 DOB and Catsel DOB flags since there are 2 age groups i.e. 18-30 and 18-32

#### 3.) There will be 4 Catsel flag i.e. Civil 18-30, Civil 18-32, Electrical Mechanical 18-30, Electrical Mechanical 18-32

### PREREQUISITES

In [1]:
import pandas as pd

In [2]:
candidate_df = pd.read_csv(r"C:\Users\AshutoshMishra\Desktop\JE 2024 FINAL RESULT\candidates_je2024.csv")
vacancy_df = pd.read_csv(r"C:\Users\AshutoshMishra\Desktop\JE 2024 FINAL RESULT\vacancy_table_je2024.csv")

C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\2002905733.py:1: DtypeWarning: Columns (27,28,29,68,82) have mixed types. Specify dtype option on import or set low_memory=False.
  candidate_df = pd.read_csv(r"C:\Users\AshutoshMishra\Desktop\JE 2024 FINAL RESULT\candidates_je2024.csv")

In [3]:
candidate_df.rename(columns={'p1_subject': 'post_applied'}, inplace=True)

In [4]:
candidate_df.columns

Index(['id', 'registrationNo', 'emailId', 'phoneNo', 'name', 'newname',
       'father_name', 'mother_name', 'dob2', 'ageAsOnDob', 'Gender', 'isPwbd',
       'typeOfDisability', 'code', 'markOfIdentification', 'tenthRollNumber',
       'tenthYearOfPassing', 'centreName1', 'centreName2', 'centreName3',
       'isBenchmarkDisabilityVh', 'isBenchmarkDisabilityOh',
       'isPhysicalLimitToWrite', 'isScribe', 'isOwnScribe', 'scribeMedium',
       'isEsm', 'dojOfEsm', 'dodOfEsm', 'lengthOfService', 'isCivilPost',
       'dojOfCivilPost', 'isAgeRelaxation', 'arccode', 'description',
       'isPersonalInfoAccess', 'regionCode', 'permanentAddress',
       'permanentStateName', 'permanentStateId', 'permanentDistrictName',
       'permanentDistrictId', 'permanentPincode', 'presentAddress',
       'presentStateName', 'presentStateId', 'presentDistrictName',
       'presentDistrictId', 'presentPincode', 'jePostCategory',
       'highestQualification', 'subject', 'Nationality', 'ApplicationStatus',
       'numberOfAttempts', 'ipAddress', 'isActive', 'createdAt', 'updatedAt',
       'ownScribeWithdrawal', 'scribeRegNo', 'isExempted', 'rollno',
       'cand_name', 'cat1', 'cat2', 'cat3', 'exsm_length', 'exs_reservation',
       'arc_code', 'p1_gi', 'p1_ga', 'p1_gen_engg', 'p1_score',
       'p1_normalized', 'paper1', 'post_applied', 'p2_score', 'p2_normalized',
       'paper2', 'p2_subject', 'total', 'debarred', 'rejection_provision',
       'remarks', 'gender', 'dob', 'post_pref'],
      dtype='object')

#### ARC Table from Notice

In [5]:
arc_dict = {'arc_code': ['1', '2', '3', '4', '5', '6', '8', '9'], 
            'arc_year': [5, 3, 10, 13, 15, 3, 3, 8],
            'arc_cat1': ['1,2', '6', '0,9', '6', '1,2', '0,1,2,6,9', '0,6,9', '1,2'],
            'arc_cat2': ['', '', '', '', '', '3', '', ''],
            'arc_cat3': ['', '', '4,5,8', '4,5,8', '4,5,8', '', '', ''],
            'arc_gender': ['1,2,3', '1,2,3', '1,2,3', '1,2,3', '1,2,3', '1,2,3', '1,2,3', '1,2,3'],
            'arc_year_against_ur': [ None, None, 10, 10, 10, None, 3, 3]
           }

arc_df = pd.DataFrame(arc_dict)

#### CUTOFF Table from Notice

In [6]:
cutoff_dict = [
    {'category': 1, 'paper1': 101.85006, 'paper2': 60, 'flag': 'cutoff_c'},
    {'category': 2, 'paper1': 97.83364, 'paper2': 60, 'flag': 'cutoff_c'},
    {'category': 6, 'paper1': 116.82650, 'paper2': 75, 'flag': 'cutoff_c'},
    {'category': 9, 'paper1': 122.92909, 'paper2': 90, 'flag': 'cutoff_c'},
    {'category': 4, 'paper1': 84.29586, 'paper2': 60, 'flag': 'cutoff_c'},
    {'category': 5, 'paper1': 40.07098, 'paper2': 60, 'flag': 'cutoff_c'},
    {'category': 8, 'paper1': 48.88704, 'paper2': 60, 'flag': 'cutoff_c'},
    {'category': 3, 'paper1': 999.99, 'paper2': 60, 'flag': 'cutoff_c'},
    {'category': 0, 'paper1': 109.20412, 'paper2': 75, 'flag': 'cutoff_c'},
    {'category': 1, 'paper1': 112.97309, 'paper2': 60, 'flag': 'cutoff_em'},
    {'category': 2, 'paper1': 101.37117, 'paper2': 60, 'flag': 'cutoff_em'},
    {'category': 6, 'paper1': 131.27256 , 'paper2': 75, 'flag': 'cutoff_em'},
    {'category': 9, 'paper1': 132.06654, 'paper2': 90, 'flag': 'cutoff_em'},
    {'category': 4, 'paper1': 86.18973, 'paper2': 60, 'flag': 'cutoff_em'},
    {'category': 5, 'paper1': 43.62910, 'paper2': 60, 'flag': 'cutoff_em'},
    {'category': 8, 'paper1': 58.92633, 'paper2': 60, 'flag': 'cutoff_em'},
    {'category': 3, 'paper1': 999.99, 'paper2': 60, 'flag': 'cutoff_em'},
    {'category': 0, 'paper1': 120.13213, 'paper2': 75, 'flag': 'cutoff_em'}
]

cutoff_df = pd.DataFrame(cutoff_dict)

In [7]:
candidate_df['dob'] = pd.to_datetime(candidate_df['dob'])

In [8]:
candidate_df['post_applied'].unique()

array(['CIVIL', 'ELECT', 'MECH'], dtype=object)

### MERIT

#### CODE

In [9]:
def get_merit(candidate_df, medium):    
    if medium == 'C':
        post = ['CIVIL']
        merit = 'merit_c'
    elif medium == 'EM':
        post = ['ELECT', 'MECH']
        merit = 'merit_em'
    else:
        return "Enter Correct Medium i.e. Either 'C' or 'EM'"

    candidate_df[merit] = None
    
    candidates =  candidate_df[(candidate_df['total'].notnull()) & (candidate_df['rejection_provision'] == 'C') &
    (candidate_df['post_applied'].isin(post))].sort_values(by = ['total', 'paper2', 'dob', 'cand_name'], ascending=[False, False, True, True])
    
    candidates[merit] = range(1, len(candidates) + 1)

    rollno_to_merit = candidates.set_index('rollno')[merit].to_dict()
    candidate_df[merit] = candidate_df['rollno'].map(rollno_to_merit)
    
    return "{flag_name} updated successfully for {merit} candidates".format(
        flag_name=merit,
        merit=len(candidates))

#### FOR CIVIL

In [10]:
medium = 'C'
get_merit(candidate_df, medium)

'merit_c updated successfully for 10432 candidates'

In [13]:
candidate_df[candidate_df['merit_c'].notnull()][['merit_c']].head()

   merit_c
0    10192
1     5894
2     6530
3     8944
4     9486

In [12]:
candidate_df['merit_c'] = candidate_df['merit_c'].astype('Int64')

#### FOR MECHANICAL AND ELECTRICAL

In [14]:
medium = 'EM'
get_merit(candidate_df, medium)

'merit_em updated successfully for 3820 candidates'

In [15]:
candidate_df[candidate_df['merit_em'].notnull()][['merit_em']].head()

     merit_em
181    1836.0
308    3368.0
317    1871.0
391    3739.0
411    3815.0

In [16]:
candidate_df['merit_em'] = candidate_df['merit_em'].astype('Int64')

In [17]:
candidate_df['cat3'] = candidate_df['cat3'].fillna(0)

In [18]:
candidate_df['cat3'].unique()

array([0., 4., 5., 8.])

In [19]:
candidate_df['cat3'] = candidate_df['cat3'].astype('Int64')

### CUTOFF FLAG

#### CODE

In [20]:
def get_cutoff(cutoff_df, candidate_df, medium):
    
    if medium == 'C':
        post = ['CIVIL']
        merit = 'merit_c'
        cutoff = 'cutoff_c'
    elif medium == 'EM':
        post = ['ELECT', 'MECH']
        merit = 'merit_em'
        cutoff = 'cutoff_em'
    else:
        return "Enter Correct Medium i.e. Either 'C' or 'EM'"

    
    candidate_df[cutoff] = None
    cutoff_dict = {}

    for index, row in cutoff_df[cutoff_df['flag'].astype(str) == cutoff].iterrows():
        category = int(row['category'])
        paper1 = float(row['paper1'])
        paper2 = float(row['paper2'])
        cutoff_dict[category] = [paper1, paper2]
    
    sorted_candidates = candidate_df[candidate_df[merit].notnull()].sort_values(by=merit)

    def calculate_cutoff(candidate):
        cutoff = ''

        if (candidate['paper1'] >= cutoff_dict[9][0]) & (candidate['paper2'] >= cutoff_dict[9][1]):
            cutoff += '9'

        for cat in [0, 1, 2, 6]:
            if (candidate['cat1'] == cat) & (cat in cutoff_dict):
                if (candidate['paper1'] >= cutoff_dict[cat][0]) & (candidate['paper2'] >= cutoff_dict[cat][1]):
                    cutoff += str(cat)

        if (candidate['cat2'] == 3) & (3 in cutoff_dict):
            if (candidate['paper1'] >= cutoff_dict[3][0]) & (candidate['paper2'] >= cutoff_dict[3][1]):
                cutoff += '3'

        for cat in [4, 5, 7, 8]:
            if (candidate['cat3'] == cat) & (cat in cutoff_dict):
                if (candidate['paper1'] >= cutoff_dict[cat][0]) & (candidate['paper2'] >= cutoff_dict[cat][1]):
                    cutoff += str(cat)

        return cutoff

    sorted_candidates[cutoff] = sorted_candidates.apply(calculate_cutoff, axis=1)
    candidate_df.update(sorted_candidates)

    return f"{cutoff} updated successfully"

#### For C

In [21]:
medium = 'C'
get_cutoff(cutoff_df, candidate_df, medium)

'cutoff_c updated successfully'

In [22]:
candidate_df[candidate_df['cutoff_c'].notnull()][['cutoff_c']].head()

  cutoff_c
0        2
1        6
2        6
3        1
4        2

In [23]:
cutoff_c_counts_me = candidate_df['cutoff_c'].value_counts()
cutoff_c_counts_me

cutoff_c
96     2549
1      1956
6      1517
9       963
0       932
2       928
90      701
91      373
92      181
4       135
5       118
8        36
         29
14        4
64        3
05        2
904       1
15        1
04        1
964       1
94        1
Name: count, dtype: int64

#### For EM

In [24]:
medium = 'EM'
get_cutoff(cutoff_df, candidate_df, medium)

'cutoff_em updated successfully'

In [25]:
candidate_df[candidate_df['cutoff_em'].notnull()][['cutoff_em']].head()

    cutoff_em
181         6
308         2
317        96
391         8
411

In [26]:
cutoff_em_counts_me = candidate_df['cutoff_em'].value_counts()
cutoff_em_counts_me

cutoff_em
96     1262
1       720
9       470
0       352
2       301
90      290
91      130
4        84
6        82
5        64
92       28
8        16
         14
964       2
04        2
64        1
94        1
14        1
Name: count, dtype: int64

### DOB FLAG

#### PREREQIUSITES

In [27]:
candidate_df.rename(columns={'arc_code': 'agerelax_code'}, inplace=True)

In [51]:
# mask = candidate_df['cat1'].isnull()
# candidate_df.loc[mask, 'cat1'] = ''
# candidate_df.loc[~mask, 'cat1'] = candidate_df.loc[~mask, 'cat1'].astype(int).astype(str)

# mask = candidate_df['cat2'].isnull()
# candidate_df.loc[mask, 'cat2'] = ''
# candidate_df.loc[~mask, 'cat2'] = candidate_df.loc[~mask, 'cat2'].astype(int).astype(str)

# mask = candidate_df['cat3'].isnull()
# candidate_df.loc[mask, 'cat3'] = ''
# candidate_df.loc[~mask, 'cat3'] = candidate_df.loc[~mask, 'cat3'].astype(int).astype(str)

# mask = candidate_df['agerelax_code'].isnull()
# candidate_df.loc[mask, 'agerelax_code'] = ''
# candidate_df.loc[~mask, 'agerelax_code'] = candidate_df.loc[~mask, 'agerelax_code'].astype(int).astype(str)

In [28]:
mask = candidate_df['cat1'].isnull()
candidate_df.loc[mask, 'cat1'] = pd.NA
candidate_df.loc[~mask, 'cat1'] = candidate_df.loc[~mask, 'cat1'].astype('Int64').astype(str)

mask = candidate_df['cat2'].isnull()
candidate_df.loc[mask, 'cat2'] = pd.NA
candidate_df.loc[~mask, 'cat2'] = candidate_df.loc[~mask, 'cat2'].astype('Int64').astype(str)

mask = candidate_df['cat3'].isnull()
candidate_df.loc[mask, 'cat3'] = pd.NA
candidate_df.loc[~mask, 'cat3'] = candidate_df.loc[~mask, 'cat3'].astype('Int64').astype(str)

mask = candidate_df['agerelax_code'].isnull()
candidate_df.loc[mask, 'agerelax_code'] = ''
candidate_df.loc[~mask, 'agerelax_code'] = candidate_df.loc[~mask, 'agerelax_code'].astype(int).astype(str)

C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\1828556211.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['2' '6' '6' ... '6' '0' '9']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_df.loc[~mask, 'cat1'] = candidate_df.loc[~mask, 'cat1'].astype('Int64').astype(str)
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\1828556211.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['0' '0' '0' ... '0' '0' '0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_df.loc[~mask, 'cat2'] = candidate_df.loc[~mask, 'cat2'].astype('Int64').astype(str)
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\1828556211.py:14: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_df.loc[mask, 'agerelax_code'] = ''

In [29]:
candidate_df.rename(columns={'lengthOfService': 'service_period'}, inplace=True)

In [30]:
candidate_df[['exsm_yrs', 'exsm_months', 'exsm_days']] = candidate_df['service_period'].str.extract(r'(\d+) Year[s]* (\d+) Month[s]* (\d+) Day[s]*')

candidate_df[['exsm_yrs', 'exsm_months', 'exsm_days']] = candidate_df[['exsm_yrs', 'exsm_months', 'exsm_days']].apply(pd.to_numeric)

#### CODE

In [31]:
def get_dob_flag(candidate_df, arc_df, age_group):
    if age_group == '18_30':
        dob_to_date = pd.to_datetime('08/01/2006', format="%m/%d/%Y")
        dob_from_date = pd.to_datetime('08/01/1994', format="%m/%d/%Y")
        dob_flag = 'dob_'+ age_group
    elif age_group == '18_32':
        dob_to_date = pd.to_datetime('08/01/2006', format="%m/%d/%Y")
        dob_from_date = pd.to_datetime('08/01/1992', format="%m/%d/%Y")
    else:
        return "Enter Valid age group i.e. either 18_30 or 18_32"

    dob_flag = 'dob_'+ age_group

    arc_year_dict = dict(zip(arc_df['arc_code'].astype(str), arc_df['arc_year']))

    candidate_df[dob_flag] = ''

    def calculate_verification_flag(row):
        dob = row['dob']
        verification_flag = ''
        
        if dob >= dob_to_date:
            verification_flag = 'U'
        elif dob_from_date < dob < dob_to_date:
            verification_flag = '9'
        elif dob <= dob_from_date:
            agerelax_code = row['agerelax_code']
            
            if pd.isna(agerelax_code) or agerelax_code == '':
                agerelax_code = '99'
            
            if isinstance(agerelax_code, str) and len(agerelax_code.strip()) == 1:
                agerelax_code = agerelax_code.strip()
            
            age_rlx_year = arc_year_dict.get(agerelax_code, 0)
            
            if agerelax_code == '6':
                ex_service_years = row['exsm_yrs']
                ex_service_months = row['exsm_months']
                ex_service_days = row['exsm_days']
                age_rlx_year += int(ex_service_years) if ex_service_years else 0
                new_dob = dob + pd.DateOffset(years=age_rlx_year, months=ex_service_months, days=ex_service_days)
            
            else:
                extract_year = dob.year
                extract_month = dob.month
                extract_day = dob.day
                new_year = extract_year + int(age_rlx_year)
                
                if extract_month == 2 and extract_day == 29:
                    extract_day = 28
            
                new_dob = pd.to_datetime(f"{new_year}-{extract_month}-{extract_day}", format='%Y-%m-%d')
                
            if new_dob > dob_from_date:
                if len(agerelax_code) < 2:
                    verification_flag = '0' + agerelax_code
                else:
                    verification_flag = agerelax_code
            else:
                verification_flag = '99'

        return verification_flag

    sorted_candidates = candidate_df[(candidate_df['merit_c'].notnull()) | (candidate_df['merit_em'].notnull())]
    
    sorted_candidates[dob_flag] = sorted_candidates.apply(calculate_verification_flag, axis=1)

    candidate_df.update(sorted_candidates)
    
    return f"{dob_flag} updated successfully"

#### FOR 18-30

In [32]:
age_group = '18_30'
get_dob_flag(candidate_df, arc_df, age_group)

C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\1446143870.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sorted_candidates[dob_flag] = sorted_candidates.apply(calculate_verification_flag, axis=1)

'dob_18_30 updated successfully'

In [33]:
candidate_df[['rollno', 'dob_18_30']].head()

       rollno dob_18_30
0  2405106841         9
1  3010103899         9
2  4206101599         9
3  3013105205         9
4  8601109782         9

In [34]:
candidate_df['dob_18_30'].unique()

array(['9', '01', '04', '02', '99', '05', '', '06', '03', '08', '09'],
      dtype=object)

In [35]:
null_cutoff_rows = candidate_df[
    candidate_df['dob_18_30'] == ''
][['dob', 'cat1', "cat2", "cat3","cutoff_c", 'cutoff_em', 'merit_c', "merit_em", "agerelax_code","rejection_provision"]].head(10)


print(null_cutoff_rows)

            dob cat1 cat2  cat3 cutoff_c cutoff_em  merit_c  merit_em  \
204  1997-06-07    0    0     0     None      None     <NA>      <NA>
277  1994-07-04    2    0     0     None      None     <NA>      <NA>
1225 2001-08-30    2    0     0     None      None     <NA>      <NA>
1530 1996-07-28    6    0     0     None      None     <NA>      <NA>
1531 1999-07-19    2    0     0     None      None     <NA>      <NA>
1532 2000-10-19    6    0     0     None      None     <NA>      <NA>
1533 1998-01-10    6    0     0     None      None     <NA>      <NA>
1534 2000-05-13    0    0     0     None      None     <NA>      <NA>
1535 1997-01-03    6    0     0     None      None     <NA>      <NA>
1536 1992-09-08    1    0     0     None      None     <NA>      <NA>

     agerelax_code rejection_provision
204                                NaN
277              1                   D
1225                                 D
1530             2                 NaN
1531                               NaN
1532                               NaN
1533                               NaN
1534                               NaN
1535                               NaN
1536             1                 NaN

In [36]:
null_cutoff_rows = candidate_df[
    candidate_df['dob_18_30'] == '99'
][['dob', 'cat1', "cat2", "cat3","cutoff_c", 'cutoff_em', 'merit_c', "merit_em", "agerelax_code","rejection_provision"]].head(10)


print(null_cutoff_rows)

           dob cat1 cat2  cat3 cutoff_c cutoff_em  merit_c  merit_em  \
85  1994-04-23    9    0     0        9      None     7816      <NA>
129 1993-03-10    0    0     0        0      None     8602      <NA>
175 1991-02-08    6    0     0        6      None     9335      <NA>
220 1992-12-26    0    0     0        0      None     4799      <NA>
266 1993-07-04    9    0     0        9      None     3538      <NA>
305 1992-08-20    0    0     0       90      None     5214      <NA>
311 1992-09-18    0    0     0        0      None     6901      <NA>
397 1993-11-15    0    0     0       90      None      522      <NA>
400 1994-05-13    9    0     0        9      None     7844      <NA>
402 1993-04-19    9    0     0        9      None     7718      <NA>

    agerelax_code rejection_provision
85                                  C
129                                 C
175             2                   C
220                                 C
266                                 C
305                                 C
311                                 C
397                                 C
400                                 C
402                                 C

In [37]:
dob_18_30_counts_me = candidate_df['dob_18_30'].value_counts()
dob_18_30_counts_me

dob_18_30
9     12691
       1971
01      628
02      519
99      337
04       34
03       24
05       12
08        3
09        3
06        1
Name: count, dtype: int64

#### FOR 18-32

In [38]:
age_group = '18_32'
get_dob_flag(candidate_df, arc_df, age_group)

C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\1446143870.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sorted_candidates[dob_flag] = sorted_candidates.apply(calculate_verification_flag, axis=1)

'dob_18_32 updated successfully'

In [39]:
candidate_df[['rollno','dob_18_32']].head()

       rollno dob_18_32
0  2405106841         9
1  3010103899         9
2  4206101599         9
3  3013105205         9
4  8601109782         9

In [40]:
dob_18_32_counts_me = candidate_df['dob_18_32'].value_counts()
dob_18_32_counts_me

dob_18_32
9     13890
       1971
01      193
02      122
04       23
03       15
05        6
06        1
09        1
08        1
Name: count, dtype: int64

In [41]:
null_cutoff_rows = candidate_df[
    candidate_df['dob_18_32'] == '99'
][['dob', 'cat1', "cat2", "cat3","cutoff_c", 'cutoff_em', 'merit_c', "merit_em", "agerelax_code","rejection_provision" ,"rollno"]].head(10)


print(null_cutoff_rows)

Empty DataFrame
Columns: [dob, cat1, cat2, cat3, cutoff_c, cutoff_em, merit_c, merit_em, agerelax_code, rejection_provision, rollno]
Index: []

In [42]:
candidate_df[candidate_df['dob_18_32'] == 'U'].head()

Empty DataFrame
Columns: [id, registrationNo, emailId, phoneNo, name, newname, father_name, mother_name, dob2, ageAsOnDob, Gender, isPwbd, typeOfDisability, code, markOfIdentification, tenthRollNumber, tenthYearOfPassing, centreName1, centreName2, centreName3, isBenchmarkDisabilityVh, isBenchmarkDisabilityOh, isPhysicalLimitToWrite, isScribe, isOwnScribe, scribeMedium, isEsm, dojOfEsm, dodOfEsm, service_period, isCivilPost, dojOfCivilPost, isAgeRelaxation, arccode, description, isPersonalInfoAccess, regionCode, permanentAddress, permanentStateName, permanentStateId, permanentDistrictName, permanentDistrictId, permanentPincode, presentAddress, presentStateName, presentStateId, presentDistrictName, presentDistrictId, presentPincode, jePostCategory, highestQualification, subject, Nationality, ApplicationStatus, numberOfAttempts, ipAddress, isActive, createdAt, updatedAt, ownScribeWithdrawal, scribeRegNo, isExempted, rollno, cand_name, cat1, cat2, cat3, exsm_length, exs_reservation, agerelax_code, p1_gi, p1_ga, p1_gen_engg, p1_score, p1_normalized, paper1, post_applied, p2_score, p2_normalized, paper2, p2_subject, total, debarred, rejection_provision, remarks, gender, dob, post_pref, merit_c, merit_em, cutoff_c, cutoff_em, exsm_yrs, exsm_months, exsm_days, dob_18_30, dob_18_32]
Index: []

[0 rows x 97 columns]

### CATSEL DOB FLAG

#### PREREQUISITES

In [43]:
arc_df['arc_code'] = arc_df['arc_code'].astype(str)

mask = arc_df['arc_cat2'].isnull()
arc_df.loc[mask, 'arc_cat2'] = ''

mask = arc_df['arc_cat3'].isnull()
arc_df.loc[mask, 'arc_cat3'] = ''

In [44]:
arc_df['arc_code'] = arc_df['arc_code'].apply(lambda x: str(x).zfill(2))

#### CODE

In [45]:
def get_catsel_dob(candidate_df, arc_df, age_group):
    
    if age_group == '18_30':
        dob_from_date = pd.to_datetime('08/01/1994', format="%m/%d/%Y")
        
    elif age_group == '18_32':
        dob_from_date = pd.to_datetime('08/01/1992', format="%m/%d/%Y")
    else:
        return "Enter Valid age group i.e. either 18_30 or 18_32"

    dob_flag = 'dob_'+ age_group
    catsel_dob_flag = 'catsel_dob_'+ age_group

    candidate_df[catsel_dob_flag] = ''
    
    filtered_and_sorted_candidates = candidate_df[((candidate_df['merit_c'].notnull()) | (candidate_df['merit_em'].notnull())) 
    & (candidate_df[dob_flag].notnull()) 
    & (candidate_df[dob_flag] != '')]
    def calculate_catsel_dob(row, dob_flag_name):

        dob_flag = row[dob_flag_name]
       
        if dob_flag is not None and dob_flag != '' and dob_flag != '9':
            matching_rows = arc_df[arc_df['arc_code'] == dob_flag]
            if not matching_rows.empty:
                catsel = matching_rows.iloc[0]
                catsel_cat1 = catsel['arc_cat1'].split(',')
                catsel_cat2 = catsel['arc_cat2'].split(',')
                catsel_cat3 = catsel['arc_cat3'].split(',')
                catsel_gender = catsel['arc_gender'].split(',')
                condition = (str(row['cat1']) in catsel_cat1) & (str(int(row['gender'])) in catsel_gender)
                catsel_dob = ''
                if row['cat2'] == '3' and row['cat2'] in catsel_cat2:
                    catsel_dob = row['cat2']
                else:
                    if pd.isnull(catsel['arc_year_against_ur']):
                        catsel['arc_year_against_ur'] = 0
                    dob_datetime = pd.to_datetime(row['dob'])
                    extract_year = dob_datetime.year
                    extract_month = dob_datetime.month
                    extract_day = dob_datetime.day
                    if (extract_day == 29) and (extract_month == 2):
                        extract_day = 28
                    new_year = extract_year + int(catsel['arc_year_against_ur'])
                    new_dob = pd.to_datetime(f'{new_year}-{extract_month}-{extract_day}')
                    catsel_dob_decision = new_dob > dob_from_date
                    if (str(row['cat3']) in catsel_cat3 and str(row['cat3']) != ''):
                        if catsel_dob_decision:
                            catsel_dob = '9'
                        else:
                            catsel_dob = row['cat3']  
                    else:
                        catsel_dob = '9' if catsel_dob_decision else row['cat1']
                return catsel_dob if condition else ''
            else:
                return ''
        else:
            return dob_flag
    
    filtered_and_sorted_candidates[catsel_dob_flag] = filtered_and_sorted_candidates.apply(calculate_catsel_dob, args = (dob_flag, ), axis=1)
    candidate_df.update(filtered_and_sorted_candidates)
    
    print('Successfully updated ' + catsel_dob_flag)

#### FOR 18-30

In [46]:
age_group = '18_30'
get_catsel_dob(candidate_df, arc_df, age_group)

Successfully updated catsel_dob_18_30

C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\1494582381.py:60: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_and_sorted_candidates[catsel_dob_flag] = filtered_and_sorted_candidates.apply(calculate_catsel_dob, args = (dob_flag, ), axis=1)

In [47]:
candidate_df[['rollno', 'catsel_dob_18_30']].head()

       rollno catsel_dob_18_30
0  2405106841                9
1  3010103899                9
2  4206101599                9
3  3013105205                9
4  8601109782                9

In [48]:
candidate_df['catsel_dob_18_30']

0        9
1        9
2        9
3        9
4        9
        ..
16218    6
16219    9
16220    9
16221    9
16222    9
Name: catsel_dob_18_30, Length: 16223, dtype: object

In [49]:
catsel_dob_18_30_counts_me = candidate_df['catsel_dob_18_30'].value_counts()
catsel_dob_18_30_counts_me

catsel_dob_18_30
9    12765
      2308
6      519
1      452
2      177
3        1
4        1
Name: count, dtype: int64

#### FOR 18-32

In [50]:
age_group = '18_32'
get_catsel_dob(candidate_df, arc_df, age_group)

Successfully updated catsel_dob_18_32

C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\1494582381.py:60: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_and_sorted_candidates[catsel_dob_flag] = filtered_and_sorted_candidates.apply(calculate_catsel_dob, args = (dob_flag, ), axis=1)

In [140]:
candidate_df[['rollno', 'catsel_dob_18_32']].head()

       rollno catsel_dob_18_32
0  2405106841                9
1  3010103899                9
2  4206101599                9
3  3013105205                9
4  8601109782                9

In [51]:
catsel_dob_18_32_counts_me = candidate_df['catsel_dob_18_32'].value_counts()
catsel_dob_18_32_counts_me

catsel_dob_18_32
9    13935
      1971
1      138
6      122
2       55
3        1
4        1
Name: count, dtype: int64

### CATSEL FLAG

#### CODE

In [52]:
def get_catsel(candidate_df, medium, age_group):
    
    if medium == 'C':
        if age_group == '18_30':
            catsel_dob_flag = 'catsel_dob_'+age_group
            cutoff_flag = 'cutoff_c'
            merit = 'merit_c'
        elif age_group == '18_32':
            catsel_dob_flag = 'catsel_dob_'+age_group
            cutoff_flag = 'cutoff_c'
            merit = 'merit_c'
        else:
            return "Incorrect Age Group"
    elif medium == 'EM':
        if age_group == '18_30':
            catsel_dob_flag = 'catsel_dob_'+age_group
            cutoff_flag = 'cutoff_em'
            merit = 'merit_em'
        elif age_group == '18_32':
            catsel_dob_flag = 'catsel_dob_'+age_group
            cutoff_flag = 'cutoff_em'
            merit = 'merit_em'
        else:
            return "Incorrect Age Group"
    else:
        return "Incorrect medium"


    catsel_flag = 'catsel_'+medium.lower()+'_'+age_group
    candidate_df[catsel_flag] = ''
    
    candidates = candidate_df[candidate_df[merit].notnull()].sort_values(by='rollno')
    
    def update_cutoff_flag(candidate_record):
        if candidate_record['cat2'] == '3' and candidate_record['exs_reservation'] == 'No':
            candidate_record[cutoff_flag] = candidate_record[cutoff_flag].replace('3', '').strip()

        if candidate_record[catsel_dob_flag] in ['1', '2', '6', '4', '5', '7', '8']:
            return candidate_record[cutoff_flag].replace('9', '').strip()
        elif pd.isna(candidate_record[catsel_dob_flag]) or candidate_record[catsel_dob_flag] == '':
            return ''
        else:
            return candidate_record[cutoff_flag]
    
    candidate_df[catsel_flag] = candidates.apply(update_cutoff_flag, axis=1)

    return 'Successfully updated '+ catsel_flag

#### FOR C [18-30, 18-32]

In [53]:
medium = 'C'
age_group = '18_30'

get_catsel(candidate_df, medium, age_group)

'Successfully updated catsel_c_18_30'

In [54]:
candidate_df[['catsel_c_18_30']].head()

  catsel_c_18_30
0              2
1              6
2              6
3              1
4              2

In [55]:
catsel_c_18_30_counts_me = candidate_df['catsel_c_18_30'].value_counts()
catsel_c_18_30_counts_me

catsel_c_18_30
96     2327
1      1991
6      1721
2       940
9       898
0       874
90      648
91      337
        227
92      168
4       134
5       117
8        36
14        4
64        3
05        2
904       1
15        1
04        1
964       1
94        1
Name: count, dtype: int64

In [56]:
medium = 'C'
age_group = '18_32'

get_catsel(candidate_df, medium, age_group)

'Successfully updated catsel_c_18_32'

In [57]:
candidate_df[['catsel_c_18_32']].head()

  catsel_c_18_32
0              2
1              6
2              6
3              1
4              2

In [58]:
catsel_c_18_32_counts_me = candidate_df['catsel_c_18_32'].value_counts()
catsel_c_18_32_counts_me

catsel_c_18_32
96     2513
1      1965
6      1553
9       963
2       932
0       932
90      701
91      364
92      177
4       135
5       118
8        36
         29
14        4
64        3
05        2
904       1
15        1
04        1
964       1
94        1
Name: count, dtype: int64

#### FOR EM [18-30, 18-32]

In [59]:
medium = 'EM'
age_group = '18_30'

get_catsel(candidate_df, medium, age_group)

'Successfully updated catsel_em_18_30'

In [60]:
candidate_df[['catsel_em_18_30']].head()

  catsel_em_18_30
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN

In [61]:
candidate_df['catsel_em_18_30'].unique()

array([nan, '6', '2', '96', '8', '', '1', '9', '91', '0', '90', '64', '5',
       '4', '94', '92', '964', '04', '14'], dtype=object)

In [62]:
medium = 'EM'
age_group = '18_32'

get_catsel(candidate_df, medium, age_group)

'Successfully updated catsel_em_18_32'

In [63]:
catsel_em_18_30_counts_me = candidate_df['catsel_em_18_30'].value_counts()
catsel_em_18_30_counts_me

catsel_em_18_30
96     1098
1       732
9       411
0       327
2       302
90      255
6       231
        153
91      114
4        84
5        64
92       26
8        16
964       2
04        2
64        1
94        1
14        1
Name: count, dtype: int64

In [64]:
candidate_df[['catsel_em_18_32']].head()

  catsel_em_18_32
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN

In [65]:
candidate_df['catsel_em_18_32'].unique()

array([nan, '6', '2', '96', '8', '', '1', '0', '9', '91', '90', '64', '5',
       '4', '94', '92', '964', '04', '14'], dtype=object)

In [66]:
candidate_df['post_pref'].head()

0    {D,K,F,B,G,M,I}
1    {D,K,F,M,I,G,B}
2                NaN
3                NaN
4                NaN
Name: post_pref, dtype: object

In [67]:
candidate_df['post_pref'] = candidate_df['post_pref'].str.replace(r'[\{\}]', '', regex=True)

In [68]:
vacancy_df['subject_option'].unique()

array(['C', 'EM', 'M', 'E'], dtype=object)

### ALLOCATION

In [69]:
candidates_up_to_catsel_dob = candidate_df.copy()

#### PREREQUISITES

In [70]:
candidate_df[['allocated_category', 'allocated_subject', 'allocated_post', 'allocated_against_ur']] = None

In [71]:
mask = candidate_df['post_pref'].isnull()
candidate_df.loc[mask, 'post_pref'] = ''
candidate_df.loc[~mask, 'post_pref'] = candidate_df.loc[~mask, 'post_pref'].astype(str)

mask = candidate_df['catsel_c_18_30'].isnull()
candidate_df.loc[mask, 'catsel_c_18_30'] = ''
candidate_df.loc[~mask, 'catsel_c_18_30'] = candidate_df.loc[~mask, 'catsel_c_18_30'].astype(str)

mask = candidate_df['catsel_c_18_32'].isnull()
candidate_df.loc[mask, 'catsel_c_18_32'] = ''
candidate_df.loc[~mask, 'catsel_c_18_32'] = candidate_df.loc[~mask, 'catsel_c_18_32'].astype(str)

mask = candidate_df['catsel_em_18_30'].isnull()
candidate_df.loc[mask, 'catsel_em_18_30'] = ''
candidate_df.loc[~mask, 'catsel_em_18_30'] = candidate_df.loc[~mask, 'catsel_em_18_30'].astype(str)

mask = candidate_df['catsel_em_18_32'].isnull()
candidate_df.loc[mask, 'catsel_em_18_32'] = ''
candidate_df.loc[~mask, 'catsel_em_18_32'] = candidate_df.loc[~mask, 'catsel_em_18_32'].astype(str)

In [72]:
vacancy_df['allocated_hc'] = 0

In [73]:
vacancy_df['left_vacancy'] = vacancy_df['current']
vacancy_dict = {}
vacancy_df['key'] = vacancy_df['category_code'].astype(str) + vacancy_df['subject_option'].astype(str) + vacancy_df['post_code'].astype(str)

for index, row in vacancy_df.iterrows():
    key = row['key']
    vacancy_dict[key] = row.to_dict()

#### CODE

In [74]:
def update_allocation_c(candidates_df, category, post, subject, allocated_against_ur, candidate, vacancy_dict):
    if str(category) in ['3', '4', '5', '7', '8']:
    
        key_cat1 = str(candidate['cat1']) + str(subject) + str(post)
        
        if (key_cat1 not in vacancy_dict.keys()) or (vacancy_dict[key_cat1]['initial_vacancy'] == 0):
            keyCat2='9' + str(subject) + str(post)
            
            if (keyCat2 not in vacancy_dict.keys()) or (vacancy_dict[keyCat2]['initial_vacancy'] == 0):
                return False
            else:
                if vacancy_dict[keyCat2]['allocated_hc'] != vacancy_dict[keyCat2]['initial_vacancy']:
                    vacancy_dict[keyCat2]['allocated_hc'] += 1
                allocated_against_ur = '1'
        else:
            if vacancy_dict[key_cat1]['allocated_hc'] != vacancy_dict[key_cat1]['initial_vacancy']:
                vacancy_dict[key_cat1]['allocated_hc'] += 1
            
            else :
                return False
                        
    candidates_df.loc[candidate.name, 'allocated_subject'] = subject
    candidates_df.loc[candidate.name, 'allocated_category'] = category
    candidates_df.loc[candidate.name, 'allocated_post'] = post
    candidates_df.loc[candidate.name, 'allocated_against_ur'] = allocated_against_ur
    
    return True

In [75]:
def update_allocation_em(candidates_df, category, post, subject, allocated_against_ur, candidate, vacancy_dict):
    if str(category) in ['3', '4', '5', '7', '8']:
        
        key_cat1 = str(candidate['cat1']) + subject + str(post)
        
        if (key_cat1 not in vacancy_dict.keys()) or (vacancy_dict[key_cat1]['initial_vacancy'] == 0):
            keyCat2='9' + subject + str(post)
            
            if (keyCat2 not in vacancy_dict.keys()) or (vacancy_dict[keyCat2]['initial_vacancy'] == 0):
                return False
            else:
                if vacancy_dict[keyCat2]['allocated_hc'] != vacancy_dict[keyCat2]['initial_vacancy']:
                    vacancy_dict[keyCat2]['allocated_hc'] += 1
                allocated_against_ur = '1'
        else:
            if vacancy_dict[key_cat1]['allocated_hc'] != vacancy_dict[key_cat1]['initial_vacancy']:
                vacancy_dict[key_cat1]['allocated_hc'] += 1
            
            else :
                return False
                        
    candidates_df.loc[candidate.name, 'allocated_subject'] = subject
    candidates_df.loc[candidate.name, 'allocated_category'] = category
    candidates_df.loc[candidate.name, 'allocated_post'] = post
    candidates_df.loc[candidate.name, 'allocated_against_ur'] = allocated_against_ur
    
    return True

In [76]:
def allocate_candidates(candidates_df, vacancy_dict, medium):

    if medium == 'C':
        
        merit = 'merit_c'    
        filtered_candidates = candidates_df[(candidates_df['merit_c'].notnull()) & 
        (candidates_df['allocated_category'].isnull())].sort_values(by='merit_c')
        subject_option = 'C'
    
    elif medium == 'EM':
        
        merit = 'merit_em'
        filtered_candidates = candidates_df[(candidates_df['merit_em'].notnull()) & 
        (candidates_df['allocated_category'].isnull())].sort_values(by='merit_em')
        
    else:
        return "Enter Correct Medium i.e. Either 'C' or 'EM'"

    post_flag_dict = {'BFGIKM':['catsel_dob_18_30', 'catsel_c_18_30'],
                      'AEHJLNO':['catsel_dob_18_30', 'catsel_em_18_30'],
                      'C':['catsel_dob_18_32', 'catsel_em_18_32'],
                      
                      'D':['catsel_dob_18_32', 'catsel_c_18_32']}
    
    
    for idx, candidate in filtered_candidates.iterrows():
        allocated = False
        roll = candidate['rollno']
        post_preference = candidate['post_pref']
        print(post_preference)
        DOB = candidate['dob']
        
        for post in post_preference.split(','):

            if post == 'X':
                continue
        
            catsel_dob_name = [values for key, values in post_flag_dict.items() if post in key][0][0]
            catsel_name = [values for key, values in post_flag_dict.items() if post in key][0][1]

            catsel_dob = str(candidate[catsel_dob_name])
            catsel = str(candidate[catsel_name])
            
            if medium == "C" and catsel != '':

                if post == 'B' and (candidate['gender'] == 1):
                    continue
                    
                subject_option = "C"
                for category in catsel:
                    key_c = str(category) + subject_option + str(post)
                    allocated_against_ur = ''
                    if key_c in vacancy_dict and vacancy_dict[key_c]['current'] > 0:
                                    
                        allocated = update_allocation_c(candidates_df, category, post, subject_option, allocated_against_ur, candidate, vacancy_dict)
                        if allocated:
                            vacancy_dict[key_c]['current'] -= 1
                            vacancy_dict[key_c]['allocated'] += 1
                            break
                if allocated:
                    break

            if medium == "EM" and catsel != '':

                if post == 'A' and (candidate['gender'] == 1):
                    continue
                
                if post in ('A', 'J', 'C'):
                    subject_option  = "EM"
                elif post in ('H', 'L', 'N'):
                    subject_option  = "E"
                else:
                    subject_option = 'M'
                        
                for category in catsel:
                    key_em = str(category) + subject_option + str(post)
                    allocated_against_ur = ''
                    
                    if key_em in vacancy_dict and vacancy_dict[key_em]['current'] > 0:            
                        allocated = update_allocation_em(candidates_df, category, post, subject_option, allocated_against_ur, candidate, vacancy_dict)
                        
                        if allocated:
                            vacancy_dict[key_em]['current'] -= 1
                            vacancy_dict[key_em]['allocated'] += 1
                            
                            break
                if allocated:
                    break

    return vacancy_dict

In [78]:
def update_vacancy_table(vacancy_table_df, category_code, subject_option, post_code, vacancy):
    condition = (
        (vacancy_table_df['category_code'].astype(str) == category_code) &
        (vacancy_table_df['subject_option'].astype(str) == subject_option) &
        (vacancy_table_df['post_code'].astype(str) == post_code)
    )
    if condition.any():
        current = vacancy_table_df.loc[condition, 'current']
        vacancy_table_df.loc[condition, 'current'] -= vacancy


def adjust_vacancy(candidates_df, vacancy_df):
    vacancy_df['current'] = vacancy_df['initial_vacancy']
    vacancy_df['allocated'] = 0
    vacancy_df['left_vacancy'] = 0

    grouped_candidates = candidates_df[candidates_df['allocated_category'].isin(['3', '4', '5', '8'])].groupby(['cat1', 'allocated_subject', 'allocated_post', 'allocated_against_ur'])

    for (category_code, subject_option, post_code, allocated_against_ur), group in grouped_candidates:
        category_code = '9' if allocated_against_ur == '1' else category_code
        vacancy = len(group)
        
        update_vacancy_table(vacancy_df, category_code, subject_option, post_code, vacancy)
        
    vacancy_df['allocated_hc_prev'] = vacancy_df['allocated_hc']
    vacancy_df['allocated_hc'] = 0

    return vacancy_df

#### 1st TIME EXECUTION

In [79]:
medium = 'C'
upd_vacancy_dict = allocate_candidates(candidate_df, vacancy_dict, medium)

M,D,K,F,G,I,B
D,K,F,G,M,I,B
D,K,G,F,M,I,B
D,K,F,M,I,G,B
D,K,F,G,I,M,B
D,K,F,G,M,B,I
D,K,F,G,M,I
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,K,F,M,G,I,B
D,K,F,M,G,I,B
D,F,G,M,I,X,X
D,K,F,I,G,M,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,G,F,B,M,I
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,B,I
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
K,D,F,G,M,I,B
D,K,F,I,M,G,B
D,K,F,G,M,I,X
D,F,G,M,I,X,X
D,K,F,G,I,M,B
D,F,I,M,G,X,X
D,K,F,G,M,I,B
D,F,M,G,I,K,B
D,F,K,I,G,M,X
D,K,F,G,M,I,B
D,K,F,I,M,G,B
D,G,F,M,I,K,B
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,I,K,F,M,G,X
D,K,F,G,B,M,I
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,F,K,G,M,I
D,K,F,M,I,B,G
D,K,G,F,M,I,B
D,K,G,F,M,B,I
D,K,F,G,M,B,X
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,K,G,F,M,I,B
D,K,F,G,M,I,X
D,K,F,I,M,G,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,F,M,G,I,K,B
D,F,G,M,I,K,B
D,I,F,G,M,K,B
D,K,F,G,M,I,X
D,K,F,G,M,I,B
D,K,F,M,I,G,B
D,K,F,M,G,I
D,F,M,G,I,X
D,K,F,G,M,I,B
D,G,F,M,I,X,X
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,K,G,M,I
D,K,G,F,M,I,B
D,F,M,I,G,X,X
D,F,K,G,I,M,B
D,K,F,M,G,I,B
D,K,M,F,G,I,B
D,K,F,G,M,I,B
D,K,F,X,X,X,X
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,F,G,M,I,X,X
D,K,F,G,M,I
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,G,F,M,B,I
D,F,K,G,M,I,B
D,F,G,X,X,X,X
D,K,F,G,M,I,B
D,K,F,G,B,M,I
D,K,F,G,M,I,X
D,F,G,M,I,X,X
D,K,F,M,G,I,X
D,K,M,F,G,B,I
D,K,F,M,I,G,B
D,K,F,G,M,I,B
D,F,I,G,M,X,X
D,K,F,B,I,G,M
D,K,F,M,G,I,B
D,F,G,M,K,I,X
D,F,G,M,I,X,X
D,F,K,G,M,B,I
D,K,F,I,M,G,X
D,F,M,G,I,K,B
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,K,F,G,M,B,I
D,K,F,I,M,G,B
D,F,I,M,G,X,X
K,D,F,G,M,I,B
D,F,K,G,M,I,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
K,D,F,M,G,I,B
D,K,F,I,G,M,X
D,K,F,M,G,I,B
D,X,X,X,X,X,X
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,F,G,K,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,I,M,X
D,K,F,I,M,G,B
D,K,F,G,M,I,B
D,K,F,I,G,M,B
K,D,F,G,M,I,X
D,K,F,G,M,I,X
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,B,M,I,G
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,G,M,B,I
K,D,F,G,B,M,I
D,K,F,G,M,B,I
D,F,I,G,M,X,X
D,K,F,G,M,I,X
D,F,G,M,I,K,B
D,F,M,K,I,G,B
D,K,G,M,X,X,X
D,F,G,M,I,X
D,K,G,F,X,X,X
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,M,F,G,I,B
D,F,M,G,I,X,X
D,K,F,G,M,I,B
D,X,X,X,X,X,X
D,K,F,G,M,I,B
D,K,F,M,I,G,B
D,K,F,G,M,I,B
D,K,F,B,M,I,G
D,F,I,G,M,X,X
D,K,B,F,G,M,I
D,F,K,M,G,I,X
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,K,F,I,M,G,X
D,K,G,F,M,I,B
D,K,F,M,G,B,I
D,K,F,G,M,I,B
D,K,G,M,F,B,I
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,B,I
D,K,F,G,M,I,B
D,F,I,G,M,X,X
K,F,D,B,M,I,G
D,K,F,M,I,G,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,I,G,M,X,X
D,F,G,I,M,X,X
F,K,X,X,X,X,X
D,K,F,G,M,I,B
D,K,F,I,M,G,B
D,K,F,G,M,I,X
D,K,F,G,I,M,B
D,F,M,K,G,I,B
D,F,G,I,M,X,X
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
K,D,F,G,I,M,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,G,M,X,X,X
D,K,G,F,M,I,B
D,K,F,M,I,G,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,M,G,F,I,B
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,K,F,G,M,I,X
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,F,G,I,M,X,X
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,F,M,G,I,X,X
D,K,F,G,M,I,B
K,D,F,G,I,B,X
K,F,D,G,M,I,B
D,F,G,M,K,I,B
D,K,F,I,G,M,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,M,I,B,G
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,I,B,M
K,F,G,M,I,D,B
D,K,F,M,G,I,B
D,K,F,G,M,B,I
D,F,M,G,K,B,I
D,K,F,G,M,I,B
D,K,F,I,M,G,X
D,K,F,G,I,M,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,G,M,I,B
D,K,F,I,G,M,B
D,X,X,X,X,X,X
D,F,K,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
K,D,G,F,M,I,B
D,F,G,M,I,B,K
D,K,F,B,M,I,G
D,G,F,M,I,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,I,M,X,X
D,K,F,M,G,I,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,G,M,X,X
D,F,G,M,I,K,B
D,K,F,G,M,I
D,K,G,M,X,X,X
D,K,F,I,M,G,B
D,K,F,G,M,I,B
D,F,I,G,M,K,B
D,K,F,G,B,I,M
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,F,M,G,I,K,B
D,F,G,M,I,X
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,K,G,F,M,I,B
D,F,M,G,K,I
D,K,F,I,G,M,B
D,K,F,G,M,I
D,K,F,G,I,M,B
D,K,F,G,M,I,X
D,K,F,G,M,I,B
D,K,F,G,M,I,X
K,F,B,X,X,X,X
D,K,F,G,B,M,I
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,F,G,M,I,B,K
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,F,M,K,G,I,B
D,F,G,M,I,X
D,K,F,G,I,M,B
D,F,G,M,I,K,B
D,K,F,G,B,M,I
D,F,G,M,K,B,I
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,B,G,M,I
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,F,M,G,I,K,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,K,F,G,M,I,B
D,K,F,M,G,I,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,X
D,K,G,F,M,B,I
D,F,G,M,I,X,X
D,K,F,B,G,M,I
D,K,F,G,M,I,B
D,K,M,G,F,I,X
D,K,F,G,M,I,B
D,K,F,B,X,X,X
D,K,F,I,G,M,B
D,F,G,M,I,K,B
D,X,X,X,X,X,X
D,K,F,G,I,M,B
D,K,F,M,G,I,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,F,K,I,G,M,B
D,K,F,G,M,X,X
D,K,F,G,M,I,B
D,G,K,F,M,I,B
D,K,F,G,M,I
D,K,F,G,I,M,B
D,K,F,G,M,B,I
D,K,F,M,I,G,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,X
D,K,F,G,M,I,X
D,F,G,X,X,X,X
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,F,G,M,I,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,M,G,I,B
D,F,G,M,I,X,X
D,F,G,M,I,X,X
D,K,F,M,G,I,B
D,F,G,M,I,K
D,K,F,M,G,I,B
D,K,F,G,M,I,X
F,I,M,G,D,K,X
D,X,X,X,X,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I
D,K,F,B,M,G,I
D,K,X,X,X,X,X
D,F,I,M,G,X,X
D,F,M,G,I,X,X
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,I,G,M,K,B
K,D,F,M,G,I,B
D,K,F,G,M,I,B
D,K,I,F,M,G,B
D,X,X,X,X,X,X
D,F,G,I,M,K,B
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,F,M,K,G,I,B
D,K,G,M,F,I
D,K,F,G,M,I,B
D,F,K,G,I,M,B
D,F,G,M,I,K,B
D,F,G,M,I,X,X
D,F,G,M,I,X,X
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,G,M,B,I
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,F,G,M,K,I,X
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,G,F,K,M,I
D,K,F,I,M,G,B
D,K,F,G,M,I
D,K,F,G,M,I,B
I,G,M,F,D,X,X
D,K,F,G,M,B,I
D,K,F,G,B,M,I
D,K,F,G,I,M,B
D,K,F,G,I,M,B
D,K,F,M,G,B,I
D,K,G,F,I,M,B
D,K,F,M,I,G,X
D,K,F,G,M,I,B
D,F,M,I,G,K,X
D,F,G,I,M,X,X
D,F,M,G,I,K,B
D,F,G,K,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,K,F,G,I,M,B

D,K,F,G,M,I
D,K,F,G,M,I,X
D,K,F,G,M,I,B
F,I,D,G,K,M,B
D,K,F,M,I,G,B
D,K,F,G,M,I,X
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,B,G,M,I
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,I,B,M
D,K,F,G,M,I,B
D,K,F,M,G,B,I
D,K,F,G,M,I,B
D,K,F,G,M,I,X
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,K,G,M,F,I,B
D,K,F,B,I,M,G
D,K,F,G,M,B,I
D,K,F,I,G,M,B
D,F,G,M,I,K,X
D,K,F,G,M,I,B
D,K,F,G,I,M,X
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,B,I
D,F,K,M,I,G,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,G,X,X,X
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,K,M,F,G,I,B
D,K,F,G,M,I
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,B,G,M,I
D,K,F,M,G,I,B
D,K,F,G,M,B,I
D,K,F,B,M,G,I
D,K,F,G,M,I
F,K,G,M,I,D
D,K,F,G,M,I
D,F,I,M,G,X,X
D,K,F,M,I,G,X
D,K,F,G,M,I
D,X,X,X,X,X,X
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,G,F,M,I,X
D,K,F,G,M,I,B
D,K,G,F,X,X,X
D,F,I,M,G,K,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,F,G,I,M,K,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,M,G,I,X
D,K,M,F,G,I,B
D,K,F,G,M,I,X
D,K,F,G,B,M,I
D,F,K,M,G,I,B
D,F,G,I,K,B,M
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,K,F,G,M,B,I
D,F,K,M,I,G,B
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,F,K,I,M,G,B
D,I,K,F,G,M,X
D,K,F,M,I,G,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,F,I,G,M,X,X
D,F,K,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,F,M,G,I,K,B
D,K,F,I,M,G,B
D,G,F,M,I,X,X
D,G,K,F,M,I,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
K,D,X,X,X,X,X
D,K,F,M,G,I,B
I,D,K,F,G,M,B
D,K,F,G,I,M
D,K,F,M,G,I,B
D,I,K,F,G,M,B
D,K,F,B,M,I,G
D,F,G,M,I,X,X
D,K,G,M,I,F,B
D,F,M,I,G,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,M,G,I,X,X
D,K,F,G,M,I,B
D,F,G,M,K,I,B
D,K,F,I,M,G,B
D,K,F,I,G,M,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,G,F,M,I
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,M,B,G,I
D,F,M,I,G,K,B
D,K,F,I,M,G,X
D,K,F,M,I,G,X
D,K,F,G,M,B,I
D,F,G,M,I,X,X
D,K,X,X,X,X,X
D,F,G,K,I,M,B
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
K,D,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,M,G,I,B
D,F,K,M,G,B,I
D,K,G,F,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I
D,K,F,G,M,I,B
D,K,F,G,M,I,B
K,D,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,M,G,B,I
D,M,F,G,I,X
K,G,F,M,I,B,X
D,F,G,M,I,X,X
D,K,F,G,I,M,B
D,K,F,M,G,I,B
D,K,F,M,I,G,B
D,F,K,G,I,M,B
D,K,F,M,G,I,B
D,K,F,I,M,G,B
D,K,F,M,G,I,X
D,F,G,M,I,K,B
D,F,G,M,I,K
D,K,F,G,I,M,B
D,F,G,M,I,X,X
I,D,F,M,G,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I
D,F,K,G,M,I,B
D,K,F,G,M,B,X
D,K,F,G,M,I,B
D,G,F,I,M,X,X
K,D,F,G,I,M,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,B,M,I
D,K,F,G,M,I,B
D,X,X,X,X,X,X
D,K,F,G,M,I,X
K,D,F,G,M,B,X
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,G,I,M,X,X
D,F,G,M,I,K,B
D,K,F,M,G,B,I
K,F,I,M,G,B,D
D,K,F,M,I,G,B
D,K,F,G,M,I,B
D,K,G,F,I,M,B
D,K,F,G,M,I,B
D,K,I,F,G,M,B
D,F,G,K,I,B,M
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,G,M,F,I,B
D,F,G,M,I,X,X
D,F,I,G,M,X,X
D,G,M,F,I,X,X
D,K,G,F,M,I,B
D,K,F,G,M,I,B
K,D,F,G,M,I,B
D,K,F,G,M,I
D,K,G,F,M,B,I
D,F,K,G,I,M,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,K,M,G,I,B
D,K,F,G,M,B,I
D,F,I,G,M,X,X
D,G,F,I,M,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,M,I,G,B
D,K,F,M,G,I,B
D,K,F,X,X,X,X
D,F,I,G,M,X,X
D,K,F,G,M,B,I
D,F,G,M,I,X,X
D,K,F,M,G,I,B
K,F,G,M,D,I,B
D,K,F,G,M,I,X
D,F,G,M,I,B,K
D,F,M,G,X,X
D,G,K,F,M,I
D,K,F,G,M,I,B
D,K,F,G,M,I,X
D,K,F,G,M,I,B
D,F,K,I,G,M,X
D,K,F,M,G,B,I
D,K,F,G,M,I
D,K,F,M,G,I
D,K,G,F,X,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,F,K,B,G,M,I
D,F,M,G,I,X,X
D,K,F,M,G,I,B
D,F,K,G,M,I
D,K,F,M,G,B,I
D,F,G,M,I,X,X
D,F,K,G,M,B,I
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,I,G,M,X,X
D,K,F,G,X,X,X
D,F,G,M,I,K
D,K,F,G,M,I,B
D,K,F,I,B,M,G
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,G,F,B,I,M
D,K,F,G,M,I,B
D,K,F,G,M,I,X
D,F,G,M,I,K,B
D,F,K,G,M,I,B
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,K,F,G,M,B,I
D,K,F,G,M,I,X
D,F,G,M,I,K,B
D,K,F,G,M,I
D,K,F,G,M,I,B
K,F,D,G,M,I,X
D,F,G,M,I,K,B
D,K,F,G,I,M,X
D,F,I,M,G,X,X
D,K,F,G,M,B,I
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,F,G,M,I,X
D,K,F,G,M,I,B
D,F,M,G,I,K,B
D,F,K,G,I,M,X
D,F,G,M,I,X,X
D,K,F,G,M,I,B

D,F,G,M,I,X,X
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,G,F,M,I,B
D,K,M,F,G,I,X
D,F,G,I,M,K,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,I,M,G,X
D,K,F,M,I,G,B
D,K,F,M,G,I,B
D,K,G,F,M,I,B
D,K,F,M,I,G,B
D,F,I,M,G,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,I,B,G,M
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,I,M,B
D,K,F,G,M,X,X
D,F,M,G,I,K
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,X
D,K,F,B,G,M,I
D,K,F,M,I,G,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,G,M,X,X,X,X
D,F,G,K,M,I
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,F,G,M,I,B,X
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,I,M,G,B
D,F,G,M,K,I
D,K,G,M,F,I,B
D,K,F,G,M,I,B
I,F,K,D,M,B,G

D,K,F,B,M,G,I
D,F,G,M,I,X,X
D,F,M,G,K,I
D,F,K,M,G,I,B
D,K,G,F,M,I,B
D,K,F,M,G,I,B
K,D,M,F,G,I,B
D,K,F,M,G,I,B
D,K,F,B,X,X,X
D,F,M,G,I,B,K
D,K,F,G,I,M,B
D,F,G,K,M,I
D,F,X,X,X,X,X
D,F,G,I,M,K,B
D,F,K,G,M,I,B
D,K,F,G,M,I,B
D,K,G,F,M,B,I
D,G,K,F,M,I,B
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,G,F,K,M,I,X
D,F,G,I,M,K,B
D,K,M,F,G,B,I
D,K,F,G,M,I,B
D,F,M,I,G,K
D,K,F,G,M,I,X
D,F,G,M,I,K,B
D,K,F,G,M,I,B
K,F,D,G,M,I,X
D,K,I,M,F,G,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,X
D,K,F,M,G,I,B
D,F,I,G,M,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,I,G,B
F,D,K,G,M,I,B
D,K,F,I,G,M,B
D,K,F,G,M,B,I
D,K,G,F,M,I,B
D,F,I,G,M,K,B
D,K,F,G,M,I,B
D,K,M,F,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,F,M,G,I,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,X,X,X,X
D,K,F,G,I,M,B
D,F,K,G,I,M,B
D,K,F,G,M,I,B
D,K,G,F,M,I,B
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,K,F,B,G,I,M
D,K,G,F,M,I,B
D,K,F,G,M,I,B
D,K,G,F,I,M,B
D,K,F,M,G,B,I
D,K,F,I,M,G,B
D,K,F,B,M,G,I
D,F,K,M,G,I,B
G,M,D,F,I,K,B
D,K,F,G,M,I,B
D,K,F,G,M,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,B,M,I
D,K,F,G,I,M,B
D,K,F,M,I,G,X
D,K,F,M,G,B,I
D,K,F,G,M,I,B
D,F,M,G,I,K,X
D,F,K,M,G,I,B
D,F,K,G,I,M,B
D,K,F,G,M,I,X
D,F,G,M,I,K,B
D,K,F,G,M,B,I
D,K,F,B,X,X,X
D,F,G,I,M,X,X
D,F,G,M,I,B,K
D,F,K,G,M,I,B
D,F,K,X,X,X,X
D,X,X,X,X,X,X
D,K,F,G,M,I,X
D,K,X,X,X,X,X
D,K,F,B,M,I,G
D,K,F,M,I,G,B
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,X,X,X,X,X,X
D,F,K,B,G,I,M
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,K,I,G,F,M,X
D,F,G,M,K,I
D,K,F,G,M,I
D,K,F,G,M,I,X
D,K,F,M,G,I,B
D,K,F,G,M,B,I
D,K,F,I,M,G,B
D,K,F,G,M,I
D,F,M,I,G,K,X
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,K,F,G,M,I,X
D,K,F,M,G,I,B
D,F,G,M,I,X,X
D,K,F,G,M,B,I
D,K,F,G,M,B,I
D,F,G,M,I,X,X
K,D,F,G,M,I,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,X,X,X,X,X,X
D,X,X,X,X,X,X
D,F,K,M,G,I,B
D,F,G,I,M,X
D,K,F,G,I,M,B
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,K,M,G,I,F,X
D,K,F,G,I,M,B
K,D,F,G,B,I,M
D,F,G,M,I,K,B
D,F,K,G,M,I
D,K,F,G,M,I,B
D,K,F,G,I,M,X
D,F,K,G,M,I,X
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,K,X
D,F,M,I,G,K,X
D,K,F,G,M,I,B
D,F,K,I,M,G,B
D,K,G,F,M,B,I
K,D,F,X,X,X,X
D,K,G,F,M,I,B
D,K,F,G,M,I,B
D,K,G,F,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,K,F,G,I,M,B
D,F,I,M,G,X,X
D,F,I,G,M,K,B
D,K,F,B,G,M,I
D,K,F,G,M,I,B
I,D,F,K,M,G,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,I,M,G,B
D,K,F,I,G,M,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
K,D,F,M,G,I,B
D,F,G,M,I,X,X
D,K,F,M,G,I,B
D,F,G,I,M,K,B
D,K,F,I,G,M,B
D,K,G,F,I,M,X
D,F,M,I,G,K,B
D,K,F,G,M,I,B
D,K,G,F,M,I,B
K,D,F,G,M,I,B
D,F,K,M,I,G,X
D,F,G,I,M,B,K
D,K,F,B,I,G,M
K,F,D,M,G,B,I
K,F,D,M,G,I,B
D,K,F,M,G,I,B
D,K,F,I,G,B,M
D,K,F,G,M,I,B
D,K,F,G,M,I,X
D,F,K,M,B,G,I
D,F,G,M,I,X,X
D,K,F,G,M,I,X
G,D,K,F,M,B,I
D,K,G,F,M,I,B
D,F,I,M,G,K,X
D,K,F,B,G,M,I
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,K,G,M,I,B,F
D,K,F,G,M,I,B
D,F,K,G,M,I,B
D,F,I,G,M,K,B
D,F,G,M,K,B,I
D,K,F,I,G,M
D,K,F,G,M,B,I
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,K,G,X,X,X,X
D,K,F,G,M,I,B
D,G,F,I,K,M,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,B,M,G,I
D,K,F,M,G,I,X
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,F,K,G,M,I,B
D,K,F,M,I,G,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,F,G,I,M,X,X
D,K,F,G,M,I
D,K,F,M,G,I,B
D,K,F,G,I,M,B
K,D,F,G,M,I,B
D,F,K,M,G,I,B
D,F,G,M,I,X,X
D,K,F,B,G,M,I
D,K,F,G,M,I,B
D,F,M,G,I,K,B
D,F,G,M,I,K,B
D,K,G,F,M,I,B
D,K,F,G,M,I,B
D,G,F,M,K,I,B
D,F,K,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,G,F,M,I,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,B,G,I,M
D,K,F,G,M,I,X
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,F,G,I,M,X,X
D,K,F,G,M,I,X
D,F,G,K,M,I,B
D,F,K,G,M,I,B
D,K,F,G,I,M,B
D,G,M,K,F,I,B
D,K,F,G,M,I,B
D,K,F,G,B,M,I
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,G,M,I
D,K,F,G,M,I,B
D,F,K,M,G,I,B
D,F,M,G,I,K,B
D,F,M,G,I,X,X
D,K,F,M,G,B,I
G,F,D,M,B,I,X
K,X,X,X,X,X,X
D,F,K,G,M,B,I
D,K,F,M,G,I,B
D,K,G,X,X,X,X
D,F,I,M,G,K,B
D,K,F,G,M,I
D,G,F,M,K,I
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,K,F,G,I,M,B
D,F,B,K,M,G,I
D,K,G,M,F,I,B
D,K,F,G,I,M,B
K,F,G,D,M,I,B
D,F,G,M,I,K,B
D,K,F,I,M,G,B
D,F,G,I,M,K
D,K,F,G,M,I,X
D,K,F,I,M,G,B
D,K,F,G,M,I,X
D,K,F,G,M,I,B
K,D,F,G,M,I,X
D,K,G,M,I,F,B
F,D,M,K,G,I,X
D,F,G,I,M,K,B
D,K,F,G,I,M,B
D,F,G,M,I,X,X
D,K,G,F,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,M,G,I,X
D,K,F,G,I,M
D,K,F,G,M,X,X
D,K,F,G,M,I,B
D,G,F,X,X,X,X
K,D,F,G,M,I,B
D,F,G,M,I,K,B
D,F,G,K,B,I,M
D,K,G,F,I,M,B
D,K,F,G,M,I,B
K,F,D,G,I,M,B
D,F,K,M,G,I,B
D,K,F,B,G,M,I
D,G,K,X,X,X,X
D,K,F,M,G,I,B
D,F,G,I,M,X,X
D,K,X,X,X,X,X
D,K,F,M,G,B,I
D,F,G,M,I,X,X
F,D,K,G,M,I,B
D,K,F,I,M,G,X
D,F,K,M,G,I,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,K,F,M,G,I,X
K,F,I,D,M,G,X
D,F,I,G,M,X,X
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,K,G,F,M,I
D,K,F,G,M,I
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,G,M,I,X
D,K,F,I,M,G,B
D,K,F,I,G,M,B
D,K,F,G,I,M,B
D,F,G,M,I,X,X
D,K,F,I,M,G,X
D,K,F,G,M,I,B
D,K,F,M,G,I
D,K,F,G,M,I,B
D,K,F,M,G,B,I
D,K,F,G,M,I
D,K,F,G,M,I,B
D,F,G,I,M,X,X
D,F,G,M,I,K,B
D,K,M,F,G,I,B
D,F,K,G,M,I,B
D,F,M,G,I,K,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,I,B,M,G
D,K,F,B,M,G,I
K,F,D,M,G,I,X
D,F,K,I,M,G,B
D,F,G,K,M,X,X
D,F,G,I,M,X,X
D,F,K,M,G,I,X
D,K,F,G,M,I,B
D,K,F,G,M,I,X
D,K,F,G,M,I,B
D,K,F,M,I,G,B
D,I,F,G,M,K,X
D,F,G,M,I,K,B
D,F,G,I,M,K,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,F,M,G,I,K,X
D,K,G,F,M,I,B
D,F,K,M,G,B,X
D,K,F,G,I,M,B
D,F,K,B,G,I,M
D,F,K,G,M,I,B
D,G,K,M,F,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,G,M,I,F,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,B,X
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,F,G,M,I,K,B
D,K,F,G,B,M,I
D,K,F,M,I,G,B
D,F,M,G,I,K,B
D,K,F,G,M,B,I
D,K,F,M,I,G,B
D,F,M,G,I,K,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,F,M,I,G,X,X
D,K,G,F,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,I,M,K
D,K,F,G,M,I,B
D,K,F,I,M,G,B
D,F,M,G,I,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,X,X,X,X,X,X
D,K,M,G,F,I,B
M,K,D,G,F,X,X
D,K,F,G,M,I,B
D,K,B,F,G,I,M
D,K,F,M,I,G,B
D,K,F,G,B,M,I
D,G,M,I,K,F,B
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,K,X,X,X,X,X
D,K,F,G,I,M,B
D,F,K,G,I,M,X
D,K,F,M,I,G,B
D,K,M,G,F,B,I
D,K,F,G,I,M,B
D,K,F,M,G,I,X
D,K,F,M,I,G,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I
D,F,M,I,G,X,X
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,I,M,B
D,K,F,G,I,M,B
D,K,F,M,G,I,B
D,F,G,M,I,K,B
D,F,K,G,M,I,B
D,K,F,M,I,G,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,M,G,I,B
D,K,F,M,G,I,X
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,X,X,X,X,X,X
D,K,F,G,M,I,B
D,K,F,M,I,G,B
D,F,K,M,I,G,B
D,F,G,M,K,B,X
D,K,F,M,G,I,B
D,F,M,I,G,K
K,F,D,G,M,I,B
D,K,F,G,M,B,I
D,K,F,X,X,X,X
D,K,F,G,M,I,B
D,K,G,F,M,I,X
D,K,F,M,G,I,X
D,F,G,M,I,K
D,K,F,M,G,I,B
D,F,M,G,I,K,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,F,K,M,G,I,B
F,D,K,B,M,I,G
D,K,F,M,G,I,B
D,K,G,F,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,B,G,M,I
D,F,G,M,I,K,B
D,K,F,M,G,I,B
D,F,M,G,I,K,B
D,K,G,F,M,I,B
D,F,G,M,I,X,X
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,G,F,M,X,X,X
D,K,F,G,M,I,B
D,F,G,K,M,B,I
D,K,F,G,I,M,B
D,F,K,M,G,B,I
D,K,F,G,M,B,I
D,K,G,M,I,F,B
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,K,F,M,G,I,B
K,D,F,G,B,M,I
D,K,F,G,M,B,I
D,X,X,X,X,X
D,F,G,M,I,X,X
D,K,M,G,F,I,B
D,K,F,G,I,M,B
D,F,I,G,M,K,B
D,K,F,G,M,X,X
D,K,F,M,G,B,I
D,K,I,F,M,G,X
D,K,F,M,G,I,B
D,F,K,G,M,I,B
D,K,F,G,M,I,B
D,K,F,I,M,G,B
D,F,G,K,B,I,M
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,K,F,G,M,I,X
D,K,F,G,M,I,B
D,F,M,G,I,K,B
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,K,F,M,G,B,I
D,K,F,G,M,I,X
D,K,F,B,M,G,I
D,F,M,I,G,K
D,K,F,G,M,I,B
D,K,F,I,M,G,B
D,F,M,G,I,X,X
D,K,F,G,M,B,I
D,M,F,K,G,I,B
D,F,M,I,K,G,B
D,K,F,G,I,M,B
D,K,F,I,G,M,B
D,F,G,M,I,K,B
D,K,G,F,M,I,B
D,K,F,G,M,I,B
D,F,G,I,M,X,X
K,B,D,F,G,M,I
D,K,F,G,M,I,B
D,K,G,F,M,I,B
D,F,G,M,I,X,X
D,F,G,I,X,X,X
D,K,F,X,X,X,X
D,K,F,B,M,I,G
D,F,G,M,K,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I
D,B,F,I,G,K,M
D,K,F,G,B,M,I
D,K,F,M,G,I,B
D,K,F,G,M,I,X
D,K,F,G,M,I,B

D,K,G,F,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,G,I,M,B
F,I,G,M,D,X,X
D,F,K,I,M,G,B
D,K,F,G,M,I,B
K,F,G,M,I,B,D
K,F,D,G,M,I,B
D,F,G,M,I,X,X
D,F,I,M,G,X,X
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,M,G,I,X
D,F,G,K,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,F,K,G,M,I,B
D,K,F,G,M,I,B
B,I,M,G,F,X,X
D,K,F,G,I,M,B
D,F,G,M,K,I,X
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,G,K,F,M,I,B
D,K,F,G,M,I
D,K,F,M,G,I,B
D,K,F,G,I,M,B
D,F,G,M,I,K,B
D,K,F,G,M,B,X
D,K,G,M,B,I,X
D,K,F,G,M,I,B
D,K,F,M,G,I
D,F,K,G,M,I
D,K,F,M,G,I,B
D,K,B,F,M,G,I
D,F,M,K,G,I,B
D,K,F,G,I,M,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
K,D,F,G,B,M,I
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,F,I,G,M,X,X
D,K,F,G,M,I,B
D,K,G,F,M,I,B
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,M,F,G,B,I
D,K,F,G,M,I,B
D,F,K,G,M,I,B
I,M,G,F,K,D,B
D,K,F,M,G,B,I
D,K,F,M,G,I,B
D,K,F,M,G,I,B
D,F,M,G,I,K,X
D,K,F,B,G,I,M
D,K,F,G,M,I,B
D,K,G,M,F,I,B
K,F,D,G,M,B,I
D,K,G,X,X,X,X
D,K,F,G,M,I,B
D,F,M,I,G,X,X
D,G,K,F,M,I,B
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,K,F,I,M,G,B
D,K,F,I,G,X,X
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,K,F,G,I,M,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,B,X,X
D,F,G,M,I,X,X
D,F,I,M,G,K,B
D,M,F,I,G,K,B
D,G,K,F,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,K,G,M,I,B
D,K,F,G,M,B,I
D,K,F,I,G,M,B
D,K,F,M,G,I
D,F,G,M,I,X,X
K,B,D,F,I,G,M
K,F,G,M,I,B,D
D,K,M,G,F,I,B
D,K,F,G,I,M,B
D,K,F,M,G,I
D,K,F,G,M,B,I
D,K,F,G,I,M,B
D,K,F,G,M,I,B

In [80]:
updated_vacancy_df = pd.DataFrame.from_dict(upd_vacancy_dict, orient='index')

In [81]:
updated_vacancy_df['initial_vacancy'].sum()

1754

In [82]:
medium = 'EM'
upd_vacancy_dict = allocate_candidates(candidate_df, upd_vacancy_dict, medium)

A,X,X,X,X,X
C,E,J,A,O
C,L,H,X,X,X
C,J,E,O,A
C,J,L,A,N,H
C,J,E,O,X
C,J,L,A,H,N
C,J,L,H,N,A
C,J,L,N,H,X
C,J,E,X,X
E,C,J,O,A
C,J,L,H,N,A
C,X,X,X,X,X
C,E,J,O,X
C,J,N,H,L
C,J,L,N,H,A
C,H,X,X,X,X
C,J,E,O,A
C,J,H,N,X,X
C,J,L,H,N,A
C,J,N,H,L,A
C,E,J,O,A
C,J,L,N,H,A
E,O,X,X,X
C,H,L,X,X
C,J,N,A,H,X
C,H,X,X,X,X
C,J,L,N,H,A
C,H,X,X,X,X
C,H,J,L,N,A
J,C,H,N,A,L
C,E,J,O,A
C,E,O,A,J
C,J,L,N,H,A
C,J,N,L,H,A
C,H,L,N,A,X
C,J,H,N,L,X
C,J,H,L,N,A
C,E,J,O,A
C,X,X,X,X
C,J,N,H,L
C,J,E,O,A
C,J,N,H,L,A
C,H,L,X,X,X
C,J,E,O,A
C,J,L,N,H,A
C,J,L,H,N,A
C,H,L,X,X,X
C,J,E,O,A
C,J,X,X,X,X
C,J,N,L,H,A
C,J,H,N,L,A
C,X,X,X,X
C,J,N,H,L,A
C,J,H,L,N,A
C,E,J,O,A
C,J,N,L,H,A
C,J,N,L,H,A
C,L,H,X,X,X
C,J,E,O,A
C,J,N,H,A,X
C,J,E,O,A
C,J,H,N,A,L
C,X,X,X,X
C,J,A,L,N,H
C,E,J,A,O
C,J,E,O,A
C,J,L,N,H,A
C,J,N,H,A,L
C,E,J,O,A
C,J,E,O,A
C,X,X,X,X,X
C,J,E,O,A
C,X,X,X,X
C,H,X,X,X,X
C,J,L,X,X,X
C,J,E,O,A
C,J,H,N,L,A
C,J,O,E,A
C,H,J,N,A,L
C,J,E,O,A
J,C,L,H,N,A
C,J,N,H,A,X,X,X,X,X,X,X,X,X,X
C,L,X,X,X,X
C,J,A,L,N,H
C,E,J,X,X
C,J,L,N,H,A
C,J,E,A,O
C,H,L,X,X,X
C,J,A,N,H,X
C,J,A,N,X,X
C,J,E,O,A
C,J,H,N,L,A
C,J,H,L,N,A
C,J,H,N,L
C,J,H,A,N,L
C,J,N,H,A,L
C,J,E,O,A
C,J,E,O,A
C,J,N,H,L,A
C,J,N,A,H,L
C,E,J,O,A
C,E,X,X,X
C,J,A,N,H,L
C,H,L,X,X,X
C,N,L,A,J,H
C,J,N,H,X
C,J,E,O,A
C,J,L,H,A,N
C,J,N,H,A,X
C,J,H,L,N,A
C,J,E,O,A
C,L,H,J,N,A
C,E,X,X,X
C,J,E,O,A
C,X,X,X,X,X
C,H,J,N,A,X
C,J,E,O,A
C,L,H,X,X,X
C,H,L,X,X,X
C,L,H,J,N,A
C,H,X,X,X,X
C,J,E,O,A
J,C,E,O,A
C,J,L,H,N,A
C,J,N,H,A,L
C,J,N,L,H,A
C,J,N,H,A,L
C,J,H,N,L,A
C,J,H,L,N,A
C,H,X,X,X,X
C,J,A,L,H,N
C,J,E,O,A
C,E,J,O,A
C,X,X,X,X,X
C,L,H,J,A,N
C,J,E,A,O
C,J,L,A,N,H
C,X,X,X,X,X
C,J,E,O,A
C,H,L,X,X,X
C,J,E,O,A
C,L,H,X,X,X
C,J,N,H,L,A
C,E,J,X,X
C,L,H,X,X,X
C,J,E,O,A
C,J,L,H,A,N
C,L,H,X,X
J,C,H,L,N,A
C,J,N,H,L,X
C,L,H,X,X,X
C,J,L,N,H,A
C,J,E,O,A
C,H,L,J,A,N
C,J,E,O,A
C,L,H,X,X,X
C,J,E,O,X
C,J,E,O,A
C,E,J,O,A
C,J,E,O,A
C,J,A,N,H,X
H,C,X,X,X,X
E,C,J,O,X
C,J,E,O,A
C,X,X,X,X,X
C,H,L,J,N
C,J,L,N,H,A
C,J,E,O,A
C,E,J,O,A
J,A,L,C,N,H
J,C,H,N,L
C,J,L,N,H,A
C,J,E,X,X
C,J,E,X,X
C,J,E,O,A
C,H,L,X,X,X
C,H,J,N,A,X
C,X,X,X,X
C,J,E,O,A
C,H,J,N,L,A
C,H,L,J,X,X
C,J,L,H,N,A
C,H,J,N,A,L
C,H,L,X,X,X
C,J,H,L,N,A
C,J,H,N,L,X
C,J,H,N,A,X
C,J,E,O,A
C,J,E,O,A
C,J,H,N,A,L
C,J,N,A,H,X
C,E,J,O,X
C,J,E,O,X
C,J,E,X,X
C,J,E,O,A
C,J,H,L,N,A
C,J,E,O,A
C,H,L,X,X,X
C,J,E,O,A
C,J,E,O,A
C,J,H,N,L,A
C,E,J,O,A
J,C,E,O,A
C,J,E,O,A
C,J,L,N,A,H
C,J,L,H,N
C,H,N,X,X
C,J,E,O,A
C,H,X,X,X,X
C,J,L,N,H,A
C,J,L,H,N,A
C,H,J,N,A,L
C,J,L,N,H,A
C,J,A,L,N,H
C,H,X,X,X,X
C,X,X,X,X,X
J,C,E,O,A
C,J,L,N,H,A
C,E,J,X
J,C,H,N,A,X
C,J,E,O,A
C,L,H,X,X,X
C,J,L,N,H,A
C,J,H,L,N,A

C,J,L,N,A,H
C,J,H,N,A,X
C,J,E,O,A
C,J,E,A,O
C,J,N,L,H,A
C,J,L,N,H,A
C,H,L,N,X,X
C,J,A,L,N,H
E,J,O,A,C
C,H,L,J,X,X
C,J,E,O,A
H,C,N,X,X,X
C,J,E,O,A
C,L,H,J,N,A
C,H,X,X,X,X
C,J,L,N,H,A
C,E,J,O,A
J,L,C,N,H,A
C,L,H,A,N,J
C,H,L,N,X,X
J,E,C,O,A
C,J,L,N,H,A
C,J,L,N,H,A
J,C,E,O,A
C,J,E,O,A
C,J,E,O,A
C,H,J,N,A,L
C,J,L,N,H
J,C,L,N,H,A
C,L,H,X,X,X
C,X,X,X,X,X
C,L,X,X,X
C,L,H,J,N,A
C,J,H,N,L,A
C,E,X,X,X
C,J,L,H,N,A
C,L,H,X,X,X

C,J,H,L,A,N
C,J,N,L,H,A
C,J,E,O,A
C,J,L,H,N
C,J,L,A,N,H
C,J,E,O,A
C,X,X,X,X,X
C,E,X,X,X
C,X,X,X,X,X
C,J,H,L,N,A
C,J,E,X,X
C,X,X,X,X,X
E,J,C,O,A
C,X,X,X,X
C,J,H,N,L,X
C,J,E,O,A
C,L,H,J,N,A
C,J,E,O,A
C,X,X,X,X
J,C,E,A,O
C,H,J,N,A,L
C,J,A,N,H,L
C,L,H,J,X,X
C,L,X,X,X,X
C,J,N,H,A,X
C,J,H,A,N,X
J,C,N,L,H,A
C,L,H,J,N,A
J,C,H,N,A,L
J,C,A,X,X,X
C,J,E,X,X
C,J,E,O,A
J,C,L,N,H,A
C,H,X,X,X,X
C,H,L,X,X,X
C,E,X,X,X
C,H,L,J,N,A
C,H,L,X,X,X
C,H,L,X,X,X
C,H,L,J,X,X
J,C,L,N,A,H
C,E,X,X,X
E,J,C,O,A
C,J,E,O,A
C,E,X,X,X
C,J,L,H,N,A
C,J,E,O,A
C,E,X,X,X
J,C,E,O,A
C,J,N,H,A,L
C,J,N,A,L,H
C,L,X,X,X,X
C,J,E,O,A
C,E,J,O
C,J,L,N,H,A
C,J,E,O,A
C,L,H,J,A,X
C,J,N,H,L,A
C,J,N,H,L,A
C,J,E,O,A

C,J,H,A,N,L
C,J,E,O,A
C,J,N,H,L,X
C,H,X,X,X,X
C,J,E,X,X
C,J,A,N,H,X
C,X,X,X,X,X
C,J,E,O,A
C,J,E,A,O
C,J,L,N,H,A
C,J,H,L,N
C,J,A,L,N,H
C,E,X,X,X
C,J,N,A,H,L
C,J,L,N,A,H
C,H,X,X,X,X
C,J,E,O
C,E,J,O,A
C,J,E,O,A
C,H,L,X,X,X
C,J,L,A,N,H
C,L,H,J,A,N
C,J,O,E,A
C,X,X,X,X,X
C,J,L,H,A,N
C,E,X,X,X
C,J,N,L,H,A
C,J,E,O,A

C,J,A,L,N,H
C,J,N,L,H,A
C,E,J,O,A
C,L,H,X,X,X
C,J,E,O,A
C,J,O,E,A
C,J,N,H,A,L
C,J,L,A,X,X
C,J,H,A,N,L
C,J,H,L,A,N
C,H,L,X,X,X
C,J,E,O,A
J,E,C,O,A
C,J,H,L,N,A
C,J,A,L,N,H
C,J,E,O,A
C,H,J,N,A,L
C,H,X,X,X
C,J,L,N,H,A
C,H,L,J,N,A
C,J,L,N,H,A
C,X,X,X,X,X
C,J,H,L,N,A
C,J,L,N,H,A
C,J,E,O,A
E,C,J,O,A
C,J,L,A,H,N
C,E,J,O,A
J,C,E,O,A
C,J,L,H,N,A

C,J,L,H,N,A
C,L,H,J,N,A
C,H,L,X,X,X
C,J,E,O,A
C,J,E,O,A
C,J,E,A,O
C,H,L,X,X,X
C,H,L,X,X,X
C,L,H,J,A,N
C,J,L,H,N,X
J,C,H,L,N,A
C,J,L,H,A,N
J,C,E,O,A
C,E,A,J,O
C,J,L,N,H,A
C,J,E,O,A
J,C,E,O,A
C,J,L,H,N,X
A,X,X,X,X,X
J,C,N,L,H,A
C,L,H,J,N
C,E,X,X,X
J,E,C,O,A
C,J,L,N,H
C,J,N,L,H,A
C,J,A,L,H,N
C,J,A,N,L,H
C,L,H,X,X,X
C,J,E,O,A
C,J,L,N,H,A
C,H,L,X,X,X
C,H,J,N,L,A
C,J,H,L,N,A
C,H,X,X,X
C,J,L,H,N,A
C,J,H,L,N
C,L,H,X,X,X
C,J,N,H,A,L
C,J,A,L,H,N
C,L,H,J,A,N
C,H,L,N,J,A
C,J,N,L,A,H
C,J,H,A,N,X
C,J,N,H,L
C,J,L,A,H,N
C,L,H,J,A,N
C,J,H,N,A,L
J,C,L,A,N,H
C,H,L,X,X,X
C,E,J,O,A
C,J,E,O,A
C,J,L,H,N
C,J,N,H,L
J,C,N,A,H,X
C,J,E,A,O
C,J,A,E,O
C,J,A,N,H,X
C,L,H,N,X,X
C,H,J,N,A,X
C,J,N,A,X,X
C,L,H,J,N,A
C,J,N,L,H,A
C,X,X,X,X,X
C,J,X,X,X
C,X,X,X,X
C,J,L,N,H,A
C,E,X,X,X
C,E,X,X,X
C,H,L,N,X,X
C,J,L,H,N,A
J,C,E,O,A
C,H,L,X,X,X
C,J,H,N,L,A
C,J,H,N,L,A
C,J,E,O,A
C,J,E,O,A
C,J,E,O,A
C,J,X,X,X,X
C,H,L,J,N
C,L,H,X,X,X
C,E,X,X,X
C,J,L,N,H,A
C,H,L,N,X
C,H,L,J,X,X
C,A,H,N,X,X
J,C,H,L,N,A
C,J,H,L,N,A
C,J,E,O,A
C,J,L,N,H,X
C,J,N,L,H,A
C,J,A,N,L,H
C,J,N,A,H,L
C,J,N,A,L,H
C,H,L,X,X,X
C,H,L,X,X
C,H,J,L,N,A
C,J,L,H,N,A
C,E,X,X,X
C,H,L,X,X,X
C,J,E,O,A
C,J,L,H,N
C,E,J,A,O
C,E,X,X,X
E,O,J,A,C
C,E,X,X,X
C,J,L,A,N,H
C,J,E,O,A
C,J,E,O,A
C,J,L,H,N,A
C,J,L,A,H,N
C,L,H,X,X,X
C,L,J,A,N,H
J,C,E,O,X
C,J,A,L,N,H
C,J,A,H,N,L
C,J,E,O,A
C,H,L,N,J
C,J,E,O,A
C,J,L,A,N,H
C,J,L,H,N
C,L,J,N,A,H
C,J,H,N,A,L
C,E,J,O,A
C,J,E,O,A
C,J,E,A,O
C,J,E,O,A
C,J,A,L,N,H
C,E,J,X,X
C,J,E,O,A
C,J,L,N,H
C,J,N,L,H,A
C,J,L,N,H,A
C,J,N,H,A,L
C,J,X,X,X,X
C,H,N,L,J,A
H,L,C,X,X,X
J,C,E,O,A
C,J,L,N,X,X
C,J,E,O,A
C,J,E,O,A
C,J,X,X,X
C,J,H,L,N,A
C,H,L,X,X,X
C,J,H,L,N,A
C,L,J,H,A,N
C,J,L,N,A,H
J,C,H,N,L,A
C,J,H,L,N,A

E,C,J,O,A
C,J,N,H,A,L
C,J,E,O,A
C,J,E,A,O
C,J,E,O,A
C,H,J,L,N,A
C,X,X,X,X,X
J,E,C,O,A
C,L,H,X,X,X
C,J,H,A,N,X
C,J,L,N,H,A
C,J,E,O,A
J,E,C,O,A
C,H,L,X,X,X
C,J,E,O,A
C,J,L,A,N,H
C,J,L,N,H,A
C,H,J,N,X,X
C,L,H,N,J,X
C,L,H,J,N,A
C,J,L,N,H,A
C,J,L,N,H,A
C,H,X,X,X,X
C,L,H,X,X
C,J,E,A,O
C,L,H,N,J,A
C,J,L,H,A,N
C,J,N,A,L,H
C,J,L,H,A,N
C,E,J,A,O
C,E,O,J,A
C,E,X,X,X
C,J,L,A,N,H
C,J,H,L,N,A
C,J,H,L,A,N
C,J,L,N,H,A
C,H,L,N,J,A
E,C,J,O,A
C,J,E,O,A
C,J,E,O,A
C,E,J,O,A
C,J,L,N,A,H
C,J,L,H,A,N
C,J,E,O,A
C,J,E,A,O
C,J,L,N,H,A
C,J,H,N,L,A
C,E,J,O,A
C,J,E,O,A
J,C,E,O
C,H,L,N,X,X
C,L,H,X,X,X
C,H,L,X,X
J,E,C,O,A
J,C,E,O,A
J,N,C,H,L,A
C,J,L,N,H

C,J,E,O,A
C,J,E,O,A
C,J,L,N,H,A
C,J,L,H,A,N
C,J,O,E,A
C,J,L,N,H,A
C,L,J,H,N,A
C,J,A,H,L,N
C,H,J,A,L,N
C,J,E,O,A
C,J,L,A,H,N
C,J,L,N,A,H
C,J,L,A,N,H
C,J,L,H,A,N
C,J,X,X,X,X
C,J,N,H,A,L
C,J,N,A,H,L
C,J,N,H,X,X
C,X,X,X,X
C,E,J,O,A
C,J,A,N,H,L
C,J,N,H,A,L
C,J,E,O,A
E,J,O,A,C
C,J,H,L,N
J,C,L,N,H,A
C,J,H,N,A,X
C,H,L,N,X,X
C,J,E,O,A
C,J,E,A,O
C,J,E,A,O
C,J,E,O,A
C,J,N,H,L,X
C,L,J,A,H,N
C,J,L,A,N,H
C,J,E,O,A
C,L,H,X,X,X
J,E,O,A,X
C,J,E,O,A
L,H,C,J,N,A
C,J,L,N,X,X
C,J,N,H,A,X
C,J,E,O,A
C,J,E,A,O
C,E,O,A,J
C,E,J,O,A
C,J,N,A,L,H
C,E,O,X,X
C,H,L,J,N,A
C,J,E,O,A
C,J,N,L,H
C,J,H,N,L,A
C,J,A,N,H,L
C,E,J,O,A
J,E,C,O,A
C,H,L,N,J
C,J,H,L,A,N
C,L,H,J,N,A
C,J,L,H,A,N
C,H,L,X,X,X

C,N,J,A,H,L
C,J,E,O,A
J,C,E,O,A
J,E,A,O,C
C,N,L,H,J,A
C,J,E,O,A
C,J,L,N,H,A
J,E,O,C,A
E,C,J,O
C,X,X,X,X,X
E,C,J,O,A
C,E,J,O,A
C,J,E,O,A
C,L,H,J,A,N
C,L,N,J,H,A
C,J,H,N,A,L
C,H,L,X,X,X
C,J,L,H,N,A
C,J,E,O,A
C,H,L,X,X,X
C,H,L,J,N,A
C,H,L,X,X,X
C,E,X,X,X
J,C,E,O,A
J,C,E,A,O
C,J,L,N,X,X
C,J,E,O,A
C,H,L,X,X,X
C,J,H,L,N,X
C,J,L,N,H,A
C,H,J,L,A,N
C,J,L,N,H,A
J,C,N,A,H,L
C,H,L,X,X,X
C,E,J,O,A
J,C,A,E,O
J,C,N,L,H,X
C,L,H,X,X,X
C,E,J,A,O
C,H,J,L,A,N
C,J,A,L,N,H
C,E,J,A,O
C,L,H,X,X,X
C,J,A,N,L,H

C,E,J,A,O
C,J,N,L,H,A
C,J,L,A,N,H
C,J,L,N,H,A
C,J,H,N,A,L
C,X,X,X,X,X
C,J,H,N,X
C,J,L,N,H
C,J,N,H,A,L
J,C,E,O,A
C,J,L,H,N,A
C,J,H,L,A,N
C,L,J,N,H,A
C,J,E,O,X
C,E,J,O,A
C,J,X,X,X,X
C,H,L,X,X
C,E,J,O,A
C,E,X,X,X
C,E,O,A,J
C,J,O,E,A
C,J,X,X,X
C,J,L,H,N
C,J,L,N,H,X
C,J,E,O,A
C,J,E,O,A
C,J,E,O,A
C,J,L,N,A,H
J,A,C,H,L,N
C,J,E,O,A
C,J,N,L,A,H
C,J,H,L,N,A
C,J,H,N,L,A
C,H,L,J,N,A
C,L,H,X,X,X
C,H,J,L,N,A
C,J,E,O,X
J,C,E,A,O
C,X,X,X,X
C,J,X,X,X
C,J,E,O,A
C,J,H,L,N,A
C,L,H,X,X,X
C,J,E,A,O
C,E,J,O,X
C,J,E,O,A
C,E,J,O,A
C,J,L,N,H,A
J,C,N,L,A,H
C,E,O,X,X
O,E,J,C,A
C,J,A,N,H,X
C,J,L,H,N,A
C,J,E,O,A
J,C,H,L,N
C,H,X,X,X,X
C,E,J,O,A
C,J,O,E,A
C,J,L,H,N,A
C,J,A,N,L,H
C,J,L,N,H,A
C,E,J,O,A
C,J,E,O
C,E,J,A,O
C,J,N,H,L,A
C,J,A,N,H,L
C,E,X,X,X
C,H,L,X,X,X
C,N,L,H,J,A
C,J,N,L,H,X
C,L,H,X,X,X
C,J,L,A,H,N
C,J,H,A,L,N
C,J,L,H,N,A
C,H,J,L,N
C,J,E,O,A
C,J,E,A,O
E,O,J,C,A
C,J,E,O,A
C,J,L,N,A,H
C,J,N,H,A,L
J,A,N,X,X,X
C,L,H,J,N,A
C,J,E,O,A
C,H,L,X,X,X
C,E,J,O,A
C,H,X,X,X,X
C,E,J,O,A
C,E,J,O,A
C,H,J,L,N,A
C,J,H,N,X
C,H,L,X,X,X
C,J,N,H,A,L
C,L,H,X,X,X
C,L,H,J,A,N
C,J,E,O,A
C,H,L,N,J,A
C,E,X,X,X
C,J,E,O,A
J,E,O,C,X
C,J,E,O,X
C,J,N,L,H,A
C,J,L,N,H,A
C,J,L,N,H,A
C,J,N,A,H,L
C,J,H,L,N,A
C,H,L,N,A,J
C,J,H,N,A,L
C,J,N,L,H,A
C,E,J,O,A
C,E,J,O,A
C,J,L,A,N,H
C,J,L,N,A,H
C,J,L,N,H,A
C,J,E,A,O
C,J,E,O,A
C,J,E,O,A
C,L,J,A,N,H
C,E,J,O,A
J,C,L,H,N,A
C,J,N,H,L,A
C,J,E,O,A
C,J,E,O,A
C,J,E,O,A

C,J,N,L,H,X
C,E,J,O,A
J,C,L,N,H,A
C,H,L,J,A,N
C,E,J,O,A
C,J,L,H,N,A
C,J,H,A,N,L
C,L,H,J,N
C,E,J,O,A
C,J,E,A,O
C,J,L,N,A,H
C,L,H,X,X,X
C,J,L,N,H,A
H,C,L,J,N,A
C,X,X,X,X,X
J,C,E,O,A
E,J,C,O,A
C,L,H,X,X,X
J,C,E,O,A
C,J,E,O,A
C,J,X,X,X,X
C,J,X,X,X,X
C,E,J,A,O
C,J,E,O,A
J,C,L,A,N,H
C,J,E,O,A
J,C,E,O,A
C,J,E,O,A
C,J,E,O,A
C,J,N,L,H,A

J,C,N,L,H,A
C,J,O,E,A
A,H,L,N,X,X
C,H,L,J,A,N
J,C,N,L,H,A
C,J,A,L,N,H
C,J,L,N,H,A
C,J,E,O,A
J,C,L,N,H,A
C,J,E,O,A
C,J,E,O,A
J,C,N,L,H,A
C,L,J,H,N,A
C,J,L,H,N
J,C,L,N,H,A

J,C,N,L,H,A
C,L,H,J,N,A
C,J,L,H,N,A
C,E,J,X,X
C,J,O,E,A
C,J,E,O,X
C,J,L,N,H,A
C,H,L,X,X,X
C,E,X,X,X
C,J,H,N,A,L
C,E,J,O,A
C,J,E,O,A
C,L,H,N,J,A
C,H,L,N,J,A

C,H,L,N,X,X
C,L,J,A,N,H
C,E,X,X,X
C,J,H,L,N,A
C,J,L,H,N,A
C,J,E,O,A
C,J,L,H,N,A
C,E,J,O,A
C,J,E,O,A
C,H,L,X,X,X
C,J,L,A,N,H
C,J,E,A,O
C,J,N,L,H,A
C,J,H,L,N,A
C,J,E,A,O
C,J,L,H,N,A
C,H,X,X,X,X
C,X,X,X,X
C,J,L,N,H,A
C,X,X,X,X,X
C,J,N,L,H,A
C,J,H,N,A,L
C,E,J,A,O
C,J,E,O,A
J,C,E,O,A
C,J,E,O,A
C,J,N,H,L,A
C,E,X,X,X
C,J,H,L,N,A
C,J,L,N,H
C,J,E,O,A
C,E,J,O,A
C,J,H,L,N,A
C,X,X,X,X,X
A,C,H,J,L,N
C,J,N,L,H

J,C,E,O,A
J,E,C,O,A
C,J,L,A,N,H
J,E,O,C,A
C,J,E,O,A
C,J,E,A,O
C,L,H,N,J,A
C,L,H,X,X,X
C,J,E,O,A
C,E,J,O,A
C,J,E,O,A

C,J,E,O,A
C,J,E,O,A
C,J,N,L,H,A
C,L,H,X,X,X
C,J,H,A,L,N
C,J,L,N,H
C,J,E,O,A
C,J,E,X,X
C,E,J,O,A
C,X,X,X,X,X
C,J,A,L,N,H
C,J,N,H,A,L
C,E,A,J,O
C,J,E,O,A
C,J,L,H,N,A
C,L,N,J,H,A
C,H,L,N,J,A
C,J,H,A,L,N
J,E,C,O
C,J,E,O,A
J,E,C,O,A
C,J,E,O,A
C,E,X,X,X
C,E,X,X,X
C,X,X,X,X,X
C,J,L,A,N,H
C,E,J,O,A
C,L,J,H,A,N
C,J,L,A,H,N
C,J,N,A,H,X
C,X,X,X,X,X
C,J,L,N,H
J,C,E,O,X
E,C,J,O,A
C,E,J,O,A
J,C,H,A,L,N
C,J,H,A,N,L
C,J,L,H,A,N
C,L,H,N,J,A
C,H,L,X,X,X
C,J,L,H,N,A
C,J,H,A,N,X
C,J,O,E,A
J,C,E,O,A
C,E,J,X,X
C,J,N,L,H,A

C,N,H,X,X,X
J,A,E,C,O
C,H,L,X,X
C,J,E,O,A
C,E,J,O,A
C,L,H,J,N,A
C,J,L,N,H,A
C,H,X,X,X,X
C,J,N,H,L
C,H,L,X,X,X
C,J,A,L,N,H
C,H,L,J,N
C,L,J,N,H,A
C,J,H,N,A,L
E,C,X,X
C,J,E,O,A
C,J,E,O,A
C,E,O,J,A
C,J,E,A,O
C,J,N,L,H,A
C,J,N,L,A,H
C,J,L,N,A,H
C,X,X,X,X,X
J,L,N,A,H,C
C,J,H,N,L
C,J,L,A,N,H
C,L,H,J,A,N
C,H,J,A,N,X
C,J,L,N,H,A
C,H,L,X,X,X
C,E,O,J,A
C,J,E,O,A
C,J,L,H,N,A
C,J,L,N,H,A
C,E,J,O,A
C,H,L,X,X,X
C,J,E,O,A
C,J,E,O,A
C,J,L,N,H,A
C,J,N,L,H,A
C,X,X,X,X,X
C,J,L,A,N,H
E,C,O,J,A
C,J,E,O,A
C,E,J,O,A
C,J,L,A,N,H
C,L,H,J,N,A
C,L,H,X,X,X
C,J,E,O,A
C,J,N,L,H,A
C,E,J,O,A
C,J,L,A,N,H

C,J,E,O,X
C,E,J,O,A
C,L,H,X,X
C,A,J,N,H,L
C,J,E,O,A
C,J,E,O,A
C,J,L,H,N,A
C,J,X,X,X,X
C,J,E,O,A
C,J,E,O,X
C,E,J,A,X
C,J,L,A,N,H
C,J,H,A,N,L
C,H,X,X,X,X
J,C,L,H,N,A

C,X,X,X,X
C,H,L,X,X
H,C,L,N,A,J
C,L,H,X,X,X
C,H,X,X,X,X
C,H,X,X,X,X
C,X,X,X,X
C,J,E,O,A
C,E,J,O,A
J,C,A,N,H,X
C,L,H,X,X,X
C,J,E,O,A
C,J,N,L,H,A
C,E,J,O,A
C,J,E,O,A
J,E,A,O,C
J,C,L,A,N,H
C,J,E,O,A
C,E,J,O,A
C,H,L,X,X,X
C,L,H,X,X
C,J,H,A,N,X
C,J,H,N,L,A
C,L,H,X,X,X
C,L,H,X,X,X
C,H,L,X,X,X
C,J,E,A,X
C,J,A,H,N,L
E,C,O,J,A
C,J,E,O,A
C,J,N,L,A,H
C,J,E,O,A
J,C,X,X,X
C,J,L,N,H,A
C,X,X,X,X
C,J,L,N,H,A
C,E,J,O,A
J,C,E,O,A
C,H,X,X,X,X
C,H,L,N,A,X

C,J,H,L,A,N
C,L,N,H,X,X
C,H,L,X,X,X
C,J,H,N,L,A
C,L,H,X,X,X
C,E,X,X,X
C,L,H,X,X,X
H,J,C,N,A,L
J,C,O,E,A
C,J,L,N,A,H
C,N,H,J,L,A
C,J,A,H,L,N
C,J,N,H,A,X
C,J,N,H,A,L
J,C,E,O,A
J,C,E,A,O
E,J,O,A,C
J,C,E,O,A
C,J,E,O,A
C,E,J,A,O
J,A,H,L,C,N
C,L,H,J,N,X
C,J,L,N,H,A
C,J,O,E,A
C,E,X,X,X
C,E,J,O,A
C,J,L,N,H,A
C,J,L,H,N,A
C,E,J,O,A

C,E,J,O,A
C,J,L,N,H,A
C,J,L,H,N,A
J,C,L,H,N
C,J,E,A,O
C,E,J,O,A
C,J,E,O,A
C,J,L,N,H
E,C,X,X,X
C,J,L,N,H,A
C,L,H,N,A,J
C,J,N,L,H,X
C,J,N,L,H,A
C,J,E,O,A
C,J,E,O,A
E,J,O,A,X
C,E,J,A,O
J,E,C,X,X
J,C,A,H,N,L
C,J,E,O,A
C,J,L,H,N,A
C,J,L,N,H,A
C,J,N,L,H,A
C,H,L,A,J,N
C,J,E,O,A
C,E,J,A,O
C,J,L,N,H,A
J,C,E,O,A
C,J,L,N,H,A
C,X,X,X,X,X
C,L,H,J,N,A
C,J,L,N,A,H
C,E,J,O,A
C,J,E,O,A
C,J,N,L,H,A
C,H,L,J,X,X

C,J,L,A,N,H
J,C,L,A,N,H
C,E,X,X,X
C,J,E,X,X
C,J,E,O,A
C,J,E,A,O
J,E,A,O,C
C,E,J,A,O
C,J,E,A,O
J,C,H,N,A,X
C,E,X,X,X
C,H,L,X,X,X
C,L,H,X,X,X
C,J,A,N,H,L
J,A,C,L,N,H
C,J,L,A,N,H
C,L,H,X,X,X
C,J,N,L,H,A
C,E,X,X,X
C,J,E,O,A
C,L,J,N,H,A
C,L,H,J,N,A
C,L,H,N,J,A
C,J,E,O,A
E,J,C,O,A
C,L,H,J,N,A
C,J,L,N,H,A
C,J,A,N,L,H
C,J,L,H,N,X
C,J,E,O,A
C,E,J,O,A
C,E,J,O,A
C,E,J,O,A
C,J,A,L,N,H
C,J,L,N,A,H
C,E,J,O,A
E,J,C,O,A
C,J,E,O,A
C,E,J,O,A
C,J,A,H,L,N
C,J,N,A,H,L
C,J,N,L,H,A
C,J,N,L,A,H
C,E,J,O,A
C,E,O,X,X
C,J,E,O,A
C,J,L,H,N,X
C,J,N,H,A,L
C,E,X,X

C,J,L,H,N
C,J,L,N,H,A
C,E,J,O,A
C,J,E,O,A
C,J,L,H,N
C,J,A,H,N,L

C,L,X,X,X,X
C,E,J,O,A
C,E,X,X,X
E,C,J,O,A

C,E,J,O,A
C,H,L,X,X
J,C,L,A,N,H
C,H,A,J,N,L
C,J,N,H,L,X
J,E,O,C
C,L,H,J,A,N
C,J,H,L,N,A
C,J,A,H,L,N
H,C,L,X,X,X
L,C,J,N,H,A
C,X,X,X,X,X
C,L,N,H,X
C,J,L,N,A,H
C,L,H,X,X,X
C,J,E,O,A
C,E,J,A,O
C,J,E,O,A

C,J,E,O,A
C,H,N,L,X

C,J,A,N,L,H
C,J,E,O,A
C,L,H,N,J,A
J,C,L,N,H,A
C,H,A,J,L,N
C,H,L,X,X,X

C,L,H,J,N
C,J,E,A,O
A,J,O,C,E
C,L,H,X,X,X
C,J,N,H,A,L
J,C,E,O,A
C,J,N,L,A,H
C,J,E,O,A
C,J,L,N,H,A
C,L,N,J,H,A
C,J,E,O,A
C,J,N,L,H,A
J,N,C,L,H,A
C,E,O,X
C,E,J,A,O
H,C,X,X,X,X
E,C,O,J,A
C,J,H,L,N,A
C,J,E,O,A
C,J,E,A,O
C,J,L,H,A,N
E,J,O,A,C
C,J,E,O,A
C,J,N,L,H
A,H,J,L,N,C
C,E,X,X,X
C,L,H,A,N,J
C,L,H,X,X,X
J,C,N,L,A,H

C,J,E,O,A
C,J,O,E,A
C,J,E,O,A
C,J,N,A,H,L
C,J,L,H,N,A
C,L,X,X,X,X
C,H,L,X,X,X
C,J,E,A,O
C,J,E,A,O
C,J,E,O,A
J,N,C,L,H,A
C,J,N,L,H,A

C,H,L,X,X
C,E,J,O,A
C,H,L,J,N,A
C,H,L,X,X,X
C,L,N,J,H
C,L,H,J,N,A
C,H,L,X,X,X
C,J,N,H,L,A
J,E,C,O,X
C,J,E,A,O
C,J,L,A,N,H

C,J,A,N,H,X
C,L,H,X,X,X
J,C,E,O,A
C,H,L,X,X,X
C,J,L,A,H,N
C,E,J,O,A
C,N,J,L,H
C,J,L,H,N,A
C,J,L,A,H,N
J,E,O,A,X
J,C,A,N,L,H
C,L,N,J,H,A
C,J,N,H,L
C,J,A,N,H,L
C,J,L,A,N,H
C,J,E,O,A
C,E,O,J,A
C,H,L,X,X,X
C,E,X,X,X
E,O,J,A,C
C,J,N,A,L,H
C,E,J,A,X
J,C,E,O,A
J,C,E,O,A
C,E,J,O,A
C,L,H,X,X,X
C,J,N,H,A,L
C,J,A,L,N,H
C,E,O,X,X
J,E,A,C,O

C,L,N,J,A,H
C,E,O,J,A
C,H,L,N,X,X
C,J,E,O,A
C,E,J,O,A
C,J,L,H,N,A
C,J,N,L,H,A
C,H,L,X,X,X
J,E,O,A,C
C,J,A,H,N,X
C,J,N,L,H,A
C,H,N,L,J,A
C,E,J,O,A
C,E,J,X,X
N,C,J,L,H,X
C,L,H,J,N,A
C,H,X,X,X,X
C,J,H,L,N
J,C,A,L,H,N
C,J,L,A,N,H
C,L,N,H,J,A
C,H,L,X,X,X
C,J,A,L,N,H
C,J,E,O,A
C,N,L,H,J,A
C,J,A,N,H,L
E,A,J,O,C
J,C,E,O,A
C,L,H,J,A,N
C,J,E,O,A
C,J,L,H,A,N

C,L,N,H,J,A
C,J,N,H,X
C,E,J,O,A
C,J,E,O,A
C,J,L,H,A,N
C,L,N,A,H,J
C,J,E,O,A
C,J,L,N,H,A
C,J,N,L,H,A
C,J,L,A,N,H
C,J,L,H,N,A
C,J,N,L,H,A
C,L,H,J,N,A
C,J,N,H,L,A
J,E,C,O,A
C,E,J,O,A
C,E,J,A,O
J,C,E,O,X
J,A,C,H,L,N
C,J,E,O,A
C,J,L,H,N
J,A,C,L,N,H

C,X,X,X,X,X
C,E,X,X,X
C,J,N,H,L
C,L,H,J,N,A
C,L,N,H,J,A
C,J,E,O,A
J,C,O,E,A
C,J,L,N,H,A
C,H,J,N,A,L
C,J,L,N,H,A
J,A,H,N,C,L
C,L,J,H,N,A
C,L,H,X,X
C,J,H,N,A,X
C,L,H,N,J,A
C,X,X,X,X,X
C,J,N,H,L,A
C,J,E,O,A
J,E,C,A,O
J,C,N,L,H,A
C,J,A,L,H,N
C,L,H,J,A,N
C,J,E,O,A
C,J,E,O,A
C,E,J,A,O
C,J,N,H,A,L

C,E,O,J,A
C,J,E,A,O

C,J,E,A,O
C,J,E,O,X

C,H,L,X,X,X
C,J,N,L,H
C,L,J,H,X,X
C,X,X,X,X,X
E,C,O,J,X
C,J,L,N,X,X
C,J,E,O,A
C,E,J,O
J,C,A,H,L,N
C,E,X,X,X
C,X,X,X,X
C,J,L,N,H,A
C,E,J,O,A
C,J,E,O,A
C,J,N,L,H,A
C,J,H,A,N,L
C,J,L,H,N,X
C,L,H,J,A,N
C,L,H,X,X,X
C,J,L,N,H,A
C,J,A,N,H,L
C,L,H,J,N,A

C,J,L,N,H,X
C,E,J,A,O
C,E,O,J,A
C,J,N,H,A,L
C,L,H,X,X,X
C,J,L,A,H,N
C,L,N,H,J,A
C,J,L,H,N,A
C,J,A,L,H,N
C,X,X,X,X,X
C,L,N,H,J,A
C,J,L,N,A,H
C,H,X,X,X,X
C,E,J,O,A
C,E,J,A,O
C,J,H,N,A,L
C,J,E,O,A
C,H,N,L,X,X
C,L,N,H,J,A
C,J,H,A,N,L
C,J,E,O,A
C,X,X,X,X,X
C,H,L,X,X,X
C,H,L,X,X
C,J,N,L,H,A
C,E,X,X,X
J,E,C,O,A
C,J,L,N,H,A
C,L,H,X,X,X
C,J,E,O,A
C,J,A,L,N,H
C,L,H,X,X,X
C,E,O,X,X
C,J,A,H,N,L
C,J,E,O,A
C,J,E,O,A
C,J,E,O,A
J,C,E,O,A
C,J,H,L,N,A
C,H,J,L,A,N
C,E,J,O,A
C,H,L,A,N,J
C,J,A,L,H,N
C,J,N,L,H
C,J,L,A,N,H
J,C,L,N,H,A
C,H,L,A,N,J
J,C,E,O,A
C,E,O,J,A
N,C,J,L,H,A
C,J,L,N,H
C,J,A,N,X,X
C,J,L,N,H,A
C,L,J,A,N,H
C,J,H,L,N,X
C,J,L,N,H
C,L,H,X,X,X
L,N,C,A,J,H
C,E,J,O,A
C,E,O,J,A
C,J,E,O,A
C,J,E,A,O
C,J,L,N,H
J,C,E,O,A
C,J,L,H,N,A
C,J,L,N,H,X
C,J,E,O,A
C,E,J,O,A

C,H,L,X,X,X
C,H,J,N,L
C,J,A,E,O
C,J,E,O,A
C,J,E,O,A

C,J,L,H,N,A
C,J,A,L,N,H
C,J,E,O,A
C,E,O,X,X
C,X,X,X,X
J,A,N,C,H,L
C,J,L,A,H,N
C,J,H,L,N,A
C,J,E,O,A
C,J,L,N,H,A
J,N,L,C,H,A


J,E,O,A,X
C,E,J,O,A
J,N,A,X,X,X
C,H,L,N,J,A
C,E,X,X,X
C,J,A,L,N,H
J,C,N,L,H,A
C,E,O,J,A
C,J,E,O,A
C,J,H,N,L
C,L,H,N,J,A
C,L,H,X,X,X
C,L,J,N,A,H
C,N,H,L,J
C,L,H,N,J,A
C,E,O,X,X
J,C,L,N,H
C,J,N,L,H,A
C,J,N,L,H,A
C,J,H,N,L,A
C,J,L,N,H,A
C,J,N,L,H,A
J,C,E,O,A
C,L,N,A,H,J
C,E,J,A,O
J,E,O,A,C
C,J,E,O,A
C,J,H,N,L,A
C,J,E,O,A
C,E,J,O,A
C,X,X,X,X,X
C,J,L,N,H,A
C,H,L,X,X,X
C,L,X,X,X,X
C,E,J,O,A
C,J,H,L,N
C,J,E,O,A
C,J,E,A,O
C,E,O,X,X
C,J,N,L,H,A
C,H,L,N,X,X
C,L,H,X,X,X
C,L,H,X,X,X
C,J,N,H,L
C,J,E,O,A

C,J,E,O,A
J,O,C,E,A
C,J,N,H,X
C,H,L,X,X,X
C,H,L,X,X,X
C,J,E,O,A
C,H,L,X,X,X
C,J,E,O,A
C,E,J,O
C,J,A,L,H,N
C,E,J,O,A
C,J,H,A,N,L
C,J,E,A,O
C,J,L,N,H,A
C,L,H,J,N
C,J,E,A,O
C,X,X,X,X
H,C,X,X,X,X
J,O,C,E,A
C,J,N,L,H
C,J,H,L,N,A
C,L,H,N,J,A
C,H,L,N,A,J
C,N,L,J,H,A
J,C,A,N,H,L
C,J,L,N,H,A
C,J,E,O,X
C,J,E,O,A
E,O,J,C,A
J,O,E,C,A
C,J,L,H,A,N
C,E,J,O,A
J,C,A,L,H,N
C,H,L,X,X

C,E,J,O,A
H,C,L,X,X,X

C,J,L,H,N,A
J,A,H,C,L,N
J,A,C,L,H,N
C,E,J,O,A
C,L,H,X,X,X
C,J,L,N,H,A
C,A,H,L,N,J
J,C,E,O,A
C,L,H,X,X,X

C,H,L,J,A,N


C,J,E,O,A
C,L,H,X,X,X
C,H,L,X,X
C,J,L,H,N
C,J,N,H,A,L
C,L,H,N,J,A
C,L,X,X,X
J,A,E,O,C
C,J,N,H,A,X

C,J,A,L,H,N
C,J,E,O,A
C,J,E,O,A
C,J,E,O,A
J,N,A,C,L,H
C,E,J,A,O
C,J,O,A,X
J,C,E,O,A
J,C,E,A,O
C,J,E,O,A
C,J,E,O,A

C,J,A,H,L,N
C,J,E,O,A
C,E,O,X,X
C,J,H,L,N,A
C,J,A,L,H,N
C,E,O,X,X
C,J,E,O,A
C,H,X,X,X
C,J,L,A,N,H


C,J,L,N,H,A
C,J,L,N,A,H
C,L,H,X,X
C,H,L,X,X
C,E,A,J,O
C,E,X,X,X
C,J,H,L,A,N
C,J,H,N,A,L
J,C,O,E,A
C,E,J,A,O
C,H,L,N,J,A
C,E,J,O,A
C,J,L,N,A,H
C,J,L,N,H,A

C,J,E,O
C,H,X,X,X,X
C,L,H,N,J,A
C,J,H,N,L,A
N,L,H,C,A,X
C,E,J,O,A

J,C,X,X,X,X
C,J,L,N,H,A
C,J,E,A,O
C,E,O,J
C,E,O,X,X
C,E,J,O,A
C,H,N,L,A,J
C,J,H,N,A,X
J,C,N,H,L,A
C,J,E,O,A
L,N,H,J,C
C,J,L,N,H
C,H,L,X,X
C,X,X,X,X
C,E,J,O,A
C,J,L,N,H
J,C,A,L,H,N
C,J,E,O,A
J,E,C,O,A
C,J,E,O,A
C,L,H,X,X,X
C,J,L,H,N,A
C,J,L,H,N,A
C,L,H,X,X,X

C,L,H,J,N
C,J,L,A,H,N
L,C,N,H,J
C,L,H,J,N,A
C,L,H,X,X,X

J,C,A,L,N,H
C,J,L,N,A,H
E,C,X,X
C,E,J,O,A
C,J,E,O,A
C,H,L,J,A,N
C,J,L,A,N,H
C,J,L,H,N,A

J,C,L,H,N,A
C,E,J,O,A
C,L,J,H,N
C,J,E,O,A
C,J,E,A,O
C,J,L,N,H,A
C,E,O,J,A
C,E,J,O,A
J,H,C,N,L,A
C,L,H,J,N,A
C,J,L,N,H
C,J,E,X,X
C,E,J,O,A
C,J,L,H,N
C,H,L,N,J,A
C,H,L,J,A,N
C,J,L,N,H,A
C,J,A,L,H,N
O,J,E,C,A
C,X,X,X,X,X
C,L,N,H,J,A
C,L,H,J,A,N
C,E,J,O,X
C,L,H,X,X,X
C,J,E,O,A
C,J,L,A,N,H
C,H,L,N,J,A
E,C,X,X,X
J,A,C,N,H,L
C,E,J,O,A
C,L,H,J,A,N
E,O,J,C,A
C,J,O,E,A
C,L,H,J,N,A
J,E,C,O,A
E,J,A,O,C
C,E,J,O,A
J,A,C,E,O
C,J,E,O,A
L,H,N,C,X,X
C,L,H,X,X,X
C,H,L,N,J
C,J,H,L,N,A
C,J,L,N,H,A
J,C,H,L,N,A
C,A,E,J,O
C,L,J,N,H,A
J,C,E,O,X
C,E,O,J,A
C,O,E,J,A
C,N,L,H,A,J
J,L,C,N,A,H
C,X,X,X,X
C,J,L,A,H,N
C,E,O,J,A
J,A,O,C,E
C,J,E,O,A
C,E,J,O,A
C,L,J,H,N,X
C,J,H,A,L,N
C,J,E,O,A
C,J,L,H,N
C,J,E,O,A
C,E,O,J,A
C,E,J,O,A
L,J,H,C,N,X
C,J,H,L,N
J,E,O,X,X
J,E,O,C,A
C,J,A,L,N,H
C,X,X,X,X
C,J,L,A,H,N
C,J,L,N,H,A
C,J,L,N,H,A
C,H,J,A,N,L
C,J,N,L,H,A
C,H,X,X,X,X
C,J,E,O,A
C,E,J,A,O
C,J,E,O,A
C,J,N,H,L,A
C,J,E,O,A
H,C,L,N,J,A
C,J,E,O,A
C,J,E,O,A
C,J,E,O,A
E,C,J,O,A
C,E,X,X,X
C,E,O,X,X
J,C,L,H,A,N
C,J,N,L,X,X
C,E,J,O,A

C,J,N,L,H,A
C,H,L,N,J,A
C,J,E,O,A
C,J,L,N,H,A
C,E,O,A,J
C,E,J,A,O

C,J,L,N,H,A
C,J,E,O,A
C,E,J,O,A
C,E,J,O,A
C,X,X,X,X
C,E,O,A,J
C,H,L,J,N

C,L,H,N,X,X

C,J,H,L,A,N
C,L,N,A,J,H
C,J,L,N,H,A
E,C,J,O,X
C,E,X,X
C,J,L,H,N
C,L,H,X,X,X
C,J,E,O,A

C,J,N,H,X
C,L,H,J,N
C,E,J,O,A
E,C,O,J,A
C,E,J,A,O
C,E,J,O,A
C,H,L,A,J,N
C,L,A,N,J,H
C,L,N,H,X,X
C,J,H,A,L,N
C,E,O,J,A
C,J,E,A,O
C,J,A,N,H,L
C,J,L,A,N,H
C,J,E,A,O

In [83]:
candidate_df[candidate_df['allocated_category'].notnull()][['allocated_category', 'allocated_subject', 'allocated_post']]

      allocated_category allocated_subject allocated_post
9                      6                 C              B
40                     6                 C              D
59                     9                 C              B
64                     9                 C              D
93                     1                 C              K
...                  ...               ...            ...
16171                  9                 C              D
16179                  9                 C              B
16181                  0                 C              D
16185                  0                 C              B
16198                  1                 C              K

[1754 rows x 3 columns]

In [84]:
candidate_df[(candidate_df['allocated_subject'].notnull())].shape[0]

1754

In [85]:
updated_vacancy_df = pd.DataFrame.from_dict(upd_vacancy_dict, orient='index')

In [86]:
upd_vacancy_df = adjust_vacancy(candidate_df, updated_vacancy_df)

#### 2nd TIME EXECUTION

In [87]:
upd_vacancy_df['left_vacancy'] = upd_vacancy_df['current']
vacancy_dict = {}
upd_vacancy_df['key'] = upd_vacancy_df['category_code'].astype(str) + upd_vacancy_df['subject_option'].astype(str) + upd_vacancy_df['post_code'].astype(str)

for index, row in upd_vacancy_df.iterrows():
    key = row['key']
    vacancy_dict[key] = row.to_dict()

In [88]:
candidate_df[['allocated_category', 'allocated_subject', 'allocated_post', 'allocated_against_ur']] = None

In [89]:
medium = 'C'
upd_vacancy_dict = allocate_candidates(candidate_df, vacancy_dict, medium)

M,D,K,F,G,I,B
D,K,F,G,M,I,B
D,K,G,F,M,I,B
D,K,F,M,I,G,B
D,K,F,G,I,M,B
D,K,F,G,M,B,I
D,K,F,G,M,I
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,K,F,M,G,I,B
D,K,F,M,G,I,B
D,F,G,M,I,X,X
D,K,F,I,G,M,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,G,F,B,M,I
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,B,I
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
K,D,F,G,M,I,B
D,K,F,I,M,G,B
D,K,F,G,M,I,X
D,F,G,M,I,X,X
D,K,F,G,I,M,B
D,F,I,M,G,X,X
D,K,F,G,M,I,B
D,F,M,G,I,K,B
D,F,K,I,G,M,X
D,K,F,G,M,I,B
D,K,F,I,M,G,B
D,G,F,M,I,K,B
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,I,K,F,M,G,X
D,K,F,G,B,M,I
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,F,K,G,M,I
D,K,F,M,I,B,G
D,K,G,F,M,I,B
D,K,G,F,M,B,I
D,K,F,G,M,B,X
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,K,G,F,M,I,B
D,K,F,G,M,I,X
D,K,F,I,M,G,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,F,M,G,I,K,B
D,F,G,M,I,K,B
D,I,F,G,M,K,B
D,K,F,G,M,I,X
D,K,F,G,M,I,B
D,K,F,M,I,G,B
D,K,F,M,G,I
D,F,M,G,I,X
D,K,F,G,M,I,B
D,G,F,M,I,X,X
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,K,G,M,I
D,K,G,F,M,I,B
D,F,M,I,G,X,X
D,F,K,G,I,M,B
D,K,F,M,G,I,B
D,K,M,F,G,I,B
D,K,F,G,M,I,B
D,K,F,X,X,X,X
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,F,G,M,I,X,X
D,K,F,G,M,I
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,G,F,M,B,I
D,F,K,G,M,I,B
D,F,G,X,X,X,X
D,K,F,G,M,I,B
D,K,F,G,B,M,I
D,K,F,G,M,I,X
D,F,G,M,I,X,X
D,K,F,M,G,I,X
D,K,M,F,G,B,I
D,K,F,M,I,G,B
D,K,F,G,M,I,B
D,F,I,G,M,X,X
D,K,F,B,I,G,M
D,K,F,M,G,I,B
D,F,G,M,K,I,X
D,F,G,M,I,X,X
D,F,K,G,M,B,I
D,K,F,I,M,G,X
D,F,M,G,I,K,B
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,K,F,G,M,B,I
D,K,F,I,M,G,B
D,F,I,M,G,X,X
K,D,F,G,M,I,B
D,F,K,G,M,I,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
K,D,F,M,G,I,B
D,K,F,I,G,M,X
D,K,F,M,G,I,B
D,X,X,X,X,X,X
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,F,G,K,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,I,M,X
D,K,F,I,M,G,B
D,K,F,G,M,I,B
D,K,F,I,G,M,B
K,D,F,G,M,I,X
D,K,F,G,M,I,X
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,B,M,I,G
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,G,M,B,I
K,D,F,G,B,M,I
D,K,F,G,M,B,I
D,F,I,G,M,X,X
D,K,F,G,M,I,X
D,F,G,M,I,K,B
D,F,M,K,I,G,B
D,K,G,M,X,X,X
D,F,G,M,I,X
D,K,G,F,X,X,X
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,M,F,G,I,B
D,F,M,G,I,X,X
D,K,F,G,M,I,B
D,X,X,X,X,X,X
D,K,F,G,M,I,B
D,K,F,M,I,G,B
D,K,F,G,M,I,B
D,K,F,B,M,I,G
D,F,I,G,M,X,X
D,K,B,F,G,M,I
D,F,K,M,G,I,X
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,K,F,I,M,G,X
D,K,G,F,M,I,B
D,K,F,M,G,B,I
D,K,F,G,M,I,B
D,K,G,M,F,B,I
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,B,I
D,K,F,G,M,I,B
D,F,I,G,M,X,X
K,F,D,B,M,I,G
D,K,F,M,I,G,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,I,G,M,X,X
D,F,G,I,M,X,X
F,K,X,X,X,X,X
D,K,F,G,M,I,B
D,K,F,I,M,G,B
D,K,F,G,M,I,X
D,K,F,G,I,M,B
D,F,M,K,G,I,B
D,F,G,I,M,X,X
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
K,D,F,G,I,M,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,G,M,X,X,X
D,K,G,F,M,I,B
D,K,F,M,I,G,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,M,G,F,I,B
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,K,F,G,M,I,X
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,F,G,I,M,X,X
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,F,M,G,I,X,X
D,K,F,G,M,I,B
K,D,F,G,I,B,X
K,F,D,G,M,I,B
D,F,G,M,K,I,B
D,K,F,I,G,M,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,M,I,B,G
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,I,B,M
K,F,G,M,I,D,B
D,K,F,M,G,I,B
D,K,F,G,M,B,I
D,F,M,G,K,B,I
D,K,F,G,M,I,B
D,K,F,I,M,G,X
D,K,F,G,I,M,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,G,M,I,B
D,K,F,I,G,M,B
D,X,X,X,X,X,X
D,F,K,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
K,D,G,F,M,I,B
D,F,G,M,I,B,K
D,K,F,B,M,I,G
D,G,F,M,I,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,I,M,X,X
D,K,F,M,G,I,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,G,M,X,X
D,F,G,M,I,K,B
D,K,F,G,M,I
D,K,G,M,X,X,X
D,K,F,I,M,G,B
D,K,F,G,M,I,B
D,F,I,G,M,K,B
D,K,F,G,B,I,M
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,F,M,G,I,K,B
D,F,G,M,I,X
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,K,G,F,M,I,B
D,F,M,G,K,I
D,K,F,I,G,M,B
D,K,F,G,M,I
D,K,F,G,I,M,B
D,K,F,G,M,I,X
D,K,F,G,M,I,B
D,K,F,G,M,I,X
K,F,B,X,X,X,X
D,K,F,G,B,M,I
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,F,G,M,I,B,K
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,F,M,K,G,I,B
D,F,G,M,I,X
D,K,F,G,I,M,B
D,F,G,M,I,K,B
D,K,F,G,B,M,I
D,F,G,M,K,B,I
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,B,G,M,I
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,F,M,G,I,K,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,K,F,G,M,I,B
D,K,F,M,G,I,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,X
D,K,G,F,M,B,I
D,F,G,M,I,X,X
D,K,F,B,G,M,I
D,K,F,G,M,I,B
D,K,M,G,F,I,X
D,K,F,G,M,I,B
D,K,F,B,X,X,X
D,K,F,I,G,M,B
D,F,G,M,I,K,B
D,X,X,X,X,X,X
D,K,F,G,I,M,B
D,K,F,M,G,I,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,F,K,I,G,M,B
D,K,F,G,M,X,X
D,K,F,G,M,I,B
D,G,K,F,M,I,B
D,K,F,G,M,I
D,K,F,G,I,M,B
D,K,F,G,M,B,I
D,K,F,M,I,G,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,X
D,K,F,G,M,I,X
D,F,G,X,X,X,X
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,F,G,M,I,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,M,G,I,B
D,F,G,M,I,X,X
D,F,G,M,I,X,X
D,K,F,M,G,I,B
D,F,G,M,I,K
D,K,F,M,G,I,B
D,K,F,G,M,I,X
F,I,M,G,D,K,X
D,X,X,X,X,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I
D,K,F,B,M,G,I
D,K,X,X,X,X,X
D,F,I,M,G,X,X
D,F,M,G,I,X,X
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,I,G,M,K,B
K,D,F,M,G,I,B
D,K,F,G,M,I,B
D,K,I,F,M,G,B
D,X,X,X,X,X,X
D,F,G,I,M,K,B
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,F,M,K,G,I,B
D,K,G,M,F,I
D,K,F,G,M,I,B
D,F,K,G,I,M,B
D,F,G,M,I,K,B
D,F,G,M,I,X,X
D,F,G,M,I,X,X
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,G,M,B,I
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,F,G,M,K,I,X
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,G,F,K,M,I
D,K,F,I,M,G,B
D,K,F,G,M,I
D,K,F,G,M,I,B
I,G,M,F,D,X,X
D,K,F,G,M,B,I
D,K,F,G,B,M,I
D,K,F,G,I,M,B
D,K,F,G,I,M,B
D,K,F,M,G,B,I
D,K,G,F,I,M,B
D,K,F,M,I,G,X
D,K,F,G,M,I,B
D,F,M,I,G,K,X
D,F,G,I,M,X,X
D,F,M,G,I,K,B
D,F,G,K,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,K,F,G,I,M,B

D,K,F,G,M,I
D,K,F,G,M,I,X
D,K,F,G,M,I,B
F,I,D,G,K,M,B
D,K,F,M,I,G,B
D,K,F,G,M,I,X
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,B,G,M,I
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,I,B,M
D,K,F,G,M,I,B
D,K,F,M,G,B,I
D,K,F,G,M,I,B
D,K,F,G,M,I,X
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,K,G,M,F,I,B
D,K,F,B,I,M,G
D,K,F,G,M,B,I
D,K,F,I,G,M,B
D,F,G,M,I,K,X
D,K,F,G,M,I,B
D,K,F,G,I,M,X
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,B,I
D,F,K,M,I,G,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,G,X,X,X
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,K,M,F,G,I,B
D,K,F,G,M,I
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,B,G,M,I
D,K,F,M,G,I,B
D,K,F,G,M,B,I
D,K,F,B,M,G,I
D,K,F,G,M,I
F,K,G,M,I,D
D,K,F,G,M,I
D,F,I,M,G,X,X
D,K,F,M,I,G,X
D,K,F,G,M,I
D,X,X,X,X,X,X
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,G,F,M,I,X
D,K,F,G,M,I,B
D,K,G,F,X,X,X
D,F,I,M,G,K,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,F,G,I,M,K,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,M,G,I,X
D,K,M,F,G,I,B
D,K,F,G,M,I,X
D,K,F,G,B,M,I
D,F,K,M,G,I,B
D,F,G,I,K,B,M
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,K,F,G,M,B,I
D,F,K,M,I,G,B
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,F,K,I,M,G,B
D,I,K,F,G,M,X
D,K,F,M,I,G,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,F,I,G,M,X,X
D,F,K,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,F,M,G,I,K,B
D,K,F,I,M,G,B
D,G,F,M,I,X,X
D,G,K,F,M,I,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
K,D,X,X,X,X,X
D,K,F,M,G,I,B
I,D,K,F,G,M,B
D,K,F,G,I,M
D,K,F,M,G,I,B
D,I,K,F,G,M,B
D,K,F,B,M,I,G
D,F,G,M,I,X,X
D,K,G,M,I,F,B
D,F,M,I,G,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,M,G,I,X,X
D,K,F,G,M,I,B
D,F,G,M,K,I,B
D,K,F,I,M,G,B
D,K,F,I,G,M,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,G,F,M,I
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,M,B,G,I
D,F,M,I,G,K,B
D,K,F,I,M,G,X
D,K,F,M,I,G,X
D,K,F,G,M,B,I
D,F,G,M,I,X,X
D,K,X,X,X,X,X
D,F,G,K,I,M,B
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
K,D,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,M,G,I,B
D,F,K,M,G,B,I
D,K,G,F,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I
D,K,F,G,M,I,B
D,K,F,G,M,I,B
K,D,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,M,G,B,I
D,M,F,G,I,X
K,G,F,M,I,B,X
D,F,G,M,I,X,X
D,K,F,G,I,M,B
D,K,F,M,G,I,B
D,K,F,M,I,G,B
D,F,K,G,I,M,B
D,K,F,M,G,I,B
D,K,F,I,M,G,B
D,K,F,M,G,I,X
D,F,G,M,I,K,B
D,F,G,M,I,K
D,K,F,G,I,M,B
D,F,G,M,I,X,X
I,D,F,M,G,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I
D,F,K,G,M,I,B
D,K,F,G,M,B,X
D,K,F,G,M,I,B
D,G,F,I,M,X,X
K,D,F,G,I,M,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,B,M,I
D,K,F,G,M,I,B
D,X,X,X,X,X,X
D,K,F,G,M,I,X
K,D,F,G,M,B,X
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,G,I,M,X,X
D,F,G,M,I,K,B
D,K,F,M,G,B,I
K,F,I,M,G,B,D
D,K,F,M,I,G,B
D,K,F,G,M,I,B
D,K,G,F,I,M,B
D,K,F,G,M,I,B
D,K,I,F,G,M,B
D,F,G,K,I,B,M
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,G,M,F,I,B
D,F,G,M,I,X,X
D,F,I,G,M,X,X
D,G,M,F,I,X,X
D,K,G,F,M,I,B
D,K,F,G,M,I,B
K,D,F,G,M,I,B
D,K,F,G,M,I
D,K,G,F,M,B,I
D,F,K,G,I,M,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,K,M,G,I,B
D,K,F,G,M,B,I
D,F,I,G,M,X,X
D,G,F,I,M,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,M,I,G,B
D,K,F,M,G,I,B
D,K,F,X,X,X,X
D,F,I,G,M,X,X
D,K,F,G,M,B,I
D,F,G,M,I,X,X
D,K,F,M,G,I,B
K,F,G,M,D,I,B
D,K,F,G,M,I,X
D,F,G,M,I,B,K
D,F,M,G,X,X
D,G,K,F,M,I
D,K,F,G,M,I,B
D,K,F,G,M,I,X
D,K,F,G,M,I,B
D,F,K,I,G,M,X
D,K,F,M,G,B,I
D,K,F,G,M,I
D,K,F,M,G,I
D,K,G,F,X,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,F,K,B,G,M,I
D,F,M,G,I,X,X
D,K,F,M,G,I,B
D,F,K,G,M,I
D,K,F,M,G,B,I
D,F,G,M,I,X,X
D,F,K,G,M,B,I
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,I,G,M,X,X
D,K,F,G,X,X,X
D,F,G,M,I,K
D,K,F,G,M,I,B
D,K,F,I,B,M,G
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,G,F,B,I,M
D,K,F,G,M,I,B
D,K,F,G,M,I,X
D,F,G,M,I,K,B
D,F,K,G,M,I,B
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,K,F,G,M,B,I
D,K,F,G,M,I,X
D,F,G,M,I,K,B
D,K,F,G,M,I
D,K,F,G,M,I,B
K,F,D,G,M,I,X
D,F,G,M,I,K,B
D,K,F,G,I,M,X
D,F,I,M,G,X,X
D,K,F,G,M,B,I
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,F,G,M,I,X
D,K,F,G,M,I,B
D,F,M,G,I,K,B
D,F,K,G,I,M,X
D,F,G,M,I,X,X
D,K,F,G,M,I,B

D,F,G,M,I,X,X
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,G,F,M,I,B
D,K,M,F,G,I,X
D,F,G,I,M,K,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,I,M,G,X
D,K,F,M,I,G,B
D,K,F,M,G,I,B
D,K,G,F,M,I,B
D,K,F,M,I,G,B
D,F,I,M,G,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,I,B,G,M
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,I,M,B
D,K,F,G,M,X,X
D,F,M,G,I,K
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,X
D,K,F,B,G,M,I
D,K,F,M,I,G,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,G,M,X,X,X,X
D,F,G,K,M,I
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,F,G,M,I,B,X
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,I,M,G,B
D,F,G,M,K,I
D,K,G,M,F,I,B
D,K,F,G,M,I,B
I,F,K,D,M,B,G

D,K,F,B,M,G,I
D,F,G,M,I,X,X
D,F,M,G,K,I
D,F,K,M,G,I,B
D,K,G,F,M,I,B
D,K,F,M,G,I,B
K,D,M,F,G,I,B
D,K,F,M,G,I,B
D,K,F,B,X,X,X
D,F,M,G,I,B,K
D,K,F,G,I,M,B
D,F,G,K,M,I
D,F,X,X,X,X,X
D,F,G,I,M,K,B
D,F,K,G,M,I,B
D,K,F,G,M,I,B
D,K,G,F,M,B,I
D,G,K,F,M,I,B
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,G,F,K,M,I,X
D,F,G,I,M,K,B
D,K,M,F,G,B,I
D,K,F,G,M,I,B
D,F,M,I,G,K
D,K,F,G,M,I,X
D,F,G,M,I,K,B
D,K,F,G,M,I,B
K,F,D,G,M,I,X
D,K,I,M,F,G,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,X
D,K,F,M,G,I,B
D,F,I,G,M,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,I,G,B
F,D,K,G,M,I,B
D,K,F,I,G,M,B
D,K,F,G,M,B,I
D,K,G,F,M,I,B
D,F,I,G,M,K,B
D,K,F,G,M,I,B
D,K,M,F,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,F,M,G,I,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,X,X,X,X
D,K,F,G,I,M,B
D,F,K,G,I,M,B
D,K,F,G,M,I,B
D,K,G,F,M,I,B
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,K,F,B,G,I,M
D,K,G,F,M,I,B
D,K,F,G,M,I,B
D,K,G,F,I,M,B
D,K,F,M,G,B,I
D,K,F,I,M,G,B
D,K,F,B,M,G,I
D,F,K,M,G,I,B
G,M,D,F,I,K,B
D,K,F,G,M,I,B
D,K,F,G,M,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,B,M,I
D,K,F,G,I,M,B
D,K,F,M,I,G,X
D,K,F,M,G,B,I
D,K,F,G,M,I,B
D,F,M,G,I,K,X
D,F,K,M,G,I,B
D,F,K,G,I,M,B
D,K,F,G,M,I,X
D,F,G,M,I,K,B
D,K,F,G,M,B,I
D,K,F,B,X,X,X
D,F,G,I,M,X,X
D,F,G,M,I,B,K
D,F,K,G,M,I,B
D,F,K,X,X,X,X
D,X,X,X,X,X,X
D,K,F,G,M,I,X
D,K,X,X,X,X,X
D,K,F,B,M,I,G
D,K,F,M,I,G,B
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,X,X,X,X,X,X
D,F,K,B,G,I,M
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,K,I,G,F,M,X
D,F,G,M,K,I
D,K,F,G,M,I
D,K,F,G,M,I,X
D,K,F,M,G,I,B
D,K,F,G,M,B,I
D,K,F,I,M,G,B
D,K,F,G,M,I
D,F,M,I,G,K,X
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,K,F,G,M,I,X
D,K,F,M,G,I,B
D,F,G,M,I,X,X
D,K,F,G,M,B,I
D,K,F,G,M,B,I
D,F,G,M,I,X,X
K,D,F,G,M,I,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,X,X,X,X,X,X
D,X,X,X,X,X,X
D,F,K,M,G,I,B
D,F,G,I,M,X
D,K,F,G,I,M,B
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,K,M,G,I,F,X
D,K,F,G,I,M,B
K,D,F,G,B,I,M
D,F,G,M,I,K,B
D,F,K,G,M,I
D,K,F,G,M,I,B
D,K,F,G,I,M,X
D,F,K,G,M,I,X
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,K,X
D,F,M,I,G,K,X
D,K,F,G,M,I,B
D,F,K,I,M,G,B
D,K,G,F,M,B,I
K,D,F,X,X,X,X
D,K,G,F,M,I,B
D,K,F,G,M,I,B
D,K,G,F,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,K,F,G,I,M,B
D,F,I,M,G,X,X
D,F,I,G,M,K,B
D,K,F,B,G,M,I
D,K,F,G,M,I,B
I,D,F,K,M,G,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,I,M,G,B
D,K,F,I,G,M,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
K,D,F,M,G,I,B
D,F,G,M,I,X,X
D,K,F,M,G,I,B
D,F,G,I,M,K,B
D,K,F,I,G,M,B
D,K,G,F,I,M,X
D,F,M,I,G,K,B
D,K,F,G,M,I,B
D,K,G,F,M,I,B
K,D,F,G,M,I,B
D,F,K,M,I,G,X
D,F,G,I,M,B,K
D,K,F,B,I,G,M
K,F,D,M,G,B,I
K,F,D,M,G,I,B
D,K,F,M,G,I,B
D,K,F,I,G,B,M
D,K,F,G,M,I,B
D,K,F,G,M,I,X
D,F,K,M,B,G,I
D,F,G,M,I,X,X
D,K,F,G,M,I,X
G,D,K,F,M,B,I
D,K,G,F,M,I,B
D,F,I,M,G,K,X
D,K,F,B,G,M,I
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,K,G,M,I,B,F
D,K,F,G,M,I,B
D,F,K,G,M,I,B
D,F,I,G,M,K,B
D,F,G,M,K,B,I
D,K,F,I,G,M
D,K,F,G,M,B,I
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,K,G,X,X,X,X
D,K,F,G,M,I,B
D,G,F,I,K,M,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,B,M,G,I
D,K,F,M,G,I,X
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,F,K,G,M,I,B
D,K,F,M,I,G,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,F,G,I,M,X,X
D,K,F,G,M,I
D,K,F,M,G,I,B
D,K,F,G,I,M,B
K,D,F,G,M,I,B
D,F,K,M,G,I,B
D,F,G,M,I,X,X
D,K,F,B,G,M,I
D,K,F,G,M,I,B
D,F,M,G,I,K,B
D,F,G,M,I,K,B
D,K,G,F,M,I,B
D,K,F,G,M,I,B
D,G,F,M,K,I,B
D,F,K,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,G,F,M,I,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,B,G,I,M
D,K,F,G,M,I,X
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,F,G,I,M,X,X
D,K,F,G,M,I,X
D,F,G,K,M,I,B
D,F,K,G,M,I,B
D,K,F,G,I,M,B
D,G,M,K,F,I,B
D,K,F,G,M,I,B
D,K,F,G,B,M,I
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,G,M,I
D,K,F,G,M,I,B
D,F,K,M,G,I,B
D,F,M,G,I,K,B
D,F,M,G,I,X,X
D,K,F,M,G,B,I
G,F,D,M,B,I,X
K,X,X,X,X,X,X
D,F,K,G,M,B,I
D,K,F,M,G,I,B
D,K,G,X,X,X,X
D,F,I,M,G,K,B
D,K,F,G,M,I
D,G,F,M,K,I
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,K,F,G,I,M,B
D,F,B,K,M,G,I
D,K,G,M,F,I,B
D,K,F,G,I,M,B
K,F,G,D,M,I,B
D,F,G,M,I,K,B
D,K,F,I,M,G,B
D,F,G,I,M,K
D,K,F,G,M,I,X
D,K,F,I,M,G,B
D,K,F,G,M,I,X
D,K,F,G,M,I,B
K,D,F,G,M,I,X
D,K,G,M,I,F,B
F,D,M,K,G,I,X
D,F,G,I,M,K,B
D,K,F,G,I,M,B
D,F,G,M,I,X,X
D,K,G,F,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,M,G,I,X
D,K,F,G,I,M
D,K,F,G,M,X,X
D,K,F,G,M,I,B
D,G,F,X,X,X,X
K,D,F,G,M,I,B
D,F,G,M,I,K,B
D,F,G,K,B,I,M
D,K,G,F,I,M,B
D,K,F,G,M,I,B
K,F,D,G,I,M,B
D,F,K,M,G,I,B
D,K,F,B,G,M,I
D,G,K,X,X,X,X
D,K,F,M,G,I,B
D,F,G,I,M,X,X
D,K,X,X,X,X,X
D,K,F,M,G,B,I
D,F,G,M,I,X,X
F,D,K,G,M,I,B
D,K,F,I,M,G,X
D,F,K,M,G,I,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,K,F,M,G,I,X
K,F,I,D,M,G,X
D,F,I,G,M,X,X
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,K,G,F,M,I
D,K,F,G,M,I
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,G,M,I,X
D,K,F,I,M,G,B
D,K,F,I,G,M,B
D,K,F,G,I,M,B
D,F,G,M,I,X,X
D,K,F,I,M,G,X
D,K,F,G,M,I,B
D,K,F,M,G,I
D,K,F,G,M,I,B
D,K,F,M,G,B,I
D,K,F,G,M,I
D,K,F,G,M,I,B
D,F,G,I,M,X,X
D,F,G,M,I,K,B
D,K,M,F,G,I,B
D,F,K,G,M,I,B
D,F,M,G,I,K,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,I,B,M,G
D,K,F,B,M,G,I
K,F,D,M,G,I,X
D,F,K,I,M,G,B
D,F,G,K,M,X,X
D,F,G,I,M,X,X
D,F,K,M,G,I,X
D,K,F,G,M,I,B
D,K,F,G,M,I,X
D,K,F,G,M,I,B
D,K,F,M,I,G,B
D,I,F,G,M,K,X
D,F,G,M,I,K,B
D,F,G,I,M,K,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,F,M,G,I,K,X
D,K,G,F,M,I,B
D,F,K,M,G,B,X
D,K,F,G,I,M,B
D,F,K,B,G,I,M
D,F,K,G,M,I,B
D,G,K,M,F,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,G,M,I,F,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,B,X
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,F,G,M,I,K,B
D,K,F,G,B,M,I
D,K,F,M,I,G,B
D,F,M,G,I,K,B
D,K,F,G,M,B,I
D,K,F,M,I,G,B
D,F,M,G,I,K,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,F,M,I,G,X,X
D,K,G,F,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,I,M,K
D,K,F,G,M,I,B
D,K,F,I,M,G,B
D,F,M,G,I,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,X,X,X,X,X,X
D,K,M,G,F,I,B
M,K,D,G,F,X,X
D,K,F,G,M,I,B
D,K,B,F,G,I,M
D,K,F,M,I,G,B
D,K,F,G,B,M,I
D,G,M,I,K,F,B
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,K,X,X,X,X,X
D,K,F,G,I,M,B
D,F,K,G,I,M,X
D,K,F,M,I,G,B
D,K,M,G,F,B,I
D,K,F,G,I,M,B
D,K,F,M,G,I,X
D,K,F,M,I,G,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I
D,F,M,I,G,X,X
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,I,M,B
D,K,F,G,I,M,B
D,K,F,M,G,I,B
D,F,G,M,I,K,B
D,F,K,G,M,I,B
D,K,F,M,I,G,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,M,G,I,B
D,K,F,M,G,I,X
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,X,X,X,X,X,X
D,K,F,G,M,I,B
D,K,F,M,I,G,B
D,F,K,M,I,G,B
D,F,G,M,K,B,X
D,K,F,M,G,I,B
D,F,M,I,G,K
K,F,D,G,M,I,B
D,K,F,G,M,B,I
D,K,F,X,X,X,X
D,K,F,G,M,I,B
D,K,G,F,M,I,X
D,K,F,M,G,I,X
D,F,G,M,I,K
D,K,F,M,G,I,B
D,F,M,G,I,K,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,F,K,M,G,I,B
F,D,K,B,M,I,G
D,K,F,M,G,I,B
D,K,G,F,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,B,G,M,I
D,F,G,M,I,K,B
D,K,F,M,G,I,B
D,F,M,G,I,K,B
D,K,G,F,M,I,B
D,F,G,M,I,X,X
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,G,F,M,X,X,X
D,K,F,G,M,I,B
D,F,G,K,M,B,I
D,K,F,G,I,M,B
D,F,K,M,G,B,I
D,K,F,G,M,B,I
D,K,G,M,I,F,B
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,K,F,M,G,I,B
K,D,F,G,B,M,I
D,K,F,G,M,B,I
D,X,X,X,X,X
D,F,G,M,I,X,X
D,K,M,G,F,I,B
D,K,F,G,I,M,B
D,F,I,G,M,K,B
D,K,F,G,M,X,X
D,K,F,M,G,B,I
D,K,I,F,M,G,X
D,K,F,M,G,I,B
D,F,K,G,M,I,B
D,K,F,G,M,I,B
D,K,F,I,M,G,B
D,F,G,K,B,I,M
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,K,F,G,M,I,X
D,K,F,G,M,I,B
D,F,M,G,I,K,B
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,K,F,M,G,B,I
D,K,F,G,M,I,X
D,K,F,B,M,G,I
D,F,M,I,G,K
D,K,F,G,M,I,B
D,K,F,I,M,G,B
D,F,M,G,I,X,X
D,K,F,G,M,B,I
D,M,F,K,G,I,B
D,F,M,I,K,G,B
D,K,F,G,I,M,B
D,K,F,I,G,M,B
D,F,G,M,I,K,B
D,K,G,F,M,I,B
D,K,F,G,M,I,B
D,F,G,I,M,X,X
K,B,D,F,G,M,I
D,K,F,G,M,I,B
D,K,G,F,M,I,B
D,F,G,M,I,X,X
D,F,G,I,X,X,X
D,K,F,X,X,X,X
D,K,F,B,M,I,G
D,F,G,M,K,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I
D,B,F,I,G,K,M
D,K,F,G,B,M,I
D,K,F,M,G,I,B
D,K,F,G,M,I,X
D,K,F,G,M,I,B

D,K,G,F,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,G,I,M,B
F,I,G,M,D,X,X
D,F,K,I,M,G,B
D,K,F,G,M,I,B
K,F,G,M,I,B,D
K,F,D,G,M,I,B
D,F,G,M,I,X,X
D,F,I,M,G,X,X
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,M,G,I,X
D,F,G,K,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,F,K,G,M,I,B
D,K,F,G,M,I,B
B,I,M,G,F,X,X
D,K,F,G,I,M,B
D,F,G,M,K,I,X
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,G,K,F,M,I,B
D,K,F,G,M,I
D,K,F,M,G,I,B
D,K,F,G,I,M,B
D,F,G,M,I,K,B
D,K,F,G,M,B,X
D,K,G,M,B,I,X
D,K,F,G,M,I,B
D,K,F,M,G,I
D,F,K,G,M,I
D,K,F,M,G,I,B
D,K,B,F,M,G,I
D,F,M,K,G,I,B
D,K,F,G,I,M,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
K,D,F,G,B,M,I
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,F,I,G,M,X,X
D,K,F,G,M,I,B
D,K,G,F,M,I,B
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,M,F,G,B,I
D,K,F,G,M,I,B
D,F,K,G,M,I,B
I,M,G,F,K,D,B
D,K,F,M,G,B,I
D,K,F,M,G,I,B
D,K,F,M,G,I,B
D,F,M,G,I,K,X
D,K,F,B,G,I,M
D,K,F,G,M,I,B
D,K,G,M,F,I,B
K,F,D,G,M,B,I
D,K,G,X,X,X,X
D,K,F,G,M,I,B
D,F,M,I,G,X,X
D,G,K,F,M,I,B
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,K,F,I,M,G,B
D,K,F,I,G,X,X
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,K,F,G,I,M,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,B,X,X
D,F,G,M,I,X,X
D,F,I,M,G,K,B
D,M,F,I,G,K,B
D,G,K,F,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,K,G,M,I,B
D,K,F,G,M,B,I
D,K,F,I,G,M,B
D,K,F,M,G,I
D,F,G,M,I,X,X
K,B,D,F,I,G,M
K,F,G,M,I,B,D
D,K,M,G,F,I,B
D,K,F,G,I,M,B
D,K,F,M,G,I
D,K,F,G,M,B,I
D,K,F,G,I,M,B
D,K,F,G,M,I,B

In [90]:
medium = 'EM'
upd_vacancy_dict = allocate_candidates(candidate_df, upd_vacancy_dict, medium)

A,X,X,X,X,X
C,E,J,A,O
C,L,H,X,X,X
C,J,E,O,A
C,J,L,A,N,H
C,J,E,O,X
C,J,L,A,H,N
C,J,L,H,N,A
C,J,L,N,H,X
C,J,E,X,X
E,C,J,O,A
C,J,L,H,N,A
C,X,X,X,X,X
C,E,J,O,X
C,J,N,H,L
C,J,L,N,H,A
C,H,X,X,X,X
C,J,E,O,A
C,J,H,N,X,X
C,J,L,H,N,A
C,J,N,H,L,A
C,E,J,O,A
C,J,L,N,H,A
E,O,X,X,X
C,H,L,X,X
C,J,N,A,H,X
C,H,X,X,X,X
C,J,L,N,H,A
C,H,X,X,X,X
C,H,J,L,N,A
J,C,H,N,A,L
C,E,J,O,A
C,E,O,A,J
C,J,L,N,H,A
C,J,N,L,H,A
C,H,L,N,A,X
C,J,H,N,L,X
C,J,H,L,N,A
C,E,J,O,A
C,X,X,X,X
C,J,N,H,L
C,J,E,O,A
C,J,N,H,L,A
C,H,L,X,X,X
C,J,E,O,A
C,J,L,N,H,A
C,J,L,H,N,A
C,H,L,X,X,X
C,J,E,O,A
C,J,X,X,X,X
C,J,N,L,H,A
C,J,H,N,L,A
C,X,X,X,X
C,J,N,H,L,A
C,J,H,L,N,A
C,E,J,O,A
C,J,N,L,H,A
C,J,N,L,H,A
C,L,H,X,X,X
C,J,E,O,A
C,J,N,H,A,X
C,J,E,O,A
C,J,H,N,A,L
C,X,X,X,X
C,J,A,L,N,H
C,E,J,A,O
C,J,E,O,A
C,J,L,N,H,A
C,J,N,H,A,L
C,E,J,O,A
C,J,E,O,A
C,X,X,X,X,X
C,J,E,O,A
C,X,X,X,X
C,H,X,X,X,X
C,J,L,X,X,X
C,J,E,O,A
C,J,H,N,L,A
C,J,O,E,A
C,H,J,N,A,L
C,J,E,O,A
J,C,L,H,N,A
C,J,N,H,A,X,X,X,X,X,X,X,X,X,X
C,L,X,X,X,X
C,J,A,L,N,H
C,E,J,X,X
C,J,L,N,H,A
C,J,E,A,O
C,H,L,X,X,X
C,J,A,N,H,X
C,J,A,N,X,X
C,J,E,O,A
C,J,H,N,L,A
C,J,H,L,N,A
C,J,H,N,L
C,J,H,A,N,L
C,J,N,H,A,L
C,J,E,O,A
C,J,E,O,A
C,J,N,H,L,A
C,J,N,A,H,L
C,E,J,O,A
C,E,X,X,X
C,J,A,N,H,L
C,H,L,X,X,X
C,N,L,A,J,H
C,J,N,H,X
C,J,E,O,A
C,J,L,H,A,N
C,J,N,H,A,X
C,J,H,L,N,A
C,J,E,O,A
C,L,H,J,N,A
C,E,X,X,X
C,J,E,O,A
C,X,X,X,X,X
C,H,J,N,A,X
C,J,E,O,A
C,L,H,X,X,X
C,H,L,X,X,X
C,L,H,J,N,A
C,H,X,X,X,X
C,J,E,O,A
J,C,E,O,A
C,J,L,H,N,A
C,J,N,H,A,L
C,J,N,L,H,A
C,J,N,H,A,L
C,J,H,N,L,A
C,J,H,L,N,A
C,H,X,X,X,X
C,J,A,L,H,N
C,J,E,O,A
C,E,J,O,A
C,X,X,X,X,X
C,L,H,J,A,N
C,J,E,A,O
C,J,L,A,N,H
C,X,X,X,X,X
C,J,E,O,A
C,H,L,X,X,X
C,J,E,O,A
C,L,H,X,X,X
C,J,N,H,L,A
C,E,J,X,X
C,L,H,X,X,X
C,J,E,O,A
C,J,L,H,A,N
C,L,H,X,X
J,C,H,L,N,A
C,J,N,H,L,X
C,L,H,X,X,X
C,J,L,N,H,A
C,J,E,O,A
C,H,L,J,A,N
C,J,E,O,A
C,L,H,X,X,X
C,J,E,O,X
C,J,E,O,A
C,E,J,O,A
C,J,E,O,A
C,J,A,N,H,X
H,C,X,X,X,X
E,C,J,O,X
C,J,E,O,A
C,X,X,X,X,X
C,H,L,J,N
C,J,L,N,H,A
C,J,E,O,A
C,E,J,O,A
J,A,L,C,N,H
J,C,H,N,L
C,J,L,N,H,A
C,J,E,X,X
C,J,E,X,X
C,J,E,O,A
C,H,L,X,X,X
C,H,J,N,A,X
C,X,X,X,X
C,J,E,O,A
C,H,J,N,L,A
C,H,L,J,X,X
C,J,L,H,N,A
C,H,J,N,A,L
C,H,L,X,X,X
C,J,H,L,N,A
C,J,H,N,L,X
C,J,H,N,A,X
C,J,E,O,A
C,J,E,O,A
C,J,H,N,A,L
C,J,N,A,H,X
C,E,J,O,X
C,J,E,O,X
C,J,E,X,X
C,J,E,O,A
C,J,H,L,N,A
C,J,E,O,A
C,H,L,X,X,X
C,J,E,O,A
C,J,E,O,A
C,J,H,N,L,A
C,E,J,O,A
J,C,E,O,A
C,J,E,O,A
C,J,L,N,A,H
C,J,L,H,N
C,H,N,X,X
C,J,E,O,A
C,H,X,X,X,X
C,J,L,N,H,A
C,J,L,H,N,A
C,H,J,N,A,L
C,J,L,N,H,A
C,J,A,L,N,H
C,H,X,X,X,X
C,X,X,X,X,X
J,C,E,O,A
C,J,L,N,H,A
C,E,J,X
J,C,H,N,A,X
C,J,E,O,A
C,L,H,X,X,X
C,J,L,N,H,A
C,J,H,L,N,A

C,J,L,N,A,H
C,J,H,N,A,X
C,J,E,O,A
C,J,E,A,O
C,J,N,L,H,A
C,J,L,N,H,A
C,H,L,N,X,X
C,J,A,L,N,H
E,J,O,A,C
C,H,L,J,X,X
C,J,E,O,A
H,C,N,X,X,X
C,J,E,O,A
C,L,H,J,N,A
C,H,X,X,X,X
C,J,L,N,H,A
C,E,J,O,A
J,L,C,N,H,A
C,L,H,A,N,J
C,H,L,N,X,X
J,E,C,O,A
C,J,L,N,H,A
C,J,L,N,H,A
J,C,E,O,A
C,J,E,O,A
C,J,E,O,A
C,H,J,N,A,L
C,J,L,N,H
J,C,L,N,H,A
C,L,H,X,X,X
C,X,X,X,X,X
C,L,X,X,X
C,L,H,J,N,A
C,J,H,N,L,A
C,E,X,X,X
C,J,L,H,N,A
C,L,H,X,X,X

C,J,H,L,A,N
C,J,N,L,H,A
C,J,E,O,A
C,J,L,H,N
C,J,L,A,N,H
C,J,E,O,A
C,X,X,X,X,X
C,E,X,X,X
C,X,X,X,X,X
C,J,H,L,N,A
C,J,E,X,X
C,X,X,X,X,X
E,J,C,O,A
C,X,X,X,X
C,J,H,N,L,X
C,J,E,O,A
C,L,H,J,N,A
C,J,E,O,A
C,X,X,X,X
J,C,E,A,O
C,H,J,N,A,L
C,J,A,N,H,L
C,L,H,J,X,X
C,L,X,X,X,X
C,J,N,H,A,X
C,J,H,A,N,X
J,C,N,L,H,A
C,L,H,J,N,A
J,C,H,N,A,L
J,C,A,X,X,X
C,J,E,X,X
C,J,E,O,A
J,C,L,N,H,A
C,H,X,X,X,X
C,H,L,X,X,X
C,E,X,X,X
C,H,L,J,N,A
C,H,L,X,X,X
C,H,L,X,X,X
C,H,L,J,X,X
J,C,L,N,A,H
C,E,X,X,X
E,J,C,O,A
C,J,E,O,A
C,E,X,X,X
C,J,L,H,N,A
C,J,E,O,A
C,E,X,X,X
J,C,E,O,A
C,J,N,H,A,L
C,J,N,A,L,H
C,L,X,X,X,X
C,J,E,O,A
C,E,J,O
C,J,L,N,H,A
C,J,E,O,A
C,L,H,J,A,X
C,J,N,H,L,A
C,J,N,H,L,A
C,J,E,O,A

C,J,H,A,N,L
C,J,E,O,A
C,J,N,H,L,X
C,H,X,X,X,X
C,J,E,X,X
C,J,A,N,H,X
C,X,X,X,X,X
C,J,E,O,A
C,J,E,A,O
C,J,L,N,H,A
C,J,H,L,N
C,J,A,L,N,H
C,E,X,X,X
C,J,N,A,H,L
C,J,L,N,A,H
C,H,X,X,X,X
C,J,E,O
C,E,J,O,A
C,J,E,O,A
C,H,L,X,X,X
C,J,L,A,N,H
C,L,H,J,A,N
C,J,O,E,A
C,X,X,X,X,X
C,J,L,H,A,N
C,E,X,X,X
C,J,N,L,H,A
C,J,E,O,A

C,J,A,L,N,H
C,J,N,L,H,A
C,E,J,O,A
C,L,H,X,X,X
C,J,E,O,A
C,J,O,E,A
C,J,N,H,A,L
C,J,L,A,X,X
C,J,H,A,N,L
C,J,H,L,A,N
C,H,L,X,X,X
C,J,E,O,A
J,E,C,O,A
C,J,H,L,N,A
C,J,A,L,N,H
C,J,E,O,A
C,H,J,N,A,L
C,H,X,X,X
C,J,L,N,H,A
C,H,L,J,N,A
C,J,L,N,H,A
C,X,X,X,X,X
C,J,H,L,N,A
C,J,L,N,H,A
C,J,E,O,A
E,C,J,O,A
C,J,L,A,H,N
C,E,J,O,A
J,C,E,O,A
C,J,L,H,N,A

C,J,L,H,N,A
C,L,H,J,N,A
C,H,L,X,X,X
C,J,E,O,A
C,J,E,O,A
C,J,E,A,O
C,H,L,X,X,X
C,H,L,X,X,X
C,L,H,J,A,N
C,J,L,H,N,X
J,C,H,L,N,A
C,J,L,H,A,N
J,C,E,O,A
C,E,A,J,O
C,J,L,N,H,A
C,J,E,O,A
J,C,E,O,A
C,J,L,H,N,X
A,X,X,X,X,X
J,C,N,L,H,A
C,L,H,J,N
C,E,X,X,X
J,E,C,O,A
C,J,L,N,H
C,J,N,L,H,A
C,J,A,L,H,N
C,J,A,N,L,H
C,L,H,X,X,X
C,J,E,O,A
C,J,L,N,H,A
C,H,L,X,X,X
C,H,J,N,L,A
C,J,H,L,N,A
C,H,X,X,X
C,J,L,H,N,A
C,J,H,L,N
C,L,H,X,X,X
C,J,N,H,A,L
C,J,A,L,H,N
C,L,H,J,A,N
C,H,L,N,J,A
C,J,N,L,A,H
C,J,H,A,N,X
C,J,N,H,L
C,J,L,A,H,N
C,L,H,J,A,N
C,J,H,N,A,L
J,C,L,A,N,H
C,H,L,X,X,X
C,E,J,O,A
C,J,E,O,A
C,J,L,H,N
C,J,N,H,L
J,C,N,A,H,X
C,J,E,A,O
C,J,A,E,O
C,J,A,N,H,X
C,L,H,N,X,X
C,H,J,N,A,X
C,J,N,A,X,X
C,L,H,J,N,A
C,J,N,L,H,A
C,X,X,X,X,X
C,J,X,X,X
C,X,X,X,X
C,J,L,N,H,A
C,E,X,X,X
C,E,X,X,X
C,H,L,N,X,X
C,J,L,H,N,A
J,C,E,O,A
C,H,L,X,X,X
C,J,H,N,L,A
C,J,H,N,L,A
C,J,E,O,A
C,J,E,O,A
C,J,E,O,A
C,J,X,X,X,X
C,H,L,J,N
C,L,H,X,X,X
C,E,X,X,X
C,J,L,N,H,A
C,H,L,N,X
C,H,L,J,X,X
C,A,H,N,X,X
J,C,H,L,N,A
C,J,H,L,N,A
C,J,E,O,A
C,J,L,N,H,X
C,J,N,L,H,A
C,J,A,N,L,H
C,J,N,A,H,L
C,J,N,A,L,H
C,H,L,X,X,X
C,H,L,X,X
C,H,J,L,N,A
C,J,L,H,N,A
C,E,X,X,X
C,H,L,X,X,X
C,J,E,O,A
C,J,L,H,N
C,E,J,A,O
C,E,X,X,X
E,O,J,A,C
C,E,X,X,X
C,J,L,A,N,H
C,J,E,O,A
C,J,E,O,A
C,J,L,H,N,A
C,J,L,A,H,N
C,L,H,X,X,X
C,L,J,A,N,H
J,C,E,O,X
C,J,A,L,N,H
C,J,A,H,N,L
C,J,E,O,A
C,H,L,N,J
C,J,E,O,A
C,J,L,A,N,H
C,J,L,H,N
C,L,J,N,A,H
C,J,H,N,A,L
C,E,J,O,A
C,J,E,O,A
C,J,E,A,O
C,J,E,O,A
C,J,A,L,N,H
C,E,J,X,X
C,J,E,O,A
C,J,L,N,H
C,J,N,L,H,A
C,J,L,N,H,A
C,J,N,H,A,L
C,J,X,X,X,X
C,H,N,L,J,A
H,L,C,X,X,X
J,C,E,O,A
C,J,L,N,X,X
C,J,E,O,A
C,J,E,O,A
C,J,X,X,X
C,J,H,L,N,A
C,H,L,X,X,X
C,J,H,L,N,A
C,L,J,H,A,N
C,J,L,N,A,H
J,C,H,N,L,A
C,J,H,L,N,A

E,C,J,O,A
C,J,N,H,A,L
C,J,E,O,A
C,J,E,A,O
C,J,E,O,A
C,H,J,L,N,A
C,X,X,X,X,X
J,E,C,O,A
C,L,H,X,X,X
C,J,H,A,N,X
C,J,L,N,H,A
C,J,E,O,A
J,E,C,O,A
C,H,L,X,X,X
C,J,E,O,A
C,J,L,A,N,H
C,J,L,N,H,A
C,H,J,N,X,X
C,L,H,N,J,X
C,L,H,J,N,A
C,J,L,N,H,A
C,J,L,N,H,A
C,H,X,X,X,X
C,L,H,X,X
C,J,E,A,O
C,L,H,N,J,A
C,J,L,H,A,N
C,J,N,A,L,H
C,J,L,H,A,N
C,E,J,A,O
C,E,O,J,A
C,E,X,X,X
C,J,L,A,N,H
C,J,H,L,N,A
C,J,H,L,A,N
C,J,L,N,H,A
C,H,L,N,J,A
E,C,J,O,A
C,J,E,O,A
C,J,E,O,A
C,E,J,O,A
C,J,L,N,A,H
C,J,L,H,A,N
C,J,E,O,A
C,J,E,A,O
C,J,L,N,H,A
C,J,H,N,L,A
C,E,J,O,A
C,J,E,O,A
J,C,E,O
C,H,L,N,X,X
C,L,H,X,X,X
C,H,L,X,X
J,E,C,O,A
J,C,E,O,A
J,N,C,H,L,A
C,J,L,N,H

C,J,E,O,A
C,J,E,O,A
C,J,L,N,H,A
C,J,L,H,A,N
C,J,O,E,A
C,J,L,N,H,A
C,L,J,H,N,A
C,J,A,H,L,N
C,H,J,A,L,N
C,J,E,O,A
C,J,L,A,H,N
C,J,L,N,A,H
C,J,L,A,N,H
C,J,L,H,A,N
C,J,X,X,X,X
C,J,N,H,A,L
C,J,N,A,H,L
C,J,N,H,X,X
C,X,X,X,X
C,E,J,O,A
C,J,A,N,H,L
C,J,N,H,A,L
C,J,E,O,A
E,J,O,A,C
C,J,H,L,N
J,C,L,N,H,A
C,J,H,N,A,X
C,H,L,N,X,X
C,J,E,O,A
C,J,E,A,O
C,J,E,A,O
C,J,E,O,A
C,J,N,H,L,X
C,L,J,A,H,N
C,J,L,A,N,H
C,J,E,O,A
C,L,H,X,X,X
J,E,O,A,X
C,J,E,O,A
L,H,C,J,N,A
C,J,L,N,X,X
C,J,N,H,A,X
C,J,E,O,A
C,J,E,A,O
C,E,O,A,J
C,E,J,O,A
C,J,N,A,L,H
C,E,O,X,X
C,H,L,J,N,A
C,J,E,O,A
C,J,N,L,H
C,J,H,N,L,A
C,J,A,N,H,L
C,E,J,O,A
J,E,C,O,A
C,H,L,N,J
C,J,H,L,A,N
C,L,H,J,N,A
C,J,L,H,A,N
C,H,L,X,X,X

C,N,J,A,H,L
C,J,E,O,A
J,C,E,O,A
J,E,A,O,C
C,N,L,H,J,A
C,J,E,O,A
C,J,L,N,H,A
J,E,O,C,A
E,C,J,O
C,X,X,X,X,X
E,C,J,O,A
C,E,J,O,A
C,J,E,O,A
C,L,H,J,A,N
C,L,N,J,H,A
C,J,H,N,A,L
C,H,L,X,X,X
C,J,L,H,N,A
C,J,E,O,A
C,H,L,X,X,X
C,H,L,J,N,A
C,H,L,X,X,X
C,E,X,X,X
J,C,E,O,A
J,C,E,A,O
C,J,L,N,X,X
C,J,E,O,A
C,H,L,X,X,X
C,J,H,L,N,X
C,J,L,N,H,A
C,H,J,L,A,N
C,J,L,N,H,A
J,C,N,A,H,L
C,H,L,X,X,X
C,E,J,O,A
J,C,A,E,O
J,C,N,L,H,X
C,L,H,X,X,X
C,E,J,A,O
C,H,J,L,A,N
C,J,A,L,N,H
C,E,J,A,O
C,L,H,X,X,X
C,J,A,N,L,H

C,E,J,A,O
C,J,N,L,H,A
C,J,L,A,N,H
C,J,L,N,H,A
C,J,H,N,A,L
C,X,X,X,X,X
C,J,H,N,X
C,J,L,N,H
C,J,N,H,A,L
J,C,E,O,A
C,J,L,H,N,A
C,J,H,L,A,N
C,L,J,N,H,A
C,J,E,O,X
C,E,J,O,A
C,J,X,X,X,X
C,H,L,X,X
C,E,J,O,A
C,E,X,X,X
C,E,O,A,J
C,J,O,E,A
C,J,X,X,X
C,J,L,H,N
C,J,L,N,H,X
C,J,E,O,A
C,J,E,O,A
C,J,E,O,A
C,J,L,N,A,H
J,A,C,H,L,N
C,J,E,O,A
C,J,N,L,A,H
C,J,H,L,N,A
C,J,H,N,L,A
C,H,L,J,N,A
C,L,H,X,X,X
C,H,J,L,N,A
C,J,E,O,X
J,C,E,A,O
C,X,X,X,X
C,J,X,X,X
C,J,E,O,A
C,J,H,L,N,A
C,L,H,X,X,X
C,J,E,A,O
C,E,J,O,X
C,J,E,O,A
C,E,J,O,A
C,J,L,N,H,A
J,C,N,L,A,H
C,E,O,X,X
O,E,J,C,A
C,J,A,N,H,X
C,J,L,H,N,A
C,J,E,O,A
J,C,H,L,N
C,H,X,X,X,X
C,E,J,O,A
C,J,O,E,A
C,J,L,H,N,A
C,J,A,N,L,H
C,J,L,N,H,A
C,E,J,O,A
C,J,E,O
C,E,J,A,O
C,J,N,H,L,A
C,J,A,N,H,L
C,E,X,X,X
C,H,L,X,X,X
C,N,L,H,J,A
C,J,N,L,H,X
C,L,H,X,X,X
C,J,L,A,H,N
C,J,H,A,L,N
C,J,L,H,N,A
C,H,J,L,N
C,J,E,O,A
C,J,E,A,O
E,O,J,C,A
C,J,E,O,A
C,J,L,N,A,H
C,J,N,H,A,L
J,A,N,X,X,X
C,L,H,J,N,A
C,J,E,O,A
C,H,L,X,X,X
C,E,J,O,A
C,H,X,X,X,X
C,E,J,O,A
C,E,J,O,A
C,H,J,L,N,A
C,J,H,N,X
C,H,L,X,X,X
C,J,N,H,A,L
C,L,H,X,X,X
C,L,H,J,A,N
C,J,E,O,A
C,H,L,N,J,A
C,E,X,X,X
C,J,E,O,A
J,E,O,C,X
C,J,E,O,X
C,J,N,L,H,A
C,J,L,N,H,A
C,J,L,N,H,A
C,J,N,A,H,L
C,J,H,L,N,A
C,H,L,N,A,J
C,J,H,N,A,L
C,J,N,L,H,A
C,E,J,O,A
C,E,J,O,A
C,J,L,A,N,H
C,J,L,N,A,H
C,J,L,N,H,A
C,J,E,A,O
C,J,E,O,A
C,J,E,O,A
C,L,J,A,N,H
C,E,J,O,A
J,C,L,H,N,A
C,J,N,H,L,A
C,J,E,O,A
C,J,E,O,A
C,J,E,O,A

C,J,N,L,H,X
C,E,J,O,A
J,C,L,N,H,A
C,H,L,J,A,N
C,E,J,O,A
C,J,L,H,N,A
C,J,H,A,N,L
C,L,H,J,N
C,E,J,O,A
C,J,E,A,O
C,J,L,N,A,H
C,L,H,X,X,X
C,J,L,N,H,A
H,C,L,J,N,A
C,X,X,X,X,X
J,C,E,O,A
E,J,C,O,A
C,L,H,X,X,X
J,C,E,O,A
C,J,E,O,A
C,J,X,X,X,X
C,J,X,X,X,X
C,E,J,A,O
C,J,E,O,A
J,C,L,A,N,H
C,J,E,O,A
J,C,E,O,A
C,J,E,O,A
C,J,E,O,A
C,J,N,L,H,A

J,C,N,L,H,A
C,J,O,E,A
A,H,L,N,X,X
C,H,L,J,A,N
J,C,N,L,H,A
C,J,A,L,N,H
C,J,L,N,H,A
C,J,E,O,A
J,C,L,N,H,A
C,J,E,O,A
C,J,E,O,A
J,C,N,L,H,A
C,L,J,H,N,A
C,J,L,H,N
J,C,L,N,H,A

J,C,N,L,H,A
C,L,H,J,N,A
C,J,L,H,N,A
C,E,J,X,X
C,J,O,E,A
C,J,E,O,X
C,J,L,N,H,A
C,H,L,X,X,X
C,E,X,X,X
C,J,H,N,A,L
C,E,J,O,A
C,J,E,O,A
C,L,H,N,J,A
C,H,L,N,J,A

C,H,L,N,X,X
C,L,J,A,N,H
C,E,X,X,X
C,J,H,L,N,A
C,J,L,H,N,A
C,J,E,O,A
C,J,L,H,N,A
C,E,J,O,A
C,J,E,O,A
C,H,L,X,X,X
C,J,L,A,N,H
C,J,E,A,O
C,J,N,L,H,A
C,J,H,L,N,A
C,J,E,A,O
C,J,L,H,N,A
C,H,X,X,X,X
C,X,X,X,X
C,J,L,N,H,A
C,X,X,X,X,X
C,J,N,L,H,A
C,J,H,N,A,L
C,E,J,A,O
C,J,E,O,A
J,C,E,O,A
C,J,E,O,A
C,J,N,H,L,A
C,E,X,X,X
C,J,H,L,N,A
C,J,L,N,H
C,J,E,O,A
C,E,J,O,A
C,J,H,L,N,A
C,X,X,X,X,X
A,C,H,J,L,N
C,J,N,L,H

J,C,E,O,A
J,E,C,O,A
C,J,L,A,N,H
J,E,O,C,A
C,J,E,O,A
C,J,E,A,O
C,L,H,N,J,A
C,L,H,X,X,X
C,J,E,O,A
C,E,J,O,A
C,J,E,O,A

C,J,E,O,A
C,J,E,O,A
C,J,N,L,H,A
C,L,H,X,X,X
C,J,H,A,L,N
C,J,L,N,H
C,J,E,O,A
C,J,E,X,X
C,E,J,O,A
C,X,X,X,X,X
C,J,A,L,N,H
C,J,N,H,A,L
C,E,A,J,O
C,J,E,O,A
C,J,L,H,N,A
C,L,N,J,H,A
C,H,L,N,J,A
C,J,H,A,L,N
J,E,C,O
C,J,E,O,A
J,E,C,O,A
C,J,E,O,A
C,E,X,X,X
C,E,X,X,X
C,X,X,X,X,X
C,J,L,A,N,H
C,E,J,O,A
C,L,J,H,A,N
C,J,L,A,H,N
C,J,N,A,H,X
C,X,X,X,X,X
C,J,L,N,H
J,C,E,O,X
E,C,J,O,A
C,E,J,O,A
J,C,H,A,L,N
C,J,H,A,N,L
C,J,L,H,A,N
C,L,H,N,J,A
C,H,L,X,X,X
C,J,L,H,N,A
C,J,H,A,N,X
C,J,O,E,A
J,C,E,O,A
C,E,J,X,X
C,J,N,L,H,A

C,N,H,X,X,X
J,A,E,C,O
C,H,L,X,X
C,J,E,O,A
C,E,J,O,A
C,L,H,J,N,A
C,J,L,N,H,A
C,H,X,X,X,X
C,J,N,H,L
C,H,L,X,X,X
C,J,A,L,N,H
C,H,L,J,N
C,L,J,N,H,A
C,J,H,N,A,L
E,C,X,X
C,J,E,O,A
C,J,E,O,A
C,E,O,J,A
C,J,E,A,O
C,J,N,L,H,A
C,J,N,L,A,H
C,J,L,N,A,H
C,X,X,X,X,X
J,L,N,A,H,C
C,J,H,N,L
C,J,L,A,N,H
C,L,H,J,A,N
C,H,J,A,N,X
C,J,L,N,H,A
C,H,L,X,X,X
C,E,O,J,A
C,J,E,O,A
C,J,L,H,N,A
C,J,L,N,H,A
C,E,J,O,A
C,H,L,X,X,X
C,J,E,O,A
C,J,E,O,A
C,J,L,N,H,A
C,J,N,L,H,A
C,X,X,X,X,X
C,J,L,A,N,H
E,C,O,J,A
C,J,E,O,A
C,E,J,O,A
C,J,L,A,N,H
C,L,H,J,N,A
C,L,H,X,X,X
C,J,E,O,A
C,J,N,L,H,A
C,E,J,O,A
C,J,L,A,N,H

C,J,E,O,X
C,E,J,O,A
C,L,H,X,X
C,A,J,N,H,L
C,J,E,O,A
C,J,E,O,A
C,J,L,H,N,A
C,J,X,X,X,X
C,J,E,O,A
C,J,E,O,X
C,E,J,A,X
C,J,L,A,N,H
C,J,H,A,N,L
C,H,X,X,X,X
J,C,L,H,N,A

C,X,X,X,X
C,H,L,X,X
H,C,L,N,A,J
C,L,H,X,X,X
C,H,X,X,X,X
C,H,X,X,X,X
C,X,X,X,X
C,J,E,O,A
C,E,J,O,A
J,C,A,N,H,X
C,L,H,X,X,X
C,J,E,O,A
C,J,N,L,H,A
C,E,J,O,A
C,J,E,O,A
J,E,A,O,C
J,C,L,A,N,H
C,J,E,O,A
C,E,J,O,A
C,H,L,X,X,X
C,L,H,X,X
C,J,H,A,N,X
C,J,H,N,L,A
C,L,H,X,X,X
C,L,H,X,X,X
C,H,L,X,X,X
C,J,E,A,X
C,J,A,H,N,L
E,C,O,J,A
C,J,E,O,A
C,J,N,L,A,H
C,J,E,O,A
J,C,X,X,X
C,J,L,N,H,A
C,X,X,X,X
C,J,L,N,H,A
C,E,J,O,A
J,C,E,O,A
C,H,X,X,X,X
C,H,L,N,A,X

C,J,H,L,A,N
C,L,N,H,X,X
C,H,L,X,X,X
C,J,H,N,L,A
C,L,H,X,X,X
C,E,X,X,X
C,L,H,X,X,X
H,J,C,N,A,L
J,C,O,E,A
C,J,L,N,A,H
C,N,H,J,L,A
C,J,A,H,L,N
C,J,N,H,A,X
C,J,N,H,A,L
J,C,E,O,A
J,C,E,A,O
E,J,O,A,C
J,C,E,O,A
C,J,E,O,A
C,E,J,A,O
J,A,H,L,C,N
C,L,H,J,N,X
C,J,L,N,H,A
C,J,O,E,A
C,E,X,X,X
C,E,J,O,A
C,J,L,N,H,A
C,J,L,H,N,A
C,E,J,O,A

C,E,J,O,A
C,J,L,N,H,A
C,J,L,H,N,A
J,C,L,H,N
C,J,E,A,O
C,E,J,O,A
C,J,E,O,A
C,J,L,N,H
E,C,X,X,X
C,J,L,N,H,A
C,L,H,N,A,J
C,J,N,L,H,X
C,J,N,L,H,A
C,J,E,O,A
C,J,E,O,A
E,J,O,A,X
C,E,J,A,O
J,E,C,X,X
J,C,A,H,N,L
C,J,E,O,A
C,J,L,H,N,A
C,J,L,N,H,A
C,J,N,L,H,A
C,H,L,A,J,N
C,J,E,O,A
C,E,J,A,O
C,J,L,N,H,A
J,C,E,O,A
C,J,L,N,H,A
C,X,X,X,X,X
C,L,H,J,N,A
C,J,L,N,A,H
C,E,J,O,A
C,J,E,O,A
C,J,N,L,H,A
C,H,L,J,X,X

C,J,L,A,N,H
J,C,L,A,N,H
C,E,X,X,X
C,J,E,X,X
C,J,E,O,A
C,J,E,A,O
J,E,A,O,C
C,E,J,A,O
C,J,E,A,O
J,C,H,N,A,X
C,E,X,X,X
C,H,L,X,X,X
C,L,H,X,X,X
C,J,A,N,H,L
J,A,C,L,N,H
C,J,L,A,N,H
C,L,H,X,X,X
C,J,N,L,H,A
C,E,X,X,X
C,J,E,O,A
C,L,J,N,H,A
C,L,H,J,N,A
C,L,H,N,J,A
C,J,E,O,A
E,J,C,O,A
C,L,H,J,N,A
C,J,L,N,H,A
C,J,A,N,L,H
C,J,L,H,N,X
C,J,E,O,A
C,E,J,O,A
C,E,J,O,A
C,E,J,O,A
C,J,A,L,N,H
C,J,L,N,A,H
C,E,J,O,A
E,J,C,O,A
C,J,E,O,A
C,E,J,O,A
C,J,A,H,L,N
C,J,N,A,H,L
C,J,N,L,H,A
C,J,N,L,A,H
C,E,J,O,A
C,E,O,X,X
C,J,E,O,A
C,J,L,H,N,X
C,J,N,H,A,L
C,E,X,X

C,J,L,H,N
C,J,L,N,H,A
C,E,J,O,A
C,J,E,O,A
C,J,L,H,N
C,J,A,H,N,L

C,L,X,X,X,X
C,E,J,O,A
C,E,X,X,X
E,C,J,O,A

C,E,J,O,A
C,H,L,X,X
J,C,L,A,N,H
C,H,A,J,N,L
C,J,N,H,L,X
J,E,O,C
C,L,H,J,A,N
C,J,H,L,N,A
C,J,A,H,L,N
H,C,L,X,X,X
L,C,J,N,H,A
C,X,X,X,X,X
C,L,N,H,X
C,J,L,N,A,H
C,L,H,X,X,X
C,J,E,O,A
C,E,J,A,O
C,J,E,O,A

C,J,E,O,A
C,H,N,L,X

C,J,A,N,L,H
C,J,E,O,A
C,L,H,N,J,A
J,C,L,N,H,A
C,H,A,J,L,N
C,H,L,X,X,X

C,L,H,J,N
C,J,E,A,O
A,J,O,C,E
C,L,H,X,X,X
C,J,N,H,A,L
J,C,E,O,A
C,J,N,L,A,H
C,J,E,O,A
C,J,L,N,H,A
C,L,N,J,H,A
C,J,E,O,A
C,J,N,L,H,A
J,N,C,L,H,A
C,E,O,X
C,E,J,A,O
H,C,X,X,X,X
E,C,O,J,A
C,J,H,L,N,A
C,J,E,O,A
C,J,E,A,O
C,J,L,H,A,N
E,J,O,A,C
C,J,E,O,A
C,J,N,L,H
A,H,J,L,N,C
C,E,X,X,X
C,L,H,A,N,J
C,L,H,X,X,X
J,C,N,L,A,H

C,J,E,O,A
C,J,O,E,A
C,J,E,O,A
C,J,N,A,H,L
C,J,L,H,N,A
C,L,X,X,X,X
C,H,L,X,X,X
C,J,E,A,O
C,J,E,A,O
C,J,E,O,A
J,N,C,L,H,A
C,J,N,L,H,A

C,H,L,X,X
C,E,J,O,A
C,H,L,J,N,A
C,H,L,X,X,X
C,L,N,J,H
C,L,H,J,N,A
C,H,L,X,X,X
C,J,N,H,L,A
J,E,C,O,X
C,J,E,A,O
C,J,L,A,N,H

C,J,A,N,H,X
C,L,H,X,X,X
J,C,E,O,A
C,H,L,X,X,X
C,J,L,A,H,N
C,E,J,O,A
C,N,J,L,H
C,J,L,H,N,A
C,J,L,A,H,N
J,E,O,A,X
J,C,A,N,L,H
C,L,N,J,H,A
C,J,N,H,L
C,J,A,N,H,L
C,J,L,A,N,H
C,J,E,O,A
C,E,O,J,A
C,H,L,X,X,X
C,E,X,X,X
E,O,J,A,C
C,J,N,A,L,H
C,E,J,A,X
J,C,E,O,A
J,C,E,O,A
C,E,J,O,A
C,L,H,X,X,X
C,J,N,H,A,L
C,J,A,L,N,H
C,E,O,X,X
J,E,A,C,O

C,L,N,J,A,H
C,E,O,J,A
C,H,L,N,X,X
C,J,E,O,A
C,E,J,O,A
C,J,L,H,N,A
C,J,N,L,H,A
C,H,L,X,X,X
J,E,O,A,C
C,J,A,H,N,X
C,J,N,L,H,A
C,H,N,L,J,A
C,E,J,O,A
C,E,J,X,X
N,C,J,L,H,X
C,L,H,J,N,A
C,H,X,X,X,X
C,J,H,L,N
J,C,A,L,H,N
C,J,L,A,N,H
C,L,N,H,J,A
C,H,L,X,X,X
C,J,A,L,N,H
C,J,E,O,A
C,N,L,H,J,A
C,J,A,N,H,L
E,A,J,O,C
J,C,E,O,A
C,L,H,J,A,N
C,J,E,O,A
C,J,L,H,A,N

C,L,N,H,J,A
C,J,N,H,X
C,E,J,O,A
C,J,E,O,A
C,J,L,H,A,N
C,L,N,A,H,J
C,J,E,O,A
C,J,L,N,H,A
C,J,N,L,H,A
C,J,L,A,N,H
C,J,L,H,N,A
C,J,N,L,H,A
C,L,H,J,N,A
C,J,N,H,L,A
J,E,C,O,A
C,E,J,O,A
C,E,J,A,O
J,C,E,O,X
J,A,C,H,L,N
C,J,E,O,A
C,J,L,H,N
J,A,C,L,N,H

C,X,X,X,X,X
C,E,X,X,X
C,J,N,H,L
C,L,H,J,N,A
C,L,N,H,J,A
C,J,E,O,A
J,C,O,E,A
C,J,L,N,H,A
C,H,J,N,A,L
C,J,L,N,H,A
J,A,H,N,C,L
C,L,J,H,N,A
C,L,H,X,X
C,J,H,N,A,X
C,L,H,N,J,A
C,X,X,X,X,X
C,J,N,H,L,A
C,J,E,O,A
J,E,C,A,O
J,C,N,L,H,A
C,J,A,L,H,N
C,L,H,J,A,N
C,J,E,O,A
C,J,E,O,A
C,E,J,A,O
C,J,N,H,A,L

C,E,O,J,A
C,J,E,A,O

C,J,E,A,O
C,J,E,O,X

C,H,L,X,X,X
C,J,N,L,H
C,L,J,H,X,X
C,X,X,X,X,X
E,C,O,J,X
C,J,L,N,X,X
C,J,E,O,A
C,E,J,O
J,C,A,H,L,N
C,E,X,X,X
C,X,X,X,X
C,J,L,N,H,A
C,E,J,O,A
C,J,E,O,A
C,J,N,L,H,A
C,J,H,A,N,L
C,J,L,H,N,X
C,L,H,J,A,N
C,L,H,X,X,X
C,J,L,N,H,A
C,J,A,N,H,L
C,L,H,J,N,A

C,J,L,N,H,X
C,E,J,A,O
C,E,O,J,A
C,J,N,H,A,L
C,L,H,X,X,X
C,J,L,A,H,N
C,L,N,H,J,A
C,J,L,H,N,A
C,J,A,L,H,N
C,X,X,X,X,X
C,L,N,H,J,A
C,J,L,N,A,H
C,H,X,X,X,X
C,E,J,O,A
C,E,J,A,O
C,J,H,N,A,L
C,J,E,O,A
C,H,N,L,X,X
C,L,N,H,J,A
C,J,H,A,N,L
C,J,E,O,A
C,X,X,X,X,X
C,H,L,X,X,X
C,H,L,X,X
C,J,N,L,H,A
C,E,X,X,X
J,E,C,O,A
C,J,L,N,H,A
C,L,H,X,X,X
C,J,E,O,A
C,J,A,L,N,H
C,L,H,X,X,X
C,E,O,X,X
C,J,A,H,N,L
C,J,E,O,A
C,J,E,O,A
C,J,E,O,A
J,C,E,O,A
C,J,H,L,N,A
C,H,J,L,A,N
C,E,J,O,A
C,H,L,A,N,J
C,J,A,L,H,N
C,J,N,L,H
C,J,L,A,N,H
J,C,L,N,H,A
C,H,L,A,N,J
J,C,E,O,A
C,E,O,J,A
N,C,J,L,H,A
C,J,L,N,H
C,J,A,N,X,X
C,J,L,N,H,A
C,L,J,A,N,H
C,J,H,L,N,X
C,J,L,N,H
C,L,H,X,X,X
L,N,C,A,J,H
C,E,J,O,A
C,E,O,J,A
C,J,E,O,A
C,J,E,A,O
C,J,L,N,H
J,C,E,O,A
C,J,L,H,N,A
C,J,L,N,H,X
C,J,E,O,A
C,E,J,O,A

C,H,L,X,X,X
C,H,J,N,L
C,J,A,E,O
C,J,E,O,A
C,J,E,O,A

C,J,L,H,N,A
C,J,A,L,N,H
C,J,E,O,A
C,E,O,X,X
C,X,X,X,X
J,A,N,C,H,L
C,J,L,A,H,N
C,J,H,L,N,A
C,J,E,O,A
C,J,L,N,H,A
J,N,L,C,H,A


J,E,O,A,X
C,E,J,O,A
J,N,A,X,X,X
C,H,L,N,J,A
C,E,X,X,X
C,J,A,L,N,H
J,C,N,L,H,A
C,E,O,J,A
C,J,E,O,A
C,J,H,N,L
C,L,H,N,J,A
C,L,H,X,X,X
C,L,J,N,A,H
C,N,H,L,J
C,L,H,N,J,A
C,E,O,X,X
J,C,L,N,H
C,J,N,L,H,A
C,J,N,L,H,A
C,J,H,N,L,A
C,J,L,N,H,A
C,J,N,L,H,A
J,C,E,O,A
C,L,N,A,H,J
C,E,J,A,O
J,E,O,A,C
C,J,E,O,A
C,J,H,N,L,A
C,J,E,O,A
C,E,J,O,A
C,X,X,X,X,X
C,J,L,N,H,A
C,H,L,X,X,X
C,L,X,X,X,X
C,E,J,O,A
C,J,H,L,N
C,J,E,O,A
C,J,E,A,O
C,E,O,X,X
C,J,N,L,H,A
C,H,L,N,X,X
C,L,H,X,X,X
C,L,H,X,X,X
C,J,N,H,L
C,J,E,O,A

C,J,E,O,A
J,O,C,E,A
C,J,N,H,X
C,H,L,X,X,X
C,H,L,X,X,X
C,J,E,O,A
C,H,L,X,X,X
C,J,E,O,A
C,E,J,O
C,J,A,L,H,N
C,E,J,O,A
C,J,H,A,N,L
C,J,E,A,O
C,J,L,N,H,A
C,L,H,J,N
C,J,E,A,O
C,X,X,X,X
H,C,X,X,X,X
J,O,C,E,A
C,J,N,L,H
C,J,H,L,N,A
C,L,H,N,J,A
C,H,L,N,A,J
C,N,L,J,H,A
J,C,A,N,H,L
C,J,L,N,H,A
C,J,E,O,X
C,J,E,O,A
E,O,J,C,A
J,O,E,C,A
C,J,L,H,A,N
C,E,J,O,A
J,C,A,L,H,N
C,H,L,X,X

C,E,J,O,A
H,C,L,X,X,X

C,J,L,H,N,A
J,A,H,C,L,N
J,A,C,L,H,N
C,E,J,O,A
C,L,H,X,X,X
C,J,L,N,H,A
C,A,H,L,N,J
J,C,E,O,A
C,L,H,X,X,X

C,H,L,J,A,N


C,J,E,O,A
C,L,H,X,X,X
C,H,L,X,X
C,J,L,H,N
C,J,N,H,A,L
C,L,H,N,J,A
C,L,X,X,X
J,A,E,O,C
C,J,N,H,A,X

C,J,A,L,H,N
C,J,E,O,A
C,J,E,O,A
C,J,E,O,A
J,N,A,C,L,H
C,E,J,A,O
C,J,O,A,X
J,C,E,O,A
J,C,E,A,O
C,J,E,O,A
C,J,E,O,A

C,J,A,H,L,N
C,J,E,O,A
C,E,O,X,X
C,J,H,L,N,A
C,J,A,L,H,N
C,E,O,X,X
C,J,E,O,A
C,H,X,X,X
C,J,L,A,N,H


C,J,L,N,H,A
C,J,L,N,A,H
C,L,H,X,X
C,H,L,X,X
C,E,A,J,O
C,E,X,X,X
C,J,H,L,A,N
C,J,H,N,A,L
J,C,O,E,A
C,E,J,A,O
C,H,L,N,J,A
C,E,J,O,A
C,J,L,N,A,H
C,J,L,N,H,A

C,J,E,O
C,H,X,X,X,X
C,L,H,N,J,A
C,J,H,N,L,A
N,L,H,C,A,X
C,E,J,O,A

J,C,X,X,X,X
C,J,L,N,H,A
C,J,E,A,O
C,E,O,J
C,E,O,X,X
C,E,J,O,A
C,H,N,L,A,J
C,J,H,N,A,X
J,C,N,H,L,A
C,J,E,O,A
L,N,H,J,C
C,J,L,N,H
C,H,L,X,X
C,X,X,X,X
C,E,J,O,A
C,J,L,N,H
J,C,A,L,H,N
C,J,E,O,A
J,E,C,O,A
C,J,E,O,A
C,L,H,X,X,X
C,J,L,H,N,A
C,J,L,H,N,A
C,L,H,X,X,X

C,L,H,J,N
C,J,L,A,H,N
L,C,N,H,J
C,L,H,J,N,A
C,L,H,X,X,X

J,C,A,L,N,H
C,J,L,N,A,H
E,C,X,X
C,E,J,O,A
C,J,E,O,A
C,H,L,J,A,N
C,J,L,A,N,H
C,J,L,H,N,A

J,C,L,H,N,A
C,E,J,O,A
C,L,J,H,N
C,J,E,O,A
C,J,E,A,O
C,J,L,N,H,A
C,E,O,J,A
C,E,J,O,A
J,H,C,N,L,A
C,L,H,J,N,A
C,J,L,N,H
C,J,E,X,X
C,E,J,O,A
C,J,L,H,N
C,H,L,N,J,A
C,H,L,J,A,N
C,J,L,N,H,A
C,J,A,L,H,N
O,J,E,C,A
C,X,X,X,X,X
C,L,N,H,J,A
C,L,H,J,A,N
C,E,J,O,X
C,L,H,X,X,X
C,J,E,O,A
C,J,L,A,N,H
C,H,L,N,J,A
E,C,X,X,X
J,A,C,N,H,L
C,E,J,O,A
C,L,H,J,A,N
E,O,J,C,A
C,J,O,E,A
C,L,H,J,N,A
J,E,C,O,A
E,J,A,O,C
C,E,J,O,A
J,A,C,E,O
C,J,E,O,A
L,H,N,C,X,X
C,L,H,X,X,X
C,H,L,N,J
C,J,H,L,N,A
C,J,L,N,H,A
J,C,H,L,N,A
C,A,E,J,O
C,L,J,N,H,A
J,C,E,O,X
C,E,O,J,A
C,O,E,J,A
C,N,L,H,A,J
J,L,C,N,A,H
C,X,X,X,X
C,J,L,A,H,N
C,E,O,J,A
J,A,O,C,E
C,J,E,O,A
C,E,J,O,A
C,L,J,H,N,X
C,J,H,A,L,N
C,J,E,O,A
C,J,L,H,N
C,J,E,O,A
C,E,O,J,A
C,E,J,O,A
L,J,H,C,N,X
C,J,H,L,N
J,E,O,X,X
J,E,O,C,A
C,J,A,L,N,H
C,X,X,X,X
C,J,L,A,H,N
C,J,L,N,H,A
C,J,L,N,H,A
C,H,J,A,N,L
C,J,N,L,H,A
C,H,X,X,X,X
C,J,E,O,A
C,E,J,A,O
C,J,E,O,A
C,J,N,H,L,A
C,J,E,O,A
H,C,L,N,J,A
C,J,E,O,A
C,J,E,O,A
C,J,E,O,A
E,C,J,O,A
C,E,X,X,X
C,E,O,X,X
J,C,L,H,A,N
C,J,N,L,X,X
C,E,J,O,A

C,J,N,L,H,A
C,H,L,N,J,A
C,J,E,O,A
C,J,L,N,H,A
C,E,O,A,J
C,E,J,A,O

C,J,L,N,H,A
C,J,E,O,A
C,E,J,O,A
C,E,J,O,A
C,X,X,X,X
C,E,O,A,J
C,H,L,J,N

C,L,H,N,X,X

C,J,H,L,A,N
C,L,N,A,J,H
C,J,L,N,H,A
E,C,J,O,X
C,E,X,X
C,J,L,H,N
C,L,H,X,X,X
C,J,E,O,A

C,J,N,H,X
C,L,H,J,N
C,E,J,O,A
E,C,O,J,A
C,E,J,A,O
C,E,J,O,A
C,H,L,A,J,N
C,L,A,N,J,H
C,L,N,H,X,X
C,J,H,A,L,N
C,E,O,J,A
C,J,E,A,O
C,J,A,N,H,L
C,J,L,A,N,H
C,J,E,A,O

In [91]:
updated_vacancy_df = pd.DataFrame.from_dict(upd_vacancy_dict, orient='index')

In [92]:
upd_vacancy_df = adjust_vacancy(candidate_df, updated_vacancy_df)

#### 3rd TIME EXECUTION

In [98]:
upd_vacancy_df['left_vacancy'] = upd_vacancy_df['current']
vacancy_dict = {}
upd_vacancy_df['key'] = upd_vacancy_df['category_code'].astype(str) + upd_vacancy_df['subject_option'].astype(str) + upd_vacancy_df['post_code'].astype(str)

for index, row in upd_vacancy_df.iterrows():
    key = row['key']
    vacancy_dict[key] = row.to_dict()

In [99]:
candidate_df[['allocated_category', 'allocated_subject', 'allocated_post', 'allocated_against_ur']] = None

In [100]:
medium = 'C'
upd_vacancy_dict = allocate_candidates(candidate_df, vacancy_dict, medium)

M,D,K,F,G,I,B
D,K,F,G,M,I,B
D,K,G,F,M,I,B
D,K,F,M,I,G,B
D,K,F,G,I,M,B
D,K,F,G,M,B,I
D,K,F,G,M,I
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,K,F,M,G,I,B
D,K,F,M,G,I,B
D,F,G,M,I,X,X
D,K,F,I,G,M,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,G,F,B,M,I
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,B,I
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
K,D,F,G,M,I,B
D,K,F,I,M,G,B
D,K,F,G,M,I,X
D,F,G,M,I,X,X
D,K,F,G,I,M,B
D,F,I,M,G,X,X
D,K,F,G,M,I,B
D,F,M,G,I,K,B
D,F,K,I,G,M,X
D,K,F,G,M,I,B
D,K,F,I,M,G,B
D,G,F,M,I,K,B
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,I,K,F,M,G,X
D,K,F,G,B,M,I
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,F,K,G,M,I
D,K,F,M,I,B,G
D,K,G,F,M,I,B
D,K,G,F,M,B,I
D,K,F,G,M,B,X
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,K,G,F,M,I,B
D,K,F,G,M,I,X
D,K,F,I,M,G,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,F,M,G,I,K,B
D,F,G,M,I,K,B
D,I,F,G,M,K,B
D,K,F,G,M,I,X
D,K,F,G,M,I,B
D,K,F,M,I,G,B
D,K,F,M,G,I
D,F,M,G,I,X
D,K,F,G,M,I,B
D,G,F,M,I,X,X
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,K,G,M,I
D,K,G,F,M,I,B
D,F,M,I,G,X,X
D,F,K,G,I,M,B
D,K,F,M,G,I,B
D,K,M,F,G,I,B
D,K,F,G,M,I,B
D,K,F,X,X,X,X
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,F,G,M,I,X,X
D,K,F,G,M,I
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,G,F,M,B,I
D,F,K,G,M,I,B
D,F,G,X,X,X,X
D,K,F,G,M,I,B
D,K,F,G,B,M,I
D,K,F,G,M,I,X
D,F,G,M,I,X,X
D,K,F,M,G,I,X
D,K,M,F,G,B,I
D,K,F,M,I,G,B
D,K,F,G,M,I,B
D,F,I,G,M,X,X
D,K,F,B,I,G,M
D,K,F,M,G,I,B
D,F,G,M,K,I,X
D,F,G,M,I,X,X
D,F,K,G,M,B,I
D,K,F,I,M,G,X
D,F,M,G,I,K,B
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,K,F,G,M,B,I
D,K,F,I,M,G,B
D,F,I,M,G,X,X
K,D,F,G,M,I,B
D,F,K,G,M,I,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
K,D,F,M,G,I,B
D,K,F,I,G,M,X
D,K,F,M,G,I,B
D,X,X,X,X,X,X
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,F,G,K,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,I,M,X
D,K,F,I,M,G,B
D,K,F,G,M,I,B
D,K,F,I,G,M,B
K,D,F,G,M,I,X
D,K,F,G,M,I,X
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,B,M,I,G
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,G,M,B,I
K,D,F,G,B,M,I
D,K,F,G,M,B,I
D,F,I,G,M,X,X
D,K,F,G,M,I,X
D,F,G,M,I,K,B
D,F,M,K,I,G,B
D,K,G,M,X,X,X
D,F,G,M,I,X
D,K,G,F,X,X,X
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,M,F,G,I,B
D,F,M,G,I,X,X
D,K,F,G,M,I,B
D,X,X,X,X,X,X
D,K,F,G,M,I,B
D,K,F,M,I,G,B
D,K,F,G,M,I,B
D,K,F,B,M,I,G
D,F,I,G,M,X,X
D,K,B,F,G,M,I
D,F,K,M,G,I,X
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,K,F,I,M,G,X
D,K,G,F,M,I,B
D,K,F,M,G,B,I
D,K,F,G,M,I,B
D,K,G,M,F,B,I
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,B,I
D,K,F,G,M,I,B
D,F,I,G,M,X,X
K,F,D,B,M,I,G
D,K,F,M,I,G,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,I,G,M,X,X
D,F,G,I,M,X,X
F,K,X,X,X,X,X
D,K,F,G,M,I,B
D,K,F,I,M,G,B
D,K,F,G,M,I,X
D,K,F,G,I,M,B
D,F,M,K,G,I,B
D,F,G,I,M,X,X
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
K,D,F,G,I,M,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,G,M,X,X,X
D,K,G,F,M,I,B
D,K,F,M,I,G,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,M,G,F,I,B
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,K,F,G,M,I,X
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,F,G,I,M,X,X
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,F,M,G,I,X,X
D,K,F,G,M,I,B
K,D,F,G,I,B,X
K,F,D,G,M,I,B
D,F,G,M,K,I,B
D,K,F,I,G,M,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,M,I,B,G
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,I,B,M
K,F,G,M,I,D,B
D,K,F,M,G,I,B
D,K,F,G,M,B,I
D,F,M,G,K,B,I
D,K,F,G,M,I,B
D,K,F,I,M,G,X
D,K,F,G,I,M,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,G,M,I,B
D,K,F,I,G,M,B
D,X,X,X,X,X,X
D,F,K,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
K,D,G,F,M,I,B
D,F,G,M,I,B,K
D,K,F,B,M,I,G
D,G,F,M,I,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,I,M,X,X
D,K,F,M,G,I,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,G,M,X,X
D,F,G,M,I,K,B
D,K,F,G,M,I
D,K,G,M,X,X,X
D,K,F,I,M,G,B
D,K,F,G,M,I,B
D,F,I,G,M,K,B
D,K,F,G,B,I,M
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,F,M,G,I,K,B
D,F,G,M,I,X
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,K,G,F,M,I,B
D,F,M,G,K,I
D,K,F,I,G,M,B
D,K,F,G,M,I
D,K,F,G,I,M,B
D,K,F,G,M,I,X
D,K,F,G,M,I,B
D,K,F,G,M,I,X
K,F,B,X,X,X,X
D,K,F,G,B,M,I
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,F,G,M,I,B,K
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,F,M,K,G,I,B
D,F,G,M,I,X
D,K,F,G,I,M,B
D,F,G,M,I,K,B
D,K,F,G,B,M,I
D,F,G,M,K,B,I
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,B,G,M,I
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,F,M,G,I,K,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,K,F,G,M,I,B
D,K,F,M,G,I,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,X
D,K,G,F,M,B,I
D,F,G,M,I,X,X
D,K,F,B,G,M,I
D,K,F,G,M,I,B
D,K,M,G,F,I,X
D,K,F,G,M,I,B
D,K,F,B,X,X,X
D,K,F,I,G,M,B
D,F,G,M,I,K,B
D,X,X,X,X,X,X
D,K,F,G,I,M,B
D,K,F,M,G,I,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,F,K,I,G,M,B
D,K,F,G,M,X,X
D,K,F,G,M,I,B
D,G,K,F,M,I,B
D,K,F,G,M,I
D,K,F,G,I,M,B
D,K,F,G,M,B,I
D,K,F,M,I,G,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,X
D,K,F,G,M,I,X
D,F,G,X,X,X,X
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,F,G,M,I,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,M,G,I,B
D,F,G,M,I,X,X
D,F,G,M,I,X,X
D,K,F,M,G,I,B
D,F,G,M,I,K
D,K,F,M,G,I,B
D,K,F,G,M,I,X
F,I,M,G,D,K,X
D,X,X,X,X,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I
D,K,F,B,M,G,I
D,K,X,X,X,X,X
D,F,I,M,G,X,X
D,F,M,G,I,X,X
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,I,G,M,K,B
K,D,F,M,G,I,B
D,K,F,G,M,I,B
D,K,I,F,M,G,B
D,X,X,X,X,X,X
D,F,G,I,M,K,B
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,F,M,K,G,I,B
D,K,G,M,F,I
D,K,F,G,M,I,B
D,F,K,G,I,M,B
D,F,G,M,I,K,B
D,F,G,M,I,X,X
D,F,G,M,I,X,X
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,G,M,B,I
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,F,G,M,K,I,X
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,G,F,K,M,I
D,K,F,I,M,G,B
D,K,F,G,M,I
D,K,F,G,M,I,B
I,G,M,F,D,X,X
D,K,F,G,M,B,I
D,K,F,G,B,M,I
D,K,F,G,I,M,B
D,K,F,G,I,M,B
D,K,F,M,G,B,I
D,K,G,F,I,M,B
D,K,F,M,I,G,X
D,K,F,G,M,I,B
D,F,M,I,G,K,X
D,F,G,I,M,X,X
D,F,M,G,I,K,B
D,F,G,K,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,K,F,G,I,M,B

D,K,F,G,M,I
D,K,F,G,M,I,X
D,K,F,G,M,I,B
F,I,D,G,K,M,B
D,K,F,M,I,G,B
D,K,F,G,M,I,X
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,B,G,M,I
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,I,B,M
D,K,F,G,M,I,B
D,K,F,M,G,B,I
D,K,F,G,M,I,B
D,K,F,G,M,I,X
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,K,G,M,F,I,B
D,K,F,B,I,M,G
D,K,F,G,M,B,I
D,K,F,I,G,M,B
D,F,G,M,I,K,X
D,K,F,G,M,I,B
D,K,F,G,I,M,X
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,B,I
D,F,K,M,I,G,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,G,X,X,X
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,K,M,F,G,I,B
D,K,F,G,M,I
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,B,G,M,I
D,K,F,M,G,I,B
D,K,F,G,M,B,I
D,K,F,B,M,G,I
D,K,F,G,M,I
F,K,G,M,I,D
D,K,F,G,M,I
D,F,I,M,G,X,X
D,K,F,M,I,G,X
D,K,F,G,M,I
D,X,X,X,X,X,X
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,G,F,M,I,X
D,K,F,G,M,I,B
D,K,G,F,X,X,X
D,F,I,M,G,K,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,F,G,I,M,K,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,M,G,I,X
D,K,M,F,G,I,B
D,K,F,G,M,I,X
D,K,F,G,B,M,I
D,F,K,M,G,I,B
D,F,G,I,K,B,M
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,K,F,G,M,B,I
D,F,K,M,I,G,B
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,F,K,I,M,G,B
D,I,K,F,G,M,X
D,K,F,M,I,G,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,F,I,G,M,X,X
D,F,K,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,F,M,G,I,K,B
D,K,F,I,M,G,B
D,G,F,M,I,X,X
D,G,K,F,M,I,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
K,D,X,X,X,X,X
D,K,F,M,G,I,B
I,D,K,F,G,M,B
D,K,F,G,I,M
D,K,F,M,G,I,B
D,I,K,F,G,M,B
D,K,F,B,M,I,G
D,F,G,M,I,X,X
D,K,G,M,I,F,B
D,F,M,I,G,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,M,G,I,X,X
D,K,F,G,M,I,B
D,F,G,M,K,I,B
D,K,F,I,M,G,B
D,K,F,I,G,M,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,G,F,M,I
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,M,B,G,I
D,F,M,I,G,K,B
D,K,F,I,M,G,X
D,K,F,M,I,G,X
D,K,F,G,M,B,I
D,F,G,M,I,X,X
D,K,X,X,X,X,X
D,F,G,K,I,M,B
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
K,D,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,M,G,I,B
D,F,K,M,G,B,I
D,K,G,F,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I
D,K,F,G,M,I,B
D,K,F,G,M,I,B
K,D,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,M,G,B,I
D,M,F,G,I,X
K,G,F,M,I,B,X
D,F,G,M,I,X,X
D,K,F,G,I,M,B
D,K,F,M,G,I,B
D,K,F,M,I,G,B
D,F,K,G,I,M,B
D,K,F,M,G,I,B
D,K,F,I,M,G,B
D,K,F,M,G,I,X
D,F,G,M,I,K,B
D,F,G,M,I,K
D,K,F,G,I,M,B
D,F,G,M,I,X,X
I,D,F,M,G,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I
D,F,K,G,M,I,B
D,K,F,G,M,B,X
D,K,F,G,M,I,B
D,G,F,I,M,X,X
K,D,F,G,I,M,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,B,M,I
D,K,F,G,M,I,B
D,X,X,X,X,X,X
D,K,F,G,M,I,X
K,D,F,G,M,B,X
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,G,I,M,X,X
D,F,G,M,I,K,B
D,K,F,M,G,B,I
K,F,I,M,G,B,D
D,K,F,M,I,G,B
D,K,F,G,M,I,B
D,K,G,F,I,M,B
D,K,F,G,M,I,B
D,K,I,F,G,M,B
D,F,G,K,I,B,M
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,G,M,F,I,B
D,F,G,M,I,X,X
D,F,I,G,M,X,X
D,G,M,F,I,X,X
D,K,G,F,M,I,B
D,K,F,G,M,I,B
K,D,F,G,M,I,B
D,K,F,G,M,I
D,K,G,F,M,B,I
D,F,K,G,I,M,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,K,M,G,I,B
D,K,F,G,M,B,I
D,F,I,G,M,X,X
D,G,F,I,M,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,M,I,G,B
D,K,F,M,G,I,B
D,K,F,X,X,X,X
D,F,I,G,M,X,X
D,K,F,G,M,B,I
D,F,G,M,I,X,X
D,K,F,M,G,I,B
K,F,G,M,D,I,B
D,K,F,G,M,I,X
D,F,G,M,I,B,K
D,F,M,G,X,X
D,G,K,F,M,I
D,K,F,G,M,I,B
D,K,F,G,M,I,X
D,K,F,G,M,I,B
D,F,K,I,G,M,X
D,K,F,M,G,B,I
D,K,F,G,M,I
D,K,F,M,G,I
D,K,G,F,X,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,F,K,B,G,M,I
D,F,M,G,I,X,X
D,K,F,M,G,I,B
D,F,K,G,M,I
D,K,F,M,G,B,I
D,F,G,M,I,X,X
D,F,K,G,M,B,I
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,I,G,M,X,X
D,K,F,G,X,X,X
D,F,G,M,I,K
D,K,F,G,M,I,B
D,K,F,I,B,M,G
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,G,F,B,I,M
D,K,F,G,M,I,B
D,K,F,G,M,I,X
D,F,G,M,I,K,B
D,F,K,G,M,I,B
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,K,F,G,M,B,I
D,K,F,G,M,I,X
D,F,G,M,I,K,B
D,K,F,G,M,I
D,K,F,G,M,I,B
K,F,D,G,M,I,X
D,F,G,M,I,K,B
D,K,F,G,I,M,X
D,F,I,M,G,X,X
D,K,F,G,M,B,I
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,F,G,M,I,X
D,K,F,G,M,I,B
D,F,M,G,I,K,B
D,F,K,G,I,M,X
D,F,G,M,I,X,X
D,K,F,G,M,I,B

D,F,G,M,I,X,X
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,G,F,M,I,B
D,K,M,F,G,I,X
D,F,G,I,M,K,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,I,M,G,X
D,K,F,M,I,G,B
D,K,F,M,G,I,B
D,K,G,F,M,I,B
D,K,F,M,I,G,B
D,F,I,M,G,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,I,B,G,M
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,I,M,B
D,K,F,G,M,X,X
D,F,M,G,I,K
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,X
D,K,F,B,G,M,I
D,K,F,M,I,G,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,G,M,X,X,X,X
D,F,G,K,M,I
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,F,G,M,I,B,X
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,I,M,G,B
D,F,G,M,K,I
D,K,G,M,F,I,B
D,K,F,G,M,I,B
I,F,K,D,M,B,G

D,K,F,B,M,G,I
D,F,G,M,I,X,X
D,F,M,G,K,I
D,F,K,M,G,I,B
D,K,G,F,M,I,B
D,K,F,M,G,I,B
K,D,M,F,G,I,B
D,K,F,M,G,I,B
D,K,F,B,X,X,X
D,F,M,G,I,B,K
D,K,F,G,I,M,B
D,F,G,K,M,I
D,F,X,X,X,X,X
D,F,G,I,M,K,B
D,F,K,G,M,I,B
D,K,F,G,M,I,B
D,K,G,F,M,B,I
D,G,K,F,M,I,B
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,G,F,K,M,I,X
D,F,G,I,M,K,B
D,K,M,F,G,B,I
D,K,F,G,M,I,B
D,F,M,I,G,K
D,K,F,G,M,I,X
D,F,G,M,I,K,B
D,K,F,G,M,I,B
K,F,D,G,M,I,X
D,K,I,M,F,G,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,X
D,K,F,M,G,I,B
D,F,I,G,M,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,I,G,B
F,D,K,G,M,I,B
D,K,F,I,G,M,B
D,K,F,G,M,B,I
D,K,G,F,M,I,B
D,F,I,G,M,K,B
D,K,F,G,M,I,B
D,K,M,F,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,F,M,G,I,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,X,X,X,X
D,K,F,G,I,M,B
D,F,K,G,I,M,B
D,K,F,G,M,I,B
D,K,G,F,M,I,B
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,K,F,B,G,I,M
D,K,G,F,M,I,B
D,K,F,G,M,I,B
D,K,G,F,I,M,B
D,K,F,M,G,B,I
D,K,F,I,M,G,B
D,K,F,B,M,G,I
D,F,K,M,G,I,B
G,M,D,F,I,K,B
D,K,F,G,M,I,B
D,K,F,G,M,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,B,M,I
D,K,F,G,I,M,B
D,K,F,M,I,G,X
D,K,F,M,G,B,I
D,K,F,G,M,I,B
D,F,M,G,I,K,X
D,F,K,M,G,I,B
D,F,K,G,I,M,B
D,K,F,G,M,I,X
D,F,G,M,I,K,B
D,K,F,G,M,B,I
D,K,F,B,X,X,X
D,F,G,I,M,X,X
D,F,G,M,I,B,K
D,F,K,G,M,I,B
D,F,K,X,X,X,X
D,X,X,X,X,X,X
D,K,F,G,M,I,X
D,K,X,X,X,X,X
D,K,F,B,M,I,G
D,K,F,M,I,G,B
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,X,X,X,X,X,X
D,F,K,B,G,I,M
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,K,I,G,F,M,X
D,F,G,M,K,I
D,K,F,G,M,I
D,K,F,G,M,I,X
D,K,F,M,G,I,B
D,K,F,G,M,B,I
D,K,F,I,M,G,B
D,K,F,G,M,I
D,F,M,I,G,K,X
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,K,F,G,M,I,X
D,K,F,M,G,I,B
D,F,G,M,I,X,X
D,K,F,G,M,B,I
D,K,F,G,M,B,I
D,F,G,M,I,X,X
K,D,F,G,M,I,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,X,X,X,X,X,X
D,X,X,X,X,X,X
D,F,K,M,G,I,B
D,F,G,I,M,X
D,K,F,G,I,M,B
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,K,M,G,I,F,X
D,K,F,G,I,M,B
K,D,F,G,B,I,M
D,F,G,M,I,K,B
D,F,K,G,M,I
D,K,F,G,M,I,B
D,K,F,G,I,M,X
D,F,K,G,M,I,X
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,K,X
D,F,M,I,G,K,X
D,K,F,G,M,I,B
D,F,K,I,M,G,B
D,K,G,F,M,B,I
K,D,F,X,X,X,X
D,K,G,F,M,I,B
D,K,F,G,M,I,B
D,K,G,F,M,I,B
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,K,F,G,I,M,B
D,F,I,M,G,X,X
D,F,I,G,M,K,B
D,K,F,B,G,M,I
D,K,F,G,M,I,B
I,D,F,K,M,G,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,I,M,G,B
D,K,F,I,G,M,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
K,D,F,M,G,I,B
D,F,G,M,I,X,X
D,K,F,M,G,I,B
D,F,G,I,M,K,B
D,K,F,I,G,M,B
D,K,G,F,I,M,X
D,F,M,I,G,K,B
D,K,F,G,M,I,B
D,K,G,F,M,I,B
K,D,F,G,M,I,B
D,F,K,M,I,G,X
D,F,G,I,M,B,K
D,K,F,B,I,G,M
K,F,D,M,G,B,I
K,F,D,M,G,I,B
D,K,F,M,G,I,B
D,K,F,I,G,B,M
D,K,F,G,M,I,B
D,K,F,G,M,I,X
D,F,K,M,B,G,I
D,F,G,M,I,X,X
D,K,F,G,M,I,X
G,D,K,F,M,B,I
D,K,G,F,M,I,B
D,F,I,M,G,K,X
D,K,F,B,G,M,I
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,K,G,M,I,B,F
D,K,F,G,M,I,B
D,F,K,G,M,I,B
D,F,I,G,M,K,B
D,F,G,M,K,B,I
D,K,F,I,G,M
D,K,F,G,M,B,I
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,K,G,X,X,X,X
D,K,F,G,M,I,B
D,G,F,I,K,M,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,B,M,G,I
D,K,F,M,G,I,X
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,F,K,G,M,I,B
D,K,F,M,I,G,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,F,G,I,M,X,X
D,K,F,G,M,I
D,K,F,M,G,I,B
D,K,F,G,I,M,B
K,D,F,G,M,I,B
D,F,K,M,G,I,B
D,F,G,M,I,X,X
D,K,F,B,G,M,I
D,K,F,G,M,I,B
D,F,M,G,I,K,B
D,F,G,M,I,K,B
D,K,G,F,M,I,B
D,K,F,G,M,I,B
D,G,F,M,K,I,B
D,F,K,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,G,F,M,I,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,B,G,I,M
D,K,F,G,M,I,X
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,F,G,I,M,X,X
D,K,F,G,M,I,X
D,F,G,K,M,I,B
D,F,K,G,M,I,B
D,K,F,G,I,M,B
D,G,M,K,F,I,B
D,K,F,G,M,I,B
D,K,F,G,B,M,I
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,G,M,I
D,K,F,G,M,I,B
D,F,K,M,G,I,B
D,F,M,G,I,K,B
D,F,M,G,I,X,X
D,K,F,M,G,B,I
G,F,D,M,B,I,X
K,X,X,X,X,X,X
D,F,K,G,M,B,I
D,K,F,M,G,I,B
D,K,G,X,X,X,X
D,F,I,M,G,K,B
D,K,F,G,M,I
D,G,F,M,K,I
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,K,F,G,I,M,B
D,F,B,K,M,G,I
D,K,G,M,F,I,B
D,K,F,G,I,M,B
K,F,G,D,M,I,B
D,F,G,M,I,K,B
D,K,F,I,M,G,B
D,F,G,I,M,K
D,K,F,G,M,I,X
D,K,F,I,M,G,B
D,K,F,G,M,I,X
D,K,F,G,M,I,B
K,D,F,G,M,I,X
D,K,G,M,I,F,B
F,D,M,K,G,I,X
D,F,G,I,M,K,B
D,K,F,G,I,M,B
D,F,G,M,I,X,X
D,K,G,F,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,M,G,I,X
D,K,F,G,I,M
D,K,F,G,M,X,X
D,K,F,G,M,I,B
D,G,F,X,X,X,X
K,D,F,G,M,I,B
D,F,G,M,I,K,B
D,F,G,K,B,I,M
D,K,G,F,I,M,B
D,K,F,G,M,I,B
K,F,D,G,I,M,B
D,F,K,M,G,I,B
D,K,F,B,G,M,I
D,G,K,X,X,X,X
D,K,F,M,G,I,B
D,F,G,I,M,X,X
D,K,X,X,X,X,X
D,K,F,M,G,B,I
D,F,G,M,I,X,X
F,D,K,G,M,I,B
D,K,F,I,M,G,X
D,F,K,M,G,I,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,K,F,M,G,I,X
K,F,I,D,M,G,X
D,F,I,G,M,X,X
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,K,G,F,M,I
D,K,F,G,M,I
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,G,M,I,X
D,K,F,I,M,G,B
D,K,F,I,G,M,B
D,K,F,G,I,M,B
D,F,G,M,I,X,X
D,K,F,I,M,G,X
D,K,F,G,M,I,B
D,K,F,M,G,I
D,K,F,G,M,I,B
D,K,F,M,G,B,I
D,K,F,G,M,I
D,K,F,G,M,I,B
D,F,G,I,M,X,X
D,F,G,M,I,K,B
D,K,M,F,G,I,B
D,F,K,G,M,I,B
D,F,M,G,I,K,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,I,B,M,G
D,K,F,B,M,G,I
K,F,D,M,G,I,X
D,F,K,I,M,G,B
D,F,G,K,M,X,X
D,F,G,I,M,X,X
D,F,K,M,G,I,X
D,K,F,G,M,I,B
D,K,F,G,M,I,X
D,K,F,G,M,I,B
D,K,F,M,I,G,B
D,I,F,G,M,K,X
D,F,G,M,I,K,B
D,F,G,I,M,K,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,F,M,G,I,K,X
D,K,G,F,M,I,B
D,F,K,M,G,B,X
D,K,F,G,I,M,B
D,F,K,B,G,I,M
D,F,K,G,M,I,B
D,G,K,M,F,X,X
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,G,M,I,F,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,B,X
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,F,G,M,I,K,B
D,K,F,G,B,M,I
D,K,F,M,I,G,B
D,F,M,G,I,K,B
D,K,F,G,M,B,I
D,K,F,M,I,G,B
D,F,M,G,I,K,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,F,M,I,G,X,X
D,K,G,F,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,G,I,M,K
D,K,F,G,M,I,B
D,K,F,I,M,G,B
D,F,M,G,I,K,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,X,X,X,X,X,X
D,K,M,G,F,I,B
M,K,D,G,F,X,X
D,K,F,G,M,I,B
D,K,B,F,G,I,M
D,K,F,M,I,G,B
D,K,F,G,B,M,I
D,G,M,I,K,F,B
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,K,F,G,M,I,B
D,K,X,X,X,X,X
D,K,F,G,I,M,B
D,F,K,G,I,M,X
D,K,F,M,I,G,B
D,K,M,G,F,B,I
D,K,F,G,I,M,B
D,K,F,M,G,I,X
D,K,F,M,I,G,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I
D,F,M,I,G,X,X
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,K,F,G,I,M,B
D,K,F,G,I,M,B
D,K,F,M,G,I,B
D,F,G,M,I,K,B
D,F,K,G,M,I,B
D,K,F,M,I,G,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,M,G,I,B
D,K,F,M,G,I,X
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,X,X,X,X,X,X
D,K,F,G,M,I,B
D,K,F,M,I,G,B
D,F,K,M,I,G,B
D,F,G,M,K,B,X
D,K,F,M,G,I,B
D,F,M,I,G,K
K,F,D,G,M,I,B
D,K,F,G,M,B,I
D,K,F,X,X,X,X
D,K,F,G,M,I,B
D,K,G,F,M,I,X
D,K,F,M,G,I,X
D,F,G,M,I,K
D,K,F,M,G,I,B
D,F,M,G,I,K,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,F,K,M,G,I,B
F,D,K,B,M,I,G
D,K,F,M,G,I,B
D,K,G,F,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,K,F,B,G,M,I
D,F,G,M,I,K,B
D,K,F,M,G,I,B
D,F,M,G,I,K,B
D,K,G,F,M,I,B
D,F,G,M,I,X,X
D,K,F,G,I,M,B
D,K,F,G,M,I,B
D,G,F,M,X,X,X
D,K,F,G,M,I,B
D,F,G,K,M,B,I
D,K,F,G,I,M,B
D,F,K,M,G,B,I
D,K,F,G,M,B,I
D,K,G,M,I,F,B
D,K,F,G,M,I,B
D,F,G,M,I,K,B
D,K,F,M,G,I,B
K,D,F,G,B,M,I
D,K,F,G,M,B,I
D,X,X,X,X,X
D,F,G,M,I,X,X
D,K,M,G,F,I,B
D,K,F,G,I,M,B
D,F,I,G,M,K,B
D,K,F,G,M,X,X
D,K,F,M,G,B,I
D,K,I,F,M,G,X
D,K,F,M,G,I,B
D,F,K,G,M,I,B
D,K,F,G,M,I,B
D,K,F,I,M,G,B
D,F,G,K,B,I,M
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,K,F,G,M,I,X
D,K,F,G,M,I,B
D,F,M,G,I,K,B
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,K,F,M,G,B,I
D,K,F,G,M,I,X
D,K,F,B,M,G,I
D,F,M,I,G,K
D,K,F,G,M,I,B
D,K,F,I,M,G,B
D,F,M,G,I,X,X
D,K,F,G,M,B,I
D,M,F,K,G,I,B
D,F,M,I,K,G,B
D,K,F,G,I,M,B
D,K,F,I,G,M,B
D,F,G,M,I,K,B
D,K,G,F,M,I,B
D,K,F,G,M,I,B
D,F,G,I,M,X,X
K,B,D,F,G,M,I
D,K,F,G,M,I,B
D,K,G,F,M,I,B
D,F,G,M,I,X,X
D,F,G,I,X,X,X
D,K,F,X,X,X,X
D,K,F,B,M,I,G
D,F,G,M,K,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I
D,B,F,I,G,K,M
D,K,F,G,B,M,I
D,K,F,M,G,I,B
D,K,F,G,M,I,X
D,K,F,G,M,I,B

D,K,G,F,M,I,B
D,K,F,G,M,I,B
D,K,F,G,M,I,B
D,F,K,G,I,M,B
F,I,G,M,D,X,X
D,F,K,I,M,G,B
D,K,F,G,M,I,B
K,F,G,M,I,B,D
K,F,D,G,M,I,B
D,F,G,M,I,X,X
D,F,I,M,G,X,X
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,F,M,G,I,X
D,F,G,K,M,I,B
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,F,K,G,M,I,B
D,K,F,G,M,I,B
B,I,M,G,F,X,X
D,K,F,G,I,M,B
D,F,G,M,K,I,X
D,K,F,G,M,I,B
D,K,F,I,G,M,B
D,G,K,F,M,I,B
D,K,F,G,M,I
D,K,F,M,G,I,B
D,K,F,G,I,M,B
D,F,G,M,I,K,B
D,K,F,G,M,B,X
D,K,G,M,B,I,X
D,K,F,G,M,I,B
D,K,F,M,G,I
D,F,K,G,M,I
D,K,F,M,G,I,B
D,K,B,F,M,G,I
D,F,M,K,G,I,B
D,K,F,G,I,M,B
D,K,F,G,I,M,B
D,K,F,G,M,I,B
K,D,F,G,B,M,I
D,K,F,G,M,I,B
D,K,F,M,G,I,B
D,F,I,G,M,X,X
D,K,F,G,M,I,B
D,K,G,F,M,I,B
D,K,F,G,M,B,I
D,K,F,G,M,I,B
D,F,G,M,I,X,X
D,K,F,G,M,I,B
D,K,M,F,G,B,I
D,K,F,G,M,I,B
D,F,K,G,M,I,B
I,M,G,F,K,D,B
D,K,F,M,G,B,I
D,K,F,M,G,I,B
D,K,F,M,G,I,B
D,F,M,G,I,K,X
D,K,F,B,G,I,M
D,K,F,G,M,I,B
D,K,G,M,F,I,B
K,F,D,G,M,B,I
D,K,G,X,X,X,X
D,K,F,G,M,I,B
D,F,M,I,G,X,X
D,G,K,F,M,I,B
D,K,F,G,M,I,B
D,K,F,G,I,M,B
D,K,F,I,M,G,B
D,K,F,I,G,X,X
D,K,F,G,M,I,B
D,K,F,G,M,B,I
D,K,F,G,I,M,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,K,F,G,B,X,X
D,F,G,M,I,X,X
D,F,I,M,G,K,B
D,M,F,I,G,K,B
D,G,K,F,M,I,B
D,K,F,M,G,I,B
D,K,F,G,M,I,B
D,F,K,G,M,I,B
D,K,F,G,M,B,I
D,K,F,I,G,M,B
D,K,F,M,G,I
D,F,G,M,I,X,X
K,B,D,F,I,G,M
K,F,G,M,I,B,D
D,K,M,G,F,I,B
D,K,F,G,I,M,B
D,K,F,M,G,I
D,K,F,G,M,B,I
D,K,F,G,I,M,B
D,K,F,G,M,I,B

In [101]:
medium = 'EM'
upd_vacancy_dict = allocate_candidates(candidate_df, upd_vacancy_dict, medium)

A,X,X,X,X,X
C,E,J,A,O
C,L,H,X,X,X
C,J,E,O,A
C,J,L,A,N,H
C,J,E,O,X
C,J,L,A,H,N
C,J,L,H,N,A
C,J,L,N,H,X
C,J,E,X,X
E,C,J,O,A
C,J,L,H,N,A
C,X,X,X,X,X
C,E,J,O,X
C,J,N,H,L
C,J,L,N,H,A
C,H,X,X,X,X
C,J,E,O,A
C,J,H,N,X,X
C,J,L,H,N,A
C,J,N,H,L,A
C,E,J,O,A
C,J,L,N,H,A
E,O,X,X,X
C,H,L,X,X
C,J,N,A,H,X
C,H,X,X,X,X
C,J,L,N,H,A
C,H,X,X,X,X
C,H,J,L,N,A
J,C,H,N,A,L
C,E,J,O,A
C,E,O,A,J
C,J,L,N,H,A
C,J,N,L,H,A
C,H,L,N,A,X
C,J,H,N,L,X
C,J,H,L,N,A
C,E,J,O,A
C,X,X,X,X
C,J,N,H,L
C,J,E,O,A
C,J,N,H,L,A
C,H,L,X,X,X
C,J,E,O,A
C,J,L,N,H,A
C,J,L,H,N,A
C,H,L,X,X,X
C,J,E,O,A
C,J,X,X,X,X
C,J,N,L,H,A
C,J,H,N,L,A
C,X,X,X,X
C,J,N,H,L,A
C,J,H,L,N,A
C,E,J,O,A
C,J,N,L,H,A
C,J,N,L,H,A
C,L,H,X,X,X
C,J,E,O,A
C,J,N,H,A,X
C,J,E,O,A
C,J,H,N,A,L
C,X,X,X,X
C,J,A,L,N,H
C,E,J,A,O
C,J,E,O,A
C,J,L,N,H,A
C,J,N,H,A,L
C,E,J,O,A
C,J,E,O,A
C,X,X,X,X,X
C,J,E,O,A
C,X,X,X,X
C,H,X,X,X,X
C,J,L,X,X,X
C,J,E,O,A
C,J,H,N,L,A
C,J,O,E,A
C,H,J,N,A,L
C,J,E,O,A
J,C,L,H,N,A
C,J,N,H,A,X,X,X,X,X,X,X,X,X,X
C,L,X,X,X,X
C,J,A,L,N,H
C,E,J,X,X
C,J,L,N,H,A
C,J,E,A,O
C,H,L,X,X,X
C,J,A,N,H,X
C,J,A,N,X,X
C,J,E,O,A
C,J,H,N,L,A
C,J,H,L,N,A
C,J,H,N,L
C,J,H,A,N,L
C,J,N,H,A,L
C,J,E,O,A
C,J,E,O,A
C,J,N,H,L,A
C,J,N,A,H,L
C,E,J,O,A
C,E,X,X,X
C,J,A,N,H,L
C,H,L,X,X,X
C,N,L,A,J,H
C,J,N,H,X
C,J,E,O,A
C,J,L,H,A,N
C,J,N,H,A,X
C,J,H,L,N,A
C,J,E,O,A
C,L,H,J,N,A
C,E,X,X,X
C,J,E,O,A
C,X,X,X,X,X
C,H,J,N,A,X
C,J,E,O,A
C,L,H,X,X,X
C,H,L,X,X,X
C,L,H,J,N,A
C,H,X,X,X,X
C,J,E,O,A
J,C,E,O,A
C,J,L,H,N,A
C,J,N,H,A,L
C,J,N,L,H,A
C,J,N,H,A,L
C,J,H,N,L,A
C,J,H,L,N,A
C,H,X,X,X,X
C,J,A,L,H,N
C,J,E,O,A
C,E,J,O,A
C,X,X,X,X,X
C,L,H,J,A,N
C,J,E,A,O
C,J,L,A,N,H
C,X,X,X,X,X
C,J,E,O,A
C,H,L,X,X,X
C,J,E,O,A
C,L,H,X,X,X
C,J,N,H,L,A
C,E,J,X,X
C,L,H,X,X,X
C,J,E,O,A
C,J,L,H,A,N
C,L,H,X,X
J,C,H,L,N,A
C,J,N,H,L,X
C,L,H,X,X,X
C,J,L,N,H,A
C,J,E,O,A
C,H,L,J,A,N
C,J,E,O,A
C,L,H,X,X,X
C,J,E,O,X
C,J,E,O,A
C,E,J,O,A
C,J,E,O,A
C,J,A,N,H,X
H,C,X,X,X,X
E,C,J,O,X
C,J,E,O,A
C,X,X,X,X,X
C,H,L,J,N
C,J,L,N,H,A
C,J,E,O,A
C,E,J,O,A
J,A,L,C,N,H
J,C,H,N,L
C,J,L,N,H,A
C,J,E,X,X
C,J,E,X,X
C,J,E,O,A
C,H,L,X,X,X
C,H,J,N,A,X
C,X,X,X,X
C,J,E,O,A
C,H,J,N,L,A
C,H,L,J,X,X
C,J,L,H,N,A
C,H,J,N,A,L
C,H,L,X,X,X
C,J,H,L,N,A
C,J,H,N,L,X
C,J,H,N,A,X
C,J,E,O,A
C,J,E,O,A
C,J,H,N,A,L
C,J,N,A,H,X
C,E,J,O,X
C,J,E,O,X
C,J,E,X,X
C,J,E,O,A
C,J,H,L,N,A
C,J,E,O,A
C,H,L,X,X,X
C,J,E,O,A
C,J,E,O,A
C,J,H,N,L,A
C,E,J,O,A
J,C,E,O,A
C,J,E,O,A
C,J,L,N,A,H
C,J,L,H,N
C,H,N,X,X
C,J,E,O,A
C,H,X,X,X,X
C,J,L,N,H,A
C,J,L,H,N,A
C,H,J,N,A,L
C,J,L,N,H,A
C,J,A,L,N,H
C,H,X,X,X,X
C,X,X,X,X,X
J,C,E,O,A
C,J,L,N,H,A
C,E,J,X
J,C,H,N,A,X
C,J,E,O,A
C,L,H,X,X,X
C,J,L,N,H,A
C,J,H,L,N,A

C,J,L,N,A,H
C,J,H,N,A,X
C,J,E,O,A
C,J,E,A,O
C,J,N,L,H,A
C,J,L,N,H,A
C,H,L,N,X,X
C,J,A,L,N,H
E,J,O,A,C
C,H,L,J,X,X
C,J,E,O,A
H,C,N,X,X,X
C,J,E,O,A
C,L,H,J,N,A
C,H,X,X,X,X
C,J,L,N,H,A
C,E,J,O,A
J,L,C,N,H,A
C,L,H,A,N,J
C,H,L,N,X,X
J,E,C,O,A
C,J,L,N,H,A
C,J,L,N,H,A
J,C,E,O,A
C,J,E,O,A
C,J,E,O,A
C,H,J,N,A,L
C,J,L,N,H
J,C,L,N,H,A
C,L,H,X,X,X
C,X,X,X,X,X
C,L,X,X,X
C,L,H,J,N,A
C,J,H,N,L,A
C,E,X,X,X
C,J,L,H,N,A
C,L,H,X,X,X

C,J,H,L,A,N
C,J,N,L,H,A
C,J,E,O,A
C,J,L,H,N
C,J,L,A,N,H
C,J,E,O,A
C,X,X,X,X,X
C,E,X,X,X
C,X,X,X,X,X
C,J,H,L,N,A
C,J,E,X,X
C,X,X,X,X,X
E,J,C,O,A
C,X,X,X,X
C,J,H,N,L,X
C,J,E,O,A
C,L,H,J,N,A
C,J,E,O,A
C,X,X,X,X
J,C,E,A,O
C,H,J,N,A,L
C,J,A,N,H,L
C,L,H,J,X,X
C,L,X,X,X,X
C,J,N,H,A,X
C,J,H,A,N,X
J,C,N,L,H,A
C,L,H,J,N,A
J,C,H,N,A,L
J,C,A,X,X,X
C,J,E,X,X
C,J,E,O,A
J,C,L,N,H,A
C,H,X,X,X,X
C,H,L,X,X,X
C,E,X,X,X
C,H,L,J,N,A
C,H,L,X,X,X
C,H,L,X,X,X
C,H,L,J,X,X
J,C,L,N,A,H
C,E,X,X,X
E,J,C,O,A
C,J,E,O,A
C,E,X,X,X
C,J,L,H,N,A
C,J,E,O,A
C,E,X,X,X
J,C,E,O,A
C,J,N,H,A,L
C,J,N,A,L,H
C,L,X,X,X,X
C,J,E,O,A
C,E,J,O
C,J,L,N,H,A
C,J,E,O,A
C,L,H,J,A,X
C,J,N,H,L,A
C,J,N,H,L,A
C,J,E,O,A

C,J,H,A,N,L
C,J,E,O,A
C,J,N,H,L,X
C,H,X,X,X,X
C,J,E,X,X
C,J,A,N,H,X
C,X,X,X,X,X
C,J,E,O,A
C,J,E,A,O
C,J,L,N,H,A
C,J,H,L,N
C,J,A,L,N,H
C,E,X,X,X
C,J,N,A,H,L
C,J,L,N,A,H
C,H,X,X,X,X
C,J,E,O
C,E,J,O,A
C,J,E,O,A
C,H,L,X,X,X
C,J,L,A,N,H
C,L,H,J,A,N
C,J,O,E,A
C,X,X,X,X,X
C,J,L,H,A,N
C,E,X,X,X
C,J,N,L,H,A
C,J,E,O,A

C,J,A,L,N,H
C,J,N,L,H,A
C,E,J,O,A
C,L,H,X,X,X
C,J,E,O,A
C,J,O,E,A
C,J,N,H,A,L
C,J,L,A,X,X
C,J,H,A,N,L
C,J,H,L,A,N
C,H,L,X,X,X
C,J,E,O,A
J,E,C,O,A
C,J,H,L,N,A
C,J,A,L,N,H
C,J,E,O,A
C,H,J,N,A,L
C,H,X,X,X
C,J,L,N,H,A
C,H,L,J,N,A
C,J,L,N,H,A
C,X,X,X,X,X
C,J,H,L,N,A
C,J,L,N,H,A
C,J,E,O,A
E,C,J,O,A
C,J,L,A,H,N
C,E,J,O,A
J,C,E,O,A
C,J,L,H,N,A

C,J,L,H,N,A
C,L,H,J,N,A
C,H,L,X,X,X
C,J,E,O,A
C,J,E,O,A
C,J,E,A,O
C,H,L,X,X,X
C,H,L,X,X,X
C,L,H,J,A,N
C,J,L,H,N,X
J,C,H,L,N,A
C,J,L,H,A,N
J,C,E,O,A
C,E,A,J,O
C,J,L,N,H,A
C,J,E,O,A
J,C,E,O,A
C,J,L,H,N,X
A,X,X,X,X,X
J,C,N,L,H,A
C,L,H,J,N
C,E,X,X,X
J,E,C,O,A
C,J,L,N,H
C,J,N,L,H,A
C,J,A,L,H,N
C,J,A,N,L,H
C,L,H,X,X,X
C,J,E,O,A
C,J,L,N,H,A
C,H,L,X,X,X
C,H,J,N,L,A
C,J,H,L,N,A
C,H,X,X,X
C,J,L,H,N,A
C,J,H,L,N
C,L,H,X,X,X
C,J,N,H,A,L
C,J,A,L,H,N
C,L,H,J,A,N
C,H,L,N,J,A
C,J,N,L,A,H
C,J,H,A,N,X
C,J,N,H,L
C,J,L,A,H,N
C,L,H,J,A,N
C,J,H,N,A,L
J,C,L,A,N,H
C,H,L,X,X,X
C,E,J,O,A
C,J,E,O,A
C,J,L,H,N
C,J,N,H,L
J,C,N,A,H,X
C,J,E,A,O
C,J,A,E,O
C,J,A,N,H,X
C,L,H,N,X,X
C,H,J,N,A,X
C,J,N,A,X,X
C,L,H,J,N,A
C,J,N,L,H,A
C,X,X,X,X,X
C,J,X,X,X
C,X,X,X,X
C,J,L,N,H,A
C,E,X,X,X
C,E,X,X,X
C,H,L,N,X,X
C,J,L,H,N,A
J,C,E,O,A
C,H,L,X,X,X
C,J,H,N,L,A
C,J,H,N,L,A
C,J,E,O,A
C,J,E,O,A
C,J,E,O,A
C,J,X,X,X,X
C,H,L,J,N
C,L,H,X,X,X
C,E,X,X,X
C,J,L,N,H,A
C,H,L,N,X
C,H,L,J,X,X
C,A,H,N,X,X
J,C,H,L,N,A
C,J,H,L,N,A
C,J,E,O,A
C,J,L,N,H,X
C,J,N,L,H,A
C,J,A,N,L,H
C,J,N,A,H,L
C,J,N,A,L,H
C,H,L,X,X,X
C,H,L,X,X
C,H,J,L,N,A
C,J,L,H,N,A
C,E,X,X,X
C,H,L,X,X,X
C,J,E,O,A
C,J,L,H,N
C,E,J,A,O
C,E,X,X,X
E,O,J,A,C
C,E,X,X,X
C,J,L,A,N,H
C,J,E,O,A
C,J,E,O,A
C,J,L,H,N,A
C,J,L,A,H,N
C,L,H,X,X,X
C,L,J,A,N,H
J,C,E,O,X
C,J,A,L,N,H
C,J,A,H,N,L
C,J,E,O,A
C,H,L,N,J
C,J,E,O,A
C,J,L,A,N,H
C,J,L,H,N
C,L,J,N,A,H
C,J,H,N,A,L
C,E,J,O,A
C,J,E,O,A
C,J,E,A,O
C,J,E,O,A
C,J,A,L,N,H
C,E,J,X,X
C,J,E,O,A
C,J,L,N,H
C,J,N,L,H,A
C,J,L,N,H,A
C,J,N,H,A,L
C,J,X,X,X,X
C,H,N,L,J,A
H,L,C,X,X,X
J,C,E,O,A
C,J,L,N,X,X
C,J,E,O,A
C,J,E,O,A
C,J,X,X,X
C,J,H,L,N,A
C,H,L,X,X,X
C,J,H,L,N,A
C,L,J,H,A,N
C,J,L,N,A,H
J,C,H,N,L,A
C,J,H,L,N,A

E,C,J,O,A
C,J,N,H,A,L
C,J,E,O,A
C,J,E,A,O
C,J,E,O,A
C,H,J,L,N,A
C,X,X,X,X,X
J,E,C,O,A
C,L,H,X,X,X
C,J,H,A,N,X
C,J,L,N,H,A
C,J,E,O,A
J,E,C,O,A
C,H,L,X,X,X
C,J,E,O,A
C,J,L,A,N,H
C,J,L,N,H,A
C,H,J,N,X,X
C,L,H,N,J,X
C,L,H,J,N,A
C,J,L,N,H,A
C,J,L,N,H,A
C,H,X,X,X,X
C,L,H,X,X
C,J,E,A,O
C,L,H,N,J,A
C,J,L,H,A,N
C,J,N,A,L,H
C,J,L,H,A,N
C,E,J,A,O
C,E,O,J,A
C,E,X,X,X
C,J,L,A,N,H
C,J,H,L,N,A
C,J,H,L,A,N
C,J,L,N,H,A
C,H,L,N,J,A
E,C,J,O,A
C,J,E,O,A
C,J,E,O,A
C,E,J,O,A
C,J,L,N,A,H
C,J,L,H,A,N
C,J,E,O,A
C,J,E,A,O
C,J,L,N,H,A
C,J,H,N,L,A
C,E,J,O,A
C,J,E,O,A
J,C,E,O
C,H,L,N,X,X
C,L,H,X,X,X
C,H,L,X,X
J,E,C,O,A
J,C,E,O,A
J,N,C,H,L,A
C,J,L,N,H

C,J,E,O,A
C,J,E,O,A
C,J,L,N,H,A
C,J,L,H,A,N
C,J,O,E,A
C,J,L,N,H,A
C,L,J,H,N,A
C,J,A,H,L,N
C,H,J,A,L,N
C,J,E,O,A
C,J,L,A,H,N
C,J,L,N,A,H
C,J,L,A,N,H
C,J,L,H,A,N
C,J,X,X,X,X
C,J,N,H,A,L
C,J,N,A,H,L
C,J,N,H,X,X
C,X,X,X,X
C,E,J,O,A
C,J,A,N,H,L
C,J,N,H,A,L
C,J,E,O,A
E,J,O,A,C
C,J,H,L,N
J,C,L,N,H,A
C,J,H,N,A,X
C,H,L,N,X,X
C,J,E,O,A
C,J,E,A,O
C,J,E,A,O
C,J,E,O,A
C,J,N,H,L,X
C,L,J,A,H,N
C,J,L,A,N,H
C,J,E,O,A
C,L,H,X,X,X
J,E,O,A,X
C,J,E,O,A
L,H,C,J,N,A
C,J,L,N,X,X
C,J,N,H,A,X
C,J,E,O,A
C,J,E,A,O
C,E,O,A,J
C,E,J,O,A
C,J,N,A,L,H
C,E,O,X,X
C,H,L,J,N,A
C,J,E,O,A
C,J,N,L,H
C,J,H,N,L,A
C,J,A,N,H,L
C,E,J,O,A
J,E,C,O,A
C,H,L,N,J
C,J,H,L,A,N
C,L,H,J,N,A
C,J,L,H,A,N
C,H,L,X,X,X

C,N,J,A,H,L
C,J,E,O,A
J,C,E,O,A
J,E,A,O,C
C,N,L,H,J,A
C,J,E,O,A
C,J,L,N,H,A
J,E,O,C,A
E,C,J,O
C,X,X,X,X,X
E,C,J,O,A
C,E,J,O,A
C,J,E,O,A
C,L,H,J,A,N
C,L,N,J,H,A
C,J,H,N,A,L
C,H,L,X,X,X
C,J,L,H,N,A
C,J,E,O,A
C,H,L,X,X,X
C,H,L,J,N,A
C,H,L,X,X,X
C,E,X,X,X
J,C,E,O,A
J,C,E,A,O
C,J,L,N,X,X
C,J,E,O,A
C,H,L,X,X,X
C,J,H,L,N,X
C,J,L,N,H,A
C,H,J,L,A,N
C,J,L,N,H,A
J,C,N,A,H,L
C,H,L,X,X,X
C,E,J,O,A
J,C,A,E,O
J,C,N,L,H,X
C,L,H,X,X,X
C,E,J,A,O
C,H,J,L,A,N
C,J,A,L,N,H
C,E,J,A,O
C,L,H,X,X,X
C,J,A,N,L,H

C,E,J,A,O
C,J,N,L,H,A
C,J,L,A,N,H
C,J,L,N,H,A
C,J,H,N,A,L
C,X,X,X,X,X
C,J,H,N,X
C,J,L,N,H
C,J,N,H,A,L
J,C,E,O,A
C,J,L,H,N,A
C,J,H,L,A,N
C,L,J,N,H,A
C,J,E,O,X
C,E,J,O,A
C,J,X,X,X,X
C,H,L,X,X
C,E,J,O,A
C,E,X,X,X
C,E,O,A,J
C,J,O,E,A
C,J,X,X,X
C,J,L,H,N
C,J,L,N,H,X
C,J,E,O,A
C,J,E,O,A
C,J,E,O,A
C,J,L,N,A,H
J,A,C,H,L,N
C,J,E,O,A
C,J,N,L,A,H
C,J,H,L,N,A
C,J,H,N,L,A
C,H,L,J,N,A
C,L,H,X,X,X
C,H,J,L,N,A
C,J,E,O,X
J,C,E,A,O
C,X,X,X,X
C,J,X,X,X
C,J,E,O,A
C,J,H,L,N,A
C,L,H,X,X,X
C,J,E,A,O
C,E,J,O,X
C,J,E,O,A
C,E,J,O,A
C,J,L,N,H,A
J,C,N,L,A,H
C,E,O,X,X
O,E,J,C,A
C,J,A,N,H,X
C,J,L,H,N,A
C,J,E,O,A
J,C,H,L,N
C,H,X,X,X,X
C,E,J,O,A
C,J,O,E,A
C,J,L,H,N,A
C,J,A,N,L,H
C,J,L,N,H,A
C,E,J,O,A
C,J,E,O
C,E,J,A,O
C,J,N,H,L,A
C,J,A,N,H,L
C,E,X,X,X
C,H,L,X,X,X
C,N,L,H,J,A
C,J,N,L,H,X
C,L,H,X,X,X
C,J,L,A,H,N
C,J,H,A,L,N
C,J,L,H,N,A
C,H,J,L,N
C,J,E,O,A
C,J,E,A,O
E,O,J,C,A
C,J,E,O,A
C,J,L,N,A,H
C,J,N,H,A,L
J,A,N,X,X,X
C,L,H,J,N,A
C,J,E,O,A
C,H,L,X,X,X
C,E,J,O,A
C,H,X,X,X,X
C,E,J,O,A
C,E,J,O,A
C,H,J,L,N,A
C,J,H,N,X
C,H,L,X,X,X
C,J,N,H,A,L
C,L,H,X,X,X
C,L,H,J,A,N
C,J,E,O,A
C,H,L,N,J,A
C,E,X,X,X
C,J,E,O,A
J,E,O,C,X
C,J,E,O,X
C,J,N,L,H,A
C,J,L,N,H,A
C,J,L,N,H,A
C,J,N,A,H,L
C,J,H,L,N,A
C,H,L,N,A,J
C,J,H,N,A,L
C,J,N,L,H,A
C,E,J,O,A
C,E,J,O,A
C,J,L,A,N,H
C,J,L,N,A,H
C,J,L,N,H,A
C,J,E,A,O
C,J,E,O,A
C,J,E,O,A
C,L,J,A,N,H
C,E,J,O,A
J,C,L,H,N,A
C,J,N,H,L,A
C,J,E,O,A
C,J,E,O,A
C,J,E,O,A

C,J,N,L,H,X
C,E,J,O,A
J,C,L,N,H,A
C,H,L,J,A,N
C,E,J,O,A
C,J,L,H,N,A
C,J,H,A,N,L
C,L,H,J,N
C,E,J,O,A
C,J,E,A,O
C,J,L,N,A,H
C,L,H,X,X,X
C,J,L,N,H,A
H,C,L,J,N,A
C,X,X,X,X,X
J,C,E,O,A
E,J,C,O,A
C,L,H,X,X,X
J,C,E,O,A
C,J,E,O,A
C,J,X,X,X,X
C,J,X,X,X,X
C,E,J,A,O
C,J,E,O,A
J,C,L,A,N,H
C,J,E,O,A
J,C,E,O,A
C,J,E,O,A
C,J,E,O,A
C,J,N,L,H,A

J,C,N,L,H,A
C,J,O,E,A
A,H,L,N,X,X
C,H,L,J,A,N
J,C,N,L,H,A
C,J,A,L,N,H
C,J,L,N,H,A
C,J,E,O,A
J,C,L,N,H,A
C,J,E,O,A
C,J,E,O,A
J,C,N,L,H,A
C,L,J,H,N,A
C,J,L,H,N
J,C,L,N,H,A

J,C,N,L,H,A
C,L,H,J,N,A
C,J,L,H,N,A
C,E,J,X,X
C,J,O,E,A
C,J,E,O,X
C,J,L,N,H,A
C,H,L,X,X,X
C,E,X,X,X
C,J,H,N,A,L
C,E,J,O,A
C,J,E,O,A
C,L,H,N,J,A
C,H,L,N,J,A

C,H,L,N,X,X
C,L,J,A,N,H
C,E,X,X,X
C,J,H,L,N,A
C,J,L,H,N,A
C,J,E,O,A
C,J,L,H,N,A
C,E,J,O,A
C,J,E,O,A
C,H,L,X,X,X
C,J,L,A,N,H
C,J,E,A,O
C,J,N,L,H,A
C,J,H,L,N,A
C,J,E,A,O
C,J,L,H,N,A
C,H,X,X,X,X
C,X,X,X,X
C,J,L,N,H,A
C,X,X,X,X,X
C,J,N,L,H,A
C,J,H,N,A,L
C,E,J,A,O
C,J,E,O,A
J,C,E,O,A
C,J,E,O,A
C,J,N,H,L,A
C,E,X,X,X
C,J,H,L,N,A
C,J,L,N,H
C,J,E,O,A
C,E,J,O,A
C,J,H,L,N,A
C,X,X,X,X,X
A,C,H,J,L,N
C,J,N,L,H

J,C,E,O,A
J,E,C,O,A
C,J,L,A,N,H
J,E,O,C,A
C,J,E,O,A
C,J,E,A,O
C,L,H,N,J,A
C,L,H,X,X,X
C,J,E,O,A
C,E,J,O,A
C,J,E,O,A

C,J,E,O,A
C,J,E,O,A
C,J,N,L,H,A
C,L,H,X,X,X
C,J,H,A,L,N
C,J,L,N,H
C,J,E,O,A
C,J,E,X,X
C,E,J,O,A
C,X,X,X,X,X
C,J,A,L,N,H
C,J,N,H,A,L
C,E,A,J,O
C,J,E,O,A
C,J,L,H,N,A
C,L,N,J,H,A
C,H,L,N,J,A
C,J,H,A,L,N
J,E,C,O
C,J,E,O,A
J,E,C,O,A
C,J,E,O,A
C,E,X,X,X
C,E,X,X,X
C,X,X,X,X,X
C,J,L,A,N,H
C,E,J,O,A
C,L,J,H,A,N
C,J,L,A,H,N
C,J,N,A,H,X
C,X,X,X,X,X
C,J,L,N,H
J,C,E,O,X
E,C,J,O,A
C,E,J,O,A
J,C,H,A,L,N
C,J,H,A,N,L
C,J,L,H,A,N
C,L,H,N,J,A
C,H,L,X,X,X
C,J,L,H,N,A
C,J,H,A,N,X
C,J,O,E,A
J,C,E,O,A
C,E,J,X,X
C,J,N,L,H,A

C,N,H,X,X,X
J,A,E,C,O
C,H,L,X,X
C,J,E,O,A
C,E,J,O,A
C,L,H,J,N,A
C,J,L,N,H,A
C,H,X,X,X,X
C,J,N,H,L
C,H,L,X,X,X
C,J,A,L,N,H
C,H,L,J,N
C,L,J,N,H,A
C,J,H,N,A,L
E,C,X,X
C,J,E,O,A
C,J,E,O,A
C,E,O,J,A
C,J,E,A,O
C,J,N,L,H,A
C,J,N,L,A,H
C,J,L,N,A,H
C,X,X,X,X,X
J,L,N,A,H,C
C,J,H,N,L
C,J,L,A,N,H
C,L,H,J,A,N
C,H,J,A,N,X
C,J,L,N,H,A
C,H,L,X,X,X
C,E,O,J,A
C,J,E,O,A
C,J,L,H,N,A
C,J,L,N,H,A
C,E,J,O,A
C,H,L,X,X,X
C,J,E,O,A
C,J,E,O,A
C,J,L,N,H,A
C,J,N,L,H,A
C,X,X,X,X,X
C,J,L,A,N,H
E,C,O,J,A
C,J,E,O,A
C,E,J,O,A
C,J,L,A,N,H
C,L,H,J,N,A
C,L,H,X,X,X
C,J,E,O,A
C,J,N,L,H,A
C,E,J,O,A
C,J,L,A,N,H

C,J,E,O,X
C,E,J,O,A
C,L,H,X,X
C,A,J,N,H,L
C,J,E,O,A
C,J,E,O,A
C,J,L,H,N,A
C,J,X,X,X,X
C,J,E,O,A
C,J,E,O,X
C,E,J,A,X
C,J,L,A,N,H
C,J,H,A,N,L
C,H,X,X,X,X
J,C,L,H,N,A

C,X,X,X,X
C,H,L,X,X
H,C,L,N,A,J
C,L,H,X,X,X
C,H,X,X,X,X
C,H,X,X,X,X
C,X,X,X,X
C,J,E,O,A
C,E,J,O,A
J,C,A,N,H,X
C,L,H,X,X,X
C,J,E,O,A
C,J,N,L,H,A
C,E,J,O,A
C,J,E,O,A
J,E,A,O,C
J,C,L,A,N,H
C,J,E,O,A
C,E,J,O,A
C,H,L,X,X,X
C,L,H,X,X
C,J,H,A,N,X
C,J,H,N,L,A
C,L,H,X,X,X
C,L,H,X,X,X
C,H,L,X,X,X
C,J,E,A,X
C,J,A,H,N,L
E,C,O,J,A
C,J,E,O,A
C,J,N,L,A,H
C,J,E,O,A
J,C,X,X,X
C,J,L,N,H,A
C,X,X,X,X
C,J,L,N,H,A
C,E,J,O,A
J,C,E,O,A
C,H,X,X,X,X
C,H,L,N,A,X

C,J,H,L,A,N
C,L,N,H,X,X
C,H,L,X,X,X
C,J,H,N,L,A
C,L,H,X,X,X
C,E,X,X,X
C,L,H,X,X,X
H,J,C,N,A,L
J,C,O,E,A
C,J,L,N,A,H
C,N,H,J,L,A
C,J,A,H,L,N
C,J,N,H,A,X
C,J,N,H,A,L
J,C,E,O,A
J,C,E,A,O
E,J,O,A,C
J,C,E,O,A
C,J,E,O,A
C,E,J,A,O
J,A,H,L,C,N
C,L,H,J,N,X
C,J,L,N,H,A
C,J,O,E,A
C,E,X,X,X
C,E,J,O,A
C,J,L,N,H,A
C,J,L,H,N,A
C,E,J,O,A

C,E,J,O,A
C,J,L,N,H,A
C,J,L,H,N,A
J,C,L,H,N
C,J,E,A,O
C,E,J,O,A
C,J,E,O,A
C,J,L,N,H
E,C,X,X,X
C,J,L,N,H,A
C,L,H,N,A,J
C,J,N,L,H,X
C,J,N,L,H,A
C,J,E,O,A
C,J,E,O,A
E,J,O,A,X
C,E,J,A,O
J,E,C,X,X
J,C,A,H,N,L
C,J,E,O,A
C,J,L,H,N,A
C,J,L,N,H,A
C,J,N,L,H,A
C,H,L,A,J,N
C,J,E,O,A
C,E,J,A,O
C,J,L,N,H,A
J,C,E,O,A
C,J,L,N,H,A
C,X,X,X,X,X
C,L,H,J,N,A
C,J,L,N,A,H
C,E,J,O,A
C,J,E,O,A
C,J,N,L,H,A
C,H,L,J,X,X

C,J,L,A,N,H
J,C,L,A,N,H
C,E,X,X,X
C,J,E,X,X
C,J,E,O,A
C,J,E,A,O
J,E,A,O,C
C,E,J,A,O
C,J,E,A,O
J,C,H,N,A,X
C,E,X,X,X
C,H,L,X,X,X
C,L,H,X,X,X
C,J,A,N,H,L
J,A,C,L,N,H
C,J,L,A,N,H
C,L,H,X,X,X
C,J,N,L,H,A
C,E,X,X,X
C,J,E,O,A
C,L,J,N,H,A
C,L,H,J,N,A
C,L,H,N,J,A
C,J,E,O,A
E,J,C,O,A
C,L,H,J,N,A
C,J,L,N,H,A
C,J,A,N,L,H
C,J,L,H,N,X
C,J,E,O,A
C,E,J,O,A
C,E,J,O,A
C,E,J,O,A
C,J,A,L,N,H
C,J,L,N,A,H
C,E,J,O,A
E,J,C,O,A
C,J,E,O,A
C,E,J,O,A
C,J,A,H,L,N
C,J,N,A,H,L
C,J,N,L,H,A
C,J,N,L,A,H
C,E,J,O,A
C,E,O,X,X
C,J,E,O,A
C,J,L,H,N,X
C,J,N,H,A,L
C,E,X,X

C,J,L,H,N
C,J,L,N,H,A
C,E,J,O,A
C,J,E,O,A
C,J,L,H,N
C,J,A,H,N,L

C,L,X,X,X,X
C,E,J,O,A
C,E,X,X,X
E,C,J,O,A

C,E,J,O,A
C,H,L,X,X
J,C,L,A,N,H
C,H,A,J,N,L
C,J,N,H,L,X
J,E,O,C
C,L,H,J,A,N
C,J,H,L,N,A
C,J,A,H,L,N
H,C,L,X,X,X
L,C,J,N,H,A
C,X,X,X,X,X
C,L,N,H,X
C,J,L,N,A,H
C,L,H,X,X,X
C,J,E,O,A
C,E,J,A,O
C,J,E,O,A

C,J,E,O,A
C,H,N,L,X

C,J,A,N,L,H
C,J,E,O,A
C,L,H,N,J,A
J,C,L,N,H,A
C,H,A,J,L,N
C,H,L,X,X,X

C,L,H,J,N
C,J,E,A,O
A,J,O,C,E
C,L,H,X,X,X
C,J,N,H,A,L
J,C,E,O,A
C,J,N,L,A,H
C,J,E,O,A
C,J,L,N,H,A
C,L,N,J,H,A
C,J,E,O,A
C,J,N,L,H,A
J,N,C,L,H,A
C,E,O,X
C,E,J,A,O
H,C,X,X,X,X
E,C,O,J,A
C,J,H,L,N,A
C,J,E,O,A
C,J,E,A,O
C,J,L,H,A,N
E,J,O,A,C
C,J,E,O,A
C,J,N,L,H
A,H,J,L,N,C
C,E,X,X,X
C,L,H,A,N,J
C,L,H,X,X,X
J,C,N,L,A,H

C,J,E,O,A
C,J,O,E,A
C,J,E,O,A
C,J,N,A,H,L
C,J,L,H,N,A
C,L,X,X,X,X
C,H,L,X,X,X
C,J,E,A,O
C,J,E,A,O
C,J,E,O,A
J,N,C,L,H,A
C,J,N,L,H,A

C,H,L,X,X
C,E,J,O,A
C,H,L,J,N,A
C,H,L,X,X,X
C,L,N,J,H
C,L,H,J,N,A
C,H,L,X,X,X
C,J,N,H,L,A
J,E,C,O,X
C,J,E,A,O
C,J,L,A,N,H

C,J,A,N,H,X
C,L,H,X,X,X
J,C,E,O,A
C,H,L,X,X,X
C,J,L,A,H,N
C,E,J,O,A
C,N,J,L,H
C,J,L,H,N,A
C,J,L,A,H,N
J,E,O,A,X
J,C,A,N,L,H
C,L,N,J,H,A
C,J,N,H,L
C,J,A,N,H,L
C,J,L,A,N,H
C,J,E,O,A
C,E,O,J,A
C,H,L,X,X,X
C,E,X,X,X
E,O,J,A,C
C,J,N,A,L,H
C,E,J,A,X
J,C,E,O,A
J,C,E,O,A
C,E,J,O,A
C,L,H,X,X,X
C,J,N,H,A,L
C,J,A,L,N,H
C,E,O,X,X
J,E,A,C,O

C,L,N,J,A,H
C,E,O,J,A
C,H,L,N,X,X
C,J,E,O,A
C,E,J,O,A
C,J,L,H,N,A
C,J,N,L,H,A
C,H,L,X,X,X
J,E,O,A,C
C,J,A,H,N,X
C,J,N,L,H,A
C,H,N,L,J,A
C,E,J,O,A
C,E,J,X,X
N,C,J,L,H,X
C,L,H,J,N,A
C,H,X,X,X,X
C,J,H,L,N
J,C,A,L,H,N
C,J,L,A,N,H
C,L,N,H,J,A
C,H,L,X,X,X
C,J,A,L,N,H
C,J,E,O,A
C,N,L,H,J,A
C,J,A,N,H,L
E,A,J,O,C
J,C,E,O,A
C,L,H,J,A,N
C,J,E,O,A
C,J,L,H,A,N

C,L,N,H,J,A
C,J,N,H,X
C,E,J,O,A
C,J,E,O,A
C,J,L,H,A,N
C,L,N,A,H,J
C,J,E,O,A
C,J,L,N,H,A
C,J,N,L,H,A
C,J,L,A,N,H
C,J,L,H,N,A
C,J,N,L,H,A
C,L,H,J,N,A
C,J,N,H,L,A
J,E,C,O,A
C,E,J,O,A
C,E,J,A,O
J,C,E,O,X
J,A,C,H,L,N
C,J,E,O,A
C,J,L,H,N
J,A,C,L,N,H

C,X,X,X,X,X
C,E,X,X,X
C,J,N,H,L
C,L,H,J,N,A
C,L,N,H,J,A
C,J,E,O,A
J,C,O,E,A
C,J,L,N,H,A
C,H,J,N,A,L
C,J,L,N,H,A
J,A,H,N,C,L
C,L,J,H,N,A
C,L,H,X,X
C,J,H,N,A,X
C,L,H,N,J,A
C,X,X,X,X,X
C,J,N,H,L,A
C,J,E,O,A
J,E,C,A,O
J,C,N,L,H,A
C,J,A,L,H,N
C,L,H,J,A,N
C,J,E,O,A
C,J,E,O,A
C,E,J,A,O
C,J,N,H,A,L

C,E,O,J,A
C,J,E,A,O

C,J,E,A,O
C,J,E,O,X

C,H,L,X,X,X
C,J,N,L,H
C,L,J,H,X,X
C,X,X,X,X,X
E,C,O,J,X
C,J,L,N,X,X
C,J,E,O,A
C,E,J,O
J,C,A,H,L,N
C,E,X,X,X
C,X,X,X,X
C,J,L,N,H,A
C,E,J,O,A
C,J,E,O,A
C,J,N,L,H,A
C,J,H,A,N,L
C,J,L,H,N,X
C,L,H,J,A,N
C,L,H,X,X,X
C,J,L,N,H,A
C,J,A,N,H,L
C,L,H,J,N,A

C,J,L,N,H,X
C,E,J,A,O
C,E,O,J,A
C,J,N,H,A,L
C,L,H,X,X,X
C,J,L,A,H,N
C,L,N,H,J,A
C,J,L,H,N,A
C,J,A,L,H,N
C,X,X,X,X,X
C,L,N,H,J,A
C,J,L,N,A,H
C,H,X,X,X,X
C,E,J,O,A
C,E,J,A,O
C,J,H,N,A,L
C,J,E,O,A
C,H,N,L,X,X
C,L,N,H,J,A
C,J,H,A,N,L
C,J,E,O,A
C,X,X,X,X,X
C,H,L,X,X,X
C,H,L,X,X
C,J,N,L,H,A
C,E,X,X,X
J,E,C,O,A
C,J,L,N,H,A
C,L,H,X,X,X
C,J,E,O,A
C,J,A,L,N,H
C,L,H,X,X,X
C,E,O,X,X
C,J,A,H,N,L
C,J,E,O,A
C,J,E,O,A
C,J,E,O,A
J,C,E,O,A
C,J,H,L,N,A
C,H,J,L,A,N
C,E,J,O,A
C,H,L,A,N,J
C,J,A,L,H,N
C,J,N,L,H
C,J,L,A,N,H
J,C,L,N,H,A
C,H,L,A,N,J
J,C,E,O,A
C,E,O,J,A
N,C,J,L,H,A
C,J,L,N,H
C,J,A,N,X,X
C,J,L,N,H,A
C,L,J,A,N,H
C,J,H,L,N,X
C,J,L,N,H
C,L,H,X,X,X
L,N,C,A,J,H
C,E,J,O,A
C,E,O,J,A
C,J,E,O,A
C,J,E,A,O
C,J,L,N,H
J,C,E,O,A
C,J,L,H,N,A
C,J,L,N,H,X
C,J,E,O,A
C,E,J,O,A

C,H,L,X,X,X
C,H,J,N,L
C,J,A,E,O
C,J,E,O,A
C,J,E,O,A

C,J,L,H,N,A
C,J,A,L,N,H
C,J,E,O,A
C,E,O,X,X
C,X,X,X,X
J,A,N,C,H,L
C,J,L,A,H,N
C,J,H,L,N,A
C,J,E,O,A
C,J,L,N,H,A
J,N,L,C,H,A


J,E,O,A,X
C,E,J,O,A
J,N,A,X,X,X
C,H,L,N,J,A
C,E,X,X,X
C,J,A,L,N,H
J,C,N,L,H,A
C,E,O,J,A
C,J,E,O,A
C,J,H,N,L
C,L,H,N,J,A
C,L,H,X,X,X
C,L,J,N,A,H
C,N,H,L,J
C,L,H,N,J,A
C,E,O,X,X
J,C,L,N,H
C,J,N,L,H,A
C,J,N,L,H,A
C,J,H,N,L,A
C,J,L,N,H,A
C,J,N,L,H,A
J,C,E,O,A
C,L,N,A,H,J
C,E,J,A,O
J,E,O,A,C
C,J,E,O,A
C,J,H,N,L,A
C,J,E,O,A
C,E,J,O,A
C,X,X,X,X,X
C,J,L,N,H,A
C,H,L,X,X,X
C,L,X,X,X,X
C,E,J,O,A
C,J,H,L,N
C,J,E,O,A
C,J,E,A,O
C,E,O,X,X
C,J,N,L,H,A
C,H,L,N,X,X
C,L,H,X,X,X
C,L,H,X,X,X
C,J,N,H,L
C,J,E,O,A

C,J,E,O,A
J,O,C,E,A
C,J,N,H,X
C,H,L,X,X,X
C,H,L,X,X,X
C,J,E,O,A
C,H,L,X,X,X
C,J,E,O,A
C,E,J,O
C,J,A,L,H,N
C,E,J,O,A
C,J,H,A,N,L
C,J,E,A,O
C,J,L,N,H,A
C,L,H,J,N
C,J,E,A,O
C,X,X,X,X
H,C,X,X,X,X
J,O,C,E,A
C,J,N,L,H
C,J,H,L,N,A
C,L,H,N,J,A
C,H,L,N,A,J
C,N,L,J,H,A
J,C,A,N,H,L
C,J,L,N,H,A
C,J,E,O,X
C,J,E,O,A
E,O,J,C,A
J,O,E,C,A
C,J,L,H,A,N
C,E,J,O,A
J,C,A,L,H,N
C,H,L,X,X

C,E,J,O,A
H,C,L,X,X,X

C,J,L,H,N,A
J,A,H,C,L,N
J,A,C,L,H,N
C,E,J,O,A
C,L,H,X,X,X
C,J,L,N,H,A
C,A,H,L,N,J
J,C,E,O,A
C,L,H,X,X,X

C,H,L,J,A,N


C,J,E,O,A
C,L,H,X,X,X
C,H,L,X,X
C,J,L,H,N
C,J,N,H,A,L
C,L,H,N,J,A
C,L,X,X,X
J,A,E,O,C
C,J,N,H,A,X

C,J,A,L,H,N
C,J,E,O,A
C,J,E,O,A
C,J,E,O,A
J,N,A,C,L,H
C,E,J,A,O
C,J,O,A,X
J,C,E,O,A
J,C,E,A,O
C,J,E,O,A
C,J,E,O,A

C,J,A,H,L,N
C,J,E,O,A
C,E,O,X,X
C,J,H,L,N,A
C,J,A,L,H,N
C,E,O,X,X
C,J,E,O,A
C,H,X,X,X
C,J,L,A,N,H


C,J,L,N,H,A
C,J,L,N,A,H
C,L,H,X,X
C,H,L,X,X
C,E,A,J,O
C,E,X,X,X
C,J,H,L,A,N
C,J,H,N,A,L
J,C,O,E,A
C,E,J,A,O
C,H,L,N,J,A
C,E,J,O,A
C,J,L,N,A,H
C,J,L,N,H,A

C,J,E,O
C,H,X,X,X,X
C,L,H,N,J,A
C,J,H,N,L,A
N,L,H,C,A,X
C,E,J,O,A

J,C,X,X,X,X
C,J,L,N,H,A
C,J,E,A,O
C,E,O,J
C,E,O,X,X
C,E,J,O,A
C,H,N,L,A,J
C,J,H,N,A,X
J,C,N,H,L,A
C,J,E,O,A
L,N,H,J,C
C,J,L,N,H
C,H,L,X,X
C,X,X,X,X
C,E,J,O,A
C,J,L,N,H
J,C,A,L,H,N
C,J,E,O,A
J,E,C,O,A
C,J,E,O,A
C,L,H,X,X,X
C,J,L,H,N,A
C,J,L,H,N,A
C,L,H,X,X,X

C,L,H,J,N
C,J,L,A,H,N
L,C,N,H,J
C,L,H,J,N,A
C,L,H,X,X,X

J,C,A,L,N,H
C,J,L,N,A,H
E,C,X,X
C,E,J,O,A
C,J,E,O,A
C,H,L,J,A,N
C,J,L,A,N,H
C,J,L,H,N,A

J,C,L,H,N,A
C,E,J,O,A
C,L,J,H,N
C,J,E,O,A
C,J,E,A,O
C,J,L,N,H,A
C,E,O,J,A
C,E,J,O,A
J,H,C,N,L,A
C,L,H,J,N,A
C,J,L,N,H
C,J,E,X,X
C,E,J,O,A
C,J,L,H,N
C,H,L,N,J,A
C,H,L,J,A,N
C,J,L,N,H,A
C,J,A,L,H,N
O,J,E,C,A
C,X,X,X,X,X
C,L,N,H,J,A
C,L,H,J,A,N
C,E,J,O,X
C,L,H,X,X,X
C,J,E,O,A
C,J,L,A,N,H
C,H,L,N,J,A
E,C,X,X,X
J,A,C,N,H,L
C,E,J,O,A
C,L,H,J,A,N
E,O,J,C,A
C,J,O,E,A
C,L,H,J,N,A
J,E,C,O,A
E,J,A,O,C
C,E,J,O,A
J,A,C,E,O
C,J,E,O,A
L,H,N,C,X,X
C,L,H,X,X,X
C,H,L,N,J
C,J,H,L,N,A
C,J,L,N,H,A
J,C,H,L,N,A
C,A,E,J,O
C,L,J,N,H,A
J,C,E,O,X
C,E,O,J,A
C,O,E,J,A
C,N,L,H,A,J
J,L,C,N,A,H
C,X,X,X,X
C,J,L,A,H,N
C,E,O,J,A
J,A,O,C,E
C,J,E,O,A
C,E,J,O,A
C,L,J,H,N,X
C,J,H,A,L,N
C,J,E,O,A
C,J,L,H,N
C,J,E,O,A
C,E,O,J,A
C,E,J,O,A
L,J,H,C,N,X
C,J,H,L,N
J,E,O,X,X
J,E,O,C,A
C,J,A,L,N,H
C,X,X,X,X
C,J,L,A,H,N
C,J,L,N,H,A
C,J,L,N,H,A
C,H,J,A,N,L
C,J,N,L,H,A
C,H,X,X,X,X
C,J,E,O,A
C,E,J,A,O
C,J,E,O,A
C,J,N,H,L,A
C,J,E,O,A
H,C,L,N,J,A
C,J,E,O,A
C,J,E,O,A
C,J,E,O,A
E,C,J,O,A
C,E,X,X,X
C,E,O,X,X
J,C,L,H,A,N
C,J,N,L,X,X
C,E,J,O,A

C,J,N,L,H,A
C,H,L,N,J,A
C,J,E,O,A
C,J,L,N,H,A
C,E,O,A,J
C,E,J,A,O

C,J,L,N,H,A
C,J,E,O,A
C,E,J,O,A
C,E,J,O,A
C,X,X,X,X
C,E,O,A,J
C,H,L,J,N

C,L,H,N,X,X

C,J,H,L,A,N
C,L,N,A,J,H
C,J,L,N,H,A
E,C,J,O,X
C,E,X,X
C,J,L,H,N
C,L,H,X,X,X
C,J,E,O,A

C,J,N,H,X
C,L,H,J,N
C,E,J,O,A
E,C,O,J,A
C,E,J,A,O
C,E,J,O,A
C,H,L,A,J,N
C,L,A,N,J,H
C,L,N,H,X,X
C,J,H,A,L,N
C,E,O,J,A
C,J,E,A,O
C,J,A,N,H,L
C,J,L,A,N,H
C,J,E,A,O

#### WRITING DATA

In [102]:
candidate_df[candidate_df['allocated_category'].notnull()].to_csv(r"JE_only_allocated_candidates_NEW.csv", index = False)

In [103]:
# candidate_df.to_excel(r"pura_candidates_allocated_candidates.csv", index = False)

In [104]:
candidate_df.to_excel(r"pura_candidates_allocated_candidates_NEW.xlsx", index=False, engine='xlsxwriter')

In [208]:
!pip install xlsxwriter

Defaulting to user installation because normal site-packages is not writeable
Collecting xlsxwriter
  Downloading XlsxWriter-3.2.2-py3-none-any.whl.metadata (2.8 kB)
Downloading XlsxWriter-3.2.2-py3-none-any.whl (165 kB)
   ---------------------------------------- 0.0/165.1 kB ? eta -:--:--
   ------- -------------------------------- 30.7/165.1 kB 1.4 MB/s eta 0:00:01
   ---------------------------------------- 165.1/165.1 kB 2.5 MB/s eta 0:00:00
Installing collected packages: xlsxwriter
Successfully installed xlsxwriter-3.2.2

In [105]:
def find_lowest_marks(candidates_df, vacancy_df):
    vc = []
    vacancy_df['min_total'] = 0
    for _, row in vacancy_df.iterrows():
        lmv = {
            "category_code": str(row["category_code"]),
            "subject_option": str(row["subject_option"]),
            "post_code": str(row["post_code"]),
        }

        vc.append(lmv)

    print("Vector size--->", len(vc))

    for lmv1 in vc:
        highest_merit_candidate = get_highest_merit_candidate(candidates_df, lmv1["category_code"], lmv1["subject_option"], lmv1["post_code"])
        update_vacancy_table(vacancy_df, lmv1["category_code"], lmv1["subject_option"], lmv1["post_code"], highest_merit_candidate)

def get_highest_merit_candidate(candidates_df, category_code, subject_code, post_code):
    highest_merit_candidate = None

    try:
        mask = (
            (candidates_df["allocated_category"] == str(category_code))
            & (candidates_df["allocated_subject"] == str(subject_code))
            & (candidates_df["allocated_post"] == str(post_code))
        )

        filtered_cand = candidates_df[mask]

        # Assuming 'merit_c' or 'merit_em' is the column representing the merit of the candidate
        if str(subject_code) == 'C':
            highest_merit_candidate = filtered_cand.loc[filtered_cand['merit_c'].idxmax()]
        else:
            highest_merit_candidate = filtered_cand.loc[filtered_cand['merit_em'].idxmax()]

    except Exception as ex:
        print(ex)

    return highest_merit_candidate

def update_vacancy_table(vacancy_df, category_code, subject_code, post_code, highest_merit_candidate):
    try:
        key = str(category_code) + str(subject_code) + str(post_code)
        mask = (vacancy_df['key'] == key)
        vacancy = vacancy_df.loc[mask]

        vacancy["min_total"] = highest_merit_candidate['total']
        vacancy["min_paper2"] = highest_merit_candidate['paper2']
        vacancy["min_cand_dob"] = highest_merit_candidate['dob']
        vacancy["min_paper1"] = highest_merit_candidate['paper1']

        # Use .item() to get a scalar value from the Series
        if vacancy['subject_option'].item() == 'C':
            vacancy['max_merit_civil'] = highest_merit_candidate['merit_c']
        else:
            vacancy['max_merit_em'] = highest_merit_candidate['merit_em']

        vacancy_df.loc[mask, 'min_total'] = vacancy["min_total"]
        vacancy_df.loc[mask, 'min_paper2'] = vacancy["min_paper2"]
        vacancy_df.loc[mask, 'min_cand_dob'] = vacancy["min_cand_dob"]
        vacancy_df.loc[mask, 'min_paper1'] = vacancy["min_paper1"]
        vacancy_df.loc[mask, 'max_merit_civil'] = vacancy["max_merit_civil"]
        vacancy_df.loc[mask, 'max_merit_em'] = vacancy["max_merit_em"]

        # Print statements for verification
        
    except Exception as ex:
        print(ex)

In [106]:
updated_vacancy_df = pd.DataFrame.from_dict(upd_vacancy_dict, orient='index')

In [107]:
find_lowest_marks(candidate_df, updated_vacancy_df)

Vector size---> 120
'max_merit_em'
'max_merit_em'
'max_merit_em'
'max_merit_em'
'max_merit_em'
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable

C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_total"] = highest_merit_candidate['total']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper2"] = highest_merit_candidate['paper2']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_cand_dob"] = highest_merit_candidate['dob']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper1"] = highest_merit_candidate['paper1']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy['max_merit_civil'] = highest_merit_candidate['merit_c']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[349.55415]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  vacancy_df.loc[mask, 'min_total'] = vacancy["min_total"]
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_total"] = highest_merit_candidate['total']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper2"] = highest_merit_candidate['paper2']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_cand_dob"] = highest_merit_candidate['dob']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper1"] = highest_merit_candidate['paper1']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy['max_merit_civil'] = highest_merit_candidate['merit_c']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_total"] = highest_merit_candidate['total']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper2"] = highest_merit_candidate['paper2']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_cand_dob"] = highest_merit_candidate['dob']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper1"] = highest_merit_candidate['paper1']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy['max_merit_civil'] = highest_merit_candidate['merit_c']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_total"] = highest_merit_candidate['total']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper2"] = highest_merit_candidate['paper2']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_cand_dob"] = highest_merit_candidate['dob']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper1"] = highest_merit_candidate['paper1']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy['max_merit_civil'] = highest_merit_candidate['merit_c']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_total"] = highest_merit_candidate['total']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper2"] = highest_merit_candidate['paper2']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_cand_dob"] = highest_merit_candidate['dob']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper1"] = highest_merit_candidate['paper1']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy['max_merit_civil'] = highest_merit_candidate['merit_c']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_total"] = highest_merit_candidate['total']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper2"] = highest_merit_candidate['paper2']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_cand_dob"] = highest_merit_candidate['dob']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper1"] = highest_merit_candidate['paper1']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy['max_merit_em'] = highest_merit_candidate['merit_em']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_total"] = highest_merit_candidate['total']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper2"] = highest_merit_candidate['paper2']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_cand_dob"] = highest_merit_candidate['dob']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper1"] = highest_merit_candidate['paper1']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy['max_merit_em'] = highest_merit_candidate['merit_em']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_total"] = highest_merit_candidate['total']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper2"] = highest_merit_candidate['paper2']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_cand_dob"] = highest_merit_candidate['dob']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper1"] = highest_merit_candidate['paper1']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy['max_merit_em'] = highest_merit_candidate['merit_em']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_total"] = highest_merit_candidate['total']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper2"] = highest_merit_candidate['paper2']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_cand_dob"] = highest_merit_candidate['dob']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper1"] = highest_merit_candidate['paper1']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy['max_merit_em'] = highest_merit_candidate['merit_em']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_total"] = highest_merit_candidate['total']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable

C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_total"] = highest_merit_candidate['total']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper2"] = highest_merit_candidate['paper2']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_cand_dob"] = highest_merit_candidate['dob']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper1"] = highest_merit_candidate['paper1']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy['max_merit_em'] = highest_merit_candidate['merit_em']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_total"] = highest_merit_candidate['total']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper2"] = highest_merit_candidate['paper2']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_cand_dob"] = highest_merit_candidate['dob']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper1"] = highest_merit_candidate['paper1']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy['max_merit_em'] = highest_merit_candidate['merit_em']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_total"] = highest_merit_candidate['total']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper2"] = highest_merit_candidate['paper2']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_cand_dob"] = highest_merit_candidate['dob']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper1"] = highest_merit_candidate['paper1']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy['max_merit_civil'] = highest_merit_candidate['merit_c']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_total"] = highest_merit_candidate['total']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper2"] = highest_merit_candidate['paper2']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_cand_dob"] = highest_merit_candidate['dob']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper1"] = highest_merit_candidate['paper1']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy['max_merit_civil'] = highest_merit_candidate['merit_c']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_total"] = highest_merit_candidate['total']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper2"] = highest_merit_candidate['paper2']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_cand_dob"] = highest_merit_candidate['dob']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper1"] = highest_merit_candidate['paper1']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy['max_merit_em'] = highest_merit_candidate['merit_em']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_total"] = highest_merit_candidate['total']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper2"] = highest_merit_candidate['paper2']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_cand_dob"] = highest_merit_candidate['dob']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper1"] = highest_merit_candidate['paper1']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy['max_merit_em'] = highest_merit_candidate['merit_em']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_total"] = highest_merit_candidate['total']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper2"] = highest_merit_candidate['paper2']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_cand_dob"] = highest_merit_candidate['dob']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper1"] = highest_merit_candidate['paper1']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy['max_merit_em'] = highest_merit_candidate['merit_em']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_total"] = highest_merit_candidate['total']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper2"] = highest_merit_candidate['paper2']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_cand_dob"] = highest_merit_candidate['dob']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper1"] = highest_merit_candidate['paper1']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy['max_merit_em'] = highest_merit_candidate['merit_em']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_total"] = highest_merit_candidate['total']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper2"] = highest_merit_candidate['paper2']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_cand_dob"] = highest_merit_candidate['dob']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper1"] = highest_merit_candidate['paper1']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy['max_merit_em'] = highest_merit_candidate['merit_em']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_total"] = highest_merit_candidate['total']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper2"] = highest_merit_candidate['paper2']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:50: SettingWithCopyWarning:

attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable
attempt to get argmax of an empty sequence
'NoneType' object is not subscriptable

C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_total"] = highest_merit_candidate['total']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper2"] = highest_merit_candidate['paper2']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_cand_dob"] = highest_merit_candidate['dob']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper1"] = highest_merit_candidate['paper1']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy['max_merit_em'] = highest_merit_candidate['merit_em']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_total"] = highest_merit_candidate['total']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper2"] = highest_merit_candidate['paper2']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_cand_dob"] = highest_merit_candidate['dob']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper1"] = highest_merit_candidate['paper1']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy['max_merit_em'] = highest_merit_candidate['merit_em']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_total"] = highest_merit_candidate['total']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper2"] = highest_merit_candidate['paper2']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_cand_dob"] = highest_merit_candidate['dob']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper1"] = highest_merit_candidate['paper1']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy['max_merit_em'] = highest_merit_candidate['merit_em']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_total"] = highest_merit_candidate['total']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper2"] = highest_merit_candidate['paper2']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_cand_dob"] = highest_merit_candidate['dob']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper1"] = highest_merit_candidate['paper1']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy['max_merit_em'] = highest_merit_candidate['merit_em']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_total"] = highest_merit_candidate['total']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper2"] = highest_merit_candidate['paper2']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_cand_dob"] = highest_merit_candidate['dob']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper1"] = highest_merit_candidate['paper1']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy['max_merit_em'] = highest_merit_candidate['merit_em']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_total"] = highest_merit_candidate['total']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper2"] = highest_merit_candidate['paper2']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_cand_dob"] = highest_merit_candidate['dob']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper1"] = highest_merit_candidate['paper1']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy['max_merit_em'] = highest_merit_candidate['merit_em']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_total"] = highest_merit_candidate['total']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper2"] = highest_merit_candidate['paper2']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_cand_dob"] = highest_merit_candidate['dob']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper1"] = highest_merit_candidate['paper1']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy['max_merit_em'] = highest_merit_candidate['merit_em']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_total"] = highest_merit_candidate['total']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper2"] = highest_merit_candidate['paper2']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_cand_dob"] = highest_merit_candidate['dob']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper1"] = highest_merit_candidate['paper1']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy['max_merit_civil'] = highest_merit_candidate['merit_c']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_total"] = highest_merit_candidate['total']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper2"] = highest_merit_candidate['paper2']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_cand_dob"] = highest_merit_candidate['dob']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper1"] = highest_merit_candidate['paper1']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy['max_merit_civil'] = highest_merit_candidate['merit_c']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_total"] = highest_merit_candidate['total']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vacancy["min_paper2"] = highest_merit_candidate['paper2']
C:\Users\AshutoshMishra\AppData\Local\Temp\ipykernel_7996\381652182.py:50: SettingWithCopyWarning:

In [108]:
updated_vacancy_df['left_vacancy'] = updated_vacancy_df['current']
updated_vacancy_df['current'] = updated_vacancy_df['left_vacancy'] + updated_vacancy_df['allocated']
updated_vacancy_df = updated_vacancy_df.drop(columns = ['allocated_hc', 'allocated_hc_prev'])

In [109]:
updated_vacancy_df.to_csv(r"Updated_Vacancy_allocated_vacancy_NEW.csv", index = False)