### PREREQUISITES

#### Importing Modules and Tables

In [24]:
import pandas as pd
import re

In [25]:
candidate_df = pd.read_csv(r"C:\Users\SalauddinKhan\Desktop\PYTHON\5359_candidates_sicpo.csv")
vacancy_df = pd.read_csv(r"C:\Users\SalauddinKhan\Desktop\PYTHON\vacancy_sicpo24_revised_v2_new.csv")

In [26]:
candidate_df.columns

Index(['registrationNo', 'rollno', 'name', 'gender', 'dob', 'cat1_cpo',
       'cat1_dp', 'cat2', 'exs_reservation', 'isexs_specialquota',
       'service_period', 'paper1', 'p2_score', 'paper2', 'total',
       'agerelax_code', 'post_preference', 'post_pref', 'post_pref_new',
       'rejection_provision', 'merit1', 'allocated_category', 'allocated_post',
       'allocated_sub_category'],
      dtype='object')

In [27]:
candidate_df.shape

(5359, 24)

#### ARC Table from Notice

In [201]:
arc_dict = [
    {'arc_code': 1, 'arc_year': 5, 'arc_cat1': '1,2', 'arc_cat2': '' , 'arc_gender': '1,2,3' , 'arc_year_against_ur': None},
    {'arc_code': 2, 'arc_year': 3, 'arc_cat1': '6', 'arc_cat2': '', 'arc_gender': '1,2,3' , 'arc_year_against_ur': None},
    {'arc_code': 6, 'arc_year': 3, 'arc_cat1': '0,1,2,6,9', 'arc_cat2': '3', 'arc_gender': '1,2,3' , 'arc_year_against_ur': None},
    {'arc_code': 12, 'arc_year': 10, 'arc_cat1': '0,6,9', 'arc_cat2': '', 'arc_gender': '1' , 'arc_year_against_ur': 10},
    {'arc_code': 13, 'arc_year': 15, 'arc_cat1': '1,2', 'arc_cat2': '', 'arc_gender': '1' , 'arc_year_against_ur': 10},
    {'arc_code': 17, 'arc_year': 5, 'arc_cat1': '0,9', 'arc_cat2': '', 'arc_gender': '1,2,3' , 'arc_year_against_ur': 5},
    {'arc_code': 18, 'arc_year': 8, 'arc_cat1': '6', 'arc_cat2': '', 'arc_gender': '1,2,3' , 'arc_year_against_ur': 5},
    {'arc_code': 19, 'arc_year': 10, 'arc_cat1': '1,2', 'arc_cat2': '', 'arc_gender': '1,2,3' , 'arc_year_against_ur': 5},
]

arc_df = pd.DataFrame(arc_dict)

#### Cutoff Table from Notice

In [202]:
cutoff_data = [
    {'gender': 1, 'category': 1, 'sub_category': None, 'paper1': 106.75022, 'total': 40},
    {'gender': 1, 'category': 2, 'sub_category': None, 'paper1': 98.10614, 'total': 40},
    {'gender': 1, 'category': 6, 'sub_category': None, 'paper1': 128.64348, 'total': 50},
    {'gender': 1, 'category': 0, 'sub_category': None, 'paper1': 127.40295, 'total': 50},
    {'gender': 1, 'category': 9, 'sub_category': None, 'paper1': 135.27003, 'total': 60},
    {'gender': 2, 'category': 1, 'sub_category': None, 'paper1': 89.85810, 'total': 40},
    {'gender': 2, 'category': 2, 'sub_category': None, 'paper1': 82.65680, 'total': 40},
    {'gender': 2, 'category': 3, 'sub_category': None, 'paper1': 40.07024, 'total': 40},
    {'gender': 2, 'category': 6, 'sub_category': None, 'paper1': 113.50911, 'total': 50},
    {'gender': 2, 'category': 0, 'sub_category': None, 'paper1': 111.43520, 'total': 50},
    {'gender': 2, 'category': 9, 'sub_category': None, 'paper1': 119.80335, 'total': 60},
    {'gender': 2, 'category': 0, 'sub_category': '3*', 'paper1': 40.07024, 'total': 40},
    {'gender': 2, 'category': 1, 'sub_category': '3*', 'paper1': 40.07024, 'total': 40},
    {'gender': 2, 'category': 2, 'sub_category': '3*', 'paper1': 40.07024, 'total': 40},
    {'gender': 2, 'category': 6, 'sub_category': '3*', 'paper1': 40.07024, 'total': 40},
    {'gender': 2, 'category': 9, 'sub_category': '3*', 'paper1': 40.07024, 'total': 40},
]

cutoff_df = pd.DataFrame(cutoff_data)

In [28]:
candidate_df['dob'] = pd.to_datetime(candidate_df['dob'])

### MERIT

#### CODE

In [29]:
def get_merit(candidate_df):    
    
    candidate_df['merit'] = None
    
    candidates =  candidate_df[
    (candidate_df['total'].notnull()) &
    (candidate_df['rejection_provision'].astype(str).isin(('Q','W','TU','WWV')))
    ].sort_values(by = ['total', 'paper2', 'dob', 'name'], ascending=[False, False, True, True])
    
    candidates['merit'] = range(1, len(candidates) + 1)

    rollno_to_merit = candidates.set_index('rollno')['merit'].to_dict()
    candidate_df['merit'] = candidate_df['rollno'].map(rollno_to_merit)
    
    return "{flag_name} updated successfully for {merit} candidates".format(
        flag_name='merit',
        merit=len(candidates))

#### EXECUTION

In [30]:
get_merit(candidate_df)

'merit updated successfully for 5359 candidates'

In [206]:
candidate_df[['rollno', 'merit']].head()

       rollno  merit
0  1801001916  14176
1  1004007924  14141
2  2233003514   6375
3  2227000251  13784
4  2222000910  14152

In [207]:
candidate_df.sort_values(by='merit', ascending = False).iloc[0]

registrationNo                     10006656853
rollno                              1408002059
name                                 TILAK RAJ
gender                                       2
dob                        1977-08-24 00:00:00
cat1_cpo                                     9
cat1_dp                                      9
cat2                                       3.0
exs_reservation                            Yes
isexs_specialquota                         NaN
service_period         26 Years 0 Month 4 Days
paper1                                40.31834
p2_score                                  40.0
paper2                                    40.0
total                                 80.31834
agerelax_code                              6.0
post_pref                          A,C,F,B,E,D
rejection_provision                          Q
cat3                                       NaN
merit                                    14242
Name: 4250, dtype: object

### CUTOFF FLAG

#### CODE

In [208]:
def get_cutoff(cutoff_df, candidate_df, post):

    if post == 'CAPF':
        cutoff = 'cutoff_flag_cpo'
        cat1 = 'cat1_cpo'
        df_cutoff = cutoff_df[cutoff_df['sub_category'].isnull()]
        sorted_candidates = candidate_df[candidate_df['merit'].notnull()].sort_values(by='merit')

    elif post == 'DP':
        cutoff = 'cutoff_flag_dp'
        cat1 = 'cat1_dp'
        df_cutoff = cutoff_df[cutoff_df['sub_category'].isnull()]
        sorted_candidates = candidate_df[candidate_df['merit'].notnull()].sort_values(by='merit')

    elif post == 'ESM_SPL':
        cutoff = 'cutoff_flag_spclexs_dp'
        cat1 = 'cat1_dp'
        df_cutoff = cutoff_df[cutoff_df['sub_category'].notnull()]
        sorted_candidates = candidate_df[(candidate_df['merit'].notnull()) & (candidate_df['isexs_specialquota']== 'Yes')].sort_values(by='merit')

    candidate_df[cutoff] = None
    cutoff_dict_m = {}
    cutoff_dict_f = {}

    for index, row in df_cutoff.iterrows():
        category = int(row['category'])
        gender = int(row['gender'])
        paper1 = float(row['paper1'])
        paper2 = float(row['total'])
        if gender  == 1:
            cutoff_dict_f[category] = [paper1, paper2, gender]
        else:
            cutoff_dict_m[category] = [paper1, paper2, gender]
    
    
    def calculate_cutoff(candidate):
        cutoff = ''

        if candidate['gender'] == 1:
            cutoff_dict = cutoff_dict_f
        
        else:
            cutoff_dict = cutoff_dict_m
    
        if (candidate['paper1'] >= cutoff_dict[9][0]) & (candidate['p2_score'] >= cutoff_dict[9][1]) & (candidate['gender'] == cutoff_dict[9][2]):
            cutoff += '9'

        for cat in [0, 1, 2, 6]:
            if (candidate[cat1] == cat) & (cat in cutoff_dict):
                if (candidate['paper1'] >= cutoff_dict[cat][0]) & (candidate['p2_score'] >= cutoff_dict[cat][1]) & (candidate['gender'] == cutoff_dict[cat][2]):
                    cutoff += str(cat)

        if (candidate['cat2'] == 3) & (3 in cutoff_dict):
            if (candidate['paper1'] >= cutoff_dict[3][0]) & (candidate['p2_score'] >= cutoff_dict[3][1]) & (candidate['gender'] == cutoff_dict[3][2]):
                cutoff += '3'

        for cat in [4, 5, 7, 8]:
            if (candidate['cat3'] == cat) & (cat in cutoff_dict):
                if (candidate['paper1'] >= cutoff_dict[cat][0]) & (candidate['p2_score'] >= cutoff_dict[cat][1]) & (candidate['gender'] == cutoff_dict[cat][2]):
                    cutoff += str(cat)

        return cutoff

    sorted_candidates[cutoff] = sorted_candidates.apply(lambda row: calculate_cutoff(row), axis=1)
    candidate_df.update(sorted_candidates)

    return f"{cutoff} updated successfully"

#### EXECUTION

##### For CAPF

In [209]:
post = 'CAPF'
get_cutoff(cutoff_df, candidate_df, post)

'cutoff_flag_cpo updated successfully'

In [210]:
candidate_df[['rollno', 'cutoff_flag_cpo']].head()

       rollno cutoff_flag_cpo
0  1801001916               3
1  1004007924               3
2  2233003514               9
3  2227000251               3
4  2222000910               3

In [211]:
null_cutoff_rows = candidate_df[
    candidate_df['agerelax_code'] == '17'
][['dob', 'cat1_cpo', "cat2", "cat3","merit", "agerelax_code","cutoff_flag_cpo"]].head(10)


print(null_cutoff_rows)

Empty DataFrame
Columns: [dob, cat1_cpo, cat2, cat3, merit, agerelax_code, cutoff_flag_cpo]
Index: []

In [212]:
candidate_df['cutoff_flag_cpo'].unique()

array(['3', '9', '92', '91', '96', '1', '90', '6', '2', '0', '', '963',
       '93', '13', '903', '63'], dtype=object)

##### For Delhi Police

In [213]:
post = 'DP'
get_cutoff(cutoff_df, candidate_df, post)

'cutoff_flag_dp updated successfully'

In [214]:
candidate_df[['rollno', 'cutoff_flag_dp']].head()

       rollno cutoff_flag_dp
0  1801001916              3
1  1004007924              3
2  2233003514              9
3  2227000251              3
4  2222000910              3

In [215]:
candidate_df['cutoff_flag_dp'].unique()

array(['3', '9', '92', '91', '96', '1', '90', '6', '2', '0', '', '963',
       '93', '13', '903', '63'], dtype=object)

##### For Special ESM

In [216]:
post = 'ESM_SPL'
get_cutoff(cutoff_df, candidate_df, post)

'cutoff_flag_spclexs_dp updated successfully'

In [217]:
candidate_df[['rollno', 'cutoff_flag_spclexs_dp']].head()

       rollno cutoff_flag_spclexs_dp
0  1801001916                   None
1  1004007924                   None
2  2233003514                   None
3  2227000251                   None
4  2222000910                   None

In [218]:
candidate_df['cutoff_flag_spclexs_dp'].unique()

array([None, '9', '96', '91', '90'], dtype=object)

### DOB FLAG

#### PREREQIUSITES

In [219]:
mask = candidate_df['cat1_cpo'].isnull()
candidate_df.loc[mask, 'cat1_cpo'] = ''
candidate_df.loc[~mask, 'cat1_cpo'] = candidate_df.loc[~mask, 'cat1_cpo'].astype(int).astype(str)

mask = candidate_df['cat1_dp'].isnull()
candidate_df.loc[mask, 'cat1_dp'] = ''
candidate_df.loc[~mask, 'cat1_dp'] = candidate_df.loc[~mask, 'cat1_dp'].astype(int).astype(str)

mask = candidate_df['cat2'].isnull()
candidate_df.loc[mask, 'cat2'] = ''
candidate_df.loc[~mask, 'cat2'] = candidate_df.loc[~mask, 'cat2'].astype(int).astype(str)

mask = candidate_df['cat3'].isnull()
candidate_df.loc[mask, 'cat3'] = ''
candidate_df.loc[~mask, 'cat3'] = candidate_df.loc[~mask, 'cat3'].astype(int).astype(str)

mask = candidate_df['agerelax_code'].isnull()
candidate_df.loc[mask, 'agerelax_code'] = ''
candidate_df.loc[~mask, 'agerelax_code'] = candidate_df.loc[~mask, 'agerelax_code'].astype(int).astype(str)

C:\Users\SalauddinKhan\AppData\Local\Temp\ipykernel_18852\3960442290.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  candidate_df.loc[mask, 'cat1_cpo'] = ''
C:\Users\SalauddinKhan\AppData\Local\Temp\ipykernel_18852\3960442290.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  candidate_df.loc[mask, 'cat1_dp'] = ''
C:\Users\SalauddinKhan\AppData\Local\Temp\ipykernel_18852\3960442290.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_df.loc[mask, 'cat2'] = ''
C:\Users\SalauddinKhan\AppData\Local\Temp\ipykernel_18852\3960442290.py:14: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_df.loc[mask, 'cat3'] = ''
C:\Users\SalauddinKhan\AppData\Local\Temp\ipykernel_18852\3960442290.py:18: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_df.loc[mask, 'agerelax_code'] = ''

In [220]:
def convert_service_period(df, column_name):
    def extract_values(text):
        if pd.isna(text):
            return None, None, None

        years, months, days = 0, 0, 0
        matches = re.findall(r'(\d+)\s*(Year[s]*)', text)
        if matches:
            years = int(matches[0][0])

        matches = re.findall(r'(\d+)\s*(Month[s]*)', text)
        if matches:
            months = int(matches[0][0])

        matches = re.findall(r'(\d+)\s*(Day[s]*)', text)
        if matches:
            days = int(matches[0][0])

        return years, months, days

    extracted_data = df[column_name].apply(extract_values)
    df[['exsm_yrs', 'exsm_months', 'exsm_days']] = pd.DataFrame(extracted_data.tolist(), index=df.index)

convert_service_period(candidate_df, 'service_period')

#### CODE

In [58]:
def get_dob_flag(candidate_df, arc_df, medium):
    
    if medium == 'CAPF':
        cat1 = 'cat1_cpo'
        dob_flag = 'dob_flag_cpo'
    
    elif medium == 'DP':
        cat1 = 'cat1_dp'
        dob_flag = 'dob_flag_dp'
    
    dob_to_date = pd.to_datetime('08/02/2004', format="%m/%d/%Y")
    dob_from_date = pd.to_datetime('08/01/1999', format="%m/%d/%Y")
    
    arc_year_dict = dict(zip(arc_df['arc_code'].astype(str), arc_df['arc_year']))

    candidate_df[dob_flag] = ''

    def calculate_verification_flag(row):
        dob = row['dob']
        verification_flag = ''
        
        if dob >= dob_to_date:
            verification_flag = 'U'
        
        elif dob_from_date < dob < dob_to_date:
            verification_flag = '9'
        
        elif dob <= dob_from_date:
            
            if row['cat2']=='' and (row[cat1]=='9' or row[cat1]=='0'):
                verification_flag = '99'
                return verification_flag
            
            agerelax_code = row['agerelax_code']
            
            if pd.isna(agerelax_code) or agerelax_code == '':
                agerelax_code = '99'
            
            if isinstance(agerelax_code, str) and len(agerelax_code.strip()) == 1:
                agerelax_code = agerelax_code.strip()
            
            age_rlx_year = arc_year_dict.get(agerelax_code, 0)
            
            if agerelax_code == '6':
                ex_service_years = row['exsm_yrs']
                ex_service_months = row['exsm_months']
                ex_service_days = row['exsm_days']
                age_rlx_year += int(ex_service_years) if ex_service_years else 0
                new_dob = dob + pd.DateOffset(years=age_rlx_year, months=ex_service_months, days=ex_service_days)
            
            else:
                extract_year = dob.year
                extract_month = dob.month
                extract_day = dob.day
                new_year = extract_year + int(age_rlx_year)
                
                if extract_month == 2 and extract_day == 29:
                    extract_day = 28
            
                new_dob = pd.to_datetime(f"{new_year}-{extract_month}-{extract_day}", format='%Y-%m-%d')
                
            if new_dob > dob_from_date:
                if len(agerelax_code) < 2:
                    verification_flag = '0' + agerelax_code
                else:
                    verification_flag = agerelax_code
            else:
                verification_flag = '99'

        return verification_flag

    sorted_candidates = candidate_df[(candidate_df['merit'].notnull())]
    
    sorted_candidates[dob_flag] = sorted_candidates.apply(calculate_verification_flag, axis=1)

    candidate_df.update(sorted_candidates)
    
    return f"{dob_flag} updated successfully"

In [221]:
def get_dob_flag(candidate_df, arc_df, medium):
    
    if medium == 'CAPF':
        cat1 = 'cat1_cpo'
        dob_flag = 'dob_flag_cpo'

    elif medium == 'DP':
        cat1 = 'cat1_dp'
        dob_flag = 'dob_flag_dp'
    
    dob_to_date = pd.to_datetime('08/02/2004', format="%m/%d/%Y")
    dob_from_date = pd.to_datetime('08/01/1999', format="%m/%d/%Y")
    
    arc_year_dict = dict(zip(arc_df['arc_code'].astype(str), arc_df['arc_year']))

    candidate_df[dob_flag] = ''

    def calculate_verification_flag(row):
        dob = row['dob']
        verification_flag = ''
        
        if dob >= dob_to_date:
            verification_flag = 'U'
        
        elif dob_from_date < dob < dob_to_date:
            verification_flag = '9'
        
        elif dob <= dob_from_date:
            agerelax_code = row['agerelax_code']
            
            if pd.isna(agerelax_code) or agerelax_code == '':
                agerelax_code = '99'
            
            if isinstance(agerelax_code, str) and len(agerelax_code.strip()) == 1:
                agerelax_code = agerelax_code.strip()
            
            age_rlx_year = arc_year_dict.get(agerelax_code, 0)
            
            if agerelax_code == '6' :
                ex_service_years = row['exsm_yrs']
                ex_service_months = row['exsm_months']
                ex_service_days = row['exsm_days']
                age_rlx_year += int(ex_service_years) if ex_service_years else 0
                new_dob = dob + pd.DateOffset(years=age_rlx_year, months=ex_service_months, days=ex_service_days)
            
            else:
                extract_year = dob.year
                extract_month = dob.month
                extract_day = dob.day
                new_year = extract_year + int(age_rlx_year)
                
                if extract_month == 2 and extract_day == 29:
                    extract_day = 28
            
                new_dob = pd.to_datetime(f"{new_year}-{extract_month}-{extract_day}", format='%Y-%m-%d')
                
            if new_dob > dob_from_date:
                if len(agerelax_code) < 2:
                    verification_flag = '0' + agerelax_code
                else:
                    verification_flag = agerelax_code
            else:
                verification_flag = '99'

        return verification_flag

    sorted_candidates = candidate_df[(candidate_df['merit'].notnull())]
    
    sorted_candidates[dob_flag] = sorted_candidates.apply(calculate_verification_flag, axis=1)

    candidate_df.update(sorted_candidates)
    
    return f"{dob_flag} updated successfully"

#### EXECUTION

##### For CAPF

In [222]:
medium = 'CAPF'
get_dob_flag(candidate_df, arc_df, medium)

'dob_flag_cpo updated successfully'

In [223]:
candidate_df[['rollno', 'dob_flag_cpo']].head()

       rollno dob_flag_cpo
0  1801001916           06
1  1004007924           06
2  2233003514            9
3  2227000251           06
4  2222000910           06

In [224]:
null_cutoff_rows = candidate_df[
    candidate_df['agerelax_code'] == '12'
][['dob', 'cat1_cpo', "cat1_dp","merit", "agerelax_code","dob_flag_cpo"]].head(10)


print(null_cutoff_rows)

             dob cat1_cpo cat1_dp  merit agerelax_code dob_flag_cpo
12888 1996-10-17        0       0   6779            12           12

In [225]:
null_cutoff_rows = candidate_df[
    candidate_df['agerelax_code'] == '17'
][['dob', 'cat1_cpo', "cat1_dp","merit", "agerelax_code","dob_flag_cpo"]].head(10)


print(null_cutoff_rows)

            dob cat1_cpo cat1_dp  merit agerelax_code dob_flag_cpo
553  1997-11-25        9       9   1327            17           17
851  1995-12-20        0       0   1013            17           17
862  1997-12-03        0       0   3383            17           17
933  1997-07-30        0       0    541            17           17
935  1997-04-03        9       9   2610            17           17
3333 1998-05-19        0       0   3187            17           17
3357 1997-02-01        9       9   1524            17           17
3359 1997-01-29        0       0    621            17           17
3464 1996-08-04        9       9    778            17           17
3469 1997-12-15        9       9    250            17           17

In [226]:
null_cutoff_rows = candidate_df[
    candidate_df['agerelax_code'] == '18'
][['dob', 'cat1_cpo', "cat1_dp","merit", "agerelax_code","dob_flag_cpo"]].head(10)


print(null_cutoff_rows)

             dob cat1_cpo cat1_dp  merit agerelax_code dob_flag_cpo
3250  1997-09-13        6       6  10004            18           18
3336  1994-09-08        6       6   3592            18           18
4726  1993-10-25        6       6   1728            18           18
4750  1994-10-03        6       6   1221            18           18
5542  1995-04-04        6       6   8374            18           18
6449  1997-05-08        6       6    769            18           18
9354  1993-02-09        6       6   2244            18           18
10806 1992-12-18        6       6   1757            18           18
11724 1993-09-05        6       6    522            18           18
12620 1996-10-29        6       6   1438            18           18

In [229]:
null_cutoff_rows = candidate_df[
    candidate_df['agerelax_code'] == '19'
][['dob', 'cat1_cpo', "cat1_dp","merit", "agerelax_code","dob_flag_cpo"]].head(10)


print(null_cutoff_rows)

             dob cat1_cpo cat1_dp  merit agerelax_code dob_flag_cpo
849   1997-11-11        1       1   7340            19           99
850   1994-06-06        2       2   9492            19           99
3445  1996-04-16        1       1   3661            19           99
4638  1990-07-23        2       2  13401            19           99
4699  1992-07-05        2       2  13817            19           99
5372  1989-10-08        1       1  12785            19           99
5373  1993-07-26        1       1  13143            19           99
12124 1997-11-04        1       1   8810            19           99
13222 1993-05-17        1       1  13041            19           99
14216 1993-11-16        2       2  12042            19           99

In [29]:
# Ensure consistent string format old
candidate_df['rollno'] = candidate_df['rollno'].astype(str).str.strip()

# List of roll numbers to update
rollnos_to_update = ["2201042500", "2201091203", "2214005756", "2214005837", "2233006741", "2201021757", "3009003070", "2201084176", "2201058045", "2201091173", "2201031867", "2201027987", "2233001560", "2233000304", "2233001782", "2201092417", "2201077626", "2215000152", "2201093929", "2233000710", "2214005860", "2233002971", "2201088584", "2214006361", "2233008012", "2201076578"]

# Update the dob_flag_cpo column
candidate_df.loc[candidate_df['rollno'].isin(rollnos_to_update), 'dob_flag_cpo'] = '99'

In [228]:
# Ensure consistent string format new updates 38 candidates
candidate_df['rollno'] = candidate_df['rollno'].astype(str).str.strip()

# List of roll numbers to update
rollnos_to_update = ["2218003890", "2201073034", "2201045284", "2218004819", "2218009037", "2227003034", "2215009583", "2201031867", "2201042500", "2227001261", "3009003070", "2215009488", "2233006741", "2201092417", "2215000152", "2201076578", "2214006361", "2201058045", "2233000304", "2233001560", "2201091203", "2214005837", "2218011537", "2201077626", "2218010736", "2201021757", "2201093929", "2233000710", "2214005860", "2233002971", "2201088584", "2201091173", "2214005756", "2201027987", "2233001782", "2233008012", "2201084176", "2218011803"]

# Update the dob_flag_cpo column
candidate_df.loc[candidate_df['rollno'].isin(rollnos_to_update), 'dob_flag_cpo'] = '99'

##### For DP

In [230]:
medium = 'DP'
get_dob_flag(candidate_df, arc_df, medium)

'dob_flag_dp updated successfully'

In [231]:
candidate_df[['rollno', 'dob_flag_dp']].head()

       rollno dob_flag_dp
0  1801001916          06
1  1004007924          06
2  2233003514           9
3  2227000251          06
4  2222000910          06

In [232]:
null_cutoff_rows = candidate_df[
    candidate_df['agerelax_code'] == '18'
][['dob', 'cat1_cpo', "cat1_dp","merit", "agerelax_code","dob_flag_cpo", "dob_flag_dp"]].head(10)


print(null_cutoff_rows)

             dob cat1_cpo cat1_dp  merit agerelax_code dob_flag_cpo  \
3250  1997-09-13        6       6  10004            18           99
3336  1994-09-08        6       6   3592            18           99
4726  1993-10-25        6       6   1728            18           99
4750  1994-10-03        6       6   1221            18           99
5542  1995-04-04        6       6   8374            18           99
6449  1997-05-08        6       6    769            18           99
9354  1993-02-09        6       6   2244            18           99
10806 1992-12-18        6       6   1757            18           99
11724 1993-09-05        6       6    522            18           99
12620 1996-10-29        6       6   1438            18           99

      dob_flag_dp
3250           18
3336           18
4726           18
4750           18
5542           18
6449           18
9354           18
10806          18
11724          18
12620          18

### CATSEL DOB FLAG

#### PREREQUISITES

In [233]:
arc_df['arc_code'] = arc_df['arc_code'].astype(str)

mask = arc_df['arc_cat2'].isnull()
arc_df.loc[mask, 'arc_cat2'] = ''

In [234]:
arc_df['arc_code'] = arc_df['arc_code'].apply(lambda x: str(x).zfill(2))

#### CODE

In [235]:
def get_catsel_dob(candidate_df, arc_df, medium):
    dob_from_date = pd.to_datetime('08/01/1999', format="%m/%d/%Y")
    
    if medium == 'CAPF':
        cat1 = 'cat1_cpo'
        dob_flag = 'dob_flag_cpo'
        catsel_dob_flag = 'catsel_dob_cpo'
    elif medium == 'DP':
        cat1 = 'cat1_dp'
        dob_flag = 'dob_flag_dp'
        catsel_dob_flag = 'catsel_dob_dp'

    candidate_df[catsel_dob_flag] = ''
    
    filtered_and_sorted_candidates = candidate_df[(candidate_df['merit'].notnull()) 
    & (candidate_df[dob_flag].notnull()) 
    & (candidate_df[dob_flag] != '')]
    
    def calculate_catsel_dob(row, dob_flag_name):
        dob_flag = row[dob_flag_name]
       
        if dob_flag is not None and dob_flag != '' and dob_flag != '9':
            matching_rows = arc_df[arc_df['arc_code'] == dob_flag]
            if not matching_rows.empty:
                catsel = matching_rows.iloc[0]
                catsel_cat1 = catsel['arc_cat1'].split(',')
                catsel_cat2 = catsel['arc_cat2'].split(',')
                catsel_gender = catsel['arc_gender'].split(',')
                condition = (str(row[cat1]) in catsel_cat1) & (str(int(row['gender'])) in catsel_gender)
                catsel_dob = ''
                if row['cat2'] == '3' and row['cat2'] in catsel_cat2:
                    catsel_dob = row['cat2']
                else:
                    if pd.isnull(catsel['arc_year_against_ur']):
                        catsel['arc_year_against_ur'] = 0
                    dob_datetime = pd.to_datetime(row['dob'])
                    extract_year = dob_datetime.year
                    extract_month = dob_datetime.month
                    extract_day = dob_datetime.day
                    if (extract_day == 29) and (extract_month == 2):
                        extract_day = 28
                    new_year = extract_year + int(catsel['arc_year_against_ur'])
                    new_dob = pd.to_datetime(f'{new_year}-{extract_month}-{extract_day}')
                    catsel_dob_decision = new_dob > dob_from_date
                    
                    catsel_dob = '9' if catsel_dob_decision else row[cat1]
                    
                return catsel_dob if condition else ''
            else:
                return ''
        else:
            return dob_flag
    
    filtered_and_sorted_candidates[catsel_dob_flag] = filtered_and_sorted_candidates.apply(calculate_catsel_dob, args = (dob_flag, ), axis=1)
    candidate_df.update(filtered_and_sorted_candidates)
    
    print('Successfully updated ' + catsel_dob_flag)

#### EXECUTION

##### For CAPF

In [236]:
medium = 'CAPF'
get_catsel_dob(candidate_df, arc_df, medium)

Successfully updated catsel_dob_cpo

In [237]:
candidate_df[['rollno', 'catsel_dob_cpo']].head()

       rollno catsel_dob_cpo
0  1801001916              3
1  1004007924              3
2  2233003514              9
3  2227000251              3
4  2222000910              3

In [238]:
null_cutoff_rows = candidate_df[
    candidate_df['agerelax_code'] == '18'
][['dob', 'cat1_cpo', "cat1_dp","merit", "agerelax_code","dob_flag_cpo", "dob_flag_dp","catsel_dob_cpo"]].head(10)


print(null_cutoff_rows)

             dob cat1_cpo cat1_dp  merit agerelax_code dob_flag_cpo  \
3250  1997-09-13        6       6  10004            18           99
3336  1994-09-08        6       6   3592            18           99
4726  1993-10-25        6       6   1728            18           99
4750  1994-10-03        6       6   1221            18           99
5542  1995-04-04        6       6   8374            18           99
6449  1997-05-08        6       6    769            18           99
9354  1993-02-09        6       6   2244            18           99
10806 1992-12-18        6       6   1757            18           99
11724 1993-09-05        6       6    522            18           99
12620 1996-10-29        6       6   1438            18           99

      dob_flag_dp catsel_dob_cpo
3250           18
3336           18
4726           18
4750           18
5542           18
6449           18
9354           18
10806          18
11724          18
12620          18

##### For DP

In [239]:
medium = 'DP'
get_catsel_dob(candidate_df, arc_df, medium)

Successfully updated catsel_dob_dp

In [240]:
candidate_df[['rollno', 'catsel_dob_dp']].head()

       rollno catsel_dob_dp
0  1801001916             3
1  1004007924             3
2  2233003514             9
3  2227000251             3
4  2222000910             3

In [241]:
null_cutoff_rows = candidate_df[
    candidate_df['agerelax_code'] == '19'
][['dob', 'cat1_cpo', "cat1_dp","merit", "agerelax_code","dob_flag_cpo", "dob_flag_dp","catsel_dob_cpo","catsel_dob_dp"]].head(10)


print(null_cutoff_rows)

             dob cat1_cpo cat1_dp  merit agerelax_code dob_flag_cpo  \
849   1997-11-11        1       1   7340            19           99
850   1994-06-06        2       2   9492            19           99
3445  1996-04-16        1       1   3661            19           99
4638  1990-07-23        2       2  13401            19           99
4699  1992-07-05        2       2  13817            19           99
5372  1989-10-08        1       1  12785            19           99
5373  1993-07-26        1       1  13143            19           99
12124 1997-11-04        1       1   8810            19           99
13222 1993-05-17        1       1  13041            19           99
14216 1993-11-16        2       2  12042            19           99

      dob_flag_dp catsel_dob_cpo catsel_dob_dp
849            19                            9
850            19                            2
3445           19                            9
4638           19                            2
4699           19                            2
5372           19                            1
5373           19                            1
12124          19                            9
13222          19                            1
14216          19                            2

### CATSEL FLAG

In [242]:
mask = candidate_df['catsel_dob_cpo'].isnull()
candidate_df.loc[mask, 'catsel_dob_cpo'] = ''
candidate_df.loc[~mask, 'catsel_dob_cpo'] = candidate_df.loc[~mask, 'catsel_dob_cpo'].astype(str)

mask = candidate_df['catsel_dob_dp'].isnull()
candidate_df.loc[mask, 'catsel_dob_dp'] = ''
candidate_df.loc[~mask, 'catsel_dob_dp'] = candidate_df.loc[~mask, 'catsel_dob_dp'].astype(str)

In [243]:
candidate_df['exs_reservation'].unique()

array(['Yes', nan, 'No'], dtype=object)

#### CODE

In [244]:
def get_catsel(candidate_df, post):

    if post == 'CAPF':
        cutoff_flag = 'cutoff_flag_cpo'
        cat1 = 'cat1_cpo'
        catsel_flag = 'catsel_cpo'
        catsel_dob_flag = 'catsel_dob_cpo'
    
    elif post == 'DP':
        cutoff_flag = 'cutoff_flag_dp'
        cat1 = 'cat1_dp'
        catsel_flag = 'catsel_dp'
        catsel_dob_flag = 'catsel_dob_dp'
    
    elif post == 'ESM_SPL':
        cutoff_flag = 'cutoff_flag_spclexs_dp'
        cat1 = 'cat1_dp'
        catsel_flag = 'catsel_spclexs_dp'
        catsel_dob_flag = 'catsel_dob_dp'
        
    candidate_df[catsel_flag] = ''
    
    candidates = candidate_df[(candidate_df['merit'].notnull()) & (candidate_df[cutoff_flag].notnull())].sort_values(by='rollno')
    
    def update_cutoff_flag(candidate_record):
        if candidate_record['cat2'] == '3' and candidate_record['exs_reservation'] == 'No':
            candidate_record[cutoff_flag] = candidate_record[cutoff_flag].replace('3', '').strip()

        if candidate_record[catsel_dob_flag] in ['1', '2', '6', '4', '5', '7', '8']:
            return candidate_record[cutoff_flag].replace('9', '').strip()
        elif pd.isna(candidate_record[catsel_dob_flag]) or candidate_record[catsel_dob_flag] == '':
            return ''
        else:
            return candidate_record[cutoff_flag]
    
    candidate_df[catsel_flag] = candidates.apply(update_cutoff_flag, axis=1)

    return 'Successfully updated '+ catsel_flag

#### EXECUTION

##### For CAPF

In [245]:
post = 'CAPF'
get_catsel(candidate_df, post)

'Successfully updated catsel_cpo'

In [246]:
candidate_df[['rollno', 'catsel_cpo']].head()

       rollno catsel_cpo
0  1801001916          3
1  1004007924          3
2  2233003514          9
3  2227000251          3
4  2222000910          3

##### For DP

In [247]:
post = 'DP'
get_catsel(candidate_df, post)

'Successfully updated catsel_dp'

In [248]:
candidate_df[['rollno', 'catsel_dp']].head()

       rollno catsel_dp
0  1801001916         3
1  1004007924         3
2  2233003514         9
3  2227000251         3
4  2222000910         3

In [249]:
null_cutoff_rows = candidate_df[
    candidate_df['agerelax_code'] == '17'
][['dob', 'cat1_cpo', "cat1_dp","merit", "agerelax_code","dob_flag_cpo", "dob_flag_dp","catsel_dob_cpo","catsel_dob_dp","cutoff_flag_dp","cutoff_flag_dp","catsel_cpo", "catsel_dp"]].head(10)


print(null_cutoff_rows)

            dob cat1_cpo cat1_dp  merit agerelax_code dob_flag_cpo  \
553  1997-11-25        9       9   1327            17           99
851  1995-12-20        0       0   1013            17           99
862  1997-12-03        0       0   3383            17           99
933  1997-07-30        0       0    541            17           99
935  1997-04-03        9       9   2610            17           99
3333 1998-05-19        0       0   3187            17           99
3357 1997-02-01        9       9   1524            17           99
3359 1997-01-29        0       0    621            17           99
3464 1996-08-04        9       9    778            17           99
3469 1997-12-15        9       9    250            17           99

     dob_flag_dp catsel_dob_cpo catsel_dob_dp cutoff_flag_dp cutoff_flag_dp  \
553           17                            9              9              9
851           17                            9             90             90
862           17                            9             90             90
933           17                            9             90             90
935           17                            9              9              9
3333          17                            9             90             90
3357          17                            9              9              9
3359          17                            9             90             90
3464          17                            9              9              9
3469          17                            9              9              9

     catsel_cpo catsel_dp
553                     9
851                    90
862                    90
933                    90
935                     9
3333                   90
3357                    9
3359                   90
3464                    9
3469                    9

##### For Special ESM

In [250]:
post = 'ESM_SPL'
get_catsel(candidate_df, post)

'Successfully updated catsel_spclexs_dp'

In [251]:
candidate_df[['rollno', 'catsel_spclexs_dp']].head()

       rollno catsel_spclexs_dp
0  1801001916               NaN
1  1004007924               NaN
2  2233003514               NaN
3  2227000251               NaN
4  2222000910               NaN

In [252]:
candidate_df['catsel_spclexs_dp'].unique()

array([nan, '9', '96', '91', '90'], dtype=object)

# TO WORK

In [32]:
cand = candidate_df.copy()
vac = vacancy_df.copy()

In [254]:
cand[['allocated_category', 'allocated_post', 'allocated_against_ur', 'allocated_sub_category']] = None

In [255]:
mask = cand['post_pref'].isnull()
cand.loc[mask, 'post_pref'] = ''
cand.loc[~mask, 'post_pref'] = cand.loc[~mask, 'post_pref'].astype(str)

mask = cand['catsel_cpo'].isnull()
cand.loc[mask, 'catsel_cpo'] = ''
cand.loc[~mask, 'catsel_cpo'] = cand.loc[~mask, 'catsel_cpo'].astype(str)

mask = cand['catsel_dp'].isnull()
cand.loc[mask, 'catsel_dp'] = ''
cand.loc[~mask, 'catsel_dp'] = cand.loc[~mask, 'catsel_dp'].astype(str)

mask = cand['catsel_spclexs_dp'].isnull()
cand.loc[mask, 'catsel_spclexs_dp'] = ''
cand.loc[~mask, 'catsel_spclexs_dp'] = cand.loc[~mask, 'catsel_spclexs_dp'].astype(str)

In [256]:
vac['allocated_hc'] = 0
vac['allocated_hc_prev'] = 0

In [257]:
vac['sub_category_code'].unique()

array(['0', '3', '3*'], dtype=object)

In [258]:
vac['left_vacancy'] = vac['current']
vacancy_dict = {}
vac['key'] = vac['category_code'].astype(str) + vac['post_code'].astype(str) + vac['gender'].astype(str) + vac['sub_category_code'].astype(str)
for index, row in vac.iterrows():
    key = row['key']
    vacancy_dict[key] = row.to_dict()

#### CODE

In [259]:
def update_allocation_dp(candidates_df, category, post, gender, subcat, allocated_against_ur, candidate, vacancy_dict):
                        
    candidates_df.loc[candidate.name, 'allocated_category'] = category
    candidates_df.loc[candidate.name, 'allocated_post'] = post
    candidates_df.loc[candidate.name, 'allocated_sub_category'] = subcat
    candidates_df.loc[candidate.name, 'allocated_against_ur'] = allocated_against_ur
    
    return True

In [260]:
def update_allocation_cpo(candidates_df, category, post, gender, subcat, allocated_against_ur, candidate, vacancy_dict):
    if str(category) in ['3', '4', '5', '7', '8']:
    
        key_cat1 = str(candidate['cat1_cpo']) + str(post) + str(gender) + str(subcat)
        
        if (key_cat1 not in vacancy_dict.keys()) or (vacancy_dict[key_cat1]['initial_vacancy'] == 0):
            keyCat2= '9' + str(post) + str(gender) + str(subcat)
            
            if (keyCat2 not in vacancy_dict.keys()) or (vacancy_dict[keyCat2]['initial_vacancy'] == 0):
                return False
            else:
                if vacancy_dict[keyCat2]['allocated_hc'] != vacancy_dict[keyCat2]['initial_vacancy']:
                    vacancy_dict[keyCat2]['allocated_hc'] += 1
                allocated_against_ur = '1'
        else:
            if vacancy_dict[key_cat1]['allocated_hc'] != vacancy_dict[key_cat1]['initial_vacancy']:
                vacancy_dict[key_cat1]['allocated_hc'] += 1
            
            else :
                return False
                        
    candidates_df.loc[candidate.name, 'allocated_category'] = category
    candidates_df.loc[candidate.name, 'allocated_post'] = post
    candidates_df.loc[candidate.name, 'allocated_sub_category'] = subcat
    candidates_df.loc[candidate.name, 'allocated_against_ur'] = allocated_against_ur
    
    return True

In [261]:
def allocate_candidates(candidates_df, vacancy_dict):
     
    filtered_candidates = candidates_df[(candidates_df['merit'].notnull())].sort_values(by='merit')
    
    for idx, candidate in filtered_candidates.iterrows():
        allocated = False
        roll = candidate['rollno']
        post_preference = candidate['post_pref']
        DOB = candidate['dob']
        gender = candidate['gender']
       
        
        for post in post_preference.split(','):

            if post == 'A':
                if candidate['cat2'] == '3':
                    if candidate['catsel_spclexs_dp'] != '':
                        subcat = '3*'
                        catsel_name = 'catsel_spclexs_dp'
                        catsel = candidate['catsel_spclexs_dp']
                    else:
                        subcat = '3'
                        catsel_name = 'catsel_dp'
                        catsel = candidate['catsel_dp']
                else:
                    subcat = '0'
                    catsel_name = 'catsel_dp'
                    catsel = candidate['catsel_dp']
            
                
                for category in catsel:

                    if catsel != candidate['catsel_spclexs_dp'] and category == '3':
                        category = candidate['cat1_dp']
                        subcat = '3'
                    elif catsel == candidate['catsel_spclexs_dp']:
                        category = candidate['cat1_dp']
                        subcat = '3*'
                    else:
                        subcat = '0'
                    
                    key =  str(category) + str(post) + str(gender) + str(subcat)
                    
                    allocated_against_ur = ''
                    
                    if key in vacancy_dict and vacancy_dict[key]['current'] > 0 and candidate['total'] >= vacancy_dict[key]['min_marks_old']:
                        post = vacancy_dict[key]['post_code']
                                    
                        allocated = update_allocation_dp(candidates_df, category, post, gender, subcat, allocated_against_ur, candidate, vacancy_dict)
                        if allocated:
                            vacancy_dict[key]['current'] -= 1
                            vacancy_dict[key]['allocated'] += 1
                            break
                    else:
                        if subcat == '3*' and vacancy_dict[key]['current'] == 0:
                            subcat = '3'
                            key = str(category) + str(post) + str(gender) + str(subcat)
                            if key in vacancy_dict and vacancy_dict[key]['current'] > 0 and candidate['total'] >= vacancy_dict[key]['min_marks_old']:
                                post = vacancy_dict[key]['post_code']
                                        
                                allocated = update_allocation_dp(candidates_df, category, post, gender, subcat, allocated_against_ur, candidate, vacancy_dict)
                                if allocated:
                                    vacancy_dict[key]['current'] -= 1
                                    vacancy_dict[key]['allocated'] += 1
                                    break
                if allocated:
                    break
            else:
                subcat='0'
                catsel_name = 'catsel_cpo'
                catsel = candidate['catsel_cpo']

                for category in catsel:
                    key =  str(category) + str(post) + str(gender) + str(subcat)
                    
                    allocated_against_ur = ''
                    
                    if key in vacancy_dict and vacancy_dict[key]['current'] > 0 and candidate['total'] >= vacancy_dict[key]['min_marks_old']:
                        post = vacancy_dict[key]['post_code']
                                    
                        allocated = update_allocation_cpo(candidates_df, category, post, gender, subcat, allocated_against_ur, candidate, vacancy_dict)
                        if allocated:
                            vacancy_dict[key]['current'] -= 1
                            vacancy_dict[key]['allocated'] += 1
                            break
                if allocated:
                    break
    

    for key, vacancy_info in vacancy_dict.items():
        if key.endswith('*') and (vacancy_info['current'] != 0):
            filter_condition = (candidates_df['allocated_category'].isnull()) & (candidates_df['cat2'] == '3') & (candidates_df['catsel_dp'].notnull()) & (candidates_df['post_pref'].str.contains('A')) & (candidates_df['cat1_dp'].astype(str) == str(vacancy_info['category_code']))
            filtered_candidates_spl_esm = candidates_df[filter_condition]
    
            for i in range(vacancy_info['current']):
                index = filtered_candidates_spl_esm.index[i]
                columns_to_update = ['allocated_category', 'allocated_post', 'allocated_sub_category', 'allocated_against_ur']
                values_to_update = [vacancy_info['category_code'], vacancy_info['post_code'], '3', '']
                
                candidates_df.loc[index, columns_to_update] = values_to_update
                vacancy_info['current'] -= 1
                vacancy_info['allocated'] += 1
                continue

                
    return vacancy_dict

In [262]:
def adjust_vacancy(candidates_df, vacancy_df):
    vacancy_df['current'] = vacancy_df['initial_vacancy'] - vacancy_df['allocated_hc']
    vacancy_df['allocated'] = 0
    vacancy_df['left_vacancy'] = 0
        
    vacancy_df['allocated_hc_prev'] = vacancy_df['allocated_hc']
    vacancy_df['allocated_hc'] = 0

    return vacancy_df

#### EXECUTION

##### FIRST TIME

In [263]:
upd_vacancy_dict = allocate_candidates(cand, vacancy_dict)

##### ADJUST LOOP

In [265]:
updated_vacancy_df = pd.DataFrame.from_dict(upd_vacancy_dict, orient='index')
i=0
while (updated_vacancy_df['allocated_hc_prev'] != updated_vacancy_df['allocated_hc']).any():
    i+=1
    print('Adjust Attempt-'+str(i))
    upd_vacancy_df = adjust_vacancy(cand, updated_vacancy_df)
    
    upd_vacancy_df['left_vacancy'] = upd_vacancy_df['current']
    vacancy_dict = {}
    upd_vacancy_df['key'] = upd_vacancy_df['category_code'].astype(str) + upd_vacancy_df['post_code'].astype(str) + upd_vacancy_df['gender'].astype(str) + upd_vacancy_df['sub_category_code'].astype(str)
    
    for index, row in upd_vacancy_df.iterrows():
        key = row['key']
        vacancy_dict[key] = row.to_dict()
    cand[['allocated_category', 'allocated_post', 'allocated_against_ur', 'allocated_sub_category']] = None
    upd_vacancy_dict = allocate_candidates(cand, vacancy_dict)
    updated_vacancy_df = pd.DataFrame.from_dict(upd_vacancy_dict, orient='index')

Adjust Attempt-1

In [266]:
updated_vacancy_df['left_vacancy'] = updated_vacancy_df['current']
updated_vacancy_df['current'] = updated_vacancy_df['left_vacancy'] + updated_vacancy_df['allocated']

In [267]:
updated_vacancy_df.head(2)

,slno,post_name,post_code,category_code,sub_category_code,gender,vacancy,initial_vacancy,current,allocated,left_vacancy,min_marks_old,min_paper2_old,min_marks_cand_dob_old,max_merit_old,allocated_hc,allocated_hc_prev,key
9A20,1,SIDP,A,9,0,2,45,45,45,45,0,353.65465,182.50,2001-12-12,NaN,0,0,9A20
0A20,2,SIDP,A,0,0,2,12,12,12,12,0,345.81888,188.75,2003-08-12,NaN,0,0,0A20

In [31]:
cand[cand['allocated_sub_category'].notnull()].shape[0]

5359

#### WRITING TO CSV

In [36]:
cand.to_csv(r"C:\Users\SalauddinKhan\Desktop\PYTHON\sicpo24_revised_v2_today.csv", index = False)
#cand[cand['allocated_category'].notnull()].to_csv(r"C:\Users\Aviral Chaudhary\Downloads\RP_SICPO_22\only_allocated_candidates.csv", index = False)
updated_vacancy_df.to_csv(r"C:\Users\SalauddinKhan\Desktop\PYTHON\vacancy_sicpo24_revised_v2_TODAY.csv", index = False)

In [ ]:
updated_vacancy_df[['min_marks', 'min_marks_paper2','min_marks_paper1', 'min_marks_cand_dob', 'min_marks_merit']] = None

In [33]:
vacancy_df[['min_marks', 'min_marks_paper2','min_marks_paper1', 'min_marks_cand_dob', 'min_marks_merit']] = None

In [34]:
def find_lowest_marks(candidates_df, vacancy_df):
    candidates_df['key'] = (candidates_df['allocated_category'].astype(str) +
                            candidates_df['gender'].astype(str) +
                            candidates_df['allocated_post'].astype(str) +
                            candidates_df['allocated_sub_category'].astype(str))

    vacancy_df['key'] = (vacancy_df['category_code'].astype(str) +
                         vacancy_df['gender'].astype(str) +
                         vacancy_df['post_code'].astype(str) +
                         vacancy_df['sub_category_code'].astype(str))

    highest_merit_candidates = candidates_df.loc[candidates_df.groupby('key')['merit'].idxmax()]

    vacancy_df_merged = vacancy_df.merge(highest_merit_candidates[['key', 'total', 'paper2' , 'dob', 'merit']],
                                  on='key', how='left')

    vacancy_df_merged['min_marks'] = vacancy_df_merged['total']
    vacancy_df_merged['min_marks_paper2'] = vacancy_df_merged['paper2']
    #vacancy_df_merged['min_marks_paper1'] = vacancy_df_merged['paper1']
    vacancy_df_merged['min_marks_cand_dob'] = vacancy_df_merged['dob']
    vacancy_df_merged['min_marks_merit'] = vacancy_df_merged['merit']


    #vacancy_df.drop(columns=['total_marks', 'parta_gi', 'partb_ga', 'dob'], inplace=True)

    return vacancy_df_merged

In [35]:
updated_vacancy_df =  find_lowest_marks(cand, vacancy_df)

In [20]:
cand[['key', 'total', 'paper2', 'dob', 'merit']].head(10)

    key      total  paper2         dob    merit
0  62C0  314.01985  160.50  2002-01-29   2215.0
1  92C0  329.24018  163.75  2002-02-25    786.0
2  12D0  268.53177  138.50  2002-01-26   9230.0
3  92C0  326.46674  166.25  1999-10-02    976.0
4  92D0  305.96953  163.75  2004-01-02   3314.0
5  12C0  314.00151  168.75  2001-10-17   2221.0
6  92D0  309.75220  172.75  2002-06-29   2775.0
7  62E0  311.22929  163.75  1997-11-20   2570.0
8  12B0  272.42728  146.25  2001-06-21   8681.0
9  32D0  149.73446   98.00  1983-05-16  14004.0